<a href="https://colab.research.google.com/github/Salma53ster/Flash-Chat/blob/master/Download_Clinical_data_Project_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install requests pandas tqdm scipy

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (1.16.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.6.17)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

### Create a folder for output
All scripts will write outputs into `tcga_tnbc_data/`.

In [1]:
!mkdir -p tcga_tnbc_data

### 1) RNA‑seq expression matrix (CSV)
File: `01_download_rnaseq_matrix.py`

In [2]:
import requests
import pandas as pd
from pathlib import Path
from tqdm import tqdm
import gzip # Import gzip module

GDC_API = "https://api.gdc.cancer.gov"
PROJECT = "TCGA-BRCA"
TOKEN_PATH = "gdc_token.txt"
OUTPUT_DIR = Path("tcga_tnbc_data")
OUTPUT_DIR.mkdir(exist_ok=True)

HEADERS_WITH_TOKEN = {}
try:
    with open(TOKEN_PATH, "r") as f:
        token = f.read().strip()
    HEADERS_WITH_TOKEN = {"X-GDC-TOKEN": token}
except FileNotFoundError:
    pass


def post_gdc(endpoint, filters, fields=None, size=200):
    url = f"{GDC_API}/{endpoint}"
    payload = {"filters": filters, "format": "JSON", "size": size}
    if fields:
        payload["fields"] = fields

    all_hits = []
    from_val = 0

    while True:
        params = {"from": from_val}
        resp = requests.post(url, params=params, json=payload, headers=HEADERS_WITH_TOKEN)
        resp.raise_for_status()
        data = resp.json()
        hits = data["data"]["hits"]
        all_hits.extend(hits)

        pagination = data["data"]["pagination"]
        # Changed 'per_page' to 'size' based on common GDC API pagination structure
        if pagination["page"] * pagination["size"] >= pagination["total"]:
            break
        from_val += pagination["size"]

    return all_hits


def get_rnaseq_files(workflow_type="STAR - Counts"):
    filters = {
        "op": "and",
        "content": [
            {"op": "=", "content": {"field": "cases.project.project_id", "value": PROJECT}},
            {"op": "=", "content": {"field": "files.data_category", "value": "Transcriptome Profiling"}},
            {"op": "=", "content": {"field": "files.data_type", "value": "Gene Expression Quantification"}},
            {"op": "=", "content": {"field": "files.experimental_strategy", "value": "RNA-Seq"}},
            {"op": "=", "content": {"field": "files.analysis.workflow_type", "value": workflow_type}},
            {"op": "in", "content": {"field": "cases.samples.sample_type", "value": ["Primary Tumor", "Solid Tissue Normal"]}},
        ]
    }

    fields = ",".join([
        "file_id",
        "file_name",
        "analysis.workflow_type",
        "cases.project.project_id",
        "cases.samples.sample_type",
        "cases.submitter_id"
    ])

    hits = post_gdc("files", filters, fields=fields)
    print(f"Found {len(hits)} RNA-seq files for workflow: {workflow_type}")
    return hits


def download_file(file_id, out_path):
    url = f"{GDC_API}/data/{file_id}"
    with requests.get(url, headers=HEADERS_WITH_TOKEN, stream=True, timeout=300) as r:
        r.raise_for_status()
        with open(out_path, "wb") as f:
            for chunk in r.iter_content(chunk_size=8192):
                f.write(chunk)


def build_and_save_rnaseq_matrix(file_info, output_csv):
    all_dfs = []
    sample_names = []

    for info in tqdm(file_info, desc="Downloading RNA-seq files"):
        fid = info["file_id"]
        tmp_path = OUTPUT_DIR / f"{fid}.tsv.gz" # Still download with .gz extension as it might be gzipped
        download_file(fid, tmp_path)

        df = None
        try:
            # Check if file is actually gzipped by reading magic bytes
            is_gzipped = False
            with open(tmp_path, 'rb') as f:
                magic_bytes = f.read(2)
                if magic_bytes == b'\x1f\x8b': # Gzip magic bytes
                    is_gzipped = True

            if is_gzipped:
                df = pd.read_csv(tmp_path, sep="\t", compression='gzip', header=None, comment='#')
            else:
                print(f"Warning: File {tmp_path} is not gzipped despite extension. Attempting to read as plain TSV with comments.")
                df = pd.read_csv(tmp_path, sep="\t", compression=None, header=None, comment='#') # Explicitly no compression

        except Exception as e:
            print(f"Error: Could not read file {tmp_path}: {e}. Skipping this file.")
            tmp_path.unlink(missing_ok=True) # Clean up partial file
            continue # Skip this file and continue with the next one

        if df is None or df.empty:
            print(f"Warning: Skipping empty or unreadable file {tmp_path}.")
            tmp_path.unlink(missing_ok=True) # Clean up partial file
            continue

        # Ensure the DataFrame has at least two columns before proceeding
        if df.shape[1] < 2:
            print(f"Warning: File {tmp_path} does not have enough columns. Skipping.")
            tmp_path.unlink(missing_ok=True) # Clean up partial file
            continue

        df = df.iloc[:, :2]
        df.columns = ["gene_id", fid]

        # Drop duplicate gene_ids, keeping the first occurrence
        df = df.drop_duplicates(subset=['gene_id'], keep='first')
        df = df.set_index("gene_id")

        all_dfs.append(df)

        case_sub = info.get("cases", [{}])[0].get("submitter_id", fid)
        sample_type = info.get("cases", [{}])[0].get("samples", [{}])[0].get("sample_type", "UNK")
        sample_name = f"{case_sub}_{sample_type}"
        sample_names.append(sample_name)

        # Optionally delete tmp file:
        tmp_path.unlink(missing_ok=True) # Delete temp file after processing

    if not all_dfs:
        print("No valid RNA-seq files were processed.")
        return pd.DataFrame()

    merged = pd.concat(all_dfs, axis=1)
    merged.columns = sample_names
    merged.to_csv(output_csv)
    print(f"RNA-seq matrix saved to: {output_csv}")
    return merged


# __name__ == "__main__" block
# Choose workflow: "STAR - Counts", "HTSeq - Counts", "STAR - FPKM", "STAR - TPM"
rna_files = get_rnaseq_files(workflow_type="STAR - Counts")

if not rna_files:
    print("No RNA-seq files found. Try another workflow_type.")
else:
    build_and_save_rnaseq_matrix(
        rna_files,
        OUTPUT_DIR / "TCGA_BRCA_RNAseq_matrix.csv"
    )

Found 1224 RNA-seq files for workflow: STAR - Counts

Downloading RNA-seq files:   0%|          | 0/1224 [00:00<?, ?it/s]

Warning: File tcga_tnbc_data/744a6d3d-b666-49aa-8d26-47f34e3d1eb5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   0%|          | 1/1224 [00:06<2:10:30,  6.40s/it]

Warning: File tcga_tnbc_data/4ecc1f1a-8ff4-4552-a5e8-7a9652b6d1d5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   0%|          | 2/1224 [00:07<1:05:18,  3.21s/it]

Warning: File tcga_tnbc_data/1ace2a0c-773d-45b5-8fd6-968c88731bbb.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   0%|          | 3/1224 [00:08<43:17,  2.13s/it]

Warning: File tcga_tnbc_data/2d5b0962-b5c4-4482-9f28-47e4dcdb6df6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   0%|          | 4/1224 [00:09<33:21,  1.64s/it]

Warning: File tcga_tnbc_data/84cff855-d17a-4c09-b432-53893ae69c1e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   0%|          | 5/1224 [00:09<27:23,  1.35s/it]

Warning: File tcga_tnbc_data/c2515ef2-5cfc-4cc2-9541-ae072616d361.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   0%|          | 6/1224 [00:10<24:19,  1.20s/it]

Warning: File tcga_tnbc_data/61647238-a8c4-4156-af15-c32947983cfd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   1%|          | 7/1224 [00:11<22:33,  1.11s/it]

Warning: File tcga_tnbc_data/488399aa-ef3c-42d7-817f-9db11b9902dd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   1%|          | 8/1224 [00:12<20:46,  1.03s/it]

Warning: File tcga_tnbc_data/3d0b3b80-92ae-44dc-89fc-2ead925b81a2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   1%|          | 9/1224 [00:13<20:58,  1.04s/it]

Warning: File tcga_tnbc_data/5cce30f3-99ae-4959-987a-0d280dc2ec44.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   1%|          | 10/1224 [00:14<20:13,  1.00it/s]

Warning: File tcga_tnbc_data/ddeb1445-08ae-441c-9f2a-4647df1b4ed6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   1%|          | 11/1224 [00:15<19:50,  1.02it/s]

Warning: File tcga_tnbc_data/5c0579f7-6184-4afa-805c-7aeec4a4c5d2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   1%|          | 12/1224 [00:16<18:27,  1.09it/s]

Warning: File tcga_tnbc_data/9c00a43c-1da0-4e3b-b7e2-54a48d29ecae.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   1%|          | 13/1224 [00:17<17:52,  1.13it/s]

Warning: File tcga_tnbc_data/6ce774a5-2636-4a01-ab6e-737f89a4bd4f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   1%|          | 14/1224 [00:17<17:40,  1.14it/s]

Warning: File tcga_tnbc_data/fed0a382-2eee-4acc-af00-53a9fdcd2a61.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   1%|          | 15/1224 [00:18<17:15,  1.17it/s]

Warning: File tcga_tnbc_data/80d565a0-59f6-409e-8850-5d4e2b5b996d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   1%|▏         | 16/1224 [00:19<17:37,  1.14it/s]

Warning: File tcga_tnbc_data/263123b0-ec68-47cd-96dd-4f0795503d89.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   1%|▏         | 17/1224 [00:20<17:33,  1.15it/s]

Warning: File tcga_tnbc_data/f205f47f-bd57-42bf-a702-4a17d4391411.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   1%|▏         | 18/1224 [00:21<16:53,  1.19it/s]

Warning: File tcga_tnbc_data/0e0df72c-33c0-4e4f-939c-a4d45a6e1ea3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   2%|▏         | 20/1224 [00:22<16:30,  1.22it/s]

Warning: File tcga_tnbc_data/111b2865-e7dc-45c9-b206-20b5713714bc.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/9a1c9a5a-7b3f-463b-bc9c-e06107b2aeb7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   2%|▏         | 21/1224 [00:23<16:53,  1.19it/s]

Warning: File tcga_tnbc_data/931442ba-af81-4b68-beca-7285fc44b1df.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   2%|▏         | 22/1224 [00:24<17:49,  1.12it/s]

Warning: File tcga_tnbc_data/eff9c23b-fc85-403c-8e88-86b4def8ced1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   2%|▏         | 23/1224 [00:25<17:51,  1.12it/s]

Warning: File tcga_tnbc_data/a63cca36-139d-4054-9d99-9b04ddae7ec2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   2%|▏         | 24/1224 [00:26<17:21,  1.15it/s]

Warning: File tcga_tnbc_data/5645320f-820e-45b7-b4cf-ea05085f53e3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   2%|▏         | 25/1224 [00:27<17:06,  1.17it/s]

Warning: File tcga_tnbc_data/f9432d83-a322-4f5b-9c45-7dad736005a4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   2%|▏         | 27/1224 [00:29<17:31,  1.14it/s]

Warning: File tcga_tnbc_data/3d075fc4-5a01-47ce-bef0-a77acf71061d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/f599be9a-0cac-4441-905c-5a6c87e7bc8c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   2%|▏         | 28/1224 [00:30<17:27,  1.14it/s]

Warning: File tcga_tnbc_data/4f54add3-c33d-4bc9-9e1f-c75f52d15f1e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   2%|▏         | 29/1224 [00:30<17:16,  1.15it/s]

Warning: File tcga_tnbc_data/fc0e74d2-ab94-48b1-8e31-808bde7a3fe6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   2%|▏         | 30/1224 [00:31<17:52,  1.11it/s]

Warning: File tcga_tnbc_data/7ff8696e-3809-4b96-9259-be654631d952.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   3%|▎         | 31/1224 [00:32<17:43,  1.12it/s]

Warning: File tcga_tnbc_data/73edea85-f978-4c99-b9c3-fda3ffc6a065.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   3%|▎         | 33/1224 [00:34<17:19,  1.15it/s]

Warning: File tcga_tnbc_data/c00ad8a9-ed1d-4289-aa62-3e64cb574205.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/d657ed9a-fd92-493c-ae10-120c8b0c58d7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   3%|▎         | 34/1224 [00:35<16:44,  1.18it/s]

Warning: File tcga_tnbc_data/d5586fdb-d796-4176-84e3-11a72124b41f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   3%|▎         | 35/1224 [00:36<21:49,  1.10s/it]

Warning: File tcga_tnbc_data/e4f49b9c-faed-4f15-a79c-79664e2c03b6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   3%|▎         | 36/1224 [00:37<20:26,  1.03s/it]

Warning: File tcga_tnbc_data/81801e72-d293-42e0-8871-5468e33b6d89.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   3%|▎         | 37/1224 [00:38<19:25,  1.02it/s]

Warning: File tcga_tnbc_data/56be281f-e85c-4dcb-9d75-cd9ae3430bbe.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   3%|▎         | 39/1224 [00:40<17:19,  1.14it/s]

Warning: File tcga_tnbc_data/50721c97-1a23-405b-b7b3-2955e4c62e5a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   3%|▎         | 40/1224 [00:41<17:03,  1.16it/s]

Warning: File tcga_tnbc_data/0e62a6d0-87a7-4efc-922f-753328694458.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/be65c37e-7aa8-466d-a1fe-102e8e25e2e9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   3%|▎         | 42/1224 [00:42<17:39,  1.12it/s]

Warning: File tcga_tnbc_data/f2a4b38d-bfc0-4363-9a58-b5fa2af26ff3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   4%|▎         | 43/1224 [00:43<17:15,  1.14it/s]

Warning: File tcga_tnbc_data/71ea0cc0-d979-4efd-a670-1e8e8a329aca.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   4%|▎         | 44/1224 [00:44<17:14,  1.14it/s]

Warning: File tcga_tnbc_data/222b562a-3ef7-4e69-a60d-54aac5104102.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   4%|▎         | 45/1224 [00:45<16:38,  1.18it/s]

Warning: File tcga_tnbc_data/3ce988e2-61c5-4f53-b9c8-cfc280649c1f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/0d11c50a-8648-48ea-a107-e138a1d3e086.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   4%|▍         | 46/1224 [00:46<16:06,  1.22it/s]

Warning: File tcga_tnbc_data/2e6baa15-85d7-43b0-8a89-a0dc169ae16a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   4%|▍         | 48/1224 [00:48<17:06,  1.15it/s]

Warning: File tcga_tnbc_data/08b0fe4c-ee3c-4510-b75a-6d240cb038cc.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/dbe79158-b616-4c7b-94d7-5f127b3013ff.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   4%|▍         | 49/1224 [00:48<16:53,  1.16it/s]

Warning: File tcga_tnbc_data/a436c52a-e63f-4d61-bc60-eb497c196489.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   4%|▍         | 50/1224 [00:49<17:38,  1.11it/s]

Warning: File tcga_tnbc_data/e4086c26-d200-4e42-8249-ed8cbeec0951.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   4%|▍         | 52/1224 [00:51<17:24,  1.12it/s]

Warning: File tcga_tnbc_data/08837ae7-6f4f-4aa1-8722-7c404b66ed75.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   4%|▍         | 53/1224 [00:52<18:26,  1.06it/s]

Warning: File tcga_tnbc_data/ad4b2d76-b4bb-457d-903f-823630a4d37b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   4%|▍         | 54/1224 [00:53<17:45,  1.10it/s]

Warning: File tcga_tnbc_data/1f9a9190-4157-457e-9794-a9217d2aa2f8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/c95841fa-ea90-4a12-99aa-5c342af9e0e8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   5%|▍         | 56/1224 [00:55<16:41,  1.17it/s]

Warning: File tcga_tnbc_data/cd417f4e-c065-4e73-a7c7-955b2fe71add.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/90cb5f76-ec86-4532-8352-e6622ef24980.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   5%|▍         | 58/1224 [00:56<16:10,  1.20it/s]

Warning: File tcga_tnbc_data/c71bfebf-e152-4706-bd72-07103f936a85.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   5%|▍         | 59/1224 [00:57<15:39,  1.24it/s]

Warning: File tcga_tnbc_data/ef227e3c-7a6d-4c43-945f-c1c7b410d50b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/76367cee-b571-49e5-8121-9e69f906c230.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   5%|▍         | 61/1224 [00:59<16:35,  1.17it/s]

Warning: File tcga_tnbc_data/537ec810-35bc-47d8-8242-72ef91cd63e0.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   5%|▌         | 62/1224 [01:00<16:22,  1.18it/s]

Warning: File tcga_tnbc_data/2a18db7b-b054-4210-b8cb-a647c26f90c1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/5599b7dd-7c2a-4037-ad77-11a0b4ddcb54.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   5%|▌         | 63/1224 [01:01<17:32,  1.10it/s]

Warning: File tcga_tnbc_data/2040d4e4-0ecb-4081-9478-9d2707833a1b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   5%|▌         | 64/1224 [01:02<17:33,  1.10it/s]

Warning: File tcga_tnbc_data/c15e9ead-0373-486e-a99b-26b96bd3ccc4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   5%|▌         | 66/1224 [01:03<16:58,  1.14it/s]

Warning: File tcga_tnbc_data/280141da-fd54-4901-bc15-5d106c56fb23.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   5%|▌         | 67/1224 [01:04<16:40,  1.16it/s]

Warning: File tcga_tnbc_data/81f86e31-55db-4483-b6e0-55451ffbd1db.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   6%|▌         | 68/1224 [01:05<16:39,  1.16it/s]

Warning: File tcga_tnbc_data/845def46-3502-40a8-aff1-8d021906cee5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   6%|▌         | 69/1224 [01:06<15:50,  1.22it/s]

Warning: File tcga_tnbc_data/8a7fe670-bcef-4fcb-9759-9892ff5f4f61.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   6%|▌         | 70/1224 [01:07<15:22,  1.25it/s]

Warning: File tcga_tnbc_data/1c74a1ed-8000-4dc0-970f-03831ca5e167.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/2faa9332-e577-4884-94e4-b895827db8b6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   6%|▌         | 71/1224 [01:07<14:58,  1.28it/s]

Warning: File tcga_tnbc_data/0c0ddcd7-8b4c-4489-b642-e48c4ab4602a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   6%|▌         | 72/1224 [01:08<15:48,  1.21it/s]

Warning: File tcga_tnbc_data/d757b1cc-31a6-495a-ae82-c63b031ece49.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   6%|▌         | 74/1224 [01:10<15:47,  1.21it/s]

Warning: File tcga_tnbc_data/ca6e4602-bcd4-4299-bd31-37f585658b8a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   6%|▌         | 75/1224 [01:11<15:12,  1.26it/s]

Warning: File tcga_tnbc_data/f2bf29d2-4c33-4810-90e8-88f37ea47bc8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/e25bb12b-f88b-41c5-951e-a36d4b94008f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   6%|▋         | 77/1224 [01:12<15:48,  1.21it/s]

Warning: File tcga_tnbc_data/71175258-a00a-4035-8f33-eb48bf04066f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/ff1f2f31-8607-4627-b487-c5e39e7c30f5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   6%|▋         | 78/1224 [01:13<15:36,  1.22it/s]

Warning: File tcga_tnbc_data/63454d5d-a654-4be0-b812-dd5c98d07ea1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   6%|▋         | 79/1224 [01:14<16:13,  1.18it/s]

Warning: File tcga_tnbc_data/e2a43c17-8973-49bc-a1f3-30afa26ef5f1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   7%|▋         | 80/1224 [01:15<16:59,  1.12it/s]

Warning: File tcga_tnbc_data/064215bd-9ec9-4a16-8ea2-9c6604156398.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   7%|▋         | 82/1224 [01:17<17:53,  1.06it/s]

Warning: File tcga_tnbc_data/fc1ea7f7-814a-43c5-a841-fb0c11734603.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   7%|▋         | 83/1224 [01:18<17:03,  1.11it/s]

Warning: File tcga_tnbc_data/2abc5233-1389-4efb-ba21-de05251ab25a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/ee447251-5c90-426f-a0c7-bd2041189761.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   7%|▋         | 84/1224 [01:19<17:03,  1.11it/s]

Warning: File tcga_tnbc_data/9684fb22-becb-44dc-8d84-4c8540507c8c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   7%|▋         | 85/1224 [01:20<17:32,  1.08it/s]

Warning: File tcga_tnbc_data/ad67e3a9-1751-4e6f-a962-2175f824f96d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   7%|▋         | 86/1224 [01:21<17:33,  1.08it/s]

Warning: File tcga_tnbc_data/75d5bcb2-3055-4b6a-822c-1aa37a9f1337.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   7%|▋         | 87/1224 [01:22<18:07,  1.05it/s]

Warning: File tcga_tnbc_data/befa225f-9fe9-412f-a503-449874cf52d8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   7%|▋         | 88/1224 [01:23<18:14,  1.04it/s]

Warning: File tcga_tnbc_data/92fc6274-1d0f-4e1c-a124-9e5135753d99.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   7%|▋         | 90/1224 [01:24<17:09,  1.10it/s]

Warning: File tcga_tnbc_data/6d488c27-ae90-41d4-8ddb-01a8eb731f0e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/26415014-f0fe-4b7c-b9dc-2a6f85d47a5e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   7%|▋         | 91/1224 [01:25<17:04,  1.11it/s]

Warning: File tcga_tnbc_data/64bfe46f-8152-4c70-b69d-ea412a4dfcff.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   8%|▊         | 92/1224 [01:26<17:13,  1.10it/s]

Warning: File tcga_tnbc_data/0648c6fc-df6d-450a-a5a0-e5655febbdf1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   8%|▊         | 93/1224 [01:27<17:18,  1.09it/s]

Warning: File tcga_tnbc_data/59980021-265a-4817-b7ea-02908a52cbcb.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   8%|▊         | 94/1224 [01:28<16:43,  1.13it/s]

Warning: File tcga_tnbc_data/4c9005a5-2cca-4cc3-9a6d-09eb76d780ab.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   8%|▊         | 96/1224 [01:30<16:07,  1.17it/s]

Warning: File tcga_tnbc_data/b6bbcd01-c1a3-42b8-afe7-c17b987903b0.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   8%|▊         | 97/1224 [01:30<15:51,  1.18it/s]

Warning: File tcga_tnbc_data/1a4e1855-911d-4eb4-bc77-547bc3b8e063.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   8%|▊         | 98/1224 [01:31<15:40,  1.20it/s]

Warning: File tcga_tnbc_data/3690d431-165d-40bb-af61-cfda445b3be8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/cba08218-0a7b-4425-8776-b240fac9b6cf.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   8%|▊         | 99/1224 [01:32<16:19,  1.15it/s]

Warning: File tcga_tnbc_data/0019c951-16c5-48d0-85c8-58d96b12d330.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   8%|▊         | 101/1224 [01:34<18:24,  1.02it/s]

Warning: File tcga_tnbc_data/2e753306-2df6-4666-b1ce-06992d109d02.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/e5393dc3-65d0-4d65-bb75-2fed770af595.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   8%|▊         | 102/1224 [01:35<17:35,  1.06it/s]

Warning: File tcga_tnbc_data/97dd05b6-58a9-43ab-9e03-faa105d2a700.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   8%|▊         | 103/1224 [01:36<16:53,  1.11it/s]

Warning: File tcga_tnbc_data/7f2773df-bece-43e0-94ff-46ba7dcf713e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   8%|▊         | 104/1224 [01:37<16:56,  1.10it/s]

Warning: File tcga_tnbc_data/bab81011-81b1-4fa4-bda1-fddec99245f5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   9%|▊         | 105/1224 [01:38<17:40,  1.05it/s]

Warning: File tcga_tnbc_data/9bb406c8-2b8e-410e-8bca-02a778312056.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   9%|▊         | 106/1224 [01:39<18:00,  1.03it/s]

Warning: File tcga_tnbc_data/23ac8b84-f000-45ea-ad35-a46323d3670a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   9%|▉         | 108/1224 [01:41<16:50,  1.10it/s]

Warning: File tcga_tnbc_data/a853d2bb-b696-493a-9451-59dcedde5f20.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/9e056a2a-a643-478a-b96c-85d5221f487a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   9%|▉         | 109/1224 [01:42<16:05,  1.16it/s]

Warning: File tcga_tnbc_data/3e8cff80-ed17-479c-8327-ca8e71ee7482.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   9%|▉         | 110/1224 [01:42<16:02,  1.16it/s]

Warning: File tcga_tnbc_data/0e1999e0-9c02-4804-88b6-60b46d100739.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   9%|▉         | 111/1224 [01:43<16:13,  1.14it/s]

Warning: File tcga_tnbc_data/385ddd6f-c126-4c4f-acde-1ef2d74d3639.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   9%|▉         | 112/1224 [01:44<15:57,  1.16it/s]

Warning: File tcga_tnbc_data/79bfddcc-1d7b-43a7-9221-8f230eca31d8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   9%|▉         | 114/1224 [01:46<15:07,  1.22it/s]

Warning: File tcga_tnbc_data/9dcf3c95-cc67-4a83-a2c8-12cbce82b9c4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/7acdca8d-6231-4077-b7ac-eec857c43092.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:   9%|▉         | 115/1224 [01:47<15:42,  1.18it/s]

Warning: File tcga_tnbc_data/db921dd3-3d39-4b42-b2ff-dbe0f6c9f093.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  10%|▉         | 117/1224 [01:48<15:21,  1.20it/s]

Warning: File tcga_tnbc_data/c6ec90b5-d323-4a55-b48a-c3acf38557ba.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/b46720bc-7f5a-4bf4-a2a3-3d9fe500d193.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  10%|▉         | 119/1224 [01:50<14:40,  1.25it/s]

Warning: File tcga_tnbc_data/3eadce70-ba3d-4806-b112-6ac83bc89dc4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/ed0aae7b-f815-4dc8-a98f-5844602cbaea.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  10%|▉         | 120/1224 [01:51<15:04,  1.22it/s]

Warning: File tcga_tnbc_data/58037e4a-a82f-42a9-84a1-715966343bd4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  10%|▉         | 121/1224 [01:52<15:25,  1.19it/s]

Warning: File tcga_tnbc_data/be002264-f534-49b3-90d1-fd5a3f622fb2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  10%|█         | 123/1224 [01:53<15:16,  1.20it/s]

Warning: File tcga_tnbc_data/acfa0ea5-3345-4734-9917-d3acc10d1a15.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/836f61df-2b3d-4e1f-abcc-37734091b746.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  10%|█         | 124/1224 [01:54<15:21,  1.19it/s]

Warning: File tcga_tnbc_data/b0cc3c29-89fe-4010-8f56-137f2b897bce.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  10%|█         | 125/1224 [01:55<16:26,  1.11it/s]

Warning: File tcga_tnbc_data/987603ab-513b-44d6-8b8e-344fd299a81a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  10%|█         | 126/1224 [01:56<16:28,  1.11it/s]

Warning: File tcga_tnbc_data/e3a49d98-c7d6-45a1-a8cb-33bab31186c2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  10%|█         | 127/1224 [01:57<17:01,  1.07it/s]

Warning: File tcga_tnbc_data/1b65bcb7-8170-4eb8-af93-c547b984c571.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  10%|█         | 128/1224 [01:58<17:06,  1.07it/s]

Warning: File tcga_tnbc_data/51aab02d-11b1-4ef3-a8f3-8146b6c24aad.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  11%|█         | 129/1224 [01:59<16:32,  1.10it/s]

Warning: File tcga_tnbc_data/2c74854f-4afe-48c3-9c81-d64634c14677.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  11%|█         | 131/1224 [02:01<16:40,  1.09it/s]

Warning: File tcga_tnbc_data/c8b0b391-320c-4fea-9b68-3070103cb148.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  11%|█         | 132/1224 [02:02<16:38,  1.09it/s]

Warning: File tcga_tnbc_data/cd47d9e9-8072-4681-93ac-6c1420f6624c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/98dc2008-d132-4a88-b428-45b0f715b296.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  11%|█         | 133/1224 [02:02<16:40,  1.09it/s]

Warning: File tcga_tnbc_data/b8c05229-16e4-4888-9f44-556c5570a4af.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  11%|█         | 134/1224 [02:03<16:33,  1.10it/s]

Warning: File tcga_tnbc_data/df416c2a-523d-4409-98ac-b0900584a065.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  11%|█         | 135/1224 [02:04<16:55,  1.07it/s]

Warning: File tcga_tnbc_data/da2cff7a-9b9d-4ae8-aa49-d717a77906e1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  11%|█         | 136/1224 [02:05<17:35,  1.03it/s]

Warning: File tcga_tnbc_data/0e56b380-a3d6-4e81-8299-9f8a62330d7b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  11%|█         | 137/1224 [02:06<17:24,  1.04it/s]

Warning: File tcga_tnbc_data/25294e7a-1f15-411c-a2fd-93097e387db2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  11%|█▏        | 138/1224 [02:07<16:26,  1.10it/s]

Warning: File tcga_tnbc_data/046fe29e-7c99-4093-8565-f2f205a00796.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  11%|█▏        | 139/1224 [02:08<16:01,  1.13it/s]

Warning: File tcga_tnbc_data/ccaa907b-71d5-467e-ace4-f2ea16109202.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  11%|█▏        | 140/1224 [02:09<15:50,  1.14it/s]

Warning: File tcga_tnbc_data/e64c5a32-13c4-495e-ab4c-b5000332c09d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  12%|█▏        | 141/1224 [02:10<15:47,  1.14it/s]

Warning: File tcga_tnbc_data/e173c170-b7c6-4aa9-9f34-33cd02702d75.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  12%|█▏        | 142/1224 [02:11<15:50,  1.14it/s]

Warning: File tcga_tnbc_data/45702d4f-2d23-4e37-88ad-565e44a18fa2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  12%|█▏        | 143/1224 [02:11<15:50,  1.14it/s]

Warning: File tcga_tnbc_data/842b0c9e-a03d-4074-b0fe-be8d0e056c7d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  12%|█▏        | 144/1224 [02:12<15:37,  1.15it/s]

Warning: File tcga_tnbc_data/c003fb3b-179c-49b0-8d9a-656c4dc39901.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  12%|█▏        | 146/1224 [02:14<15:40,  1.15it/s]

Warning: File tcga_tnbc_data/519b92e0-0dbc-471c-988f-48ce9dc95be3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/0c068d5a-ccad-47a5-bfe0-0dc5f136d6aa.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  12%|█▏        | 147/1224 [02:15<15:26,  1.16it/s]

Warning: File tcga_tnbc_data/a8ab2eb8-9da3-494f-b740-dc3f4185acb2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  12%|█▏        | 148/1224 [02:16<15:45,  1.14it/s]

Warning: File tcga_tnbc_data/6fe2f370-6592-4d85-992c-1b5449a62dbe.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  12%|█▏        | 149/1224 [02:17<16:46,  1.07it/s]

Warning: File tcga_tnbc_data/d9b6b523-00de-4638-a3f3-8de841fb7183.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  12%|█▏        | 151/1224 [02:19<15:56,  1.12it/s]

Warning: File tcga_tnbc_data/66dbe196-661b-4d0e-ac48-b82fc6a67cc8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/80902247-a485-4374-836b-4b67db4c4981.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  12%|█▏        | 152/1224 [02:19<15:36,  1.15it/s]

Warning: File tcga_tnbc_data/ef3ba95e-2251-43a6-8910-2bdfb02d22be.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  12%|█▎        | 153/1224 [02:20<15:36,  1.14it/s]

Warning: File tcga_tnbc_data/5b6828f2-4da6-49a4-a19c-569e089ff0b0.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  13%|█▎        | 154/1224 [02:21<16:18,  1.09it/s]

Warning: File tcga_tnbc_data/9218f3a6-1ae1-4898-8be4-2335a204aae7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  13%|█▎        | 155/1224 [02:22<16:36,  1.07it/s]

Warning: File tcga_tnbc_data/5711aa8f-5cd6-41d0-b469-40f049556693.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  13%|█▎        | 156/1224 [02:23<16:48,  1.06it/s]

Warning: File tcga_tnbc_data/c3f4adee-86da-42fa-b37a-d48d66f89e09.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  13%|█▎        | 157/1224 [02:24<17:08,  1.04it/s]

Warning: File tcga_tnbc_data/c9ff3787-de6e-4535-be34-6425ccf9079f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  13%|█▎        | 158/1224 [02:25<16:52,  1.05it/s]

Warning: File tcga_tnbc_data/e1a528ee-1bec-4aa5-bb9c-9d0af3ba4108.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  13%|█▎        | 159/1224 [02:26<16:29,  1.08it/s]

Warning: File tcga_tnbc_data/e06eeb14-0ebf-453f-847b-b1ae63fe8194.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  13%|█▎        | 160/1224 [02:27<17:03,  1.04it/s]

Warning: File tcga_tnbc_data/406cb497-badd-4bbe-be62-e1dac7b49180.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  13%|█▎        | 161/1224 [02:28<17:59,  1.02s/it]

Warning: File tcga_tnbc_data/0e9ea184-c4bc-43f0-817c-8a950008e4bd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  13%|█▎        | 162/1224 [02:29<17:38,  1.00it/s]

Warning: File tcga_tnbc_data/9cbb73a5-7b3b-4559-a295-d4693ae6dee2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  13%|█▎        | 163/1224 [02:30<19:11,  1.08s/it]

Warning: File tcga_tnbc_data/2aa3a845-cce2-4fe2-92f7-1fece9e619d5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  13%|█▎        | 164/1224 [02:31<17:58,  1.02s/it]

Warning: File tcga_tnbc_data/1a4285b8-765b-4954-b9f2-dc8609572889.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  13%|█▎        | 165/1224 [02:32<17:35,  1.00it/s]

Warning: File tcga_tnbc_data/b9d564b4-4561-44b2-b020-baf106f23baa.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  14%|█▎        | 166/1224 [02:33<16:34,  1.06it/s]

Warning: File tcga_tnbc_data/783b4e4f-d65d-4025-a7ce-99a7e86255e9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  14%|█▎        | 167/1224 [02:34<15:53,  1.11it/s]

Warning: File tcga_tnbc_data/deb932e6-470e-4fae-88f1-efb2e820325e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  14%|█▎        | 168/1224 [02:35<15:35,  1.13it/s]

Warning: File tcga_tnbc_data/ae2e0936-a225-491b-8361-3c20663768d9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  14%|█▍        | 169/1224 [02:36<15:33,  1.13it/s]

Warning: File tcga_tnbc_data/da333184-1ddd-4cd7-9c0d-e4526a03a1c9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  14%|█▍        | 170/1224 [02:36<15:18,  1.15it/s]

Warning: File tcga_tnbc_data/6df72103-ccfb-4a53-b839-2e8c47ec2145.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  14%|█▍        | 172/1224 [02:38<14:47,  1.19it/s]

Warning: File tcga_tnbc_data/04e03ae1-b2f3-446d-862d-172fea6320de.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/542856ab-164d-4edd-833a-925da96d1eeb.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  14%|█▍        | 173/1224 [02:39<14:54,  1.17it/s]

Warning: File tcga_tnbc_data/06227b3b-56d0-4657-bb37-8f56a3dc15f7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  14%|█▍        | 174/1224 [02:40<15:05,  1.16it/s]

Warning: File tcga_tnbc_data/068841a8-af6a-4925-bad0-586005f59521.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  14%|█▍        | 175/1224 [02:41<15:02,  1.16it/s]

Warning: File tcga_tnbc_data/59ce4079-0da6-4339-8861-ad376b150f75.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  14%|█▍        | 176/1224 [02:42<15:07,  1.15it/s]

Warning: File tcga_tnbc_data/98ca3aa5-f509-4e55-a184-12e44c8c8464.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  14%|█▍        | 177/1224 [02:43<15:38,  1.12it/s]

Warning: File tcga_tnbc_data/7286a685-17ef-4ef5-9b7b-2696c6e7e1a6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  15%|█▍        | 178/1224 [02:43<15:14,  1.14it/s]

Warning: File tcga_tnbc_data/e855de31-6adc-423f-9295-3064f2449f35.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  15%|█▍        | 180/1224 [02:45<15:01,  1.16it/s]

Warning: File tcga_tnbc_data/4bb6eb79-4256-4b19-b158-883da969a582.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/f7a47166-9593-4a37-b95a-2de86b6d65c9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  15%|█▍        | 182/1224 [02:47<14:02,  1.24it/s]

Warning: File tcga_tnbc_data/aabb4a65-aff2-4f78-a969-bacbe5b80856.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/fe7dfda5-6846-4238-9ccc-472978eb78a1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  15%|█▍        | 183/1224 [02:48<14:18,  1.21it/s]

Warning: File tcga_tnbc_data/54a6b5bc-f788-4bea-b92c-e4dc9c71d99e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  15%|█▌        | 184/1224 [02:48<14:19,  1.21it/s]

Warning: File tcga_tnbc_data/f63a40ad-26af-48d6-bb36-91fd91d32e6b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  15%|█▌        | 185/1224 [02:49<14:19,  1.21it/s]

Warning: File tcga_tnbc_data/89e67cfd-7728-4a0e-bfa5-4c55ae957ef8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  15%|█▌        | 186/1224 [02:50<14:19,  1.21it/s]

Warning: File tcga_tnbc_data/40d222ea-3a59-45b9-91a2-0566b239c89e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  15%|█▌        | 187/1224 [02:51<14:54,  1.16it/s]

Warning: File tcga_tnbc_data/fa48dda4-5b65-44fa-b0c3-b02d53d928c5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  15%|█▌        | 188/1224 [02:52<14:53,  1.16it/s]

Warning: File tcga_tnbc_data/6c3f2469-50ea-48a7-bb17-043e74e54535.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  15%|█▌        | 189/1224 [02:53<15:04,  1.14it/s]

Warning: File tcga_tnbc_data/a25f8ce5-b3f3-4d2d-b862-b703650066fb.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  16%|█▌        | 190/1224 [02:54<15:29,  1.11it/s]

Warning: File tcga_tnbc_data/88a16056-cc45-4fee-99e0-f7fc7e1971df.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  16%|█▌        | 191/1224 [02:55<15:36,  1.10it/s]

Warning: File tcga_tnbc_data/ccc7b8e5-7ea4-4efc-81c1-ef6c15acd241.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  16%|█▌        | 192/1224 [02:56<15:52,  1.08it/s]

Warning: File tcga_tnbc_data/9a6563cf-557b-4f26-b6a2-6c6f1eb03654.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  16%|█▌        | 193/1224 [02:56<15:31,  1.11it/s]

Warning: File tcga_tnbc_data/05aa6d12-6d48-4ecb-8211-036e647ef72e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  16%|█▌        | 195/1224 [02:58<15:39,  1.10it/s]

Warning: File tcga_tnbc_data/4f4862e1-abfc-4577-bdb2-a96759ef2b53.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/d52eff00-a7b7-42f0-82fe-ec4c054b1dd9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  16%|█▌        | 197/1224 [03:00<15:58,  1.07it/s]

Warning: File tcga_tnbc_data/1aa289bb-8ac9-4e9e-be61-3164afbe06a2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/dc8b305a-6f43-410e-9ce6-96ac24827550.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  16%|█▌        | 198/1224 [03:01<15:31,  1.10it/s]

Warning: File tcga_tnbc_data/22fdb34e-9f50-4382-9800-e6e35773c538.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  16%|█▋        | 200/1224 [03:03<15:08,  1.13it/s]

Warning: File tcga_tnbc_data/195c9f03-31c3-465a-ac58-3949246b173b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/c0f6d246-c872-41a5-8135-2bdbdb1f924f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  16%|█▋        | 201/1224 [03:04<15:08,  1.13it/s]

Warning: File tcga_tnbc_data/010e405c-b91d-4046-898e-105d5830d9a9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  17%|█▋        | 202/1224 [03:04<14:53,  1.14it/s]

Warning: File tcga_tnbc_data/eedfb6fb-3db6-4eae-8c6c-8b6722ae72b6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  17%|█▋        | 203/1224 [03:05<14:44,  1.15it/s]

Warning: File tcga_tnbc_data/1c386dc6-8279-4156-bd7c-47e2f8af27bf.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  17%|█▋        | 204/1224 [03:06<15:01,  1.13it/s]

Warning: File tcga_tnbc_data/7efb7266-28ee-41d3-912a-b0f67135216f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  17%|█▋        | 205/1224 [03:07<14:59,  1.13it/s]

Warning: File tcga_tnbc_data/92dd3ded-2b51-4d1d-8c8a-09ed1f0b16ed.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  17%|█▋        | 206/1224 [03:08<15:28,  1.10it/s]

Warning: File tcga_tnbc_data/eba83203-1de1-447a-88d0-2ffbccc24990.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  17%|█▋        | 208/1224 [03:10<15:44,  1.08it/s]

Warning: File tcga_tnbc_data/e24e6f7c-49c1-498e-b269-4bee014007af.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/7b4d770a-2b8c-4ca5-bf51-c4745c5de39a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  17%|█▋        | 209/1224 [03:11<14:50,  1.14it/s]

Warning: File tcga_tnbc_data/bb761704-bced-4fd6-9a90-187595b1d005.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  17%|█▋        | 211/1224 [03:12<14:35,  1.16it/s]

Warning: File tcga_tnbc_data/56209bc1-f94b-4aa4-a9dd-757003f36fd2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  17%|█▋        | 212/1224 [03:13<14:32,  1.16it/s]

Warning: File tcga_tnbc_data/2ce2b916-b768-424c-a57b-96ab4a77276e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  17%|█▋        | 213/1224 [03:14<13:59,  1.20it/s]

Warning: File tcga_tnbc_data/c7571e35-d912-4935-b2c3-bbba019fe9f8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/8e475a5c-0a90-4c31-a472-b1ae0946633d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  18%|█▊        | 215/1224 [03:16<13:47,  1.22it/s]

Warning: File tcga_tnbc_data/6a40f728-eee2-4777-a8e0-67fd6f9f7927.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/b3b6d3bf-426f-4720-9adb-98783faa0eff.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  18%|█▊        | 216/1224 [03:16<13:31,  1.24it/s]

Warning: File tcga_tnbc_data/1cf56202-05e5-41ad-9f27-3519bee045f4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  18%|█▊        | 217/1224 [03:17<13:41,  1.23it/s]

Warning: File tcga_tnbc_data/b0e906d2-e2ae-49fa-8d7a-8a00f1d6d0a1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  18%|█▊        | 218/1224 [03:18<14:28,  1.16it/s]

Warning: File tcga_tnbc_data/ed76d903-de08-4060-ab15-b4add3c551f0.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  18%|█▊        | 219/1224 [03:19<14:39,  1.14it/s]

Warning: File tcga_tnbc_data/cf53cdad-a323-475e-a84a-87b68d13e262.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  18%|█▊        | 220/1224 [03:20<14:47,  1.13it/s]

Warning: File tcga_tnbc_data/e3e56a3c-5a8b-419e-8904-194a2fdfa550.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  18%|█▊        | 222/1224 [03:22<13:36,  1.23it/s]

Warning: File tcga_tnbc_data/96e54b36-0b71-4ad0-9b21-72668708fc62.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/d0dcec39-c407-4593-98e3-133714cf2f7b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  18%|█▊        | 223/1224 [03:23<14:06,  1.18it/s]

Warning: File tcga_tnbc_data/bd86e2d9-6098-4f78-9e9b-f2f95367c739.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  18%|█▊        | 225/1224 [03:24<13:33,  1.23it/s]

Warning: File tcga_tnbc_data/664d7ba8-9b87-4f17-b98d-8e07dea3c488.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/c782b873-2727-4fe4-9c9a-741964290349.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  19%|█▊        | 227/1224 [03:26<13:30,  1.23it/s]

Warning: File tcga_tnbc_data/d56cbe4c-2158-4f78-a545-d5c963a22978.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/2cd221ee-4d29-4f40-ab4c-780cc9045c5a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  19%|█▊        | 228/1224 [03:26<13:20,  1.24it/s]

Warning: File tcga_tnbc_data/f43b97fd-8953-4a5e-bafb-eb572145abe3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  19%|█▊        | 229/1224 [03:27<14:09,  1.17it/s]

Warning: File tcga_tnbc_data/1936f1a9-66bc-4e48-8189-f0e3a67a5593.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  19%|█▉        | 230/1224 [03:28<14:13,  1.16it/s]

Warning: File tcga_tnbc_data/0caa1750-ec80-484f-9097-1e90fbfa41c2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  19%|█▉        | 231/1224 [03:29<14:29,  1.14it/s]

Warning: File tcga_tnbc_data/4cafa8be-69f1-4c1a-87fb-c71df6de6a74.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  19%|█▉        | 232/1224 [03:30<14:24,  1.15it/s]

Warning: File tcga_tnbc_data/4662f2d3-edd6-4260-a4ad-04c46ca54443.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  19%|█▉        | 233/1224 [03:31<14:50,  1.11it/s]

Warning: File tcga_tnbc_data/b9bdb9d3-4d2b-4a53-9804-d0511174e553.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  19%|█▉        | 234/1224 [03:32<15:05,  1.09it/s]

Warning: File tcga_tnbc_data/cdfe79d9-a0bd-4700-937f-07bd0ee51d73.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  19%|█▉        | 235/1224 [03:33<15:16,  1.08it/s]

Warning: File tcga_tnbc_data/f8b403a1-37cf-4acb-b5d7-b3437fafa7f8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  19%|█▉        | 236/1224 [03:34<15:03,  1.09it/s]

Warning: File tcga_tnbc_data/6d505305-dc5f-4dc7-8721-817f444ff7ee.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  19%|█▉        | 237/1224 [03:35<14:44,  1.12it/s]

Warning: File tcga_tnbc_data/e37e5793-921d-4930-8f22-ddcd5f881fe6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  19%|█▉        | 238/1224 [03:36<15:16,  1.08it/s]

Warning: File tcga_tnbc_data/307261f2-f88f-4658-b6d1-98ef946148e2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  20%|█▉        | 239/1224 [03:37<15:00,  1.09it/s]

Warning: File tcga_tnbc_data/23bf74db-bb4e-44c5-8473-e651b818e460.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  20%|█▉        | 240/1224 [03:38<14:59,  1.09it/s]

Warning: File tcga_tnbc_data/2d75b6a1-0f93-4c6a-9554-73a214969c6b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  20%|█▉        | 241/1224 [03:38<14:16,  1.15it/s]

Warning: File tcga_tnbc_data/040d00da-2bc9-49d4-bf6c-b4515b6a2bbf.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  20%|█▉        | 242/1224 [03:39<14:22,  1.14it/s]

Warning: File tcga_tnbc_data/15d7e135-acb7-46ef-a8b1-f424e40a9e4d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  20%|█▉        | 243/1224 [03:40<14:41,  1.11it/s]

Warning: File tcga_tnbc_data/a39993c2-0b95-4df1-b501-b1a746633449.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  20%|██        | 245/1224 [03:42<13:53,  1.17it/s]

Warning: File tcga_tnbc_data/aa2ab118-b3cc-4452-a29c-104f80f16f8d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/a04fdd52-6d4c-4dc6-b63d-fa67ecfe4744.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  20%|██        | 246/1224 [03:43<14:46,  1.10it/s]

Warning: File tcga_tnbc_data/4bfe1281-919d-47ee-afc7-2b373b113674.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  20%|██        | 247/1224 [03:44<14:48,  1.10it/s]

Warning: File tcga_tnbc_data/e8d97ce6-190e-4189-a148-5a8d9f4215c3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  20%|██        | 248/1224 [03:45<14:44,  1.10it/s]

Warning: File tcga_tnbc_data/0427af63-b665-4c57-874b-65222c200bfe.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  20%|██        | 249/1224 [03:46<15:02,  1.08it/s]

Warning: File tcga_tnbc_data/c4ceaaf8-4803-45d7-9937-42d25db60148.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  21%|██        | 251/1224 [03:47<14:17,  1.13it/s]

Warning: File tcga_tnbc_data/363736c4-cc2d-4920-a10b-bd0de899cdb1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/c4241ab5-95b7-4870-aaed-55541756c42f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  21%|██        | 253/1224 [03:49<13:38,  1.19it/s]

Warning: File tcga_tnbc_data/6ac73ea5-48e8-40d8-8383-fa28991813fd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  21%|██        | 254/1224 [03:50<13:07,  1.23it/s]

Warning: File tcga_tnbc_data/e38111a3-54f9-4229-8803-fc74e0c12c55.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  21%|██        | 255/1224 [03:50<13:11,  1.22it/s]

Warning: File tcga_tnbc_data/fd4bd1de-fc4a-42bc-aca5-5ac16ec14118.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/d5120825-ab1f-446c-af1e-3be57846a15b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  21%|██        | 256/1224 [03:51<13:11,  1.22it/s]

Warning: File tcga_tnbc_data/0ca579b1-763e-4f6a-a071-c6514aaa2f11.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  21%|██        | 257/1224 [03:52<12:52,  1.25it/s]

Warning: File tcga_tnbc_data/bc39baa2-786e-4d9a-874e-a7f4febc3be2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  21%|██        | 258/1224 [03:53<12:28,  1.29it/s]

Warning: File tcga_tnbc_data/f45af277-1f94-4cdd-97d4-8ccdbd7ff18e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  21%|██        | 259/1224 [03:54<13:19,  1.21it/s]

Warning: File tcga_tnbc_data/3fafe34a-38e2-4645-af4e-0d77fd5464c1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  21%|██        | 260/1224 [03:54<13:19,  1.21it/s]

Warning: File tcga_tnbc_data/3173d46f-7344-41e4-bd4c-027fe5b5ec06.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  21%|██▏       | 261/1224 [03:55<13:33,  1.18it/s]

Warning: File tcga_tnbc_data/f69ca0e5-201f-4066-81a5-c5b9c8a5012c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  21%|██▏       | 262/1224 [03:56<13:40,  1.17it/s]

Warning: File tcga_tnbc_data/7140b89b-50b6-42ed-a69d-1cbc7901d530.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  21%|██▏       | 263/1224 [03:57<14:57,  1.07it/s]

Warning: File tcga_tnbc_data/d3badb09-df1e-488e-ade9-97f1925b5649.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  22%|██▏       | 264/1224 [03:58<14:36,  1.10it/s]

Warning: File tcga_tnbc_data/c4a9a1df-4397-409e-85ec-30e0789377c2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  22%|██▏       | 265/1224 [03:59<15:00,  1.06it/s]

Warning: File tcga_tnbc_data/309dcac2-7efa-467c-9dc7-222c130b0fec.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  22%|██▏       | 267/1224 [04:01<13:44,  1.16it/s]

Warning: File tcga_tnbc_data/ccb87d7a-2729-4017-bc17-10e5a67bd5cc.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  22%|██▏       | 268/1224 [04:02<13:59,  1.14it/s]

Warning: File tcga_tnbc_data/e58f3dde-82f6-4a5d-9909-8f5659a26915.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/0a7dc8b9-4196-41d3-ada1-a50cb36bfd2b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  22%|██▏       | 269/1224 [04:02<13:25,  1.18it/s]

Warning: File tcga_tnbc_data/8c600781-5238-4b46-80bc-aa2710c1ed3f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  22%|██▏       | 271/1224 [04:04<13:52,  1.14it/s]

Warning: File tcga_tnbc_data/6487c7e6-38ad-417c-8009-6c899fe74a64.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/416defdf-a4f7-4305-97ff-d3b3ebce672f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  22%|██▏       | 272/1224 [04:05<13:59,  1.13it/s]

Warning: File tcga_tnbc_data/0a06329d-82cd-41a9-822e-43cfd49e63a2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  22%|██▏       | 273/1224 [04:06<13:59,  1.13it/s]

Warning: File tcga_tnbc_data/50260fba-c435-480a-9bb8-f2839ba499a4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  22%|██▏       | 274/1224 [04:07<14:12,  1.11it/s]

Warning: File tcga_tnbc_data/4e98f490-cbdf-4864-8cc3-b5f9d3c95146.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  22%|██▏       | 275/1224 [04:08<13:48,  1.14it/s]

Warning: File tcga_tnbc_data/e2b3728b-9827-4a13-b52c-caabd58f902e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  23%|██▎       | 276/1224 [04:09<13:53,  1.14it/s]

Warning: File tcga_tnbc_data/7be570ba-7f69-431e-88c2-614e92bc88ae.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  23%|██▎       | 277/1224 [04:10<14:32,  1.08it/s]

Warning: File tcga_tnbc_data/68814d4d-9db8-471f-b4b3-5c2fecb10773.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  23%|██▎       | 278/1224 [04:11<14:27,  1.09it/s]

Warning: File tcga_tnbc_data/0094f9d0-45ec-4aad-bca0-71c60bdd7113.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  23%|██▎       | 279/1224 [04:12<14:28,  1.09it/s]

Warning: File tcga_tnbc_data/be6f8b24-e668-41c6-89f7-f4cdc8533cae.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  23%|██▎       | 280/1224 [04:13<15:17,  1.03it/s]

Warning: File tcga_tnbc_data/c8c7b9cc-7015-4405-a7f5-f60587de285a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  23%|██▎       | 282/1224 [04:14<14:05,  1.11it/s]

Warning: File tcga_tnbc_data/c95a37a1-d3cd-421c-bc5f-0f8dc448f64c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/97387357-c741-43a6-9b3a-55c925f9a516.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  23%|██▎       | 283/1224 [04:15<13:40,  1.15it/s]

Warning: File tcga_tnbc_data/d914654b-ec4f-4be5-a525-2997a4b39279.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  23%|██▎       | 284/1224 [04:16<13:18,  1.18it/s]

Warning: File tcga_tnbc_data/5113a198-1bfe-4d4e-8e17-4c8e3359061a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  23%|██▎       | 285/1224 [04:17<13:20,  1.17it/s]

Warning: File tcga_tnbc_data/6129ca9a-5466-4cf5-be19-a4e3134659cb.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  23%|██▎       | 287/1224 [04:18<12:45,  1.22it/s]

Warning: File tcga_tnbc_data/9c99e8d0-a96d-4252-8ea8-e15bfae278c3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/e21262db-a694-4461-b1b0-e52c0891113a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  24%|██▎       | 288/1224 [04:19<12:53,  1.21it/s]

Warning: File tcga_tnbc_data/7d0189e8-9726-439a-b5e4-b650bc33794b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  24%|██▎       | 289/1224 [04:20<12:54,  1.21it/s]

Warning: File tcga_tnbc_data/1dacccf9-58ae-490f-9f3f-31c82f93b3b8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  24%|██▎       | 290/1224 [04:21<13:09,  1.18it/s]

Warning: File tcga_tnbc_data/79d67844-5389-40ee-a1fd-5b19ecf81b73.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  24%|██▍       | 291/1224 [04:22<13:15,  1.17it/s]

Warning: File tcga_tnbc_data/9e5ecae5-faf0-41a2-a795-d1b4db79486a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  24%|██▍       | 292/1224 [04:23<13:36,  1.14it/s]

Warning: File tcga_tnbc_data/5755f322-5df5-4b88-9c79-640167775c12.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  24%|██▍       | 293/1224 [04:24<13:16,  1.17it/s]

Warning: File tcga_tnbc_data/4c941474-f3e0-4735-bad0-cff8894fb08d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  24%|██▍       | 294/1224 [04:24<13:04,  1.19it/s]

Warning: File tcga_tnbc_data/1320db11-22a5-417f-8ec7-65c0bf4681a2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  24%|██▍       | 296/1224 [04:26<13:02,  1.19it/s]

Warning: File tcga_tnbc_data/c9920595-31f2-4977-b6bd-c0fa3ffcf461.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/9b2a1467-775c-48cf-9a3c-e259ccd344e4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  24%|██▍       | 297/1224 [04:27<12:37,  1.22it/s]

Warning: File tcga_tnbc_data/f6565f25-4317-4615-a437-af79da929ecd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  24%|██▍       | 298/1224 [04:28<13:10,  1.17it/s]

Warning: File tcga_tnbc_data/e94299a9-67bc-4c30-963c-1476fbb7d5ff.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  24%|██▍       | 299/1224 [04:29<13:03,  1.18it/s]

Warning: File tcga_tnbc_data/5405b59e-44cc-4745-b838-ca279210cbed.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  25%|██▍       | 301/1224 [04:30<13:11,  1.17it/s]

Warning: File tcga_tnbc_data/8ced7ce3-86ec-4bc8-afce-8fcfb06d8be4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/934aa789-6d42-4b2d-8a74-7d482d79ed8b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  25%|██▍       | 302/1224 [04:31<13:28,  1.14it/s]

Warning: File tcga_tnbc_data/56e43b33-6dc7-496b-bdee-75e5fed5d502.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  25%|██▍       | 303/1224 [04:32<13:21,  1.15it/s]

Warning: File tcga_tnbc_data/fad07753-c9c6-4eba-8f43-09740bff6d69.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  25%|██▍       | 304/1224 [04:33<13:26,  1.14it/s]

Warning: File tcga_tnbc_data/dafb2454-1ea7-4cb6-8b3b-2b5b6f19aa89.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  25%|██▍       | 305/1224 [04:34<13:24,  1.14it/s]

Warning: File tcga_tnbc_data/19264a73-b106-4b24-be01-0a9a137c6de9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  25%|██▌       | 306/1224 [04:35<13:46,  1.11it/s]

Warning: File tcga_tnbc_data/131d96e3-0799-4956-a752-dc244a05c493.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  25%|██▌       | 307/1224 [04:36<13:50,  1.10it/s]

Warning: File tcga_tnbc_data/5e05ff45-9f44-484d-889f-529e2bfe2a48.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  25%|██▌       | 308/1224 [04:37<13:36,  1.12it/s]

Warning: File tcga_tnbc_data/f6cb208f-cc43-4245-8392-dc5ada57bb9b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  25%|██▌       | 310/1224 [04:38<12:32,  1.22it/s]

Warning: File tcga_tnbc_data/d14d5953-f379-4adb-9a1b-028f91b1a9e6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/09f9ebad-e7cd-4c20-9eab-8fd2066d9051.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  25%|██▌       | 311/1224 [04:39<12:33,  1.21it/s]

Warning: File tcga_tnbc_data/fc203d80-6254-402c-8c8b-a5500bfa909e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  26%|██▌       | 313/1224 [04:41<12:36,  1.20it/s]

Warning: File tcga_tnbc_data/e748021e-b8ec-4b17-8b59-ce9d0a3d42e1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/e20d0db7-984a-4bcf-9f1e-54ec63d55a2f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  26%|██▌       | 314/1224 [04:41<12:29,  1.21it/s]

Warning: File tcga_tnbc_data/0c279a15-1250-4923-bcde-96cc3fd32d42.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  26%|██▌       | 315/1224 [04:42<12:38,  1.20it/s]

Warning: File tcga_tnbc_data/e8149278-3269-4dbe-9500-7045fd56cd2f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  26%|██▌       | 316/1224 [04:43<12:53,  1.17it/s]

Warning: File tcga_tnbc_data/eb914a22-6e3f-4296-89d4-a960902fba2b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  26%|██▌       | 317/1224 [04:44<13:05,  1.15it/s]

Warning: File tcga_tnbc_data/b4835808-46fa-4b6c-a933-92acc9908319.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  26%|██▌       | 319/1224 [04:46<12:24,  1.22it/s]

Warning: File tcga_tnbc_data/e0b65eec-7c30-4607-9cae-c8e8463c80c5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/63adf5e2-d5cb-4937-a0ee-f2914e130b25.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  26%|██▌       | 320/1224 [04:47<13:03,  1.15it/s]

Warning: File tcga_tnbc_data/2a73a18d-eca4-475b-9c37-283feb92915f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  26%|██▋       | 322/1224 [04:49<14:18,  1.05it/s]

Warning: File tcga_tnbc_data/e4e099ea-7207-48b8-a578-d5e6d83054b0.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  26%|██▋       | 323/1224 [04:50<13:39,  1.10it/s]

Warning: File tcga_tnbc_data/dcac8f3c-d282-4ac9-9194-b1461966c795.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/fd121fe6-7529-4a92-a324-2186622180b3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  27%|██▋       | 325/1224 [04:51<12:48,  1.17it/s]

Warning: File tcga_tnbc_data/12b68e56-a83f-4b65-bb66-59e8522acbc9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/75a7e5eb-1db8-4858-9a9f-78abea32ccd4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  27%|██▋       | 327/1224 [04:53<12:28,  1.20it/s]

Warning: File tcga_tnbc_data/2e7a0005-4efb-4121-91d9-c2ca2cb5201d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/ffeede9a-d9a9-4836-8c56-39f12a5fde0e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  27%|██▋       | 328/1224 [04:54<12:10,  1.23it/s]

Warning: File tcga_tnbc_data/6d0f2c52-47f8-4032-8468-38dcc578ed6a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  27%|██▋       | 330/1224 [04:55<11:42,  1.27it/s]

Warning: File tcga_tnbc_data/5b318f75-dda6-4410-bfc0-2fd52030cae7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/abefed1d-9f40-4a97-9435-4d9df47f7ebd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  27%|██▋       | 331/1224 [04:56<12:17,  1.21it/s]

Warning: File tcga_tnbc_data/95775d9a-4f7f-47c9-806b-acea8e01d40e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  27%|██▋       | 333/1224 [04:58<12:59,  1.14it/s]

Warning: File tcga_tnbc_data/a572e59c-096f-4054-bbb4-90f2e2461d99.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/c94fb480-7f46-4c24-bcb1-26f66a57c45a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  27%|██▋       | 334/1224 [04:59<12:59,  1.14it/s]

Warning: File tcga_tnbc_data/80c3e656-26e4-4b45-acce-fac1a0c09d28.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  27%|██▋       | 336/1224 [05:01<13:38,  1.09it/s]

Warning: File tcga_tnbc_data/3e0cc1e4-0882-4e9b-9373-34bcbce097d7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  28%|██▊       | 337/1224 [05:02<13:37,  1.08it/s]

Warning: File tcga_tnbc_data/892928f7-8239-4d15-812b-046f9192d7de.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  28%|██▊       | 338/1224 [05:02<13:00,  1.14it/s]

Warning: File tcga_tnbc_data/d2a12641-a25f-4aab-99a4-433cf664ae73.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  28%|██▊       | 339/1224 [05:03<12:36,  1.17it/s]

Warning: File tcga_tnbc_data/893122aa-117b-49a4-a81c-1229dde4d78a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/9cf6e387-2b87-4f53-bb5a-d545a78f21cd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  28%|██▊       | 341/1224 [05:05<12:23,  1.19it/s]

Warning: File tcga_tnbc_data/270356b5-f258-49b3-a850-16ea88ec6c76.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  28%|██▊       | 342/1224 [05:06<12:10,  1.21it/s]

Warning: File tcga_tnbc_data/8603da6b-3bb9-4fff-b409-c5af2afd53b3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  28%|██▊       | 343/1224 [05:06<11:53,  1.23it/s]

Warning: File tcga_tnbc_data/4dc3285f-fd32-4a3e-ad59-28597ab5323a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  28%|██▊       | 344/1224 [05:07<11:26,  1.28it/s]

Warning: File tcga_tnbc_data/0f1bec43-6235-4390-a148-e7038126c0c8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/2c3000b7-4db9-4f00-a82a-ca6802806631.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  28%|██▊       | 345/1224 [05:08<12:12,  1.20it/s]

Warning: File tcga_tnbc_data/11631339-f447-4b28-97a8-3c7c6ccbc843.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  28%|██▊       | 347/1224 [05:10<12:17,  1.19it/s]

Warning: File tcga_tnbc_data/99ce2ebd-7a50-4808-ba75-8626ad6d7cfd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/2dc5eb24-fb84-455a-ae05-3b58ad2fc284.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  28%|██▊       | 348/1224 [05:11<12:49,  1.14it/s]

Warning: File tcga_tnbc_data/5d875fca-d1ff-4c08-9dfa-0f1e67dc586b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  29%|██▊       | 349/1224 [05:12<12:59,  1.12it/s]

Warning: File tcga_tnbc_data/9d535d7d-0fff-4134-be8f-daa6d687a48c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  29%|██▊       | 350/1224 [05:13<13:06,  1.11it/s]

Warning: File tcga_tnbc_data/ec2687cf-9496-4232-9a96-41b935d6ffb3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  29%|██▊       | 351/1224 [05:14<17:28,  1.20s/it]

Warning: File tcga_tnbc_data/19318058-604e-4c3b-a037-eab07708ff82.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  29%|██▉       | 352/1224 [05:16<16:49,  1.16s/it]

Warning: File tcga_tnbc_data/8849e5bf-ff35-4cbf-972c-01fb92201a73.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  29%|██▉       | 353/1224 [05:16<15:06,  1.04s/it]

Warning: File tcga_tnbc_data/55214dd2-b3e8-444c-9d02-3db6008b1920.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  29%|██▉       | 354/1224 [05:17<14:59,  1.03s/it]

Warning: File tcga_tnbc_data/b2fdef29-2c03-4aaf-bac8-2e1e5d07333b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  29%|██▉       | 355/1224 [05:18<14:30,  1.00s/it]

Warning: File tcga_tnbc_data/5461f36b-c2a2-4a6a-8b17-444c143655fc.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  29%|██▉       | 356/1224 [05:19<14:09,  1.02it/s]

Warning: File tcga_tnbc_data/7000e222-556a-4548-9542-9337ba70f79c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  29%|██▉       | 357/1224 [05:20<13:26,  1.07it/s]

Warning: File tcga_tnbc_data/de98339e-9b13-4def-b3d9-234fdc784cec.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  29%|██▉       | 358/1224 [05:21<13:23,  1.08it/s]

Warning: File tcga_tnbc_data/dbbacb2c-b675-4a35-a6ff-157865f24945.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  29%|██▉       | 359/1224 [05:22<13:25,  1.07it/s]

Warning: File tcga_tnbc_data/cd9fd232-1d69-4ef0-911d-28130243994f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  29%|██▉       | 360/1224 [05:23<12:43,  1.13it/s]

Warning: File tcga_tnbc_data/0e89f9f0-419f-46e7-981d-781a1302e4be.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  29%|██▉       | 361/1224 [05:24<13:25,  1.07it/s]

Warning: File tcga_tnbc_data/a3e73f16-dc65-4c2e-9846-052b8fae144c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  30%|██▉       | 362/1224 [05:25<13:28,  1.07it/s]

Warning: File tcga_tnbc_data/cbfb8ffe-ae83-4a16-aaa6-f21ea893cb8d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  30%|██▉       | 363/1224 [05:25<12:49,  1.12it/s]

Warning: File tcga_tnbc_data/8256e097-4476-4906-a5c5-c9da288a363a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  30%|██▉       | 365/1224 [05:27<12:26,  1.15it/s]

Warning: File tcga_tnbc_data/4ad2cbb3-5bca-462b-af1f-8a292c317722.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/0710056c-2f04-4182-90ca-45492dd6444c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  30%|██▉       | 366/1224 [05:28<11:57,  1.20it/s]

Warning: File tcga_tnbc_data/e4f80aa3-eace-4ab4-afff-69d952ed5442.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  30%|███       | 368/1224 [05:30<12:04,  1.18it/s]

Warning: File tcga_tnbc_data/cee1efda-644b-4cee-aad2-d7f5ca93cdec.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/4f464ced-080f-41f1-9a00-955db0d5fda6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  30%|███       | 369/1224 [05:30<12:24,  1.15it/s]

Warning: File tcga_tnbc_data/31180222-da6e-4106-9b49-09be93d68138.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  30%|███       | 371/1224 [05:32<12:11,  1.17it/s]

Warning: File tcga_tnbc_data/4e261db3-6727-49bc-8a2e-77a7a30b4fa7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/1852f5d0-ce76-4f0d-87a7-0383f338c96b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  30%|███       | 373/1224 [05:34<11:41,  1.21it/s]

Warning: File tcga_tnbc_data/a835cfe4-9359-4178-9c9a-44ecb4173e47.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  31%|███       | 374/1224 [05:35<11:51,  1.19it/s]

Warning: File tcga_tnbc_data/a39defa6-87ec-4855-ab78-44f6b46152e1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/0a511373-8fd3-433a-a5e1-877530d6a239.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  31%|███       | 375/1224 [05:36<12:15,  1.15it/s]

Warning: File tcga_tnbc_data/3ecfecef-4180-4b7a-8d9a-5532b47ef500.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  31%|███       | 376/1224 [05:37<12:38,  1.12it/s]

Warning: File tcga_tnbc_data/36a42825-dbc2-4dff-828c-e5008207d254.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  31%|███       | 377/1224 [05:38<13:01,  1.08it/s]

Warning: File tcga_tnbc_data/c28e4bbf-6ddc-42fd-9268-826edc17aee5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  31%|███       | 378/1224 [05:38<12:38,  1.12it/s]

Warning: File tcga_tnbc_data/55f42211-4119-40a3-b5e4-329e913ef910.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  31%|███       | 379/1224 [05:39<12:22,  1.14it/s]

Warning: File tcga_tnbc_data/d1237195-a00b-4c52-86b3-4627c42eb14c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  31%|███       | 381/1224 [05:41<11:58,  1.17it/s]

Warning: File tcga_tnbc_data/44c12577-af9f-4f8c-8b18-24269d6604cb.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  31%|███       | 382/1224 [05:42<11:57,  1.17it/s]

Warning: File tcga_tnbc_data/1d8697f1-4e89-4987-b26b-a29d791f19ca.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/dad6be14-a519-478d-9f53-122417453a0e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  31%|███▏      | 383/1224 [05:43<11:48,  1.19it/s]

Warning: File tcga_tnbc_data/e6ea1343-0da3-43f3-9845-4845db02edb8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  31%|███▏      | 385/1224 [05:44<11:41,  1.20it/s]

Warning: File tcga_tnbc_data/3253f315-5ea3-44fc-899f-f9e8f5b6fa96.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/21836f98-cc95-46d3-8f40-6c9625f940ba.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  32%|███▏      | 386/1224 [05:45<11:32,  1.21it/s]

Warning: File tcga_tnbc_data/27513ce4-3807-481f-abcb-c59774a90519.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  32%|███▏      | 387/1224 [05:46<11:27,  1.22it/s]

Warning: File tcga_tnbc_data/5728b421-9832-417b-8963-b7b17decc58e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  32%|███▏      | 389/1224 [05:48<12:04,  1.15it/s]

Warning: File tcga_tnbc_data/bbd09e9b-84ba-458f-a595-b03069b843dd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/150cf3db-44a8-4553-a648-66913d68adde.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  32%|███▏      | 390/1224 [05:49<12:19,  1.13it/s]

Warning: File tcga_tnbc_data/a8fa9282-6695-477a-8202-73882cdfa8f7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  32%|███▏      | 391/1224 [05:49<12:28,  1.11it/s]

Warning: File tcga_tnbc_data/0a74ea3f-dadc-4c9f-96ea-62a77c1e602c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  32%|███▏      | 393/1224 [05:51<11:56,  1.16it/s]

Warning: File tcga_tnbc_data/f36e613e-af30-4b1c-aaf3-89540e05ddb1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/c642f518-6ba5-4c90-9f0c-0bad0ed80199.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  32%|███▏      | 394/1224 [05:52<11:46,  1.17it/s]

Warning: File tcga_tnbc_data/cf0ca663-a857-4aea-ab72-b0d4373b2456.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  32%|███▏      | 395/1224 [05:53<12:15,  1.13it/s]

Warning: File tcga_tnbc_data/da8c5f1e-a4e3-46bd-adb3-ce758e654983.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  32%|███▏      | 396/1224 [05:54<12:55,  1.07it/s]

Warning: File tcga_tnbc_data/466bf078-4844-457e-8f59-7b0ca28024d8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  32%|███▏      | 397/1224 [05:55<12:33,  1.10it/s]

Warning: File tcga_tnbc_data/ec7b77d4-41a2-4892-be79-23cb24f986d3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  33%|███▎      | 399/1224 [05:56<11:59,  1.15it/s]

Warning: File tcga_tnbc_data/0682b5b9-8529-4152-b6f9-1a13180eedee.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/b9a1e2f1-e5c4-4855-9720-4c168474dd26.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  33%|███▎      | 401/1224 [05:58<12:03,  1.14it/s]

Warning: File tcga_tnbc_data/683e004b-7992-4250-a94b-c355c45725d2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/fbdb3ca1-c7c8-437e-a315-25e3bc623236.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  33%|███▎      | 402/1224 [05:59<12:02,  1.14it/s]

Warning: File tcga_tnbc_data/d721071e-6c0e-46df-9158-1fe37a64f1ed.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  33%|███▎      | 403/1224 [06:00<12:20,  1.11it/s]

Warning: File tcga_tnbc_data/196aed5b-6812-47c5-ad7b-4dd1743ed0b5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  33%|███▎      | 404/1224 [06:01<12:38,  1.08it/s]

Warning: File tcga_tnbc_data/f88ba6a1-27bf-43fa-a2c7-05db1eb9e8ea.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  33%|███▎      | 405/1224 [06:02<12:08,  1.12it/s]

Warning: File tcga_tnbc_data/121a48ed-798d-4102-bb8f-e736570e18d6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  33%|███▎      | 407/1224 [06:04<11:55,  1.14it/s]

Warning: File tcga_tnbc_data/2ff175d2-100f-4ce8-8d1e-b3b95b41ae56.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  33%|███▎      | 408/1224 [06:04<11:42,  1.16it/s]

Warning: File tcga_tnbc_data/0d140db1-dc0d-431d-b389-846d05bbb827.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/8ebe0bf6-11fa-418d-918c-5c73f0e7e9ac.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  33%|███▎      | 409/1224 [06:05<11:25,  1.19it/s]

Warning: File tcga_tnbc_data/908283cf-b948-4474-906e-bd07195d0805.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  34%|███▎      | 411/1224 [06:07<11:06,  1.22it/s]

Warning: File tcga_tnbc_data/7774e389-c3c5-4abf-846c-4e8eead7e521.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/e18e1661-70dd-4b36-ae6c-c0265fbe01bb.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  34%|███▎      | 413/1224 [06:08<11:11,  1.21it/s]

Warning: File tcga_tnbc_data/4c57cb4f-b4dc-4cfa-9af5-1447422c5b95.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/1277b2ec-0374-403f-8bba-cb57aeeb0d01.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  34%|███▍      | 415/1224 [06:10<11:14,  1.20it/s]

Warning: File tcga_tnbc_data/707414cc-7f34-41c6-8803-6641521a4069.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/3208ca18-f70a-415e-8d10-5e9cb8a24b52.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  34%|███▍      | 417/1224 [06:12<12:01,  1.12it/s]

Warning: File tcga_tnbc_data/6185d5c4-f757-4baa-bd82-fd4050c57312.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/247f1d7d-fc33-4f35-aca7-60aa1c9631ad.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  34%|███▍      | 418/1224 [06:13<11:51,  1.13it/s]

Warning: File tcga_tnbc_data/158cc60a-89b0-40f0-8536-8c0f0e31429b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  34%|███▍      | 419/1224 [06:14<11:37,  1.15it/s]

Warning: File tcga_tnbc_data/ac16e2b7-9566-4330-8e13-4b31b92410e4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  34%|███▍      | 421/1224 [06:15<11:02,  1.21it/s]

Warning: File tcga_tnbc_data/d93c4b85-2617-43d9-8017-ed3a82dc4117.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  34%|███▍      | 422/1224 [06:16<10:41,  1.25it/s]

Warning: File tcga_tnbc_data/477f941f-1fb8-438f-802e-2e7fe6552fab.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/800ca72f-4bd7-46d7-904b-bcda2fa3500c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  35%|███▍      | 423/1224 [06:17<11:10,  1.19it/s]

Warning: File tcga_tnbc_data/641c4e5d-4880-4f5e-9d1e-702cab91a6b4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  35%|███▍      | 424/1224 [06:18<10:37,  1.25it/s]

Warning: File tcga_tnbc_data/c7019746-2fcf-4b4b-b7e5-025413e1014f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  35%|███▍      | 425/1224 [06:19<11:01,  1.21it/s]

Warning: File tcga_tnbc_data/a930c017-565f-49ad-893a-37cc394c269d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  35%|███▍      | 426/1224 [06:20<11:08,  1.19it/s]

Warning: File tcga_tnbc_data/77cdf045-d52d-4cc1-b2f1-e2b0d106af0f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  35%|███▍      | 427/1224 [06:20<11:09,  1.19it/s]

Warning: File tcga_tnbc_data/165fe176-2dea-489f-92d6-34b0c6848312.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  35%|███▍      | 428/1224 [06:21<11:03,  1.20it/s]

Warning: File tcga_tnbc_data/de6f1503-33d7-4f86-b835-bdffba7ea4e3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  35%|███▌      | 429/1224 [06:22<11:56,  1.11it/s]

Warning: File tcga_tnbc_data/ccd3b6f5-b425-47fb-b48e-0e24a4d6a4b2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  35%|███▌      | 430/1224 [06:23<11:39,  1.14it/s]

Warning: File tcga_tnbc_data/cf089a52-2196-422d-affa-a5f434edd134.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  35%|███▌      | 432/1224 [06:25<10:40,  1.24it/s]

Warning: File tcga_tnbc_data/4ef93d93-a6c6-4137-944c-6092e4ff7ae9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/3bc9d1c0-b57f-44b5-8624-b3ee99aeafe4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  35%|███▌      | 433/1224 [06:26<11:27,  1.15it/s]

Warning: File tcga_tnbc_data/a4589532-53e0-4025-b8d3-e11e79e1fc9c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  35%|███▌      | 434/1224 [06:26<11:15,  1.17it/s]

Warning: File tcga_tnbc_data/f7b5d569-1a46-4f23-bfca-a46daacda793.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  36%|███▌      | 436/1224 [06:28<11:41,  1.12it/s]

Warning: File tcga_tnbc_data/82d46633-2eea-4b43-81b6-addab4f069b4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/a03952ab-2ac1-43a5-a438-1f022bcd0b16.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  36%|███▌      | 438/1224 [06:30<10:57,  1.19it/s]

Warning: File tcga_tnbc_data/24c5fcbb-019c-4636-813b-0b9d4d1d9501.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  36%|███▌      | 439/1224 [06:31<11:15,  1.16it/s]

Warning: File tcga_tnbc_data/a58e2ae3-a236-4209-8292-70465216cb85.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  36%|███▌      | 440/1224 [06:32<10:59,  1.19it/s]

Warning: File tcga_tnbc_data/ab3475d0-e057-4512-8c01-a5383359a1ad.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  36%|███▌      | 441/1224 [06:32<10:23,  1.26it/s]

Warning: File tcga_tnbc_data/d53192c4-2356-4b6c-b98f-19eded7b7e29.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  36%|███▌      | 442/1224 [06:33<11:27,  1.14it/s]

Warning: File tcga_tnbc_data/03d18286-1038-4c0c-9c05-d1269e280250.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  36%|███▌      | 443/1224 [06:34<11:31,  1.13it/s]

Warning: File tcga_tnbc_data/d880fcce-ad8a-4402-911c-11129d2225df.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/4f89dad8-a12e-47d2-a7d9-c1b90f1bd61b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  36%|███▋      | 444/1224 [06:35<11:09,  1.17it/s]

Warning: File tcga_tnbc_data/0c3ddae2-366f-4b21-ab46-a2cfe1963e42.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  36%|███▋      | 446/1224 [06:37<11:13,  1.15it/s]

Warning: File tcga_tnbc_data/b9549737-232d-446f-812f-e7e015bfb462.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/ea7281b8-a53c-453a-93e9-69549c5f0fe8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  37%|███▋      | 447/1224 [06:38<11:15,  1.15it/s]

Warning: File tcga_tnbc_data/490df7f9-4b05-449d-bf47-d7de49aa50c0.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  37%|███▋      | 448/1224 [06:38<11:00,  1.18it/s]

Warning: File tcga_tnbc_data/c96ef17c-52c1-43d9-a7e5-730fd8f3641f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  37%|███▋      | 450/1224 [06:40<10:52,  1.19it/s]

Warning: File tcga_tnbc_data/1a8d6cfd-095d-4461-875a-56d27816a0f5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/269215ae-9040-4ac6-9d3d-017c0cbb2811.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  37%|███▋      | 451/1224 [06:41<10:53,  1.18it/s]

Warning: File tcga_tnbc_data/27aab1a6-96af-4dc1-b9ce-4690ead0d355.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  37%|███▋      | 452/1224 [06:42<10:52,  1.18it/s]

Warning: File tcga_tnbc_data/5064b439-81da-4ef3-b2de-bbca8d3a07e7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  37%|███▋      | 454/1224 [06:43<10:35,  1.21it/s]

Warning: File tcga_tnbc_data/3a0c96d3-4cea-44a3-99e5-71622279700f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  37%|███▋      | 455/1224 [06:44<10:26,  1.23it/s]

Warning: File tcga_tnbc_data/7789d241-991c-4cc9-a557-69d5c439b930.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  37%|███▋      | 456/1224 [06:45<10:12,  1.25it/s]

Warning: File tcga_tnbc_data/5039a492-4dc7-4191-9edd-187cb181da2d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/f03677e2-11ab-40b2-8499-591357c2c9d6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  37%|███▋      | 458/1224 [06:47<10:02,  1.27it/s]

Warning: File tcga_tnbc_data/17ff23ff-17b3-4ed1-b10c-2d922c045807.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  38%|███▊      | 459/1224 [06:47<10:03,  1.27it/s]

Warning: File tcga_tnbc_data/383b947b-6824-4c75-b4f3-ccfa933d3d33.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/0fc096b2-7fb5-4dc6-ae94-aa7dae6f885f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  38%|███▊      | 461/1224 [06:49<09:48,  1.30it/s]

Warning: File tcga_tnbc_data/1ce0d66a-176d-4d8a-b1c4-64d847e299be.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  38%|███▊      | 462/1224 [06:50<10:13,  1.24it/s]

Warning: File tcga_tnbc_data/a7091211-3bf5-4d3b-8625-57281bc0cd56.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/f73d3dce-d75f-4f76-b49c-99348ee641cc.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  38%|███▊      | 463/1224 [06:51<10:59,  1.15it/s]

Warning: File tcga_tnbc_data/bb1ee078-38d1-4e5d-af50-50754fce7112.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  38%|███▊      | 465/1224 [06:53<10:59,  1.15it/s]

Warning: File tcga_tnbc_data/c84958db-e7a3-4cd5-9b5e-a5435a86021d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/6bd03014-d3b8-4cac-929b-af970321ae1f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  38%|███▊      | 466/1224 [06:53<10:44,  1.18it/s]

Warning: File tcga_tnbc_data/51886a03-7aee-4b58-806f-906a29bfad0c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  38%|███▊      | 468/1224 [06:55<10:39,  1.18it/s]

Warning: File tcga_tnbc_data/e94ef671-995d-452b-bcbe-993e5b437a68.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/bf26a3fb-39a8-4eff-b801-a7dd915e73f5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  38%|███▊      | 469/1224 [06:56<10:53,  1.16it/s]

Warning: File tcga_tnbc_data/ea5c9d47-1803-4bd5-88da-352e172bc45d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  38%|███▊      | 470/1224 [06:57<11:08,  1.13it/s]

Warning: File tcga_tnbc_data/87b59374-da2d-41ba-bbde-43a9022eac2c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  38%|███▊      | 471/1224 [06:58<11:00,  1.14it/s]

Warning: File tcga_tnbc_data/9054231e-9b1f-4ee4-b22c-1e9dbfdcfc03.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  39%|███▊      | 473/1224 [07:00<11:10,  1.12it/s]

Warning: File tcga_tnbc_data/fd371070-c312-4eca-b3da-d41b1c8a86a7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  39%|███▊      | 474/1224 [07:00<10:42,  1.17it/s]

Warning: File tcga_tnbc_data/ea01e210-0d45-4c23-8644-904771672188.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  39%|███▉      | 475/1224 [07:01<10:29,  1.19it/s]

Warning: File tcga_tnbc_data/f55dbdb1-0301-4000-a854-717aed117a63.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/bdf5a2b7-f9cb-4668-9687-1db0541bdfe4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  39%|███▉      | 476/1224 [07:02<10:29,  1.19it/s]

Warning: File tcga_tnbc_data/392edd04-fdec-4eb7-ba2e-cef02519c219.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  39%|███▉      | 477/1224 [07:03<10:17,  1.21it/s]

Warning: File tcga_tnbc_data/82255740-abaa-47b3-9def-89b0673d1cfb.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  39%|███▉      | 479/1224 [07:05<10:30,  1.18it/s]

Warning: File tcga_tnbc_data/06952c59-978d-4ef4-b716-c55dd6747699.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/4b96ee43-874c-4fa6-b5ce-08caf37ef2e1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  39%|███▉      | 480/1224 [07:05<10:15,  1.21it/s]

Warning: File tcga_tnbc_data/c2c7669c-0eea-48a8-add8-bd5ea3f9808f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  39%|███▉      | 482/1224 [07:07<10:27,  1.18it/s]

Warning: File tcga_tnbc_data/73aeda8d-ef07-4d3d-a0fc-643943dd046a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  39%|███▉      | 483/1224 [07:08<10:39,  1.16it/s]

Warning: File tcga_tnbc_data/65264188-23f8-4214-a45a-574f47471bb3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/90116c25-271c-4be2-b20f-295448e6e421.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  40%|███▉      | 484/1224 [07:09<10:48,  1.14it/s]

Warning: File tcga_tnbc_data/819746a4-f2c1-4fc2-8dbe-b9c34892d510.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  40%|███▉      | 486/1224 [07:11<10:47,  1.14it/s]

Warning: File tcga_tnbc_data/10d1a1f0-c89b-4b1e-93fa-7c6fd7f5bb8f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  40%|███▉      | 487/1224 [07:12<10:57,  1.12it/s]

Warning: File tcga_tnbc_data/b70b68a1-28c4-4ed3-a04c-b622e583f10b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/d6882616-b77d-4d4c-90dc-7318c57876e1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  40%|███▉      | 489/1224 [07:13<10:43,  1.14it/s]

Warning: File tcga_tnbc_data/478c9754-5a19-477b-8b9d-0825f95f88ff.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  40%|████      | 490/1224 [07:14<10:20,  1.18it/s]

Warning: File tcga_tnbc_data/f35ae5c7-6e88-410d-b86f-c5bdae11a5f4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/8c6fa126-82a0-4290-a657-8466959585c4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  40%|████      | 491/1224 [07:15<10:39,  1.15it/s]

Warning: File tcga_tnbc_data/c25c7ca5-8d03-4bba-b42b-c8b1042c0d48.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  40%|████      | 492/1224 [07:16<10:48,  1.13it/s]

Warning: File tcga_tnbc_data/017d71aa-0999-4d8e-9cb4-88b9013e61eb.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  40%|████      | 493/1224 [07:17<10:32,  1.16it/s]

Warning: File tcga_tnbc_data/cdd283b5-8dea-4736-859c-f1a2bbda57c2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  40%|████      | 495/1224 [07:18<10:13,  1.19it/s]

Warning: File tcga_tnbc_data/6084a2ac-a342-4378-b4ba-a2d7e6af9124.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  41%|████      | 496/1224 [07:19<09:51,  1.23it/s]

Warning: File tcga_tnbc_data/7ae79f8e-a8fa-4030-b46a-458db80a36c1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/82fea6e8-7c6a-4575-bfcd-c164094538e6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  41%|████      | 497/1224 [07:20<09:49,  1.23it/s]

Warning: File tcga_tnbc_data/3e3125cd-a554-4a76-a9e2-b9187e0db6ab.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  41%|████      | 498/1224 [07:21<10:09,  1.19it/s]

Warning: File tcga_tnbc_data/9928c491-426a-4507-8ddd-999d6b892e29.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  41%|████      | 500/1224 [07:23<09:52,  1.22it/s]

Warning: File tcga_tnbc_data/3c2914f4-200f-4bec-93f0-b0fdb6460378.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  41%|████      | 501/1224 [07:23<10:04,  1.20it/s]

Warning: File tcga_tnbc_data/a7d3a4c0-36ee-43ff-bdcc-37db4b11df76.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  41%|████      | 502/1224 [07:24<09:50,  1.22it/s]

Warning: File tcga_tnbc_data/447e3faf-a5f2-4739-b2aa-c907f33b634a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  41%|████      | 503/1224 [07:25<09:55,  1.21it/s]

Warning: File tcga_tnbc_data/9c0043c4-b65a-42ca-9f02-fe1cef04beaf.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/cbbbb1af-8bf4-4bb6-9258-33bf416190e7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  41%|████▏     | 505/1224 [07:27<09:38,  1.24it/s]

Warning: File tcga_tnbc_data/fc0a2d23-31a3-4aab-bdd9-0abb51880043.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/7aff89e2-86cb-43d8-96cd-341c02ebdd49.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  41%|████▏     | 506/1224 [07:28<10:11,  1.17it/s]

Warning: File tcga_tnbc_data/739fe30a-4fae-4f4d-a360-3ab300a4848a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  42%|████▏     | 508/1224 [07:29<10:16,  1.16it/s]

Warning: File tcga_tnbc_data/de397789-9ff5-4cb0-be88-957477820714.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/e3569a42-412b-405d-a1ca-5c89b1ea36d0.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  42%|████▏     | 510/1224 [07:31<09:38,  1.23it/s]

Warning: File tcga_tnbc_data/2a2d5de1-44d7-4c83-91d6-fc1b3c136143.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  42%|████▏     | 511/1224 [07:32<09:29,  1.25it/s]

Warning: File tcga_tnbc_data/9d487523-ce75-4146-98d9-aed08dc2f632.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  42%|████▏     | 512/1224 [07:32<09:30,  1.25it/s]

Warning: File tcga_tnbc_data/2377e521-919f-4f6f-b426-ddc993775597.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  42%|████▏     | 513/1224 [07:33<09:34,  1.24it/s]

Warning: File tcga_tnbc_data/f9fe6c47-0955-432f-b402-a6dc2665e04d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/78b9cc4c-a99b-4814-9538-3cf9515af75b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  42%|████▏     | 515/1224 [07:35<10:06,  1.17it/s]

Warning: File tcga_tnbc_data/54dcd665-8138-4cab-8622-224d7066d466.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/d5d23d6a-c141-442f-ac4f-714e46b8d9ef.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  42%|████▏     | 517/1224 [07:37<09:47,  1.20it/s]

Warning: File tcga_tnbc_data/8c884351-1c8b-47ff-8bef-1a4f25f645fb.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  42%|████▏     | 518/1224 [07:37<09:47,  1.20it/s]

Warning: File tcga_tnbc_data/7f1cbb4f-aecf-42be-91cc-fb35d03447df.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  42%|████▏     | 519/1224 [07:38<09:34,  1.23it/s]

Warning: File tcga_tnbc_data/1d7789a1-1ff1-4865-a9c9-dfb40e57aff5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/d67b8114-b70f-4e69-bae5-4f2f982c4b1b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  42%|████▏     | 520/1224 [07:39<10:07,  1.16it/s]

Warning: File tcga_tnbc_data/478a40b1-0f88-401d-92b6-4b58b2c56798.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  43%|████▎     | 521/1224 [07:40<10:15,  1.14it/s]

Warning: File tcga_tnbc_data/575ef8e2-dfbc-48b3-9836-089b94498e09.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  43%|████▎     | 522/1224 [07:41<10:26,  1.12it/s]

Warning: File tcga_tnbc_data/467cc312-373e-4655-a07e-533ccb133b22.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  43%|████▎     | 524/1224 [07:43<09:52,  1.18it/s]

Warning: File tcga_tnbc_data/4376b78e-bfec-4142-8407-b967883d7b6b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/9b13d7e4-d265-4c0b-8aa3-5b4af70ff87d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  43%|████▎     | 525/1224 [07:44<10:23,  1.12it/s]

Warning: File tcga_tnbc_data/958813f4-8036-42f7-856d-7a69c4175adc.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  43%|████▎     | 526/1224 [07:45<10:29,  1.11it/s]

Warning: File tcga_tnbc_data/ada5cdcf-f9e0-4209-aa92-ac3b921bbdf4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  43%|████▎     | 528/1224 [07:46<09:58,  1.16it/s]

Warning: File tcga_tnbc_data/0a7421d4-5722-427a-9643-da1074e5c25c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  43%|████▎     | 529/1224 [07:47<10:05,  1.15it/s]

Warning: File tcga_tnbc_data/248ac510-a5af-4608-9cdc-5c8673633b82.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/243fe98b-3355-4b09-8094-b9e06a2b8329.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  43%|████▎     | 531/1224 [07:49<10:16,  1.12it/s]

Warning: File tcga_tnbc_data/1c3a771f-43db-4b45-93f8-f8e6d2ab6847.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/16786247-5ff5-47e0-83e2-fee15779e522.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  44%|████▎     | 533/1224 [07:51<10:30,  1.10it/s]

Warning: File tcga_tnbc_data/da93e1a9-6863-4c98-b1fd-52d22ecbca45.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/89dfc6f3-9f78-4e03-a2e7-e9010c7814a2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  44%|████▎     | 534/1224 [07:52<10:55,  1.05it/s]

Warning: File tcga_tnbc_data/895b7107-2c08-4106-b119-6fbb597392da.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  44%|████▎     | 535/1224 [07:53<10:30,  1.09it/s]

Warning: File tcga_tnbc_data/5e863e9f-1449-4a38-ac00-cfd7c21ba6e2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  44%|████▍     | 537/1224 [07:54<10:12,  1.12it/s]

Warning: File tcga_tnbc_data/2ea0b718-c634-4692-9cf0-4f118adfafbd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  44%|████▍     | 538/1224 [07:55<09:55,  1.15it/s]

Warning: File tcga_tnbc_data/5aba8f7f-c815-45e9-bee0-4dda9bfac07f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/d141392c-757b-44f5-b531-0bcc136d8b17.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  44%|████▍     | 539/1224 [07:56<09:38,  1.18it/s]

Warning: File tcga_tnbc_data/38854c85-fc09-4a51-93a7-257762517583.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  44%|████▍     | 540/1224 [07:57<09:27,  1.21it/s]

Warning: File tcga_tnbc_data/295d363f-0366-4102-a35c-86e4a4fe7d84.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  44%|████▍     | 542/1224 [07:58<09:07,  1.25it/s]

Warning: File tcga_tnbc_data/22dad91c-889d-4d40-b9b8-c9facd752dc9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  44%|████▍     | 543/1224 [07:59<09:22,  1.21it/s]

Warning: File tcga_tnbc_data/c6882939-729e-4360-b850-9f7a84df2d7e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/40ad8a2a-abd2-4701-b984-4afa4c27c260.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  44%|████▍     | 544/1224 [08:00<10:06,  1.12it/s]

Warning: File tcga_tnbc_data/9cac5296-0f61-46a2-bcbf-9bd3212fb7dd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  45%|████▍     | 545/1224 [08:01<10:32,  1.07it/s]

Warning: File tcga_tnbc_data/2a09e101-9e01-45ec-9b02-d806f4cd7469.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  45%|████▍     | 546/1224 [08:02<10:32,  1.07it/s]

Warning: File tcga_tnbc_data/20e1a6f6-c34f-4744-9b2a-392ea074ebe2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  45%|████▍     | 547/1224 [08:03<10:36,  1.06it/s]

Warning: File tcga_tnbc_data/d898d021-e82b-42e6-b82e-28c187136674.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  45%|████▍     | 548/1224 [08:05<11:55,  1.06s/it]

Warning: File tcga_tnbc_data/59bb8b6d-9827-4d5c-8714-cbc8ec3b8be5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  45%|████▍     | 549/1224 [08:06<12:03,  1.07s/it]

Warning: File tcga_tnbc_data/891873c8-bb26-4215-9281-a79be2651f11.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  45%|████▍     | 550/1224 [08:07<12:24,  1.11s/it]

Warning: File tcga_tnbc_data/4c75e72b-db9f-425b-9f14-946ee801071e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  45%|████▌     | 551/1224 [08:08<12:18,  1.10s/it]

Warning: File tcga_tnbc_data/7c89d4dc-cccb-4833-9731-be8affb76c89.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  45%|████▌     | 552/1224 [08:09<12:02,  1.08s/it]

Warning: File tcga_tnbc_data/5fbe4a11-de4d-418e-9bc3-75b768d4a665.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  45%|████▌     | 553/1224 [08:10<12:34,  1.12s/it]

Warning: File tcga_tnbc_data/3844ac53-a01f-41f1-a3f3-d9decf12d024.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  45%|████▌     | 554/1224 [08:11<12:13,  1.10s/it]

Warning: File tcga_tnbc_data/8ebe5f43-053c-4bfc-aefd-b9c22897b4ce.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  45%|████▌     | 555/1224 [08:12<11:42,  1.05s/it]

Warning: File tcga_tnbc_data/86b7ddd7-1c59-4937-99ec-b30fa9b4f0bd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  45%|████▌     | 556/1224 [08:13<10:53,  1.02it/s]

Warning: File tcga_tnbc_data/1f224847-d745-4dc5-9338-4044413e8ec4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  46%|████▌     | 557/1224 [08:14<10:16,  1.08it/s]

Warning: File tcga_tnbc_data/4dd3d7e2-8a60-41e8-8812-a06f413afe2b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  46%|████▌     | 558/1224 [08:15<10:09,  1.09it/s]

Warning: File tcga_tnbc_data/788a4858-c6c6-4a8d-9aef-dbd32d74776b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  46%|████▌     | 559/1224 [08:15<09:34,  1.16it/s]

Warning: File tcga_tnbc_data/6c908d24-e571-436a-9a06-705c294ba5d7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  46%|████▌     | 560/1224 [08:16<09:38,  1.15it/s]

Warning: File tcga_tnbc_data/1a000feb-3b71-4f95-8b39-68ec25b64d96.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  46%|████▌     | 561/1224 [08:17<09:23,  1.18it/s]

Warning: File tcga_tnbc_data/9da9a119-9f9a-4ddb-947e-97724b9fe45f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  46%|████▌     | 562/1224 [08:18<09:51,  1.12it/s]

Warning: File tcga_tnbc_data/43820fe3-a899-4e6b-9227-27e32edaefd5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  46%|████▌     | 563/1224 [08:19<09:47,  1.12it/s]

Warning: File tcga_tnbc_data/f502949f-ca10-4617-a7ee-b8f142f7ec93.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  46%|████▌     | 565/1224 [08:21<09:41,  1.13it/s]

Warning: File tcga_tnbc_data/5030e484-7981-462f-b78d-9fdf1a8531c5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/91577462-386f-43eb-88e1-859c1d74763c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  46%|████▌     | 566/1224 [08:22<10:17,  1.07it/s]

Warning: File tcga_tnbc_data/d777e8a9-92a8-48eb-bf58-8e13af99c77f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  46%|████▋     | 567/1224 [08:23<10:28,  1.05it/s]

Warning: File tcga_tnbc_data/1051db4c-40a5-4a98-a239-d96c986aa349.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  46%|████▋     | 568/1224 [08:24<10:06,  1.08it/s]

Warning: File tcga_tnbc_data/fc9fab5b-52f0-4c79-bdf3-750c650a0fdc.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  46%|████▋     | 569/1224 [08:25<09:57,  1.10it/s]

Warning: File tcga_tnbc_data/7fadaf69-2a7b-4eca-aec9-c2f2b43eab3c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  47%|████▋     | 570/1224 [08:26<10:17,  1.06it/s]

Warning: File tcga_tnbc_data/ad8be67e-a885-4d33-8776-fa0a5f9863d1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  47%|████▋     | 571/1224 [08:27<10:22,  1.05it/s]

Warning: File tcga_tnbc_data/7814e438-105f-4d5b-94fe-8c66e95585ea.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  47%|████▋     | 572/1224 [08:27<09:55,  1.10it/s]

Warning: File tcga_tnbc_data/51a3cb9a-e745-49ac-af0e-3a750f9e7521.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  47%|████▋     | 573/1224 [08:28<09:59,  1.09it/s]

Warning: File tcga_tnbc_data/f1dc7a14-29f1-4fe1-bc67-01e0776d6b40.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  47%|████▋     | 574/1224 [08:29<10:12,  1.06it/s]

Warning: File tcga_tnbc_data/e4f1f27b-24a1-4d01-af87-b2692d092d2a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  47%|████▋     | 575/1224 [08:30<10:13,  1.06it/s]

Warning: File tcga_tnbc_data/6e8e0eef-1fc8-446c-9038-3a06657784ec.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  47%|████▋     | 576/1224 [08:31<09:50,  1.10it/s]

Warning: File tcga_tnbc_data/589dda89-b968-4f26-b3c7-5371dfdb8a90.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  47%|████▋     | 577/1224 [08:32<10:17,  1.05it/s]

Warning: File tcga_tnbc_data/89e048e0-2bdb-4c62-9c0e-2e6e796238dd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  47%|████▋     | 578/1224 [08:33<09:54,  1.09it/s]

Warning: File tcga_tnbc_data/9ccdf2cc-ca01-4ef7-bed9-f955fd0396c2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  47%|████▋     | 579/1224 [08:35<14:11,  1.32s/it]

Warning: File tcga_tnbc_data/23304266-b28c-4ff2-8dcf-bb18f56417b4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  47%|████▋     | 580/1224 [08:36<12:49,  1.19s/it]

Warning: File tcga_tnbc_data/1d15f05d-2ac2-4b83-987e-6f4b157b0b74.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  47%|████▋     | 581/1224 [08:37<11:33,  1.08s/it]

Warning: File tcga_tnbc_data/a127fb1e-aa3b-4b6d-98b5-c141ffba9ae7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  48%|████▊     | 582/1224 [08:39<15:06,  1.41s/it]

Warning: File tcga_tnbc_data/d5330be0-9f72-4be5-9139-8503aa4d00b4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  48%|████▊     | 583/1224 [08:40<14:17,  1.34s/it]

Warning: File tcga_tnbc_data/ac88a5c1-caae-4b08-87bc-0dedbe61d996.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  48%|████▊     | 584/1224 [08:41<13:40,  1.28s/it]

Warning: File tcga_tnbc_data/37939d7d-074b-42b7-8d68-95a8afef4c38.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  48%|████▊     | 585/1224 [08:42<12:29,  1.17s/it]

Warning: File tcga_tnbc_data/41e96cc6-43d5-4eea-bbd3-23fb389d5532.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  48%|████▊     | 586/1224 [08:43<11:41,  1.10s/it]

Warning: File tcga_tnbc_data/59f472a7-ce4f-4d3a-9193-8b3a4500d52b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  48%|████▊     | 587/1224 [08:44<11:02,  1.04s/it]

Warning: File tcga_tnbc_data/4b558a24-b10c-4d59-a921-10e6a3a9fb35.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  48%|████▊     | 588/1224 [08:45<10:39,  1.01s/it]

Warning: File tcga_tnbc_data/4004cdd0-51fa-4330-bd03-5448f6c7b787.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  48%|████▊     | 589/1224 [08:46<10:44,  1.02s/it]

Warning: File tcga_tnbc_data/f9418a79-3614-41a1-8ab0-c2b4313c6fd4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  48%|████▊     | 591/1224 [08:48<09:44,  1.08it/s]

Warning: File tcga_tnbc_data/927604f9-a38e-4c3f-b50f-3e0db4daf5ec.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/c3bab823-4bf2-40ea-903c-fb342067c893.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  48%|████▊     | 592/1224 [08:49<09:30,  1.11it/s]

Warning: File tcga_tnbc_data/c1f6f39f-db8f-4449-bfb2-d1f3f2a95d22.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  48%|████▊     | 593/1224 [08:50<09:28,  1.11it/s]

Warning: File tcga_tnbc_data/a2f1fa8f-26d6-4b3e-8816-33f42e3f9209.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  49%|████▊     | 594/1224 [08:50<09:23,  1.12it/s]

Warning: File tcga_tnbc_data/511ca25f-0b7f-4912-9b79-ed551721a420.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  49%|████▊     | 595/1224 [08:51<09:23,  1.12it/s]

Warning: File tcga_tnbc_data/69bb06b6-74b3-441b-82d7-c6783aa88cdd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  49%|████▊     | 596/1224 [08:52<09:07,  1.15it/s]

Warning: File tcga_tnbc_data/f3746445-b2d0-4455-a6c0-46562188c056.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  49%|████▉     | 597/1224 [08:53<09:50,  1.06it/s]

Warning: File tcga_tnbc_data/a9f49b86-3801-420d-915c-0e09a15c6e59.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  49%|████▉     | 598/1224 [08:54<09:43,  1.07it/s]

Warning: File tcga_tnbc_data/11a64d0e-1dd1-471e-87bf-9e2a7fc13f09.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  49%|████▉     | 599/1224 [08:55<09:28,  1.10it/s]

Warning: File tcga_tnbc_data/5b92e1c6-6265-46b5-bcf7-0c0bafe6f390.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  49%|████▉     | 600/1224 [08:56<10:24,  1.00s/it]

Warning: File tcga_tnbc_data/18b0bd2d-505f-4ecb-9bea-b52e6a74cebd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  49%|████▉     | 601/1224 [08:57<10:36,  1.02s/it]

Warning: File tcga_tnbc_data/89409cf3-e710-47fd-af3c-6f8f0dec7c90.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  49%|████▉     | 602/1224 [08:58<10:16,  1.01it/s]

Warning: File tcga_tnbc_data/a5c799bc-1332-4127-8fda-84da04084d25.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  49%|████▉     | 603/1224 [08:59<10:07,  1.02it/s]

Warning: File tcga_tnbc_data/03a1a105-4856-4e5c-b537-508bdbda50b5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  49%|████▉     | 604/1224 [09:00<09:56,  1.04it/s]

Warning: File tcga_tnbc_data/461fda5d-d6e6-4354-b035-c302cc43b03f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  49%|████▉     | 605/1224 [09:01<09:35,  1.08it/s]

Warning: File tcga_tnbc_data/5a827399-307b-412b-a2ce-f6c81d2750a6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  50%|████▉     | 606/1224 [09:02<09:11,  1.12it/s]

Warning: File tcga_tnbc_data/0b4cae8e-1a2c-4ba9-b126-5abf35f73b36.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  50%|████▉     | 607/1224 [09:03<09:10,  1.12it/s]

Warning: File tcga_tnbc_data/aa89d193-05a1-4f7f-9291-b9cf646656de.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  50%|████▉     | 609/1224 [09:04<09:10,  1.12it/s]

Warning: File tcga_tnbc_data/4ef3b472-5fce-4e6a-a835-659cc3fee694.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/7e035247-3586-443f-a94c-0addbaf3b17f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  50%|████▉     | 610/1224 [09:05<09:15,  1.10it/s]

Warning: File tcga_tnbc_data/e914127b-20a0-4ef1-a614-06b697da648c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  50%|████▉     | 611/1224 [09:06<09:38,  1.06it/s]

Warning: File tcga_tnbc_data/79f97f73-b650-49cf-8654-53038a6c0de7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  50%|█████     | 612/1224 [09:07<09:07,  1.12it/s]

Warning: File tcga_tnbc_data/7125229a-2fc6-402d-bd87-ad0d3195fd49.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  50%|█████     | 613/1224 [09:08<09:34,  1.06it/s]

Warning: File tcga_tnbc_data/28c03f8f-7f7a-4a53-a840-db0f4052ed26.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  50%|█████     | 614/1224 [09:09<09:20,  1.09it/s]

Warning: File tcga_tnbc_data/f52fccc4-745f-4e5d-bff8-8d2009b6588d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  50%|█████     | 615/1224 [09:10<09:12,  1.10it/s]

Warning: File tcga_tnbc_data/f0107961-a5e1-46ec-b232-a47f0049bc5f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  50%|█████     | 616/1224 [09:11<09:21,  1.08it/s]

Warning: File tcga_tnbc_data/b96a8979-77c1-41b5-a247-0342262d30f7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  50%|█████     | 617/1224 [09:12<09:15,  1.09it/s]

Warning: File tcga_tnbc_data/584eef35-12c2-4aac-be09-175a9f9c5dfc.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  50%|█████     | 618/1224 [09:13<09:10,  1.10it/s]

Warning: File tcga_tnbc_data/7806768a-e8c6-48b0-a241-c036c230e78b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  51%|█████     | 619/1224 [09:14<08:42,  1.16it/s]

Warning: File tcga_tnbc_data/a73c6624-c462-4c25-94bf-58769257c6dc.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  51%|█████     | 621/1224 [09:15<09:11,  1.09it/s]

Warning: File tcga_tnbc_data/1737104f-367e-4098-a068-12f8ece492bf.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  51%|█████     | 622/1224 [09:16<09:02,  1.11it/s]

Warning: File tcga_tnbc_data/d8a94ea1-68a3-43be-8a30-d690541a23aa.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  51%|█████     | 623/1224 [09:17<08:37,  1.16it/s]

Warning: File tcga_tnbc_data/1b98fd3e-d3e3-4ecc-9fe3-02600177efed.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  51%|█████     | 624/1224 [09:18<08:23,  1.19it/s]

Warning: File tcga_tnbc_data/aedc877a-f4b9-4657-b5c9-b7768b5751c9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/4ed31cce-6d4f-4c79-a4e4-80eaedd1c4d2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  51%|█████     | 625/1224 [09:19<08:19,  1.20it/s]

Warning: File tcga_tnbc_data/c7f1e894-f50d-437c-ad42-4a35f531c795.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  51%|█████     | 626/1224 [09:20<08:07,  1.23it/s]

Warning: File tcga_tnbc_data/6c7f9fc6-3dba-4605-9f0c-d4f00095352f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  51%|█████     | 627/1224 [09:20<08:34,  1.16it/s]

Warning: File tcga_tnbc_data/778642d9-e4e2-4ae8-a900-b2e663c9d5b9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  51%|█████▏    | 628/1224 [09:21<08:38,  1.15it/s]

Warning: File tcga_tnbc_data/e9fe2319-2624-4ac1-9c41-d0ac44608f02.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  51%|█████▏    | 630/1224 [09:23<08:39,  1.14it/s]

Warning: File tcga_tnbc_data/4c2bb8e3-2527-466b-a3bb-0f36c3b2a3e7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/02e08315-4d34-421c-acc0-129b1e1de38b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  52%|█████▏    | 632/1224 [09:25<08:41,  1.14it/s]

Warning: File tcga_tnbc_data/fdd73b76-517e-4554-ba4d-1c67b1b758f8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/ea1fadc2-1cdc-4658-9619-eeb26ae09da8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  52%|█████▏    | 633/1224 [09:26<08:25,  1.17it/s]

Warning: File tcga_tnbc_data/cc12e7a8-e384-47f5-94b8-3e472925cc87.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  52%|█████▏    | 634/1224 [09:27<08:18,  1.18it/s]

Warning: File tcga_tnbc_data/1eca5ea8-093a-494d-968b-2ffcfe2b4604.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  52%|█████▏    | 635/1224 [09:27<08:14,  1.19it/s]

Warning: File tcga_tnbc_data/7882ff91-e415-48ae-9151-26b55f1cfc57.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  52%|█████▏    | 636/1224 [09:28<08:18,  1.18it/s]

Warning: File tcga_tnbc_data/21f16535-a7bb-4bbd-affe-bff937467374.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  52%|█████▏    | 637/1224 [09:29<08:14,  1.19it/s]

Warning: File tcga_tnbc_data/b4ac6e06-8760-4cb2-883c-c829eaefdc4c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  52%|█████▏    | 638/1224 [09:30<08:14,  1.19it/s]

Warning: File tcga_tnbc_data/b88daf3f-645d-4d11-a2be-2295e186747f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  52%|█████▏    | 639/1224 [09:31<08:16,  1.18it/s]

Warning: File tcga_tnbc_data/1db8a1bb-fef2-4e06-9cd5-a1f6579573a5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  52%|█████▏    | 640/1224 [09:32<08:26,  1.15it/s]

Warning: File tcga_tnbc_data/28ecd88f-6249-425c-99e1-9055989feff8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  52%|█████▏    | 641/1224 [09:32<08:11,  1.19it/s]

Warning: File tcga_tnbc_data/d889e5ea-58f5-4d2f-ad1e-6ab5d3217642.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  52%|█████▏    | 642/1224 [09:33<08:28,  1.15it/s]

Warning: File tcga_tnbc_data/0081f507-b104-4214-9ea1-31dd69130991.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  53%|█████▎    | 644/1224 [09:35<08:20,  1.16it/s]

Warning: File tcga_tnbc_data/09385f52-e4ad-4ae0-9f09-91e8dd5fc953.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/391a3465-d22e-424b-af09-3e6342159bbb.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  53%|█████▎    | 645/1224 [09:36<08:25,  1.15it/s]

Warning: File tcga_tnbc_data/35fd75aa-21e8-49c0-8b40-159839c3cc19.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  53%|█████▎    | 646/1224 [09:37<08:13,  1.17it/s]

Warning: File tcga_tnbc_data/a2f902f5-2413-4698-b53b-446df6409d61.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  53%|█████▎    | 648/1224 [09:38<08:03,  1.19it/s]

Warning: File tcga_tnbc_data/34d68427-f4e7-4c9e-97ee-c853519961fb.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/4cce67eb-0cb7-4c8f-a81e-0e521c2b0168.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  53%|█████▎    | 649/1224 [09:39<08:27,  1.13it/s]

Warning: File tcga_tnbc_data/1dd5828f-8e81-4196-992f-70b8203c915f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  53%|█████▎    | 650/1224 [09:40<08:28,  1.13it/s]

Warning: File tcga_tnbc_data/86b68671-beef-4a15-aabb-89d79396fd9d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  53%|█████▎    | 651/1224 [09:41<08:20,  1.15it/s]

Warning: File tcga_tnbc_data/742a677b-e99b-4916-bb92-3536c55ee5e3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  53%|█████▎    | 652/1224 [09:42<08:28,  1.12it/s]

Warning: File tcga_tnbc_data/48847088-1303-4b23-8902-c0ca4ea5ae80.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  53%|█████▎    | 653/1224 [09:43<08:22,  1.14it/s]

Warning: File tcga_tnbc_data/1d7e99d8-052d-491a-8088-91cb0790cb17.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  53%|█████▎    | 654/1224 [09:44<08:07,  1.17it/s]

Warning: File tcga_tnbc_data/69aebf68-5357-4269-84fb-ee91a6bd67fd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  54%|█████▎    | 655/1224 [09:45<08:14,  1.15it/s]

Warning: File tcga_tnbc_data/9b03a281-22c7-4ad4-b1c8-ba7eed0e8c5b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  54%|█████▎    | 656/1224 [09:46<08:43,  1.08it/s]

Warning: File tcga_tnbc_data/baec6a46-7c48-41ed-a8a9-eef52d32cba3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  54%|█████▍    | 658/1224 [09:48<08:37,  1.09it/s]

Warning: File tcga_tnbc_data/ae72486a-e98c-4d72-b172-085d5b79df2c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/f979b428-649b-42ac-9eae-31ff4daa7b8f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  54%|█████▍    | 660/1224 [09:49<08:40,  1.08it/s]

Warning: File tcga_tnbc_data/76cff555-d8a3-46d1-ac93-12d856adb445.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/6e112ec6-1791-4764-8a62-7ad4dfea2d3b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  54%|█████▍    | 661/1224 [09:50<08:23,  1.12it/s]

Warning: File tcga_tnbc_data/87d5686a-5d57-4ce2-b06a-dee5c2926ebf.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  54%|█████▍    | 662/1224 [09:51<08:23,  1.12it/s]

Warning: File tcga_tnbc_data/5e789924-9d98-4765-a348-90a27349d906.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  54%|█████▍    | 663/1224 [09:52<08:33,  1.09it/s]

Warning: File tcga_tnbc_data/36e4ffb0-0bab-4035-88f1-a181b195fce1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  54%|█████▍    | 664/1224 [09:53<08:15,  1.13it/s]

Warning: File tcga_tnbc_data/45bf52c6-b1a3-4f01-8345-a224fc195e18.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  54%|█████▍    | 665/1224 [09:54<08:02,  1.16it/s]

Warning: File tcga_tnbc_data/d923e06d-c747-419d-bd40-b05eb3e13edb.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  54%|█████▍    | 666/1224 [09:55<08:00,  1.16it/s]

Warning: File tcga_tnbc_data/130343f0-62f4-4400-8002-e596edb3c02a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  54%|█████▍    | 667/1224 [09:56<08:22,  1.11it/s]

Warning: File tcga_tnbc_data/67347e29-6d43-4234-8b04-188be7e6440b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  55%|█████▍    | 668/1224 [09:56<08:10,  1.13it/s]

Warning: File tcga_tnbc_data/206804c1-e5be-4076-9793-406d11094266.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  55%|█████▍    | 669/1224 [09:58<08:41,  1.07it/s]

Warning: File tcga_tnbc_data/136df0c2-a2a4-42e9-9cc6-9051d4f4c13d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  55%|█████▍    | 670/1224 [09:58<08:23,  1.10it/s]

Warning: File tcga_tnbc_data/8a84b9a5-d453-416b-b481-f15402c2eb54.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  55%|█████▍    | 671/1224 [09:59<08:05,  1.14it/s]

Warning: File tcga_tnbc_data/f1934efb-1c8a-4c72-ba94-d263ef0d0cd4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  55%|█████▍    | 672/1224 [10:00<07:49,  1.18it/s]

Warning: File tcga_tnbc_data/207ea988-6795-460c-bfeb-382d8c758f31.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  55%|█████▌    | 674/1224 [10:02<07:31,  1.22it/s]

Warning: File tcga_tnbc_data/8d87fbd5-8ca7-4ff6-b8b1-79f098dbca9f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  55%|█████▌    | 675/1224 [10:02<07:29,  1.22it/s]

Warning: File tcga_tnbc_data/78805478-bf7a-4d7b-8c4f-15e334430efd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  55%|█████▌    | 676/1224 [10:03<07:10,  1.27it/s]

Warning: File tcga_tnbc_data/4df2233b-3bbc-4d20-9abc-2a09b3f37383.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  55%|█████▌    | 677/1224 [10:04<07:13,  1.26it/s]

Warning: File tcga_tnbc_data/37af19f9-56f9-48ec-97a9-5b0b6e364293.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  55%|█████▌    | 678/1224 [10:05<07:10,  1.27it/s]

Warning: File tcga_tnbc_data/fe7c2cdd-7c3f-4d76-ad78-2a676116f464.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  55%|█████▌    | 679/1224 [10:05<07:09,  1.27it/s]

Warning: File tcga_tnbc_data/12959673-a8ec-4223-a5fe-0648276db5fc.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/398fa6bf-78af-473b-8f2c-a2b3b605131f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  56%|█████▌    | 680/1224 [10:07<09:15,  1.02s/it]

Warning: File tcga_tnbc_data/b1d29048-b913-40d9-bb58-97c107b95e8d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  56%|█████▌    | 681/1224 [10:08<08:35,  1.05it/s]

Warning: File tcga_tnbc_data/5b4ec1fd-516d-4c32-a233-0699e591df1a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  56%|█████▌    | 682/1224 [10:09<08:16,  1.09it/s]

Warning: File tcga_tnbc_data/9dc09c86-c728-4bd9-b2b6-2d9962dad662.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  56%|█████▌    | 683/1224 [10:09<08:00,  1.13it/s]

Warning: File tcga_tnbc_data/aa9179e0-a44c-440a-a150-a9d5727579ea.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  56%|█████▌    | 684/1224 [10:10<08:11,  1.10it/s]

Warning: File tcga_tnbc_data/77e51e8b-b21e-458a-9d00-217baa96d771.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  56%|█████▌    | 685/1224 [10:11<08:09,  1.10it/s]

Warning: File tcga_tnbc_data/4660cd29-08ac-452c-9bb8-10e9d9e906ab.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  56%|█████▌    | 686/1224 [10:12<07:54,  1.13it/s]

Warning: File tcga_tnbc_data/83eeba96-e3dc-44a3-846c-43dcc2ff9806.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  56%|█████▌    | 687/1224 [10:13<07:43,  1.16it/s]

Warning: File tcga_tnbc_data/2a73e390-7415-486e-8d15-d9ea6ede09ba.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  56%|█████▌    | 688/1224 [10:14<07:58,  1.12it/s]

Warning: File tcga_tnbc_data/c6a4afd8-8044-475f-b4fd-a1b4cb922976.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  56%|█████▋    | 689/1224 [10:15<07:51,  1.13it/s]

Warning: File tcga_tnbc_data/fcb1b40a-85c0-498c-881e-7161edcf39e6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  56%|█████▋    | 690/1224 [10:16<07:55,  1.12it/s]

Warning: File tcga_tnbc_data/a260d9e5-d88e-44eb-8431-4266c1baf68a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  56%|█████▋    | 691/1224 [10:17<07:43,  1.15it/s]

Warning: File tcga_tnbc_data/a542178a-a338-40d4-be52-b9a71af89b58.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  57%|█████▋    | 692/1224 [10:17<07:35,  1.17it/s]

Warning: File tcga_tnbc_data/8e60d7c9-0fee-415f-b7bd-072f1bcd0fac.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  57%|█████▋    | 693/1224 [10:18<07:44,  1.14it/s]

Warning: File tcga_tnbc_data/d27acb8c-2551-4ea7-8c09-f211cb4a9ec0.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  57%|█████▋    | 694/1224 [10:19<07:53,  1.12it/s]

Warning: File tcga_tnbc_data/427a04c9-9b48-49de-8a47-2adc4e1dd32a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  57%|█████▋    | 695/1224 [10:20<07:59,  1.10it/s]

Warning: File tcga_tnbc_data/95668f0b-130d-44d4-94c0-ba7a4e7798e6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  57%|█████▋    | 696/1224 [10:21<07:58,  1.10it/s]

Warning: File tcga_tnbc_data/c7aeba7e-b78e-4586-a4dd-8a04cc440737.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  57%|█████▋    | 697/1224 [10:22<07:49,  1.12it/s]

Warning: File tcga_tnbc_data/e5016a2d-c839-4962-aa12-16b6c0e1328b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  57%|█████▋    | 698/1224 [10:23<08:09,  1.07it/s]

Warning: File tcga_tnbc_data/da7f48b2-3bed-4824-8de7-187d0b22f54d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  57%|█████▋    | 700/1224 [10:25<07:51,  1.11it/s]

Warning: File tcga_tnbc_data/c9230a1c-9844-43ef-a2c3-95ea6061000b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/19520ee7-658f-4e16-8a24-291beed9f0af.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  57%|█████▋    | 701/1224 [10:26<07:36,  1.15it/s]

Warning: File tcga_tnbc_data/f0a63361-78bb-4a7f-9d78-31f7b2980ba2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  57%|█████▋    | 702/1224 [10:26<07:47,  1.12it/s]

Warning: File tcga_tnbc_data/0b829610-f28e-418e-b79d-d3351e13e1fe.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  57%|█████▋    | 703/1224 [10:27<07:37,  1.14it/s]

Warning: File tcga_tnbc_data/afedbcf7-d427-4371-9c2a-f349b03de522.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  58%|█████▊    | 705/1224 [10:29<07:58,  1.08it/s]

Warning: File tcga_tnbc_data/621b0997-70e5-415b-8d8c-1e5f90d0d4aa.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/9c87ef50-5854-4f69-820b-9e0b4d46c982.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  58%|█████▊    | 707/1224 [10:31<07:38,  1.13it/s]

Warning: File tcga_tnbc_data/8437bf97-2354-40cf-8dc4-631c5d7ae63a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/0525bcb6-d206-46c8-b37d-b9b7cc90fef6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  58%|█████▊    | 708/1224 [10:32<07:28,  1.15it/s]

Warning: File tcga_tnbc_data/15f5f60a-13f0-41a2-8711-171d19c2903a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  58%|█████▊    | 709/1224 [10:33<07:15,  1.18it/s]

Warning: File tcga_tnbc_data/ad18b7e0-57ec-41c5-99a1-0c9d8740e0f1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  58%|█████▊    | 710/1224 [10:34<07:18,  1.17it/s]

Warning: File tcga_tnbc_data/3071e512-94ea-4820-9573-668235188e34.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  58%|█████▊    | 711/1224 [10:35<07:35,  1.13it/s]

Warning: File tcga_tnbc_data/502fcba1-9d3c-4117-86fb-70a26c090692.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  58%|█████▊    | 712/1224 [10:36<07:56,  1.07it/s]

Warning: File tcga_tnbc_data/bb3c5c27-7e75-43cc-8dfd-eab290e2f9da.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  58%|█████▊    | 713/1224 [10:36<07:58,  1.07it/s]

Warning: File tcga_tnbc_data/189f1a1b-96d6-4cb9-9000-001e08dca1ba.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  58%|█████▊    | 715/1224 [10:42<15:13,  1.80s/it]

Warning: File tcga_tnbc_data/0e3cf07b-2cea-4ce7-a8f0-c8dc7d3db7a7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  58%|█████▊    | 716/1224 [10:43<12:43,  1.50s/it]

Warning: File tcga_tnbc_data/da84f488-af86-4472-bf87-063a9137e1db.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/a4fc84b0-29ff-4994-b493-1102a044838d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  59%|█████▊    | 717/1224 [10:44<11:03,  1.31s/it]

Warning: File tcga_tnbc_data/a37587aa-2e1f-42f5-a691-c4a41ae79ea9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  59%|█████▊    | 718/1224 [10:45<10:09,  1.20s/it]

Warning: File tcga_tnbc_data/c6fd0f95-d74a-49e3-9a70-fec12e63ff1a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  59%|█████▊    | 719/1224 [10:46<09:24,  1.12s/it]

Warning: File tcga_tnbc_data/5dfadec2-3a10-40a9-99be-4984e917ba88.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  59%|█████▉    | 720/1224 [10:47<08:52,  1.06s/it]

Warning: File tcga_tnbc_data/c9bc7edd-c545-4d76-9246-1bfa043a966c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  59%|█████▉    | 721/1224 [10:48<08:44,  1.04s/it]

Warning: File tcga_tnbc_data/5aaaf8b5-a75f-4070-93e8-f5b982144638.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  59%|█████▉    | 723/1224 [10:50<07:54,  1.06it/s]

Warning: File tcga_tnbc_data/0e2a0a41-fc0f-40d0-a0e7-d3eecac3cfd7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/7d8935d4-33df-4a11-a352-e4e1acc563a4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  59%|█████▉    | 724/1224 [10:51<07:50,  1.06it/s]

Warning: File tcga_tnbc_data/7493bcbc-658d-4789-a25c-9a990dcd44b8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  59%|█████▉    | 725/1224 [10:52<07:45,  1.07it/s]

Warning: File tcga_tnbc_data/c5baa506-f18b-42d8-bafd-4e9b85e1d390.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  59%|█████▉    | 726/1224 [10:52<07:44,  1.07it/s]

Warning: File tcga_tnbc_data/e22bc31b-332f-45a1-b17c-c747179abe61.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  59%|█████▉    | 727/1224 [10:53<07:26,  1.11it/s]

Warning: File tcga_tnbc_data/9985bb0b-d1cc-455b-80d9-f8007669cd5c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  59%|█████▉    | 728/1224 [10:54<07:21,  1.12it/s]

Warning: File tcga_tnbc_data/c1d62c39-f3ab-47d3-b654-8b6285cd97a3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  60%|█████▉    | 729/1224 [10:55<07:29,  1.10it/s]

Warning: File tcga_tnbc_data/451ecdf8-433f-4d38-8ab6-3cc8d428ed95.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  60%|█████▉    | 730/1224 [10:56<07:30,  1.10it/s]

Warning: File tcga_tnbc_data/440bdce7-eb0c-4661-b96a-e90d10e230d6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  60%|█████▉    | 731/1224 [10:57<07:09,  1.15it/s]

Warning: File tcga_tnbc_data/4c2a67aa-54ef-405d-a498-45c1790380da.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  60%|█████▉    | 732/1224 [10:58<07:06,  1.15it/s]

Warning: File tcga_tnbc_data/3e0c80d6-5091-454c-ad27-eb513cf6f45d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  60%|█████▉    | 733/1224 [10:59<07:08,  1.15it/s]

Warning: File tcga_tnbc_data/c47a7c89-551d-4115-94e4-7ba4b938e88b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  60%|█████▉    | 734/1224 [11:00<07:45,  1.05it/s]

Warning: File tcga_tnbc_data/7d1c40bf-6119-4f2b-bb33-3ba23546799f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  60%|██████    | 735/1224 [11:01<07:49,  1.04it/s]

Warning: File tcga_tnbc_data/c587bd27-778a-4729-b614-e0631bb3717b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  60%|██████    | 736/1224 [11:02<07:44,  1.05it/s]

Warning: File tcga_tnbc_data/8e063797-856c-491a-b702-1a37ebf6b6a8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  60%|██████    | 737/1224 [11:02<07:26,  1.09it/s]

Warning: File tcga_tnbc_data/70f7e473-4a58-4186-aedd-1bab29bef4f3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  60%|██████    | 738/1224 [11:03<07:01,  1.15it/s]

Warning: File tcga_tnbc_data/fd94a0ed-37d8-49a5-af96-e2160a9e6096.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  60%|██████    | 739/1224 [11:04<06:57,  1.16it/s]

Warning: File tcga_tnbc_data/97c68557-c395-40bb-aaa3-a16514da3644.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  61%|██████    | 741/1224 [11:06<06:51,  1.17it/s]

Warning: File tcga_tnbc_data/56cc8f11-ba1c-48c9-8455-1f73640f9cf5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/06598222-e18b-45b1-9e4b-407aa120442c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  61%|██████    | 742/1224 [11:07<06:47,  1.18it/s]

Warning: File tcga_tnbc_data/ed1497db-7c6f-4bd2-83ed-ee05fa286f8b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  61%|██████    | 744/1224 [11:08<06:51,  1.17it/s]

Warning: File tcga_tnbc_data/62e7008b-f4ca-40e3-88b3-7354ba2585ac.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  61%|██████    | 745/1224 [11:09<06:52,  1.16it/s]

Warning: File tcga_tnbc_data/41e79241-b5a4-4541-848b-e20e693e8ee3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/c55e6460-fea1-468e-951e-bf45bbddd7a6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  61%|██████    | 746/1224 [11:10<06:46,  1.18it/s]

Warning: File tcga_tnbc_data/e67bbc10-91cf-406e-8d5f-8d44c77315f1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  61%|██████    | 747/1224 [11:11<06:32,  1.21it/s]

Warning: File tcga_tnbc_data/e6f927ef-840f-438a-9559-863cc64f71e0.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  61%|██████    | 748/1224 [11:12<06:51,  1.16it/s]

Warning: File tcga_tnbc_data/b2c326d7-25ab-42dc-afc2-bc93381062ea.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  61%|██████    | 749/1224 [11:13<06:57,  1.14it/s]

Warning: File tcga_tnbc_data/65bc2a34-2355-4193-b20e-439f2d7f6df2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  61%|██████▏   | 751/1224 [11:14<06:47,  1.16it/s]

Warning: File tcga_tnbc_data/ee39aea6-23f8-470f-863c-545ef6c5ea77.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/8d558ae5-f3a1-49fa-aa44-5abc6244b57a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  61%|██████▏   | 752/1224 [11:15<06:30,  1.21it/s]

Warning: File tcga_tnbc_data/97dbbbc5-cd1a-4bb8-99c5-600870ccd35d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  62%|██████▏   | 753/1224 [11:16<06:19,  1.24it/s]

Warning: File tcga_tnbc_data/87b7171a-7340-4e1e-849b-c52351f23ab0.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  62%|██████▏   | 754/1224 [11:17<06:35,  1.19it/s]

Warning: File tcga_tnbc_data/03891509-3109-450d-8564-77b024a6128e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  62%|██████▏   | 755/1224 [11:18<06:35,  1.18it/s]

Warning: File tcga_tnbc_data/7300d49e-2e8c-42e0-873a-1674a19b71e6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  62%|██████▏   | 756/1224 [11:19<07:01,  1.11it/s]

Warning: File tcga_tnbc_data/57a43ef5-102a-4cd9-833d-00a2daf4e56a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  62%|██████▏   | 757/1224 [11:20<06:58,  1.12it/s]

Warning: File tcga_tnbc_data/336f0e3e-878e-4ee8-b2aa-cc536f3432f3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  62%|██████▏   | 758/1224 [11:21<07:12,  1.08it/s]

Warning: File tcga_tnbc_data/16b9a021-447f-44d8-a1f9-ad45edc73bc9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  62%|██████▏   | 760/1224 [11:22<06:46,  1.14it/s]

Warning: File tcga_tnbc_data/30ff778c-844b-4140-9025-7ab1938f10a9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/dbdaac00-02bf-41e0-8d54-734273e10baa.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  62%|██████▏   | 761/1224 [11:23<06:41,  1.15it/s]

Warning: File tcga_tnbc_data/b5f2a171-35a3-4b7f-9221-199c589f3147.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  62%|██████▏   | 762/1224 [11:24<06:38,  1.16it/s]

Warning: File tcga_tnbc_data/09f1c0ee-ee22-435f-88c9-d9f5c936c45c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  62%|██████▏   | 763/1224 [11:25<06:44,  1.14it/s]

Warning: File tcga_tnbc_data/c441b2f1-d5ad-4aae-a37e-946579ff604f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  62%|██████▏   | 764/1224 [11:26<06:42,  1.14it/s]

Warning: File tcga_tnbc_data/9d61e56d-690b-4d66-891a-f8d010d704cf.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  62%|██████▎   | 765/1224 [11:27<06:50,  1.12it/s]

Warning: File tcga_tnbc_data/287a036d-5b2d-4faf-93a0-cf0be006fa6b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  63%|██████▎   | 766/1224 [11:28<06:42,  1.14it/s]

Warning: File tcga_tnbc_data/1dd898ab-3b85-4932-b889-0eb0a494f2b6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  63%|██████▎   | 767/1224 [11:28<06:39,  1.14it/s]

Warning: File tcga_tnbc_data/46933fec-1800-4da5-814c-30cce4ae2fb5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  63%|██████▎   | 768/1224 [11:29<06:49,  1.11it/s]

Warning: File tcga_tnbc_data/7d496f9f-8a04-496a-ad25-68b1b72f864a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  63%|██████▎   | 769/1224 [11:30<06:45,  1.12it/s]

Warning: File tcga_tnbc_data/3728cb73-4a8a-4392-8140-f027ad876cf2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  63%|██████▎   | 770/1224 [11:31<06:38,  1.14it/s]

Warning: File tcga_tnbc_data/f24d6e88-634e-4d86-b993-76a40f1190d0.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  63%|██████▎   | 771/1224 [11:32<06:46,  1.12it/s]

Warning: File tcga_tnbc_data/3f44f7ab-7299-4b8e-b2b9-16ed5291e727.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  63%|██████▎   | 772/1224 [11:33<06:20,  1.19it/s]

Warning: File tcga_tnbc_data/f7e414a0-c2ca-40c7-a7a0-282d80247fa0.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  63%|██████▎   | 773/1224 [11:33<06:06,  1.23it/s]

Warning: File tcga_tnbc_data/a6f9b537-d843-4181-9ba8-712c44986581.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  63%|██████▎   | 774/1224 [11:34<05:59,  1.25it/s]

Warning: File tcga_tnbc_data/c7db3ef0-0440-4fcf-a18b-c70b3f88e327.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  63%|██████▎   | 775/1224 [11:35<05:59,  1.25it/s]

Warning: File tcga_tnbc_data/59858555-bc6a-4286-8280-0f8341123cac.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  63%|██████▎   | 776/1224 [11:36<06:23,  1.17it/s]

Warning: File tcga_tnbc_data/4a2ad226-ed26-4f81-af7d-9d8b6db7cdd4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  63%|██████▎   | 777/1224 [11:37<06:48,  1.09it/s]

Warning: File tcga_tnbc_data/58764dda-7c61-4705-a834-4d654c60ef2b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  64%|██████▎   | 778/1224 [11:38<06:51,  1.08it/s]

Warning: File tcga_tnbc_data/5d720a05-3673-45be-9163-08e0fc332f80.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  64%|██████▎   | 779/1224 [11:39<06:45,  1.10it/s]

Warning: File tcga_tnbc_data/bdee019c-38ae-4686-84fe-2454ba4c70dc.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  64%|██████▍   | 781/1224 [11:41<06:31,  1.13it/s]

Warning: File tcga_tnbc_data/6f3bd40b-98b5-431b-a0b3-c7767b479d7d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/26702590-872f-4e36-a631-ee6cb3f61ec4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  64%|██████▍   | 782/1224 [11:41<06:24,  1.15it/s]

Warning: File tcga_tnbc_data/7e0c78b6-4020-47b6-a8bf-46cf290c5c85.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  64%|██████▍   | 783/1224 [11:42<06:23,  1.15it/s]

Warning: File tcga_tnbc_data/c1ac2f8b-9ff2-47b9-a685-6cf10a7a925f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  64%|██████▍   | 784/1224 [11:43<06:23,  1.15it/s]

Warning: File tcga_tnbc_data/18340589-696e-4f56-80c2-dc7d7428c471.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  64%|██████▍   | 786/1224 [11:45<06:08,  1.19it/s]

Warning: File tcga_tnbc_data/74b16304-eb3f-4311-9b2e-dbf5eac89b44.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  64%|██████▍   | 787/1224 [11:46<06:06,  1.19it/s]

Warning: File tcga_tnbc_data/b3eb0ef4-66e8-48df-9acc-fd252dc2ac61.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/318c3a49-64bc-4704-8739-d4cf31cef51f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  64%|██████▍   | 788/1224 [11:47<06:10,  1.18it/s]

Warning: File tcga_tnbc_data/51948358-b1bb-46d7-a25c-8d3fe81557f0.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  64%|██████▍   | 789/1224 [11:47<06:10,  1.17it/s]

Warning: File tcga_tnbc_data/ef181439-d071-40e0-a185-f29343085f8c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  65%|██████▍   | 790/1224 [11:48<06:07,  1.18it/s]

Warning: File tcga_tnbc_data/1af79ae6-8b40-40ae-8f68-195d8367ac38.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  65%|██████▍   | 791/1224 [11:49<06:30,  1.11it/s]

Warning: File tcga_tnbc_data/115d8b96-f3ac-4e6f-a975-60b71b32531a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  65%|██████▍   | 792/1224 [11:50<06:40,  1.08it/s]

Warning: File tcga_tnbc_data/a9b2ff1a-3b37-4388-a1e6-826e2edea49b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  65%|██████▍   | 793/1224 [11:51<06:40,  1.08it/s]

Warning: File tcga_tnbc_data/e0cb738d-854a-4033-b370-79fa28d7cef8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  65%|██████▍   | 794/1224 [11:52<06:39,  1.08it/s]

Warning: File tcga_tnbc_data/76d94448-4fd0-4476-af15-3c845d70851d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  65%|██████▍   | 795/1224 [11:53<06:31,  1.10it/s]

Warning: File tcga_tnbc_data/d9126541-4eb3-48fc-88ed-2e0ecea0d9d4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  65%|██████▌   | 796/1224 [11:54<06:24,  1.11it/s]

Warning: File tcga_tnbc_data/3974a62d-d399-42f3-b550-336e793b0cfe.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  65%|██████▌   | 797/1224 [11:55<06:28,  1.10it/s]

Warning: File tcga_tnbc_data/9b980569-4da2-43ee-a06a-18ee09baf41d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  65%|██████▌   | 798/1224 [11:56<06:31,  1.09it/s]

Warning: File tcga_tnbc_data/c7646bc5-436b-4ad5-b5ae-894b2e843cda.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  65%|██████▌   | 799/1224 [11:57<06:25,  1.10it/s]

Warning: File tcga_tnbc_data/1deadf31-dc7d-4361-8041-ab0a27edebb3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  65%|██████▌   | 800/1224 [11:58<06:22,  1.11it/s]

Warning: File tcga_tnbc_data/56081713-6249-4a3f-8498-277e688d1ec9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  65%|██████▌   | 801/1224 [11:58<06:20,  1.11it/s]

Warning: File tcga_tnbc_data/ac7c3a38-5d88-488e-86f7-1c72a26fe5ef.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  66%|██████▌   | 802/1224 [11:59<06:03,  1.16it/s]

Warning: File tcga_tnbc_data/f90e51cb-b862-4a76-acb0-cc882bfb4ee6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  66%|██████▌   | 803/1224 [12:00<06:08,  1.14it/s]

Warning: File tcga_tnbc_data/90e074a0-ca6d-4031-aa26-f79e5c662ba7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  66%|██████▌   | 804/1224 [12:01<06:07,  1.14it/s]

Warning: File tcga_tnbc_data/f11c5295-697a-46f7-91fe-b760dc9f1029.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  66%|██████▌   | 805/1224 [12:02<06:28,  1.08it/s]

Warning: File tcga_tnbc_data/898920ea-31b3-4244-a413-4b957e93594f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  66%|██████▌   | 806/1224 [12:03<06:36,  1.06it/s]

Warning: File tcga_tnbc_data/7af23ba7-e5bf-41b9-b91f-5709321dadb7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  66%|██████▌   | 807/1224 [12:04<06:23,  1.09it/s]

Warning: File tcga_tnbc_data/75182885-7501-49b1-bb0d-8a88da1080a3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  66%|██████▌   | 809/1224 [12:06<06:04,  1.14it/s]

Warning: File tcga_tnbc_data/25c20f52-1031-4cd1-a9ed-4b2049b01a3e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/84e36620-ae1e-4221-84c9-3a6f1d11606d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  66%|██████▌   | 810/1224 [12:06<05:50,  1.18it/s]

Warning: File tcga_tnbc_data/870fb4d4-8366-4bfa-b4c1-04d55eded427.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  66%|██████▋   | 812/1224 [12:08<05:46,  1.19it/s]

Warning: File tcga_tnbc_data/a1a6d1dd-a1c6-4c5c-b54d-42de80680bc3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  66%|██████▋   | 813/1224 [12:09<05:32,  1.24it/s]

Warning: File tcga_tnbc_data/04024f75-7405-4ccc-8976-91d0a3035b3a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  67%|██████▋   | 814/1224 [12:09<05:23,  1.27it/s]

Warning: File tcga_tnbc_data/5bee33e8-6c0e-4b47-b5b4-a82bf5784d81.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  67%|██████▋   | 815/1224 [12:11<06:32,  1.04it/s]

Warning: File tcga_tnbc_data/77f150b1-5f40-442d-91c5-6d3571513513.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  67%|██████▋   | 816/1224 [12:12<06:10,  1.10it/s]

Warning: File tcga_tnbc_data/1581b466-9502-491e-828b-dd9b721690cb.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/a217c1ab-e2cb-487c-982a-8241da38272f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  67%|██████▋   | 818/1224 [12:13<05:52,  1.15it/s]

Warning: File tcga_tnbc_data/f55eb7a0-34e6-4d0d-9427-7d7896ddf060.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/659f84a0-df18-44a4-8b82-ebaec356153d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  67%|██████▋   | 819/1224 [12:14<05:57,  1.13it/s]

Warning: File tcga_tnbc_data/4ef4f9f1-7883-4fff-91c0-223cac5f1887.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  67%|██████▋   | 820/1224 [12:15<06:04,  1.11it/s]

Warning: File tcga_tnbc_data/469c052c-d2c8-4626-af1c-7276653168fe.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  67%|██████▋   | 822/1224 [12:17<05:46,  1.16it/s]

Warning: File tcga_tnbc_data/ec9437c2-dad0-471a-bd2c-faa61846af57.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  67%|██████▋   | 823/1224 [12:18<05:37,  1.19it/s]

Warning: File tcga_tnbc_data/430184b1-040d-4b3a-863d-1e6c71009d93.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  67%|██████▋   | 824/1224 [12:18<05:28,  1.22it/s]

Warning: File tcga_tnbc_data/d7a48283-c113-4745-be6b-553966e6b457.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  67%|██████▋   | 825/1224 [12:19<05:20,  1.25it/s]

Warning: File tcga_tnbc_data/1936440a-9cfc-4b04-af40-3fbc22fe87f6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  67%|██████▋   | 826/1224 [12:20<05:33,  1.19it/s]

Warning: File tcga_tnbc_data/6efd37a6-1669-4cdd-95b6-60c688e1e236.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/a8898537-0afa-4655-b123-78c11b90c53a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  68%|██████▊   | 827/1224 [12:21<05:37,  1.18it/s]

Warning: File tcga_tnbc_data/c89590e8-8b74-4c05-a022-e21eab5cffdd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  68%|██████▊   | 828/1224 [12:22<05:38,  1.17it/s]

Warning: File tcga_tnbc_data/0b798fe4-1c51-4c36-afc8-5bee39fd6077.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  68%|██████▊   | 830/1224 [12:23<05:22,  1.22it/s]

Warning: File tcga_tnbc_data/14edb678-3b6c-4a58-aabf-0f9d1f7d9bdc.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  68%|██████▊   | 831/1224 [12:24<05:34,  1.17it/s]

Warning: File tcga_tnbc_data/27f4c9d4-d6ba-4fea-9f0b-fb06066e69a8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/7e915086-4926-4670-9f43-e35e2d04d6c5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  68%|██████▊   | 832/1224 [12:25<05:56,  1.10it/s]

Warning: File tcga_tnbc_data/89ece3f8-e2db-4ed6-b5b8-dd4df34d6224.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  68%|██████▊   | 833/1224 [12:26<05:40,  1.15it/s]

Warning: File tcga_tnbc_data/14979d31-e8b1-4948-beea-f913dfefa200.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  68%|██████▊   | 834/1224 [12:27<05:44,  1.13it/s]

Warning: File tcga_tnbc_data/fb397586-1b5b-40e0-a885-8663f9c76f6d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  68%|██████▊   | 836/1224 [12:29<05:34,  1.16it/s]

Warning: File tcga_tnbc_data/99367019-5583-4bcc-aa62-25916515fe17.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  68%|██████▊   | 837/1224 [12:30<05:28,  1.18it/s]

Warning: File tcga_tnbc_data/c1f3f326-e99f-4811-9665-d15d6d8a1c33.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  68%|██████▊   | 838/1224 [12:30<05:17,  1.21it/s]

Warning: File tcga_tnbc_data/90452523-0f9a-4c14-9d5f-e44f7079fb18.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  69%|██████▊   | 839/1224 [12:31<05:31,  1.16it/s]

Warning: File tcga_tnbc_data/cc7f30ec-5369-45ec-80cb-68534838a655.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/cde8361d-ade2-4103-b092-3ee9cbf85ea1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  69%|██████▊   | 840/1224 [12:32<05:28,  1.17it/s]

Warning: File tcga_tnbc_data/d240cdef-e1a3-481f-a0d5-895d7cc5cabd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  69%|██████▉   | 842/1224 [12:34<05:28,  1.16it/s]

Warning: File tcga_tnbc_data/0022cd20-f64f-4773-b9ff-a3de0b71b259.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  69%|██████▉   | 843/1224 [12:35<05:34,  1.14it/s]

Warning: File tcga_tnbc_data/4d27c8ac-375b-414a-8f88-75092f03bdd8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  69%|██████▉   | 844/1224 [12:36<05:29,  1.15it/s]

Warning: File tcga_tnbc_data/cc7ea1eb-4947-4030-ace5-673e9441a9a8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  69%|██████▉   | 845/1224 [12:36<05:11,  1.22it/s]

Warning: File tcga_tnbc_data/577dde85-20c6-44c0-bf77-bda22a7f58c0.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/561bb38a-f9b8-4a0a-b03b-fbe70859869a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  69%|██████▉   | 847/1224 [12:38<05:11,  1.21it/s]

Warning: File tcga_tnbc_data/83707590-e4c8-4e06-98d5-f6c5dc710d1b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/1300bf72-ead0-4c03-b140-fca26302b43c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  69%|██████▉   | 848/1224 [12:39<05:32,  1.13it/s]

Warning: File tcga_tnbc_data/50c7c034-fccb-4eb1-b8db-e0a5d9e50172.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  69%|██████▉   | 849/1224 [12:40<05:24,  1.16it/s]

Warning: File tcga_tnbc_data/f8e5691a-e24d-4dba-873e-9ffa3ca12bb6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  70%|██████▉   | 851/1224 [12:42<05:24,  1.15it/s]

Warning: File tcga_tnbc_data/d01e4cd5-3c52-4655-8b7c-ef6070d58090.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/09a491b5-1bfb-47d9-963f-69f6c7e6c1e5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  70%|██████▉   | 852/1224 [12:42<05:24,  1.15it/s]

Warning: File tcga_tnbc_data/e52108ad-c4ab-4ab4-8636-caaeaae7ea62.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  70%|██████▉   | 854/1224 [12:44<05:19,  1.16it/s]

Warning: File tcga_tnbc_data/57044315-cc7f-4677-90fa-2e959740bd9c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  70%|██████▉   | 855/1224 [12:45<05:27,  1.13it/s]

Warning: File tcga_tnbc_data/e4744b03-e390-43f2-a14b-86bddceaf9ae.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/8f1fa5b0-7b8b-41ae-9ba4-9bce8776e5a8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  70%|██████▉   | 856/1224 [12:46<05:23,  1.14it/s]

Warning: File tcga_tnbc_data/67eceef4-f870-47a0-82d8-b39aa3282bd3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  70%|███████   | 857/1224 [12:47<05:11,  1.18it/s]

Warning: File tcga_tnbc_data/f7619693-b880-408e-8be5-f266f61a403e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  70%|███████   | 859/1224 [12:48<05:13,  1.17it/s]

Warning: File tcga_tnbc_data/ecf9996e-0cba-4394-9f5a-51fceab1ac56.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  70%|███████   | 860/1224 [12:49<05:10,  1.17it/s]

Warning: File tcga_tnbc_data/b3b9ae66-e8d1-4a32-a2a9-46931b753527.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  70%|███████   | 861/1224 [12:50<05:09,  1.17it/s]

Warning: File tcga_tnbc_data/e5f6e803-fc44-4f0f-9f6e-562b4e7d77ca.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/2e60bad2-2dd2-4dc3-aa45-dfc36ef4884b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  70%|███████   | 862/1224 [12:51<05:29,  1.10it/s]

Warning: File tcga_tnbc_data/762adf07-6d7a-4d02-98fb-16fffd548a93.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  71%|███████   | 863/1224 [12:52<05:17,  1.14it/s]

Warning: File tcga_tnbc_data/da29bf10-4629-4234-8e49-43a4513fe579.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  71%|███████   | 864/1224 [12:53<05:26,  1.10it/s]

Warning: File tcga_tnbc_data/4bf6ebc1-575d-49e4-9f66-068b537373c0.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  71%|███████   | 865/1224 [12:54<05:22,  1.11it/s]

Warning: File tcga_tnbc_data/3e5dce7b-3f1e-4b43-b83e-8c0fc654e9c4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  71%|███████   | 867/1224 [12:56<05:12,  1.14it/s]

Warning: File tcga_tnbc_data/e3cfb618-5ed2-4841-b7c1-a9f049ac8f9d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  71%|███████   | 868/1224 [12:56<05:16,  1.12it/s]

Warning: File tcga_tnbc_data/0fef4f4a-1c4e-4035-acff-af12febbaf1e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/a9b5ab37-10c2-4fb6-9c4e-3fcd5ea26526.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  71%|███████   | 870/1224 [12:58<05:00,  1.18it/s]

Warning: File tcga_tnbc_data/2fa144d0-2776-46d9-a7d4-41f68a1d3727.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/28b84c2b-6524-46ee-9d1e-24e7d6379af4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  71%|███████   | 871/1224 [12:59<05:11,  1.13it/s]

Warning: File tcga_tnbc_data/d9ea5bde-aa1a-4210-976f-b2f67c6d0191.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  71%|███████   | 872/1224 [13:00<05:28,  1.07it/s]

Warning: File tcga_tnbc_data/2081a155-9d2d-41f6-b243-68a12e9b342a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  71%|███████▏  | 873/1224 [13:01<05:29,  1.07it/s]

Warning: File tcga_tnbc_data/ed797859-4d7e-40e6-bae3-54ef15ad0f0a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  71%|███████▏  | 874/1224 [13:02<05:27,  1.07it/s]

Warning: File tcga_tnbc_data/812eeeed-1222-4add-b6d1-f53ae2669218.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  71%|███████▏  | 875/1224 [13:03<05:33,  1.05it/s]

Warning: File tcga_tnbc_data/7fa9ad2e-67a7-449f-be73-9e18dc46b529.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  72%|███████▏  | 876/1224 [13:04<05:20,  1.08it/s]

Warning: File tcga_tnbc_data/12f8a326-1417-478e-a45e-abdff8b44266.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  72%|███████▏  | 877/1224 [13:05<05:22,  1.08it/s]

Warning: File tcga_tnbc_data/7b738087-65b1-4c6e-94c4-d0ba6bb17098.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  72%|███████▏  | 879/1224 [13:06<05:03,  1.14it/s]

Warning: File tcga_tnbc_data/95f4620f-f9b0-4533-bb13-f412d774244a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/586d9c21-e58a-4171-9755-30c0e8b16293.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  72%|███████▏  | 881/1224 [13:08<04:51,  1.18it/s]

Warning: File tcga_tnbc_data/9b5bdd89-05ac-4cde-beee-66739a903939.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/373e0f41-a47e-4f4e-88fe-9703d16a840c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  72%|███████▏  | 882/1224 [13:09<04:37,  1.23it/s]

Warning: File tcga_tnbc_data/bd239a8e-56e2-45ca-bc44-bff98b72c1d6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  72%|███████▏  | 883/1224 [13:10<04:33,  1.25it/s]

Warning: File tcga_tnbc_data/94ae90d4-16a8-4922-b6b6-e5fcec9d0ae6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  72%|███████▏  | 885/1224 [13:12<05:11,  1.09it/s]

Warning: File tcga_tnbc_data/6a89e8a2-577e-4531-98e8-ba6fc6cfe525.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  72%|███████▏  | 886/1224 [13:13<05:07,  1.10it/s]

Warning: File tcga_tnbc_data/8fb0660c-fb39-47f0-8450-1f7abff3b656.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/4c46a463-f0e3-4e19-ad95-5dab0231d1c6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  73%|███████▎  | 888/1224 [13:14<04:40,  1.20it/s]

Warning: File tcga_tnbc_data/679ba4c3-49da-47d1-bef2-ce25fd862758.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  73%|███████▎  | 889/1224 [13:15<04:38,  1.20it/s]

Warning: File tcga_tnbc_data/26466526-2d6e-4869-a06a-c33344e5fab2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/ccd1dcec-f3c1-42ca-b3e8-a73a7d2237ff.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  73%|███████▎  | 890/1224 [13:16<04:44,  1.17it/s]

Warning: File tcga_tnbc_data/37bf6454-a4e7-4e00-9562-57ba6fd58b6d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  73%|███████▎  | 891/1224 [13:17<04:54,  1.13it/s]

Warning: File tcga_tnbc_data/59d61414-a337-4e45-9e89-4526dde82786.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  73%|███████▎  | 892/1224 [13:18<05:02,  1.10it/s]

Warning: File tcga_tnbc_data/cdf2bc60-591c-4219-bf96-40dd8b6c8459.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  73%|███████▎  | 893/1224 [13:19<05:00,  1.10it/s]

Warning: File tcga_tnbc_data/15e249cf-4c45-4006-84fd-899f9927e376.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  73%|███████▎  | 895/1224 [13:20<04:48,  1.14it/s]

Warning: File tcga_tnbc_data/5422b305-6411-4a01-b371-dc74c9e351e4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/9e4b6ad6-99f7-4244-8f1b-20b7b36c457f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  73%|███████▎  | 897/1224 [13:22<04:47,  1.14it/s]

Warning: File tcga_tnbc_data/e4732dd4-002a-4b37-9a56-d01d551e9cc3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  73%|███████▎  | 898/1224 [13:23<04:48,  1.13it/s]

Warning: File tcga_tnbc_data/86ce8513-c2a6-4b5c-9811-904f0eee21a0.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/eea8e274-7b23-444d-999d-1741d7a928d2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  74%|███████▎  | 900/1224 [13:25<04:25,  1.22it/s]

Warning: File tcga_tnbc_data/2b64d9ef-56fc-4362-99c7-d0cc6011c2a4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  74%|███████▎  | 901/1224 [13:25<04:26,  1.21it/s]

Warning: File tcga_tnbc_data/526d750f-3cab-4379-9b3e-1b7f9fa84528.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  74%|███████▎  | 902/1224 [13:26<04:32,  1.18it/s]

Warning: File tcga_tnbc_data/2bf56d2d-8c5e-4579-847b-03fd0ba46143.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  74%|███████▍  | 903/1224 [13:27<04:23,  1.22it/s]

Warning: File tcga_tnbc_data/de5e449b-bc57-4836-89e4-73a3ba24abdf.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/1341b934-ead3-4c4a-bd84-09084895fa83.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  74%|███████▍  | 904/1224 [13:28<04:26,  1.20it/s]

Warning: File tcga_tnbc_data/c440cfb1-33ec-4be4-a4a4-4aea9a66d021.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  74%|███████▍  | 905/1224 [13:29<04:33,  1.17it/s]

Warning: File tcga_tnbc_data/50e8fce6-5775-41d6-bcaa-73773db999e2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  74%|███████▍  | 907/1224 [13:31<04:47,  1.10it/s]

Warning: File tcga_tnbc_data/04a7cce8-c3b3-4994-9dac-c0e53099f37d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  74%|███████▍  | 908/1224 [13:32<04:41,  1.12it/s]

Warning: File tcga_tnbc_data/3396edba-0d2a-4485-ad0a-5114b38c1abe.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/4382bb60-997e-4a1a-9cdb-3d8738806379.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  74%|███████▍  | 909/1224 [13:33<04:50,  1.08it/s]

Warning: File tcga_tnbc_data/793d3caa-8353-4536-83e5-711215bd51e9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  74%|███████▍  | 911/1224 [13:34<04:37,  1.13it/s]

Warning: File tcga_tnbc_data/d67d6fbf-50fa-485e-8ac7-a3c7ac33b3b2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/871d28f4-09d5-4f16-8c29-4aa7d247f3e3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  75%|███████▍  | 913/1224 [13:36<04:38,  1.12it/s]

Warning: File tcga_tnbc_data/bc0a4326-63d2-4ec4-9af6-7b421aa8aa49.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  75%|███████▍  | 914/1224 [13:37<04:28,  1.15it/s]

Warning: File tcga_tnbc_data/56a26df4-d9c1-4f43-bb44-8afd34eea927.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/3b9e620f-a661-4a1d-ac46-ab4c56a4b241.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  75%|███████▍  | 915/1224 [13:38<04:33,  1.13it/s]

Warning: File tcga_tnbc_data/b93b04d3-7526-4d65-bc15-0148e75ac225.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  75%|███████▍  | 916/1224 [13:39<04:44,  1.08it/s]

Warning: File tcga_tnbc_data/e0bd84f0-9524-4bd2-aa92-7205357596e5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  75%|███████▍  | 917/1224 [13:40<04:50,  1.06it/s]

Warning: File tcga_tnbc_data/b0fc63c9-c4aa-4206-8636-47245f510cff.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  75%|███████▌  | 918/1224 [13:41<04:54,  1.04it/s]

Warning: File tcga_tnbc_data/b9eb33d4-1017-42cf-b72c-f917de5425e7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  75%|███████▌  | 919/1224 [13:42<04:42,  1.08it/s]

Warning: File tcga_tnbc_data/41a97024-43f7-41b8-8755-94cd29105a5f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  75%|███████▌  | 921/1224 [13:44<04:38,  1.09it/s]

Warning: File tcga_tnbc_data/6b62d6dd-bb6f-4f39-9041-992c47b875f3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/3bb2e240-9cea-4dd2-be32-6bc6976a79b1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  75%|███████▌  | 923/1224 [13:45<04:20,  1.16it/s]

Warning: File tcga_tnbc_data/e6cbdcab-7fd1-43a6-be43-68b6a0fb4fe9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/9415696a-44d9-477f-aba3-0a30ded48778.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  75%|███████▌  | 924/1224 [13:46<04:22,  1.14it/s]

Warning: File tcga_tnbc_data/8644d07c-979f-4ec6-928a-afe9229fb9f1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  76%|███████▌  | 926/1224 [13:48<04:08,  1.20it/s]

Warning: File tcga_tnbc_data/61f32a8d-4649-4ea8-8374-00ab281464bf.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  76%|███████▌  | 927/1224 [13:49<03:59,  1.24it/s]

Warning: File tcga_tnbc_data/b3d19aa0-af01-4998-b234-81f313b7a6f0.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  76%|███████▌  | 928/1224 [13:49<04:12,  1.17it/s]

Warning: File tcga_tnbc_data/4b445a8f-b60b-44c3-b501-de93010172f7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  76%|███████▌  | 929/1224 [13:50<04:02,  1.22it/s]

Warning: File tcga_tnbc_data/ec67e25e-9cc6-45a7-a7c0-8dc778ae14c1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  76%|███████▌  | 930/1224 [13:51<04:05,  1.20it/s]

Warning: File tcga_tnbc_data/5dee4a6f-9cf4-4360-a37b-e7b94aa70dac.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  76%|███████▌  | 931/1224 [13:52<04:03,  1.21it/s]

Warning: File tcga_tnbc_data/debafec8-b9f4-45f3-aa4c-8e48e58e6a49.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/4af55932-ab7a-41e5-aa7f-fb16ab18c629.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  76%|███████▌  | 932/1224 [13:53<04:05,  1.19it/s]

Warning: File tcga_tnbc_data/1d0878a6-5c7c-40b9-8eab-64981d783b71.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  76%|███████▌  | 933/1224 [13:54<04:11,  1.16it/s]

Warning: File tcga_tnbc_data/9568dc22-f91c-44dd-95ec-370466ee64c3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  76%|███████▋  | 935/1224 [13:55<04:11,  1.15it/s]

Warning: File tcga_tnbc_data/7d5e390d-86f3-4988-9606-aeedabd31b52.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/404cea41-efa9-44c0-84a1-5dd603d7a2a4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  76%|███████▋  | 936/1224 [13:56<04:13,  1.14it/s]

Warning: File tcga_tnbc_data/c4afcca9-94e4-4ecd-98d1-0aab86de8685.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  77%|███████▋  | 937/1224 [13:57<04:11,  1.14it/s]

Warning: File tcga_tnbc_data/5223fb98-dd63-4c20-a7c0-02e0b13ccb33.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  77%|███████▋  | 938/1224 [13:58<04:12,  1.13it/s]

Warning: File tcga_tnbc_data/699e47b8-5396-43eb-927d-8d05b0e79644.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  77%|███████▋  | 939/1224 [13:59<04:15,  1.12it/s]

Warning: File tcga_tnbc_data/11e658a7-64e3-47ac-8993-eea0d17fc949.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  77%|███████▋  | 940/1224 [14:00<04:17,  1.10it/s]

Warning: File tcga_tnbc_data/148fc636-0b7b-4f10-b513-45edcf71a79e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  77%|███████▋  | 942/1224 [14:02<04:04,  1.15it/s]

Warning: File tcga_tnbc_data/d32a2386-8747-4f9f-84b2-130a2c948342.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/52151eca-7819-496e-bf31-4875b68d429d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  77%|███████▋  | 944/1224 [14:04<04:13,  1.10it/s]

Warning: File tcga_tnbc_data/d144a154-2dcb-484f-b50d-1b65ab9eb19e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/cee943a8-ea26-4b2f-b8a4-66300ccacfb5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  77%|███████▋  | 945/1224 [14:05<04:43,  1.02s/it]

Warning: File tcga_tnbc_data/cf801232-8aa2-4ede-80b0-8c5b9876941b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  77%|███████▋  | 946/1224 [14:06<04:39,  1.01s/it]

Warning: File tcga_tnbc_data/a701ab46-0745-4f23-8723-df5846e8806f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  77%|███████▋  | 947/1224 [14:07<04:32,  1.02it/s]

Warning: File tcga_tnbc_data/26caf8b1-0202-4656-9bb9-4a80ffc94118.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  78%|███████▊  | 949/1224 [14:08<04:14,  1.08it/s]

Warning: File tcga_tnbc_data/e7789185-2581-4846-bafd-8b920edc0973.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/a2837f64-2441-4d31-befc-514f8526b1f7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  78%|███████▊  | 950/1224 [14:09<04:09,  1.10it/s]

Warning: File tcga_tnbc_data/4d2cc90a-574f-4184-9a1c-86af222e9bb6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  78%|███████▊  | 951/1224 [14:10<04:08,  1.10it/s]

Warning: File tcga_tnbc_data/41a87746-ec8e-47e3-986c-d1a119e7c96b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  78%|███████▊  | 952/1224 [14:11<03:56,  1.15it/s]

Warning: File tcga_tnbc_data/fd7a6cfc-0ebe-4b79-b93d-d70b9bf533bc.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  78%|███████▊  | 953/1224 [14:12<03:50,  1.18it/s]

Warning: File tcga_tnbc_data/5fe2671d-4314-444b-adc1-64bbc6a85aab.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  78%|███████▊  | 954/1224 [14:13<03:49,  1.18it/s]

Warning: File tcga_tnbc_data/1ca86ab0-2f8a-4cd3-81b8-d19e8579b1d6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  78%|███████▊  | 956/1224 [14:14<03:33,  1.25it/s]

Warning: File tcga_tnbc_data/00b13ccf-ad7c-4613-8366-7c583a399691.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  78%|███████▊  | 957/1224 [14:15<03:40,  1.21it/s]

Warning: File tcga_tnbc_data/ddb8fb65-cf53-41a0-8acd-a538a8754fa5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/e84b9f1a-0def-425b-86c1-c143b27509b5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  78%|███████▊  | 958/1224 [14:16<03:41,  1.20it/s]

Warning: File tcga_tnbc_data/8f4d34b3-5dd0-4ff2-b017-0cfa6e5c5f6b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  78%|███████▊  | 959/1224 [14:17<03:31,  1.25it/s]

Warning: File tcga_tnbc_data/0f0b1a31-1f88-40e0-bd25-320046de4970.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  78%|███████▊  | 960/1224 [14:18<03:38,  1.21it/s]

Warning: File tcga_tnbc_data/8ca36e25-aabc-4bd9-9ced-a8d432ca0260.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  79%|███████▊  | 961/1224 [14:19<03:49,  1.15it/s]

Warning: File tcga_tnbc_data/3782bc2e-5a29-4380-9b44-735ca1ac8896.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  79%|███████▊  | 963/1224 [14:20<03:47,  1.14it/s]

Warning: File tcga_tnbc_data/578022ab-5178-4440-8996-73e8826dd74d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  79%|███████▉  | 964/1224 [14:21<03:41,  1.18it/s]

Warning: File tcga_tnbc_data/99502a82-c77e-482b-8589-82d9ef82d5d1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/422ef158-74dd-4a5e-88a6-5b0da33004d1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  79%|███████▉  | 966/1224 [14:23<03:41,  1.16it/s]

Warning: File tcga_tnbc_data/072cae2e-f4c1-4a3f-85e1-6f7e35a65108.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  79%|███████▉  | 967/1224 [14:24<03:36,  1.18it/s]

Warning: File tcga_tnbc_data/4af2ea24-60fe-4fc1-858b-68ed98855082.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  79%|███████▉  | 968/1224 [14:24<03:31,  1.21it/s]

Warning: File tcga_tnbc_data/f5e5f153-f422-4c2a-ae54-fc11f416c637.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  79%|███████▉  | 969/1224 [14:25<03:39,  1.16it/s]

Warning: File tcga_tnbc_data/1b8dddf2-89d9-43aa-84c7-1d18e8865106.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  79%|███████▉  | 970/1224 [14:26<03:34,  1.18it/s]

Warning: File tcga_tnbc_data/ddb7443e-0dda-40f1-9652-adc025804c85.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/8b000fae-e6de-4038-8486-45316cae622d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  79%|███████▉  | 972/1224 [14:28<03:25,  1.23it/s]

Warning: File tcga_tnbc_data/98320692-9c1c-4ed3-9ea1-72f098c03049.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/7235fd65-e9cb-45f1-ac78-cad80823325e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  80%|███████▉  | 974/1224 [14:29<03:27,  1.20it/s]

Warning: File tcga_tnbc_data/4ec56a4e-a3ce-4511-a517-199e2a535b1a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/0f1cf3a6-6e68-440a-9744-85e44d88b61f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  80%|███████▉  | 975/1224 [14:30<03:30,  1.19it/s]

Warning: File tcga_tnbc_data/a629c407-5141-454c-bb69-ba7e58d1febc.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  80%|███████▉  | 976/1224 [14:31<03:36,  1.14it/s]

Warning: File tcga_tnbc_data/d0654d2d-37ef-4d93-996e-c68cfedea376.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  80%|███████▉  | 978/1224 [14:33<03:32,  1.16it/s]

Warning: File tcga_tnbc_data/ce53c8d2-5655-4fde-b134-1ef5a269e569.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  80%|███████▉  | 979/1224 [14:34<03:34,  1.14it/s]

Warning: File tcga_tnbc_data/3eb2d652-73f5-41c0-bf73-f40e85e1ecae.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  80%|████████  | 980/1224 [14:35<03:28,  1.17it/s]

Warning: File tcga_tnbc_data/7915bbbc-7e5b-4439-bea4-12fc7f639d6d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  80%|████████  | 981/1224 [14:35<03:22,  1.20it/s]

Warning: File tcga_tnbc_data/5fbbee45-08b5-4cd0-83c6-c18bc4e89d99.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/59c3cb45-ca6e-40ad-a3f0-9b496b934aa5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  80%|████████  | 983/1224 [14:37<03:25,  1.17it/s]

Warning: File tcga_tnbc_data/90eefb33-6808-45c3-9ab1-6eca0decdc9d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  80%|████████  | 984/1224 [14:38<03:20,  1.20it/s]

Warning: File tcga_tnbc_data/eddb2dc6-2b72-43a8-a7fc-3dd09dde68af.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/eb166054-ff70-4a86-883b-9c25a7d2b0e5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  81%|████████  | 986/1224 [14:40<03:18,  1.20it/s]

Warning: File tcga_tnbc_data/fb32f0b1-4fb7-43d5-8091-dc13a1f6d9e8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/f66aace4-01a4-4def-8e71-26d9aaf13d49.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  81%|████████  | 988/1224 [14:41<03:13,  1.22it/s]

Warning: File tcga_tnbc_data/055f6138-ea7a-468d-90c2-87a473486867.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  81%|████████  | 989/1224 [14:42<03:07,  1.25it/s]

Warning: File tcga_tnbc_data/9c55de9c-a13e-4772-9a5d-4cde38f75cf3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/ff5f8ada-17c5-497e-9182-63a05e3ab4c5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  81%|████████  | 990/1224 [14:43<03:14,  1.20it/s]

Warning: File tcga_tnbc_data/d2e2915c-125e-45c6-b7f3-6a815b3d2859.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  81%|████████  | 991/1224 [14:44<03:23,  1.15it/s]

Warning: File tcga_tnbc_data/bdef0c66-0755-4581-b813-87c8512754ba.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  81%|████████  | 992/1224 [14:45<03:29,  1.11it/s]

Warning: File tcga_tnbc_data/7b188e2a-4a56-49f9-b527-cd61a646f6c7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  81%|████████  | 994/1224 [14:46<03:14,  1.18it/s]

Warning: File tcga_tnbc_data/5fcd0660-3e77-4a56-af19-01045301708c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/9765934d-d954-485c-abfe-b9db59f18193.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  81%|████████▏ | 995/1224 [14:47<03:06,  1.23it/s]

Warning: File tcga_tnbc_data/9f06e9cd-8184-4b66-a2e0-96da9a7159e8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  81%|████████▏ | 997/1224 [14:49<03:07,  1.21it/s]

Warning: File tcga_tnbc_data/6d17023b-03fd-4e66-9c7e-72395f09e87f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/d7e1d1f4-3189-401d-91dc-048ab13ce5df.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  82%|████████▏ | 999/1224 [14:50<03:02,  1.23it/s]

Warning: File tcga_tnbc_data/456bc30b-59f8-4427-b798-5b113ca635a0.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  82%|████████▏ | 1000/1224 [14:51<02:57,  1.26it/s]

Warning: File tcga_tnbc_data/3841a099-bf19-4891-9b12-5db1d699e922.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/25352bc8-c94c-4542-a7da-d4423adf72cf.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  82%|████████▏ | 1001/1224 [14:52<02:59,  1.24it/s]

Warning: File tcga_tnbc_data/bf6e2b60-d65b-4963-8e8e-49ab3f93c3e1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  82%|████████▏ | 1002/1224 [14:53<03:02,  1.22it/s]

Warning: File tcga_tnbc_data/18022491-5c13-4a17-aed9-ea85e1088267.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  82%|████████▏ | 1003/1224 [14:54<03:04,  1.20it/s]

Warning: File tcga_tnbc_data/dcf2138e-b0f7-4b2e-b535-d463819f1b24.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  82%|████████▏ | 1004/1224 [14:55<03:05,  1.19it/s]

Warning: File tcga_tnbc_data/7d904415-9887-4738-99ae-66dcd60084ac.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  82%|████████▏ | 1005/1224 [14:55<03:04,  1.19it/s]

Warning: File tcga_tnbc_data/8b885bee-44ab-40ce-bc3e-18ef36fa35ae.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  82%|████████▏ | 1006/1224 [14:56<03:07,  1.16it/s]

Warning: File tcga_tnbc_data/80563e43-422f-458b-a543-6b1dad9171e5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  82%|████████▏ | 1007/1224 [14:57<03:16,  1.10it/s]

Warning: File tcga_tnbc_data/7860a938-e43a-4c3a-83b4-6578cea95df8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  82%|████████▏ | 1008/1224 [14:58<03:09,  1.14it/s]

Warning: File tcga_tnbc_data/b4d6811f-cb5c-4ad9-8f13-5d58f0b6afd4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  82%|████████▏ | 1009/1224 [14:59<03:15,  1.10it/s]

Warning: File tcga_tnbc_data/7cf427fc-2c7c-434b-84c5-9ea118da110f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  83%|████████▎ | 1011/1224 [15:01<03:07,  1.14it/s]

Warning: File tcga_tnbc_data/7baccc3d-54ba-4a3f-8ec0-b54ccd92df45.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/386ce911-e1c2-4d68-b0a3-aac157e1a555.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  83%|████████▎ | 1013/1224 [15:03<03:02,  1.16it/s]

Warning: File tcga_tnbc_data/4b8ef410-8612-4c64-839f-47770deba446.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  83%|████████▎ | 1014/1224 [15:03<03:00,  1.17it/s]

Warning: File tcga_tnbc_data/635084ad-0b62-4217-bc6f-e2a8c1326aee.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/7c196890-04a5-496b-ae10-43b95be57d58.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  83%|████████▎ | 1015/1224 [15:04<03:04,  1.13it/s]

Warning: File tcga_tnbc_data/0ed77a2e-a2c9-4557-8ba3-2c8bade9b792.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  83%|████████▎ | 1016/1224 [15:05<03:03,  1.13it/s]

Warning: File tcga_tnbc_data/39b28d5e-fc51-4dfc-bcbe-0285c3bad830.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  83%|████████▎ | 1017/1224 [15:06<03:04,  1.12it/s]

Warning: File tcga_tnbc_data/1479c033-ebe7-423d-8460-bbe84fd5ffb6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  83%|████████▎ | 1018/1224 [15:07<02:59,  1.15it/s]

Warning: File tcga_tnbc_data/519039a7-141e-4367-a6eb-e9307136daf3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  83%|████████▎ | 1019/1224 [15:08<03:04,  1.11it/s]

Warning: File tcga_tnbc_data/c1778b3c-5649-4e26-b937-fd00ffd58387.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  83%|████████▎ | 1021/1224 [15:10<03:05,  1.10it/s]

Warning: File tcga_tnbc_data/0d669e80-cb31-4afb-bd3f-07d69f10eb3f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  83%|████████▎ | 1022/1224 [15:11<02:56,  1.14it/s]

Warning: File tcga_tnbc_data/86d6bd3f-d1a8-4b12-bd4f-009cd707ad8b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/d5664879-53a0-490a-a3cb-47c551b6bf34.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  84%|████████▎ | 1023/1224 [15:11<02:51,  1.17it/s]

Warning: File tcga_tnbc_data/798e4669-4ca3-4af1-b713-be2b1f30e4dc.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  84%|████████▎ | 1024/1224 [15:12<02:50,  1.18it/s]

Warning: File tcga_tnbc_data/fecd341d-a370-4092-be40-e07fc44500e5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  84%|████████▍ | 1026/1224 [15:14<02:47,  1.18it/s]

Warning: File tcga_tnbc_data/808f4ac6-9bc9-402f-be36-b7ec8658c150.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  84%|████████▍ | 1027/1224 [15:15<02:47,  1.18it/s]

Warning: File tcga_tnbc_data/ab06e3b7-52ef-45e4-8fc6-dbb4f63b110e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/235a9719-23a6-48b5-bbb1-248dbec23a35.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  84%|████████▍ | 1029/1224 [15:16<02:43,  1.19it/s]

Warning: File tcga_tnbc_data/f6392b6f-24d9-4768-8269-c7c647f8ff8c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  84%|████████▍ | 1030/1224 [15:17<02:42,  1.19it/s]

Warning: File tcga_tnbc_data/987d401a-3e68-414e-8067-afe277b02fad.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  84%|████████▍ | 1031/1224 [15:18<02:40,  1.20it/s]

Warning: File tcga_tnbc_data/fde3b574-b9be-4dc2-a5ae-aaab8a0bbd26.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/3293a2fa-d57c-448e-a336-a92def5dd92a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  84%|████████▍ | 1032/1224 [15:19<02:40,  1.20it/s]

Warning: File tcga_tnbc_data/885098b3-2e01-4039-ad15-f3dda5c29dc6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  84%|████████▍ | 1033/1224 [15:20<02:41,  1.18it/s]

Warning: File tcga_tnbc_data/f2842246-b121-48f0-a8c5-474a8fb47036.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  84%|████████▍ | 1034/1224 [15:21<02:42,  1.17it/s]

Warning: File tcga_tnbc_data/097a38f3-a6c5-4267-8648-cd04e2bd9984.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  85%|████████▍ | 1036/1224 [15:23<02:48,  1.12it/s]

Warning: File tcga_tnbc_data/e267a6fb-3d15-4658-b464-25438bd41330.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/7002e8cb-0d64-4d4b-a483-bf6dec3c2abb.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  85%|████████▍ | 1038/1224 [15:24<02:40,  1.16it/s]

Warning: File tcga_tnbc_data/d2007230-83cb-4f12-bec5-e42afc4a58cd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  85%|████████▍ | 1039/1224 [15:25<02:37,  1.18it/s]

Warning: File tcga_tnbc_data/28aa7b6c-d5ec-4aa1-9c39-70d571efe6fb.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/17b87e41-8f42-48d8-90f8-d2c9b8553481.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  85%|████████▌ | 1041/1224 [15:27<02:38,  1.16it/s]

Warning: File tcga_tnbc_data/176e739b-87e2-49b7-80e1-c27a6a632576.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/4081fb70-afcd-4be3-a071-6df014f4fa52.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  85%|████████▌ | 1043/1224 [15:29<02:36,  1.15it/s]

Warning: File tcga_tnbc_data/192d2e5c-31a1-45aa-8bb5-b33e4f873077.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/ad1ea8c5-ca8b-49e9-a650-6012d71daf24.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  85%|████████▌ | 1044/1224 [15:29<02:35,  1.16it/s]

Warning: File tcga_tnbc_data/7afb1455-c2b6-4ae2-95ec-682ae7df34a2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  85%|████████▌ | 1045/1224 [15:30<02:33,  1.17it/s]

Warning: File tcga_tnbc_data/3aad7b0b-9f82-41d0-b3e5-5614afcac6a8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  85%|████████▌ | 1046/1224 [15:31<02:32,  1.16it/s]

Warning: File tcga_tnbc_data/fed5e108-cb1a-45b8-88e8-c5ea6a6bd61a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  86%|████████▌ | 1047/1224 [15:32<02:25,  1.22it/s]

Warning: File tcga_tnbc_data/e3e859ed-2cc7-4842-a9dd-72938cd2170c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  86%|████████▌ | 1048/1224 [15:33<02:36,  1.13it/s]

Warning: File tcga_tnbc_data/cd002ab8-a52b-4d20-9089-11b3e1dbaeb7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  86%|████████▌ | 1049/1224 [15:34<02:36,  1.12it/s]

Warning: File tcga_tnbc_data/a6f96d96-c761-4e98-9120-25138aa43e67.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  86%|████████▌ | 1051/1224 [15:35<02:30,  1.15it/s]

Warning: File tcga_tnbc_data/e45b755d-1df6-446a-aa05-59ae1960b442.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/425a82ae-e0bf-48ae-946f-58ccc2571bfd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  86%|████████▌ | 1052/1224 [15:36<02:28,  1.16it/s]

Warning: File tcga_tnbc_data/65582670-1c71-4606-91b5-a886144fdfa6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  86%|████████▌ | 1054/1224 [15:38<02:24,  1.17it/s]

Warning: File tcga_tnbc_data/08671bd5-f67a-46fa-979d-4aa40fb6575a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  86%|████████▌ | 1055/1224 [15:39<02:20,  1.20it/s]

Warning: File tcga_tnbc_data/69f5df3f-273f-4e02-934b-af9c9ec52067.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/9b5b1b38-58b8-47c9-badf-086676e44c1a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  86%|████████▋ | 1056/1224 [15:40<02:29,  1.13it/s]

Warning: File tcga_tnbc_data/f78dec09-cb25-49c1-828c-6a88cf2be7d3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  86%|████████▋ | 1057/1224 [15:41<02:25,  1.15it/s]

Warning: File tcga_tnbc_data/16ffdede-3d07-431a-a4ed-318c7a66c096.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  86%|████████▋ | 1058/1224 [15:41<02:23,  1.16it/s]

Warning: File tcga_tnbc_data/c38adc46-f0f2-4c71-91b6-da2159dcb190.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  87%|████████▋ | 1059/1224 [15:42<02:23,  1.15it/s]

Warning: File tcga_tnbc_data/c5e46ae9-c4c1-4afd-a772-392ede15808d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  87%|████████▋ | 1060/1224 [15:43<02:20,  1.16it/s]

Warning: File tcga_tnbc_data/9dc47384-64df-48c7-9d41-921d6021ef9c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  87%|████████▋ | 1061/1224 [15:44<02:20,  1.16it/s]

Warning: File tcga_tnbc_data/c32d5451-815d-4451-97b1-e61801574c22.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  87%|████████▋ | 1062/1224 [15:45<02:25,  1.12it/s]

Warning: File tcga_tnbc_data/94468afc-faea-4091-af0f-d2df8aec37da.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  87%|████████▋ | 1063/1224 [15:46<02:26,  1.10it/s]

Warning: File tcga_tnbc_data/f33b0d9c-486b-482d-b4a6-c2885072db7b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  87%|████████▋ | 1064/1224 [15:47<02:26,  1.09it/s]

Warning: File tcga_tnbc_data/e99a371e-14fa-46f7-89c1-ad36bcd82994.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  87%|████████▋ | 1065/1224 [15:48<02:22,  1.12it/s]

Warning: File tcga_tnbc_data/e14858ca-8bb5-4d6d-906c-5d62722d90f8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  87%|████████▋ | 1066/1224 [15:48<02:13,  1.18it/s]

Warning: File tcga_tnbc_data/515f8866-8744-44d8-9e4b-0e734d0c201b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  87%|████████▋ | 1068/1224 [15:50<02:12,  1.17it/s]

Warning: File tcga_tnbc_data/774133e2-dfca-4918-9be9-8727fc99fe26.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/2b519fff-dd2a-458e-ac2b-573167aeb7f2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  87%|████████▋ | 1069/1224 [15:51<02:12,  1.17it/s]

Warning: File tcga_tnbc_data/4d0dcaac-cf91-4737-931d-f308fb20df9d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  88%|████████▊ | 1071/1224 [15:53<02:09,  1.18it/s]

Warning: File tcga_tnbc_data/cd2dcf58-da3a-4070-b42f-07d0102a342e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/39e5a93f-7474-44f8-974a-7ce44f909002.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  88%|████████▊ | 1072/1224 [15:54<02:11,  1.15it/s]

Warning: File tcga_tnbc_data/35f78d43-917b-4a7b-b992-d004056a370f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  88%|████████▊ | 1074/1224 [15:55<01:59,  1.25it/s]

Warning: File tcga_tnbc_data/5978f5bd-575c-4b95-9265-654af1127685.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/20110ed9-8b45-4a62-bd13-e0281915a06b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  88%|████████▊ | 1075/1224 [15:56<02:02,  1.22it/s]

Warning: File tcga_tnbc_data/d80334e2-0ee0-432a-aa78-3d6ca1f017e5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  88%|████████▊ | 1076/1224 [15:57<02:05,  1.18it/s]

Warning: File tcga_tnbc_data/89fa8a0c-e046-4fbf-97c5-4ed5cc4e5e4c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  88%|████████▊ | 1077/1224 [15:58<02:12,  1.11it/s]

Warning: File tcga_tnbc_data/84ab5edd-38bf-4987-b9af-fa4d1cbdef2c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  88%|████████▊ | 1078/1224 [15:59<02:11,  1.11it/s]

Warning: File tcga_tnbc_data/f30b7e3e-f26d-47f7-a87f-6c1a4f074f65.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  88%|████████▊ | 1080/1224 [16:01<02:02,  1.17it/s]

Warning: File tcga_tnbc_data/d796de5e-4512-4b3a-93d4-2a006e79084f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/5c33730b-be75-452a-ad2f-02eb726d4eae.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  88%|████████▊ | 1081/1224 [16:01<02:02,  1.16it/s]

Warning: File tcga_tnbc_data/15f0e499-8d53-4e97-a392-334875d25cf4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  88%|████████▊ | 1082/1224 [16:02<02:06,  1.12it/s]

Warning: File tcga_tnbc_data/76267112-851f-4f5b-af40-f3c90af1b2ce.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  88%|████████▊ | 1083/1224 [16:03<02:01,  1.16it/s]

Warning: File tcga_tnbc_data/ff570f9a-a252-496d-a452-344063851a7b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  89%|████████▊ | 1084/1224 [16:04<02:01,  1.15it/s]

Warning: File tcga_tnbc_data/7ba3b335-cd4c-4b44-a4da-44fa1109a6f0.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  89%|████████▊ | 1085/1224 [16:05<01:58,  1.17it/s]

Warning: File tcga_tnbc_data/db5aadbb-3042-4c20-8235-ccd19634d9d3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  89%|████████▊ | 1086/1224 [16:06<02:02,  1.12it/s]

Warning: File tcga_tnbc_data/67d73608-5dfb-41c1-85d3-52f1eba7daa2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  89%|████████▉ | 1087/1224 [16:07<01:59,  1.14it/s]

Warning: File tcga_tnbc_data/a1516cec-76ec-4a05-97a0-a56ef8490e60.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  89%|████████▉ | 1088/1224 [16:08<02:00,  1.13it/s]

Warning: File tcga_tnbc_data/2700aca8-b120-4655-87ab-a9f8f7f633db.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  89%|████████▉ | 1089/1224 [16:09<02:04,  1.08it/s]

Warning: File tcga_tnbc_data/84225715-14a6-423c-a6d6-15558e151f56.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  89%|████████▉ | 1090/1224 [16:09<01:59,  1.12it/s]

Warning: File tcga_tnbc_data/573241d2-e298-426a-84a0-2c3889bae923.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  89%|████████▉ | 1091/1224 [16:10<02:00,  1.11it/s]

Warning: File tcga_tnbc_data/1ab2be1b-4a61-480e-aa1b-eafab958f1f7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  89%|████████▉ | 1092/1224 [16:11<01:58,  1.11it/s]

Warning: File tcga_tnbc_data/e86f9f1b-4e5c-4743-8158-14ec2e83b6f1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  89%|████████▉ | 1094/1224 [16:13<01:54,  1.13it/s]

Warning: File tcga_tnbc_data/2e9902c2-e171-465e-ae13-45c413f7515f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/2d148c3a-7bbd-414f-872e-dd916d0e3ccf.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  89%|████████▉ | 1095/1224 [16:14<01:53,  1.14it/s]

Warning: File tcga_tnbc_data/a2cb26d9-70e7-47ca-b019-a5fa136b42f7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  90%|████████▉ | 1097/1224 [16:15<01:46,  1.20it/s]

Warning: File tcga_tnbc_data/62c0cac5-05eb-46ea-b165-a2e9e342a259.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/31e1dbf5-8c97-4e4d-a488-d6737ab304c2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  90%|████████▉ | 1098/1224 [16:16<01:46,  1.19it/s]

Warning: File tcga_tnbc_data/3c70b5af-2238-4fbe-991b-dc68975cc7f1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  90%|████████▉ | 1099/1224 [16:17<01:46,  1.17it/s]

Warning: File tcga_tnbc_data/64657d41-17ad-4692-8a13-0cf55c55f11d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  90%|████████▉ | 1100/1224 [16:18<01:49,  1.14it/s]

Warning: File tcga_tnbc_data/bbff7857-30a2-41ad-b2f7-5a6ffc59fe0c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  90%|████████▉ | 1101/1224 [16:19<01:47,  1.14it/s]

Warning: File tcga_tnbc_data/94db1456-e7f2-4f5f-92e3-b8faa801097d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  90%|█████████ | 1102/1224 [16:20<01:53,  1.07it/s]

Warning: File tcga_tnbc_data/90617797-d2c7-4c49-bffe-b2bea96a7cf1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  90%|█████████ | 1103/1224 [16:21<01:52,  1.08it/s]

Warning: File tcga_tnbc_data/87af5cf5-08e6-443b-a23b-6221f7433a65.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  90%|█████████ | 1104/1224 [16:22<01:55,  1.04it/s]

Warning: File tcga_tnbc_data/2455f280-a23c-48ec-b4c1-698b56f72a45.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  90%|█████████ | 1105/1224 [16:23<01:54,  1.04it/s]

Warning: File tcga_tnbc_data/0e89a7ce-aed2-4c74-9bdf-cf50793c73b6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  90%|█████████ | 1106/1224 [16:24<01:51,  1.05it/s]

Warning: File tcga_tnbc_data/7bcb3817-31ac-4ef5-9038-a9bfebad5869.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  90%|█████████ | 1107/1224 [16:25<01:52,  1.04it/s]

Warning: File tcga_tnbc_data/7dace9fc-28bd-44fb-9e97-6319eb30bb05.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  91%|█████████ | 1108/1224 [16:26<01:47,  1.08it/s]

Warning: File tcga_tnbc_data/91060c43-f1e3-49ea-a3c9-96def417716b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  91%|█████████ | 1109/1224 [16:27<01:44,  1.10it/s]

Warning: File tcga_tnbc_data/45584684-6082-422f-abe5-ef918f8ee77a.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  91%|█████████ | 1110/1224 [16:27<01:41,  1.13it/s]

Warning: File tcga_tnbc_data/b54476c3-f6f1-4474-b447-72023ba97687.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  91%|█████████ | 1111/1224 [16:28<01:39,  1.13it/s]

Warning: File tcga_tnbc_data/e12f17ae-dc1f-4e91-93bd-b827ad276dde.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  91%|█████████ | 1112/1224 [16:29<01:36,  1.17it/s]

Warning: File tcga_tnbc_data/839a4656-f2ce-4460-858a-8e6b314695ef.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  91%|█████████ | 1113/1224 [16:30<01:37,  1.14it/s]

Warning: File tcga_tnbc_data/5c57b96c-909e-468e-bef6-f0375a788fcb.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  91%|█████████ | 1114/1224 [16:31<01:39,  1.10it/s]

Warning: File tcga_tnbc_data/104e3cb5-c6df-422b-a55f-6b19408594d4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  91%|█████████ | 1115/1224 [16:32<01:38,  1.11it/s]

Warning: File tcga_tnbc_data/a9527be9-e865-4074-ae57-f3510e70c203.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  91%|█████████ | 1116/1224 [16:33<01:34,  1.14it/s]

Warning: File tcga_tnbc_data/4a5803a6-942a-4992-8b9d-29e1091b10f6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  91%|█████████▏| 1117/1224 [16:34<01:36,  1.11it/s]

Warning: File tcga_tnbc_data/0877bc64-fbf4-427f-a889-21a4a9102600.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  91%|█████████▏| 1118/1224 [16:35<01:37,  1.09it/s]

Warning: File tcga_tnbc_data/07478a1d-adbe-4fa7-858b-0edb74171eec.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  91%|█████████▏| 1119/1224 [16:36<01:38,  1.06it/s]

Warning: File tcga_tnbc_data/f3d5f550-311d-4c59-8576-81fde80db315.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  92%|█████████▏| 1120/1224 [16:37<01:36,  1.08it/s]

Warning: File tcga_tnbc_data/2291d3f5-8269-4f31-adad-4b873c7ac770.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  92%|█████████▏| 1122/1224 [16:38<01:30,  1.13it/s]

Warning: File tcga_tnbc_data/268eed55-913e-470b-8940-68daae0b21aa.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/0437af11-bb89-4901-9764-bb410c2e94c5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  92%|█████████▏| 1123/1224 [16:39<01:28,  1.14it/s]

Warning: File tcga_tnbc_data/d393af6b-de4b-4ca6-bc06-a29068dfe086.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  92%|█████████▏| 1124/1224 [21:37<2:30:05, 90.06s/it]

Warning: File tcga_tnbc_data/ee89e01e-d54e-4166-a3ae-db9357639523.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  92%|█████████▏| 1125/1224 [21:39<1:44:58, 63.62s/it]

Warning: File tcga_tnbc_data/bbe70939-24be-4397-a125-510cad51337c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  92%|█████████▏| 1126/1224 [21:40<1:13:14, 44.84s/it]

Warning: File tcga_tnbc_data/736fca14-66fb-481a-985e-7253f75243a8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  92%|█████████▏| 1127/1224 [21:41<51:07, 31.63s/it]

Warning: File tcga_tnbc_data/760131f1-5fbf-469f-9629-43733014953d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  92%|█████████▏| 1128/1224 [21:42<35:54, 22.44s/it]

Warning: File tcga_tnbc_data/ea4c3031-5f48-4048-90ff-a525271cfebc.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  92%|█████████▏| 1129/1224 [21:43<25:15, 15.95s/it]

Warning: File tcga_tnbc_data/9314aa86-3d8d-4709-a6e1-0aa22b21d6b5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  92%|█████████▏| 1130/1224 [21:44<17:54, 11.43s/it]

Warning: File tcga_tnbc_data/e59d6b6e-1a01-4f3f-b298-06f2c6c7b111.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  92%|█████████▏| 1132/1224 [21:46<09:17,  6.06s/it]

Warning: File tcga_tnbc_data/f94b47fb-764c-456f-946d-907a2fc154db.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/7dcadaff-5d95-4ba6-9ce7-50bb2e5f17aa.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  93%|█████████▎| 1133/1224 [21:46<06:53,  4.54s/it]

Warning: File tcga_tnbc_data/5428e771-3ea8-46d1-842e-50a270d26bd3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  93%|█████████▎| 1134/1224 [21:47<05:10,  3.45s/it]

Warning: File tcga_tnbc_data/71ce6854-2231-48ad-ba1b-54bb4ec7d713.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  93%|█████████▎| 1135/1224 [21:48<04:01,  2.71s/it]

Warning: File tcga_tnbc_data/d5358d17-4c49-46fa-8a96-4af9ab298ab4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  93%|█████████▎| 1136/1224 [21:49<03:07,  2.14s/it]

Warning: File tcga_tnbc_data/481c702a-58ee-4fab-9559-434a45615aa5.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  93%|█████████▎| 1137/1224 [21:50<02:31,  1.74s/it]

Warning: File tcga_tnbc_data/86d52d54-1b0d-40b1-99ce-82b4e345acb8.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  93%|█████████▎| 1138/1224 [21:51<02:07,  1.48s/it]

Warning: File tcga_tnbc_data/4c60d168-b545-46a8-8c37-81972a537a83.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  93%|█████████▎| 1139/1224 [21:52<01:49,  1.29s/it]

Warning: File tcga_tnbc_data/ead53b27-6ad9-4b96-b5d4-0d4f06fb2d13.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  93%|█████████▎| 1140/1224 [21:53<01:42,  1.22s/it]

Warning: File tcga_tnbc_data/12c6b269-434e-4a18-aa93-844bc9c5eb4d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  93%|█████████▎| 1141/1224 [21:54<01:34,  1.13s/it]

Warning: File tcga_tnbc_data/dcf2260b-c0bf-4f59-a4da-079a340b1e33.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  93%|█████████▎| 1142/1224 [21:55<01:28,  1.08s/it]

Warning: File tcga_tnbc_data/b5fc7f21-688b-4764-b0ce-c450ad902e06.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  93%|█████████▎| 1143/1224 [21:56<01:22,  1.02s/it]

Warning: File tcga_tnbc_data/06fc39a9-8059-4ac7-9b2b-64f6c7d3b8a1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  93%|█████████▎| 1144/1224 [21:57<01:20,  1.01s/it]

Warning: File tcga_tnbc_data/6b9180f4-bdd0-4118-bff7-0523cad45567.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  94%|█████████▎| 1145/1224 [21:58<01:18,  1.01it/s]

Warning: File tcga_tnbc_data/4c8d0d1a-dbd3-4124-8458-dfb61f61f11c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  94%|█████████▎| 1146/1224 [21:58<01:13,  1.07it/s]

Warning: File tcga_tnbc_data/20e90b8d-aa05-4918-8e54-1b969488148f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  94%|█████████▍| 1148/1224 [22:00<01:08,  1.10it/s]

Warning: File tcga_tnbc_data/7b9b6f5f-bd99-421a-a22c-d3fbe110ee73.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/5db109b6-dbfe-4ec8-8697-bb7fff5beb4b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  94%|█████████▍| 1149/1224 [22:01<01:08,  1.09it/s]

Warning: File tcga_tnbc_data/b0e49ee8-40e0-4edf-bcde-277a0fe1d12f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  94%|█████████▍| 1150/1224 [22:02<01:04,  1.14it/s]

Warning: File tcga_tnbc_data/0a688b9b-06ea-4b83-bfce-9cee0d866a0c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  94%|█████████▍| 1151/1224 [22:03<01:04,  1.13it/s]

Warning: File tcga_tnbc_data/a8a6308d-04e4-47e9-adb6-c895b605ad69.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  94%|█████████▍| 1152/1224 [22:04<01:03,  1.14it/s]

Warning: File tcga_tnbc_data/051a1102-a815-4b39-b903-80d8b4a2348f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  94%|█████████▍| 1153/1224 [22:04<01:01,  1.15it/s]

Warning: File tcga_tnbc_data/588a95c5-286a-417f-aa76-b4d8b5c055ef.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  94%|█████████▍| 1154/1224 [22:05<01:02,  1.12it/s]

Warning: File tcga_tnbc_data/73ac99d6-d01b-45d9-8df2-205610109911.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  94%|█████████▍| 1155/1224 [22:06<01:00,  1.14it/s]

Warning: File tcga_tnbc_data/b26b27b0-5209-483c-a359-9a5d3ae920e9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  94%|█████████▍| 1156/1224 [22:07<00:57,  1.19it/s]

Warning: File tcga_tnbc_data/be10214b-9a03-4556-b28b-5775028c782b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  95%|█████████▍| 1157/1224 [22:08<00:57,  1.17it/s]

Warning: File tcga_tnbc_data/9b47ed32-440b-4e50-93f9-5aeb56f03397.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  95%|█████████▍| 1158/1224 [22:09<01:01,  1.07it/s]

Warning: File tcga_tnbc_data/70ea9273-29f3-425a-ba66-5b75db62c9b7.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  95%|█████████▍| 1160/1224 [22:11<00:55,  1.16it/s]

Warning: File tcga_tnbc_data/81138059-5789-4ea7-84e9-1490aa53a283.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/84df6b33-7f6a-496d-8cd7-f523b07fd0bb.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  95%|█████████▍| 1161/1224 [22:12<00:56,  1.12it/s]

Warning: File tcga_tnbc_data/67317cce-4a8c-4313-bb26-4ef7759071b9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  95%|█████████▍| 1162/1224 [22:12<00:53,  1.15it/s]

Warning: File tcga_tnbc_data/91e43fc0-1bd1-41e3-a828-43ec6620feb6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  95%|█████████▌| 1163/1224 [22:13<00:53,  1.15it/s]

Warning: File tcga_tnbc_data/587b3262-55f8-4611-8431-0c02a5df652d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  95%|█████████▌| 1165/1224 [22:15<00:49,  1.20it/s]

Warning: File tcga_tnbc_data/128bf144-f452-48af-941d-f6069e3bb0bb.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/68881256-49b8-4a19-87a9-afac4f1841d2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  95%|█████████▌| 1166/1224 [22:16<00:49,  1.18it/s]

Warning: File tcga_tnbc_data/934935ae-037b-451d-a696-0679b07bd401.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  95%|█████████▌| 1167/1224 [22:17<00:50,  1.14it/s]

Warning: File tcga_tnbc_data/e5b0c2dc-c652-40a0-bb80-d7e87830b406.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  95%|█████████▌| 1168/1224 [22:18<00:49,  1.14it/s]

Warning: File tcga_tnbc_data/507952aa-23c0-4239-ae19-04d8f862acc2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  96%|█████████▌| 1169/1224 [22:18<00:49,  1.10it/s]

Warning: File tcga_tnbc_data/59915f69-8e37-44a8-a8f6-feb9e06b6703.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  96%|█████████▌| 1170/1224 [22:19<00:48,  1.11it/s]

Warning: File tcga_tnbc_data/b01d7dfd-b577-48b8-8bf2-3c74bb617601.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  96%|█████████▌| 1171/1224 [22:20<00:47,  1.12it/s]

Warning: File tcga_tnbc_data/aa4bc249-100e-4cf6-8356-1dc96b7dbea9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  96%|█████████▌| 1172/1224 [22:21<00:49,  1.06it/s]

Warning: File tcga_tnbc_data/00469928-b243-4cae-acd7-134508e99ceb.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  96%|█████████▌| 1173/1224 [22:22<00:47,  1.07it/s]

Warning: File tcga_tnbc_data/b5994562-8eab-43a5-9846-cd3916a9260f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  96%|█████████▌| 1174/1224 [22:23<00:47,  1.05it/s]

Warning: File tcga_tnbc_data/a17d51b5-c397-4591-a227-dc0425948420.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  96%|█████████▌| 1176/1224 [22:25<00:46,  1.03it/s]

Warning: File tcga_tnbc_data/ec9fb459-42b7-47eb-8c3a-48f492a7b2dc.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/54600389-6de5-44ce-ada1-8a8508b50980.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  96%|█████████▌| 1177/1224 [22:26<00:43,  1.08it/s]

Warning: File tcga_tnbc_data/76bcf698-d2da-42de-b33c-c5deb721c643.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  96%|█████████▌| 1178/1224 [22:27<00:41,  1.11it/s]

Warning: File tcga_tnbc_data/1cb0d51d-def6-40ec-9c5f-4a98315b0382.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  96%|█████████▋| 1179/1224 [22:28<00:39,  1.15it/s]

Warning: File tcga_tnbc_data/a83dac26-4fdb-4819-be18-a6e03641fb80.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  96%|█████████▋| 1180/1224 [22:29<00:40,  1.10it/s]

Warning: File tcga_tnbc_data/ece7c643-e0b9-4b65-b6f5-89c414c1bfea.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  96%|█████████▋| 1181/1224 [22:30<00:38,  1.12it/s]

Warning: File tcga_tnbc_data/02a0b95f-ea0f-4c0d-ba2d-9724ed9ad712.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  97%|█████████▋| 1182/1224 [22:30<00:36,  1.14it/s]

Warning: File tcga_tnbc_data/82004d79-07d3-4a01-b266-4d36353ba561.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  97%|█████████▋| 1184/1224 [22:32<00:34,  1.16it/s]

Warning: File tcga_tnbc_data/ddd1c3de-8266-4f56-a982-bcc20b868e90.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/be386ce9-a12f-4c16-80ba-a5d47d5b374e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  97%|█████████▋| 1185/1224 [22:33<00:34,  1.12it/s]

Warning: File tcga_tnbc_data/83f2e26b-fefd-4027-ac5e-fa204ec9f084.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  97%|█████████▋| 1186/1224 [22:34<00:34,  1.09it/s]

Warning: File tcga_tnbc_data/2a898b49-54b6-4cb6-8af4-fb69d0818562.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  97%|█████████▋| 1187/1224 [22:35<00:35,  1.03it/s]

Warning: File tcga_tnbc_data/c3b9e954-9acd-481d-b6d1-86db1e62d037.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  97%|█████████▋| 1188/1224 [22:36<00:34,  1.04it/s]

Warning: File tcga_tnbc_data/92431faf-af89-4f25-be07-61ac770b9633.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  97%|█████████▋| 1190/1224 [22:38<00:30,  1.11it/s]

Warning: File tcga_tnbc_data/b2f5c7b1-96c1-4928-83e9-4f67ace3158e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/a3039f53-9e11-4b53-b65e-ea5e14914ef0.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  97%|█████████▋| 1192/1224 [22:39<00:28,  1.13it/s]

Warning: File tcga_tnbc_data/70c9af7f-8a58-434f-8f45-098ef0450319.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/c64a0adb-56a8-4966-9dd9-1acd789c1bb3.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  97%|█████████▋| 1193/1224 [22:40<00:27,  1.11it/s]

Warning: File tcga_tnbc_data/1873c44d-4dcb-41d3-8c3c-dec38f7ac3d1.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  98%|█████████▊| 1194/1224 [22:41<00:26,  1.15it/s]

Warning: File tcga_tnbc_data/be4d1c31-e925-4eb0-aa96-974b6f6bcc07.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  98%|█████████▊| 1195/1224 [22:42<00:25,  1.16it/s]

Warning: File tcga_tnbc_data/3448aa6c-0de2-4d47-9bac-19507aee7492.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  98%|█████████▊| 1197/1224 [22:44<00:21,  1.23it/s]

Warning: File tcga_tnbc_data/d84ce38f-afb8-4b1a-9a5f-f62d59577b3d.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/df176b72-7266-4eeb-a3ed-8f09199c1963.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  98%|█████████▊| 1198/1224 [22:44<00:20,  1.29it/s]

Warning: File tcga_tnbc_data/2a3dc057-3c00-405e-a18f-23e8c43494d4.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  98%|█████████▊| 1199/1224 [22:45<00:20,  1.22it/s]

Warning: File tcga_tnbc_data/1f5bbb4e-9b0e-4953-a360-83fd7b6a2267.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  98%|█████████▊| 1200/1224 [22:46<00:20,  1.19it/s]

Warning: File tcga_tnbc_data/152c8e57-1f2f-464c-ad13-de0f4d81dbff.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  98%|█████████▊| 1202/1224 [22:48<00:19,  1.11it/s]

Warning: File tcga_tnbc_data/02a11397-2a9b-4dba-8c6a-6b9f0aa24372.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  98%|█████████▊| 1203/1224 [22:49<00:18,  1.16it/s]

Warning: File tcga_tnbc_data/4cac7145-605b-43d2-a1e3-309971cbe173.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  98%|█████████▊| 1204/1224 [22:50<00:17,  1.13it/s]

Warning: File tcga_tnbc_data/62a4b965-7aaa-4bd4-b469-57a713b2e9fd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/d8ac1c2a-1820-4174-99e3-524b334df490.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  98%|█████████▊| 1205/1224 [22:51<00:16,  1.14it/s]

Warning: File tcga_tnbc_data/8f79405a-c78e-4a9e-a673-969658a0f90b.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  99%|█████████▊| 1206/1224 [22:51<00:15,  1.18it/s]

Warning: File tcga_tnbc_data/0ba26ef1-7b7d-48c8-a593-75504769791c.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  99%|█████████▊| 1207/1224 [22:52<00:14,  1.19it/s]

Warning: File tcga_tnbc_data/0972f396-9045-4faa-98f8-e8c3e02f9901.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  99%|█████████▊| 1208/1224 [22:53<00:13,  1.18it/s]

Warning: File tcga_tnbc_data/773071d4-438a-4da7-b833-d2d172c4c4e2.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  99%|█████████▉| 1210/1224 [22:55<00:12,  1.12it/s]

Warning: File tcga_tnbc_data/5997bdf5-2741-42c5-a01c-807864504c55.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  99%|█████████▉| 1211/1224 [22:56<00:11,  1.14it/s]

Warning: File tcga_tnbc_data/e5363f56-84fa-4b66-a005-1e7cdcb84c2f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  99%|█████████▉| 1212/1224 [22:56<00:10,  1.18it/s]

Warning: File tcga_tnbc_data/ae7a394e-b030-46d3-8cf2-c378c0afdc81.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/452e9e11-5545-4e7a-abfb-2486e70206bd.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  99%|█████████▉| 1213/1224 [22:57<00:09,  1.17it/s]

Warning: File tcga_tnbc_data/b1ad91fb-fb78-4896-83cd-dad028a1d297.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  99%|█████████▉| 1214/1224 [22:58<00:08,  1.11it/s]

Warning: File tcga_tnbc_data/ac70b1a2-ff7d-49db-a962-4c07479d50b6.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  99%|█████████▉| 1216/1224 [23:00<00:06,  1.17it/s]

Warning: File tcga_tnbc_data/19baf63b-8488-4b90-83b7-a6c671da0095.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/d2b6c967-b505-4f52-a4f7-91b6e8acbd1f.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files:  99%|█████████▉| 1217/1224 [23:01<00:06,  1.17it/s]

Warning: File tcga_tnbc_data/d4943f66-388e-4c86-b61a-5ef9fef34eff.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files: 100%|█████████▉| 1219/1224 [23:03<00:04,  1.18it/s]

Warning: File tcga_tnbc_data/bc23716d-70e8-486e-b512-8c45654d5d83.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files: 100%|█████████▉| 1220/1224 [23:03<00:03,  1.24it/s]

Warning: File tcga_tnbc_data/fae4edd8-db77-4937-94c4-3b16d39fb8c9.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.
Warning: File tcga_tnbc_data/236805b9-ea89-43b4-ba51-c09276778e90.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files: 100%|█████████▉| 1222/1224 [23:05<00:01,  1.28it/s]

Warning: File tcga_tnbc_data/b9220098-f6f9-4732-8e94-3c9eeb4b8479.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files: 100%|█████████▉| 1223/1224 [23:06<00:00,  1.26it/s]

Warning: File tcga_tnbc_data/f377c267-d5eb-4542-bd0d-e87f957f3154.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading RNA-seq files: 100%|██████████| 1224/1224 [23:06<00:00,  1.13s/it]

Warning: File tcga_tnbc_data/435f3fbf-5c8f-4800-bff4-3b4d5f9daf2e.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

RNA-seq matrix saved to: tcga_tnbc_data/TCGA_BRCA_RNAseq_matrix.csv

**Output:**
`tcga_tnbc_data/TCGA_BRCA_RNAseq_matrix.csv` (gene × sample, counts/FPKM/TPM depending on workflow).

### Retrying RNA-seq expression matrix download and processing

Based on the previous truncated output and the subsequent `RNA-seq matrix not found` error, the RNA-seq data download and processing for `TCGA_BRCA_RNAseq_matrix.csv` did not complete successfully. I will re-run the cell responsible for this task to ensure all files are downloaded and the matrix is properly constructed.

In [ ]:
import requests
import pandas as pd
from pathlib import Path
from tqdm import tqdm
import gzip
import os
import shutil # For removing temporary directories

GDC_API = "https://api.gdc.cancer.gov"
PROJECT = "TCGA-BRCA"
TOKEN_PATH = "gdc_token.txt"
OUTPUT_DIR = Path("tcga_tnbc_data")
OUTPUT_DIR.mkdir(exist_ok=True)

HEADERS_WITH_TOKEN = {}
try:
    with open(TOKEN_PATH, "r") as f:
        token = f.read().strip()
    HEADERS_WITH_TOKEN = {"X-GDC-TOKEN": token}
except FileNotFoundError:
    pass


def post_gdc(endpoint, filters, fields=None, size=200):
    url = f"{GDC_API}/{endpoint}"
    payload = {"filters": filters, "format": "JSON", "size": size}
    if fields:
        payload["fields"] = fields

    all_hits = []
    from_val = 0

    while True:
        params = {"from": from_val}
        resp = requests.post(url, params=params, json=payload, headers=HEADERS_WITH_TOKEN)
        resp.raise_for_status()
        data = resp.json()
        hits = data["data"]["hits"]
        all_hits.extend(hits)

        pagination = data["data"]["pagination"]
        if pagination["page"] * pagination["size"] >= pagination["total"]:
            break
        from_val += pagination["size"]

    return all_hits


def get_rnaseq_files(workflow_type="STAR - Counts"):
    filters = {
        "op": "and",
        "content": [
            {"op": "=", "content": {"field": "cases.project.project_id", "value": PROJECT}},
            {"op": "=", "content": {"field": "files.data_category", "value": "Transcriptome Profiling"}},
            {"op": "=", "content": {"field": "files.data_type", "value": "Gene Expression Quantification"}},
            {"op": "=", "content": {"field": "files.experimental_strategy", "value": "RNA-Seq"}},
            {"op": "=", "content": {"field": "files.analysis.workflow_type", "value": workflow_type}},
            {"op": "in", "content": {"field": "cases.samples.sample_type", "value": ["Primary Tumor", "Solid Tissue Normal"]}},
        ]
    }

    fields = ",".join([
        "file_id",
        "file_name",
        "analysis.workflow_type",
        "cases.project.project_id",
        "cases.samples.sample_type",
        "cases.submitter_id"
    ])

    hits = post_gdc("files", filters, fields=fields)
    print(f"Found {len(hits)} RNA-seq files for workflow: {workflow_type}")
    return hits


def download_file(file_id, out_path):
    url = f"{GDC_API}/data/{file_id}"
    with requests.get(url, headers=HEADERS_WITH_TOKEN, stream=True, timeout=300) as r:
        r.raise_for_status()
        with open(out_path, "wb") as f:
            for chunk in r.iter_content(chunk_size=8192):
                f.write(chunk)


def build_and_save_rnaseq_matrix(file_info, output_csv):
    # 1. Initial check for final output
    if output_csv.exists() and os.path.getsize(output_csv) > 0:
        print(f"Final RNA-seq matrix '{output_csv}' already exists and is not empty. Skipping processing.")
        return pd.read_csv(output_csv, index_col=0) # Return the existing dataframe

    temp_dir = OUTPUT_DIR / "rnaseq_temp_files"
    temp_dir.mkdir(exist_ok=True)

    # Get a set of file_ids that have already been processed and saved as temp CSVs
    existing_temp_fids = {f.stem for f in temp_dir.glob('*.csv')}

    # Prepare list of files that still need to be processed
    files_to_process_now = []
    total_expected_files = len(file_info)
    currently_processed_in_temp = len(existing_temp_fids)

    # Separate files already processed from those to be processed
    for info in file_info:
        fid = info["file_id"]
        if fid not in existing_temp_fids:
            files_to_process_now.append(info)

    print(f"Resuming processing: {currently_processed_in_temp} files already processed, {len(files_to_process_now)} remaining to process.")

    # Process remaining files
    for info in tqdm(files_to_process_now, desc="Processing RNA-seq files"):
        fid = info["file_id"]
        case_sub = info.get("cases", [{}])[0].get("submitter_id", fid)
        sample_type = info.get("cases", [{}])[0].get("samples", [{}])[0].get("sample_type", "UNK")
        sample_name = f"{case_sub}_{sample_type}"

        temp_processed_path = temp_dir / f"{fid}.csv"
        tmp_download_path = temp_dir / f"{fid}.tsv.gz"

        try:
            download_file(fid, tmp_download_path)

            df = None
            is_gzipped = False
            with open(tmp_download_path, 'rb') as f:
                magic_bytes = f.read(2)
                if magic_bytes == b'\x1f\x8b':
                    is_gzipped = True

            if is_gzipped:
                df = pd.read_csv(tmp_download_path, sep="\t", compression='gzip', header=None, comment='#')
            else:
                print(f"Warning: File {tmp_download_path} is not gzipped despite extension. Attempting to read as plain TSV with comments.")
                df = pd.read_csv(tmp_download_path, sep="\t", compression=None, header=None, comment='#')

        except requests.exceptions.RequestException as e:
            print(f"Network error downloading file {fid}: {e}. Skipping this file.")
            tmp_download_path.unlink(missing_ok=True)
            continue
        except Exception as e:
            print(f"Error: Could not read or process file {tmp_download_path}: {e}. Skipping this file.")
            tmp_download_path.unlink(missing_ok=True)
            continue

        if df is None or df.empty:
            print(f"Warning: Skipping empty or unreadable file {tmp_download_path}.")
            tmp_download_path.unlink(missing_ok=True)
            continue

        if df.shape[1] < 2:
            print(f"Warning: File {tmp_download_path} does not have enough columns. Skipping.")
            tmp_download_path.unlink(missing_ok=True)
            continue

        df = df.iloc[:, :2]
        df.columns = ["gene_id", sample_name]
        df = df.drop_duplicates(subset=['gene_id'], keep='first')
        df = df.set_index("gene_id")

        df.to_csv(temp_processed_path)
        tmp_download_path.unlink(missing_ok=True) # Delete temp downloaded file after processing

    # After attempting to process all files, check if all expected temp CSVs are present
    final_processed_count = len(list(temp_dir.glob('*.csv')))
    if final_processed_count < total_expected_files:
        print(f"Error: Only {final_processed_count} of {total_expected_files} files were successfully processed. "
              "Final RNA-seq matrix will be incomplete or not generated. Please re-run the cell to continue.")
        return pd.DataFrame() # Return empty DataFrame to indicate failure/incompletion

    # Second pass: read all temporary CSVs and concatenate
    print("All individual RNA-seq files processed. Concatenating into final matrix...")
    all_dfs_to_concat = []
    temp_csv_files = list(temp_dir.glob('*.csv'))

    for f_path in tqdm(temp_csv_files, desc="Reading temporary CSVs and concatenating"):
        try:
            df_temp = pd.read_csv(f_path, index_col=0)
            all_dfs_to_concat.append(df_temp)
        except Exception as e:
            print(f"Error reading temp file {f_path} during concatenation: {e}. Skipping.")

    if not all_dfs_to_concat:
        print("No valid dataframes to concatenate for the final matrix.")
        return pd.DataFrame()

    merged = pd.concat(all_dfs_to_concat, axis=1)
    merged.to_csv(output_csv)
    print(f"RNA-seq matrix saved to: {output_csv}")

    # Final verification and cleanup
    if output_csv.exists() and os.path.getsize(output_csv) > 0:
        print(f"Successfully created final matrix. Cleaning up temporary directory: {temp_dir}")
        shutil.rmtree(temp_dir, ignore_errors=True)
        return merged
    else:
        print(f"Error: Final matrix '{output_csv}' could not be verified after saving. "
              "Temporary files were not removed to allow debugging.")
        return pd.DataFrame()


# __name__ == "__main__" block
# Choose workflow: "STAR - Counts", "HTSeq - Counts", "STAR - FPKM", "STAR - TPM"
rna_files = get_rnaseq_files(workflow_type="STAR - Counts")

if not rna_files:
    print("No RNA-seq files found. Try another workflow_type.")
else:
    build_and_save_rnaseq_matrix(
        rna_files,
        OUTPUT_DIR / "TCGA_BRCA_RNAseq_matrix.csv"
    )

Found 1224 RNA-seq files for workflow: STAR - Counts
Resuming processing: 1224 files already processed, 0 remaining to process.

Processing RNA-seq files: 0it [00:00, ?it/s]

All individual RNA-seq files processed. Concatenating into final matrix...

Reading temporary CSVs and concatenating:  59%|█████▉    | 725/1224 [01:32<01:16,  6.51it/s]

In [1]:
import os
from pathlib import Path

OUTPUT_DIR = Path("tcga_tnbc_data")

if OUTPUT_DIR.exists() and OUTPUT_DIR.is_dir():
    print(f"Contents of '{OUTPUT_DIR}':")
    for item in os.listdir(OUTPUT_DIR):
        print(f"- {item}")
else:
    print(f"Directory '{OUTPUT_DIR}' does not exist.")

Contents of 'tcga_tnbc_data':
- 12b68e56-a83f-4b65-bb66-59e8522acbc9.tsv.gz

### 2) miRNA expression matrix (CSV)
File: `02_download_mirna_matrix.py`

In [3]:
import requests
import pandas as pd
from pathlib import Path
from tqdm import tqdm
import gzip # Import gzip module

GDC_API = "https://api.gdc.cancer.gov"
PROJECT = "TCGA-BRCA"
TOKEN_PATH = "gdc_token.txt"
OUTPUT_DIR = Path("tcga_tnbc_data")
OUTPUT_DIR.mkdir(exist_ok=True)

HEADERS_WITH_TOKEN = {}
try:
    with open(TOKEN_PATH, "r") as f:
        token = f.read().strip()
    HEADERS_WITH_TOKEN = {"X-GDC-TOKEN": token}
except FileNotFoundError:
    pass


def post_gdc(endpoint, filters, fields=None, size=200):
    url = f"{GDC_API}/{endpoint}"
    payload = {"filters": filters, "format": "JSON", "size": size}
    if fields:
        payload["fields"] = fields

    all_hits = []
    from_val = 0

    while True:
        params = {"from": from_val}
        resp = requests.post(url, params=params, json=payload, headers=HEADERS_WITH_TOKEN)
        resp.raise_for_status()
        data = resp.json()
        hits = data["data"]["hits"]
        all_hits.extend(hits)

        pagination = data["data"]["pagination"]
        # Changed 'per_page' to 'size' based on common GDC API pagination structure
        if pagination["page"] * pagination["size"] >= pagination["total"]:
            break
        from_val += pagination["size"]

    return all_hits


def get_mirna_files():
    filters = {
        "op": "and",
        "content": [
            {"op": "=", "content": {"field": "cases.project.project_id", "value": PROJECT}},
            {"op": "=", "content": {"field": "files.data_category", "value": "Transcriptome Profiling"}},
            {"op": "=", "content": {"field": "files.data_type", "value": "miRNA Expression Quantification"}},
            {"op": "=", "content": {"field": "files.experimental_strategy", "value": "miRNA-Seq"}},
            {"op": "in", "content": {"field": "cases.samples.sample_type", "value": ["Primary Tumor", "Solid Tissue Normal"]}},
        ]
    }

    fields = ",".join([
        "file_id",
        "file_name",
        "cases.project.project_id",
        "cases.samples.sample_type",
        "cases.submitter_id"
    ])

    hits = post_gdc("files", filters, fields=fields)
    print(f"Found {len(hits)} miRNA files.")
    return hits


def download_file(file_id, out_path):
    url = f"{GDC_API}/data/{file_id}"
    with requests.get(url, headers=HEADERS_WITH_TOKEN, stream=True, timeout=300) as r:
        r.raise_for_status()
        with open(out_path, "wb") as f:
            for chunk in r.iter_content(chunk_size=8192):
                f.write(chunk)


def build_and_save_mirna_matrix(file_info, output_csv):
    all_dfs = []
    sample_names = []

    for info in tqdm(file_info, desc="Downloading miRNA files"):
        fid = info["file_id"]
        tmp_path = OUTPUT_DIR / f"{fid}_mirna.tsv.gz"
        download_file(fid, tmp_path)

        df = None
        try:
            # Check if file is actually gzipped by reading magic bytes
            is_gzipped = False
            with open(tmp_path, 'rb') as f:
                magic_bytes = f.read(2)
                if magic_bytes == b'\x1f\x8b': # Gzip magic bytes
                    is_gzipped = True

            if is_gzipped:
                df = pd.read_csv(tmp_path, sep="\t", compression='gzip', comment='#') # miRNA files often have headers
            else:
                print(f"Warning: File {tmp_path} is not gzipped despite extension. Attempting to read as plain TSV with comments.")
                df = pd.read_csv(tmp_path, sep="\t", compression=None, comment='#') # Explicitly no compression

        except Exception as e:
            print(f"Error: An unexpected error occurred while reading file {tmp_path}: {e}. Skipping this file.")
            tmp_path.unlink(missing_ok=True)
            continue

        if df is None or df.empty:
            print(f"Warning: Skipping empty or unreadable file {tmp_path}.")
            tmp_path.unlink(missing_ok=True)
            continue

        if "reads_per_million_miRNA_mapped" in df.columns:
            value_col = "reads_per_million_miRNA_mapped"
        else:
            # Fallback to the second column if the specific column name is not found
            # Assuming miRNA_ID is first column and value is second
            if df.shape[1] > 1:
                value_col = df.columns[1]
            else:
                print(f"Warning: File {tmp_path} does not have enough columns for miRNA expression. Skipping.")
                tmp_path.unlink(missing_ok=True)
                continue

        sub = df[["miRNA_ID", value_col]].copy()
        sub = sub.rename(columns={"miRNA_ID": "miRNA_id", value_col: fid})
        sub = sub.set_index("miRNA_id")

        all_dfs.append(sub)

        case_sub = info.get("cases", [{}])[0].get("submitter_id", fid)
        sample_type = info.get("cases", [{}])[0].get("samples", [{}])[0].get("sample_type", "UNK")
        sample_name = f"{case_sub}_{sample_type}"
        sample_names.append(sample_name)

        tmp_path.unlink(missing_ok=True) # Delete temp file after processing

    if not all_dfs:
        print("No valid miRNA files were processed.")
        return pd.DataFrame()

    merged = pd.concat(all_dfs, axis=1)
    merged.columns = sample_names
    merged.to_csv(output_csv)
    print(f"miRNA matrix saved to: {output_csv}")
    return merged


# __name__ == "__main__" block
mirna_files = get_mirna_files()
if not mirna_files:
    print("No miRNA files found.")
else:
    build_and_save_mirna_matrix(
        mirna_files,
        OUTPUT_DIR / "TCGA_BRCA_miRNA_matrix.csv"
    )

Found 1200 miRNA files.

Downloading miRNA files:   0%|          | 1/1200 [00:00<10:19,  1.94it/s]

Warning: File tcga_tnbc_data/0e14a024-d7be-48ca-9aa4-8ce915a584e9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   0%|          | 2/1200 [00:01<09:57,  2.01it/s]

Warning: File tcga_tnbc_data/5c50f5de-8495-43d9-a6af-1a0cdec79f9e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   0%|          | 3/1200 [00:01<10:00,  1.99it/s]

Warning: File tcga_tnbc_data/9ffe4074-da8b-402b-8820-2d50aff099a0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   0%|          | 4/1200 [00:01<09:06,  2.19it/s]

Warning: File tcga_tnbc_data/4e8f027a-d311-470c-ae1b-c030e1bfa58e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   0%|          | 5/1200 [00:02<08:55,  2.23it/s]

Warning: File tcga_tnbc_data/4a705a20-e5f2-4307-98d1-4f8550cd3887_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   0%|          | 6/1200 [00:02<08:35,  2.31it/s]

Warning: File tcga_tnbc_data/efa764bd-5a4b-43cd-b646-1283894094f4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   1%|          | 7/1200 [00:03<08:31,  2.33it/s]

Warning: File tcga_tnbc_data/854cab48-2281-426a-910d-66ef0cdb0b83_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   1%|          | 8/1200 [00:03<08:52,  2.24it/s]

Warning: File tcga_tnbc_data/8153acfd-1130-4656-bd33-2d97b5a6bda5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   1%|          | 9/1200 [00:04<12:22,  1.60it/s]

Warning: File tcga_tnbc_data/0d6ee2bf-b821-434c-ba5d-a73a9e27f159_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   1%|          | 10/1200 [00:05<11:31,  1.72it/s]

Warning: File tcga_tnbc_data/a17097f7-5d41-4671-9395-61ff10aa0c97_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   1%|          | 11/1200 [00:05<11:21,  1.74it/s]

Warning: File tcga_tnbc_data/d9c7ddbc-0017-4480-8645-ec336d70fa1a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   1%|          | 12/1200 [00:06<10:29,  1.89it/s]

Warning: File tcga_tnbc_data/c645f59d-0770-4609-b4a7-0e2c38ee0ebc_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   1%|          | 13/1200 [00:06<09:32,  2.07it/s]

Warning: File tcga_tnbc_data/2550b2a1-7137-4fdc-82d5-724409e95f63_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   1%|          | 14/1200 [00:06<09:32,  2.07it/s]

Warning: File tcga_tnbc_data/f772b781-d621-4278-b224-ab16a44f0710_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   1%|▏         | 15/1200 [00:07<08:53,  2.22it/s]

Warning: File tcga_tnbc_data/c13c207a-1e95-473c-873f-6ac03d6a9b04_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   1%|▏         | 16/1200 [00:07<09:37,  2.05it/s]

Warning: File tcga_tnbc_data/a85b7101-e158-4dde-9863-d466da951f1a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   1%|▏         | 17/1200 [00:08<09:46,  2.02it/s]

Warning: File tcga_tnbc_data/4dcf0fd6-a7eb-4f62-add4-e54905acf3b9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   2%|▏         | 18/1200 [00:08<09:08,  2.16it/s]

Warning: File tcga_tnbc_data/3ef75f19-8b1a-4d77-a84a-f89e9869c0bb_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   2%|▏         | 19/1200 [00:09<09:11,  2.14it/s]

Warning: File tcga_tnbc_data/105e93d3-bb72-47ba-9513-a3b7bef6207d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   2%|▏         | 20/1200 [00:09<09:11,  2.14it/s]

Warning: File tcga_tnbc_data/7c022118-2af0-4ef0-9b1f-98a683ea6e75_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   2%|▏         | 21/1200 [00:10<09:33,  2.05it/s]

Warning: File tcga_tnbc_data/12820cd4-1a8d-4cdf-b47a-b31c926ab7e1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   2%|▏         | 22/1200 [00:10<09:50,  2.00it/s]

Warning: File tcga_tnbc_data/ccf38eda-e95b-4392-9f05-cfbdbbf8fbf8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   2%|▏         | 23/1200 [00:11<09:34,  2.05it/s]

Warning: File tcga_tnbc_data/2007f47e-b3aa-42b2-b7e1-9d5f0da934bf_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   2%|▏         | 24/1200 [00:11<09:07,  2.15it/s]

Warning: File tcga_tnbc_data/11f6716f-198e-4ddd-8f35-2177f1b6569e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   2%|▏         | 25/1200 [00:12<09:32,  2.05it/s]

Warning: File tcga_tnbc_data/6a3ed02c-cbd6-49a1-ab82-065dc847ce97_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   2%|▏         | 26/1200 [00:12<10:10,  1.92it/s]

Warning: File tcga_tnbc_data/2272a72a-201e-4e84-b4fb-5e20939e0fa9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   2%|▏         | 27/1200 [00:13<09:58,  1.96it/s]

Warning: File tcga_tnbc_data/7ee45307-85b7-437d-bf34-3c4c51e693b2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   2%|▏         | 28/1200 [00:13<09:54,  1.97it/s]

Warning: File tcga_tnbc_data/7433646c-92de-450d-8dbb-9bdb029ae1e0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   2%|▏         | 29/1200 [00:14<09:19,  2.09it/s]

Warning: File tcga_tnbc_data/19f6f994-b63f-4405-9855-9134dc5e487e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   2%|▎         | 30/1200 [00:14<08:54,  2.19it/s]

Warning: File tcga_tnbc_data/e417dd1c-a082-4acc-a01a-da833f20b936_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   3%|▎         | 31/1200 [00:15<09:05,  2.14it/s]

Warning: File tcga_tnbc_data/28c996b2-5e2d-4a48-a4e0-dd910f8599ab_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   3%|▎         | 32/1200 [00:15<09:22,  2.08it/s]

Warning: File tcga_tnbc_data/e2f83aa2-8089-4a9e-b2d8-bdec8283de69_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   3%|▎         | 33/1200 [00:16<09:29,  2.05it/s]

Warning: File tcga_tnbc_data/d6fbf4b2-a073-45cd-a63c-0b34ba0b5fd1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   3%|▎         | 34/1200 [00:16<09:11,  2.11it/s]

Warning: File tcga_tnbc_data/decf86c1-c5d2-4dd0-99fd-91b17c1e55c8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   3%|▎         | 35/1200 [00:17<09:08,  2.12it/s]

Warning: File tcga_tnbc_data/c0e234b3-a2d0-4891-856c-e65bc3b74051_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   3%|▎         | 36/1200 [00:17<09:01,  2.15it/s]

Warning: File tcga_tnbc_data/732a4929-8a67-45dd-93cd-d0e7e495b898_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   3%|▎         | 37/1200 [00:17<08:54,  2.18it/s]

Warning: File tcga_tnbc_data/4875a959-464d-4996-aa2b-efde14601743_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   3%|▎         | 38/1200 [00:18<09:47,  1.98it/s]

Warning: File tcga_tnbc_data/3b07b87f-2830-4bce-b618-316a8a02d609_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   3%|▎         | 39/1200 [00:19<09:32,  2.03it/s]

Warning: File tcga_tnbc_data/b7f48223-8420-44c2-a8ff-b59b859cd664_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   3%|▎         | 40/1200 [00:19<10:23,  1.86it/s]

Warning: File tcga_tnbc_data/898d3ebf-81f6-4e59-93bd-53130c21d963_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   3%|▎         | 41/1200 [00:20<09:34,  2.02it/s]

Warning: File tcga_tnbc_data/bfadc0b6-bd28-48f3-b5c4-59e0dfc43637_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   4%|▎         | 42/1200 [00:20<09:24,  2.05it/s]

Warning: File tcga_tnbc_data/b5aab16f-800b-4c8c-a28b-78fb34f02a8f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   4%|▎         | 43/1200 [00:21<10:09,  1.90it/s]

Warning: File tcga_tnbc_data/7106897f-1108-4f59-a5cd-8164994ab6d6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   4%|▎         | 44/1200 [00:21<10:00,  1.93it/s]

Warning: File tcga_tnbc_data/5b8a883d-3e5a-445c-9fb2-d9c52e329c56_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   4%|▍         | 45/1200 [00:22<10:16,  1.87it/s]

Warning: File tcga_tnbc_data/8abca5f3-4d83-4fe0-b41c-93a38d8a0518_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   4%|▍         | 46/1200 [00:22<09:44,  1.97it/s]

Warning: File tcga_tnbc_data/d8e18a38-0e22-4c3e-882e-2036af42a78a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   4%|▍         | 47/1200 [00:23<09:51,  1.95it/s]

Warning: File tcga_tnbc_data/e5a1fc0c-20ec-46bf-bd88-7d231842e8e2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   4%|▍         | 48/1200 [00:23<10:00,  1.92it/s]

Warning: File tcga_tnbc_data/cf2acc45-76b1-498f-a7d2-53bde5f09515_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   4%|▍         | 49/1200 [00:24<10:07,  1.90it/s]

Warning: File tcga_tnbc_data/45530049-cc5a-431b-a424-3664a4e9692d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   4%|▍         | 50/1200 [00:24<09:55,  1.93it/s]

Warning: File tcga_tnbc_data/68a2859e-73c0-4d98-aa7f-de4b7886190d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   4%|▍         | 51/1200 [00:25<09:50,  1.95it/s]

Warning: File tcga_tnbc_data/2d5310fd-1eb6-4e9f-9d54-f89b549a0609_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   4%|▍         | 52/1200 [00:25<09:39,  1.98it/s]

Warning: File tcga_tnbc_data/c6e4e020-dbe8-4e35-a198-b5e7c5483277_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   4%|▍         | 53/1200 [00:26<09:07,  2.10it/s]

Warning: File tcga_tnbc_data/b46f17b8-62c8-4882-9978-d9c4d1b02d3a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   4%|▍         | 54/1200 [00:26<08:45,  2.18it/s]

Warning: File tcga_tnbc_data/48d6066e-9233-4968-af23-26c232c95921_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   5%|▍         | 55/1200 [00:27<08:35,  2.22it/s]

Warning: File tcga_tnbc_data/eb0619c2-7b8d-4513-a296-e910001cd0a9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   5%|▍         | 56/1200 [00:27<09:35,  1.99it/s]

Warning: File tcga_tnbc_data/da1f511e-b70f-49b6-944e-600978a08adc_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   5%|▍         | 57/1200 [00:28<09:50,  1.94it/s]

Warning: File tcga_tnbc_data/5850111a-db51-4bf0-96ba-fda0423d654a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   5%|▍         | 58/1200 [00:28<09:21,  2.03it/s]

Warning: File tcga_tnbc_data/a3337105-df27-4bab-8051-3cfd830e35dc_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   5%|▍         | 59/1200 [00:29<09:18,  2.04it/s]

Warning: File tcga_tnbc_data/f6127960-9e35-4ab0-9ba6-d03a3155c3c5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   5%|▌         | 60/1200 [00:29<08:52,  2.14it/s]

Warning: File tcga_tnbc_data/429e5006-0ebe-428b-8233-5e996c5157b5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   5%|▌         | 61/1200 [00:30<09:16,  2.05it/s]

Warning: File tcga_tnbc_data/fb6ec196-dd93-4f94-9097-4cc4d2ae2290_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   5%|▌         | 62/1200 [00:30<09:44,  1.95it/s]

Warning: File tcga_tnbc_data/6e415513-48bf-4eaf-b2c5-4570c63ebeb1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   5%|▌         | 63/1200 [00:31<09:57,  1.90it/s]

Warning: File tcga_tnbc_data/49f9af50-6b9c-4ec4-9851-3a44e049df4f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   5%|▌         | 64/1200 [00:31<09:34,  1.98it/s]

Warning: File tcga_tnbc_data/da0e5fa1-10d4-4b8a-89d4-35fbc5c1ec87_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   5%|▌         | 65/1200 [00:32<10:12,  1.85it/s]

Warning: File tcga_tnbc_data/0d8cc2b6-69bc-446c-82b3-9367cf14be7f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   6%|▌         | 66/1200 [00:32<09:43,  1.94it/s]

Warning: File tcga_tnbc_data/2036698c-6928-49d5-b536-d5ba34d319e6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   6%|▌         | 67/1200 [00:33<10:19,  1.83it/s]

Warning: File tcga_tnbc_data/c343b4e9-3e1a-48f5-8d40-0c9e280cbd42_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   6%|▌         | 68/1200 [00:33<10:04,  1.87it/s]

Warning: File tcga_tnbc_data/26856fa7-dd5f-4951-9c29-bba62f2ed9bb_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   6%|▌         | 69/1200 [00:34<09:37,  1.96it/s]

Warning: File tcga_tnbc_data/871d7ddc-4ac4-4ee4-a827-e7f7caa9b52f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   6%|▌         | 70/1200 [00:34<09:42,  1.94it/s]

Warning: File tcga_tnbc_data/82e5d342-4aa9-4413-9ff0-73f6a76018f4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   6%|▌         | 71/1200 [00:35<09:25,  2.00it/s]

Warning: File tcga_tnbc_data/9003b6c4-6b3b-4518-8827-3f48d5958bf9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   6%|▌         | 72/1200 [00:35<09:11,  2.05it/s]

Warning: File tcga_tnbc_data/41a30b1b-9f16-4a48-a237-2e0a3b95d864_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   6%|▌         | 73/1200 [00:36<09:15,  2.03it/s]

Warning: File tcga_tnbc_data/7020de49-7d6f-44d5-bc2f-4c28a7b3f823_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   6%|▌         | 74/1200 [00:36<09:10,  2.04it/s]

Warning: File tcga_tnbc_data/99b5d58c-f91c-46d7-8c57-fe017a14f81b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   6%|▋         | 75/1200 [00:37<10:04,  1.86it/s]

Warning: File tcga_tnbc_data/8c6c51d4-6734-490b-9690-01f937485e35_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   6%|▋         | 76/1200 [00:37<09:38,  1.94it/s]

Warning: File tcga_tnbc_data/301711d1-3725-4d5e-95f2-ea14ff5f9e5d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   6%|▋         | 77/1200 [00:38<09:56,  1.88it/s]

Warning: File tcga_tnbc_data/ec5e3513-30f6-4d1a-9b0a-9224c1e97d36_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   6%|▋         | 78/1200 [00:38<09:36,  1.95it/s]

Warning: File tcga_tnbc_data/fcafba62-54f6-42b7-a863-28bbf1ece7aa_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   7%|▋         | 79/1200 [00:39<11:11,  1.67it/s]

Warning: File tcga_tnbc_data/499cf32f-6122-4773-affe-92d1a26786ab_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   7%|▋         | 80/1200 [00:40<11:39,  1.60it/s]

Warning: File tcga_tnbc_data/a5400877-bf80-4332-a111-8ef646135782_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   7%|▋         | 81/1200 [00:40<10:31,  1.77it/s]

Warning: File tcga_tnbc_data/347a8e69-dab4-4920-a395-8ee80256d0ff_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   7%|▋         | 82/1200 [00:41<09:38,  1.93it/s]

Warning: File tcga_tnbc_data/44156cdb-28a8-45c7-8d6c-c009affffab9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   7%|▋         | 83/1200 [00:41<09:32,  1.95it/s]

Warning: File tcga_tnbc_data/49f51142-960c-43a1-b738-4996fcf4bf2d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   7%|▋         | 84/1200 [00:42<09:36,  1.94it/s]

Warning: File tcga_tnbc_data/801e740f-4f91-4d3f-adab-bfedbc2e8cda_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   7%|▋         | 85/1200 [00:42<09:42,  1.92it/s]

Warning: File tcga_tnbc_data/06245a7f-7fb8-489b-b906-97aad6cc3dd7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   7%|▋         | 86/1200 [00:43<09:16,  2.00it/s]

Warning: File tcga_tnbc_data/21589a6c-f540-4927-ae32-cc626844aa9c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   7%|▋         | 87/1200 [00:43<08:59,  2.06it/s]

Warning: File tcga_tnbc_data/f1eaed92-a9f4-4865-b40c-da60046262b6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   7%|▋         | 88/1200 [00:44<09:25,  1.97it/s]

Warning: File tcga_tnbc_data/04e89bf1-f3f3-40dd-ab4e-298425cafb91_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   7%|▋         | 89/1200 [00:44<09:29,  1.95it/s]

Warning: File tcga_tnbc_data/c0e35d10-7d8e-4968-8213-f81c8fc5632a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   8%|▊         | 90/1200 [00:45<10:20,  1.79it/s]

Warning: File tcga_tnbc_data/5221cacc-3d04-4a17-8822-6fd9b4bfb2a4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   8%|▊         | 91/1200 [00:45<10:04,  1.84it/s]

Warning: File tcga_tnbc_data/2f047527-d137-4f50-870d-1de05964627c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   8%|▊         | 92/1200 [00:46<09:53,  1.87it/s]

Warning: File tcga_tnbc_data/6a1831e3-a68e-461b-b770-0087c57dbc24_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   8%|▊         | 93/1200 [00:46<09:31,  1.94it/s]

Warning: File tcga_tnbc_data/85df6b0d-d432-4215-aabd-39cdff61d3c2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   8%|▊         | 94/1200 [00:47<09:08,  2.02it/s]

Warning: File tcga_tnbc_data/0c8bf472-f685-455d-a71f-13e90744169f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   8%|▊         | 95/1200 [00:47<08:49,  2.09it/s]

Warning: File tcga_tnbc_data/52bf7f7d-166f-4207-8737-ea117f3be518_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   8%|▊         | 96/1200 [00:48<08:58,  2.05it/s]

Warning: File tcga_tnbc_data/ebce49de-2b04-4824-959b-6712e071436f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   8%|▊         | 97/1200 [00:48<09:00,  2.04it/s]

Warning: File tcga_tnbc_data/aa273e13-4932-44ac-87d8-0f71ee6db500_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   8%|▊         | 98/1200 [00:49<08:48,  2.09it/s]

Warning: File tcga_tnbc_data/64a82f72-229e-4413-93b6-6b88011ea4f2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   8%|▊         | 99/1200 [00:49<08:20,  2.20it/s]

Warning: File tcga_tnbc_data/2aa27014-dedc-4dd5-9f0d-5906d7925391_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   8%|▊         | 100/1200 [00:50<09:08,  2.00it/s]

Warning: File tcga_tnbc_data/967dadf3-dc42-4c11-b7fb-6d3ecebdc4e4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   8%|▊         | 101/1200 [00:50<09:20,  1.96it/s]

Warning: File tcga_tnbc_data/a3361ee3-2e6f-48e7-a526-e6d1b1aa6d75_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   8%|▊         | 102/1200 [00:51<09:21,  1.95it/s]

Warning: File tcga_tnbc_data/a335cf3e-1504-46c7-a130-628ef6b543aa_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   9%|▊         | 103/1200 [00:51<09:16,  1.97it/s]

Warning: File tcga_tnbc_data/0c6dd343-cf69-4a93-a304-3afc9b287a5e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   9%|▊         | 104/1200 [00:52<09:09,  2.00it/s]

Warning: File tcga_tnbc_data/936f8576-8e59-4e4d-8a72-52ce4c6ae585_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   9%|▉         | 105/1200 [00:52<09:29,  1.92it/s]

Warning: File tcga_tnbc_data/ca8d0a76-611f-467d-9539-3d893645c308_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   9%|▉         | 106/1200 [00:53<09:01,  2.02it/s]

Warning: File tcga_tnbc_data/a6e94c3b-2e72-4a4a-bc47-e5f6a12b6d89_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   9%|▉         | 107/1200 [00:53<09:31,  1.91it/s]

Warning: File tcga_tnbc_data/5257a7c7-99ed-4033-b065-3cd7f38a9703_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   9%|▉         | 108/1200 [00:54<09:24,  1.94it/s]

Warning: File tcga_tnbc_data/9356ab97-fd04-4903-a219-1a096421b99a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   9%|▉         | 109/1200 [00:55<09:49,  1.85it/s]

Warning: File tcga_tnbc_data/790e77fb-fe92-4413-bb39-0f1edc92093d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   9%|▉         | 110/1200 [00:55<09:36,  1.89it/s]

Warning: File tcga_tnbc_data/cba39ceb-4b7e-49cb-8b01-c44b7e70ad25_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   9%|▉         | 111/1200 [00:56<09:25,  1.92it/s]

Warning: File tcga_tnbc_data/e6cb449a-c889-48bb-a650-471453c30dbb_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   9%|▉         | 112/1200 [00:56<09:13,  1.97it/s]

Warning: File tcga_tnbc_data/9d8886ed-3a21-4b34-b9b1-e403659b0d94_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:   9%|▉         | 113/1200 [00:56<08:50,  2.05it/s]

Warning: File tcga_tnbc_data/4954ec61-d9ee-437f-a4b7-870f11ceb71d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  10%|▉         | 114/1200 [00:57<09:05,  1.99it/s]

Warning: File tcga_tnbc_data/039f4135-fb25-4fd8-8c36-be3b48462e36_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  10%|▉         | 115/1200 [00:57<08:52,  2.04it/s]

Warning: File tcga_tnbc_data/dd4dc066-210e-45e4-a2e3-4fa2e2635276_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  10%|▉         | 116/1200 [00:58<09:04,  1.99it/s]

Warning: File tcga_tnbc_data/e2a34ea2-26f0-4cd9-853c-4f66b2912c56_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  10%|▉         | 117/1200 [00:59<09:39,  1.87it/s]

Warning: File tcga_tnbc_data/f1394f51-c3ab-45e8-87a2-fe641f00518e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  10%|▉         | 118/1200 [00:59<09:04,  1.99it/s]

Warning: File tcga_tnbc_data/342e1ce8-6605-4daa-bfc7-4ab5924bbffd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  10%|▉         | 119/1200 [00:59<08:38,  2.09it/s]

Warning: File tcga_tnbc_data/6f7baac5-47ff-4542-8254-a6ca6d5a03d5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  10%|█         | 120/1200 [01:00<08:45,  2.06it/s]

Warning: File tcga_tnbc_data/4aa7dbad-2fc6-45e5-8900-d827d93b1f47_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  10%|█         | 121/1200 [01:00<09:10,  1.96it/s]

Warning: File tcga_tnbc_data/03b656ac-9aa2-415a-aec0-a7fbcdf4a592_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  10%|█         | 122/1200 [01:01<09:07,  1.97it/s]

Warning: File tcga_tnbc_data/fa1f1ee4-7567-4808-a57a-540aa7bc1ca6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  10%|█         | 123/1200 [01:02<09:15,  1.94it/s]

Warning: File tcga_tnbc_data/66a43c8b-bb8b-42bf-a692-9a79c4ce1280_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  10%|█         | 124/1200 [01:02<09:00,  1.99it/s]

Warning: File tcga_tnbc_data/00ff9946-9ddd-40bb-8e31-7be8efe0cc6e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  10%|█         | 125/1200 [01:03<09:47,  1.83it/s]

Warning: File tcga_tnbc_data/54575111-3b09-4a6a-bbc7-a332db5ed7f1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  10%|█         | 126/1200 [01:03<10:09,  1.76it/s]

Warning: File tcga_tnbc_data/8b1478bc-6e80-40d3-a083-05b948ac0310_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  11%|█         | 127/1200 [01:04<09:49,  1.82it/s]

Warning: File tcga_tnbc_data/f0c94748-968a-4308-a95f-aaec4b5051c0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  11%|█         | 128/1200 [01:04<09:27,  1.89it/s]

Warning: File tcga_tnbc_data/e28b31c5-4d5b-4700-bdd9-82471e53be73_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  11%|█         | 129/1200 [01:05<09:25,  1.89it/s]

Warning: File tcga_tnbc_data/ab5230a5-b9b3-434e-89a2-67e6f2dbe44e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  11%|█         | 130/1200 [01:05<08:52,  2.01it/s]

Warning: File tcga_tnbc_data/74c57e6a-badb-4c90-817f-f265e9f0eae7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  11%|█         | 131/1200 [01:06<08:15,  2.16it/s]

Warning: File tcga_tnbc_data/53601c4d-ee9a-4e2a-a1ca-8d6f79f7785f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  11%|█         | 132/1200 [01:06<07:43,  2.31it/s]

Warning: File tcga_tnbc_data/65b34f4b-b11e-4716-9d20-51091c45ae7e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  11%|█         | 133/1200 [01:06<07:33,  2.35it/s]

Warning: File tcga_tnbc_data/757ee75b-674e-49a5-8ba0-cc1b574a51ae_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  11%|█         | 134/1200 [01:07<07:44,  2.29it/s]

Warning: File tcga_tnbc_data/6a94d33d-a3eb-4d5a-9173-3f0b0c049b15_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  11%|█▏        | 135/1200 [01:07<07:54,  2.24it/s]

Warning: File tcga_tnbc_data/d936528d-2256-4f76-862f-b550be76f874_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  11%|█▏        | 136/1200 [01:08<07:51,  2.26it/s]

Warning: File tcga_tnbc_data/9b7b5c81-80c9-4db4-8cd4-9eb4c41e88f9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  11%|█▏        | 137/1200 [01:08<07:42,  2.30it/s]

Warning: File tcga_tnbc_data/66a33c82-2163-4817-b1d3-6afd1b34b2da_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  12%|█▏        | 138/1200 [01:09<08:32,  2.07it/s]

Warning: File tcga_tnbc_data/86fdcdf4-fcc1-4c36-9c9d-ba0ecebc615c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  12%|█▏        | 139/1200 [01:09<08:41,  2.03it/s]

Warning: File tcga_tnbc_data/fee8a8f6-2ebb-4dff-b3f6-f2650de24139_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  12%|█▏        | 140/1200 [01:10<08:06,  2.18it/s]

Warning: File tcga_tnbc_data/c23c8319-a199-41ff-9782-463333c4164a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  12%|█▏        | 141/1200 [01:10<08:18,  2.12it/s]

Warning: File tcga_tnbc_data/a41c7eb9-8c05-418c-a339-29cbe7b15ce0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  12%|█▏        | 142/1200 [01:11<09:22,  1.88it/s]

Warning: File tcga_tnbc_data/5a60bc87-bd7f-4e42-bdd5-cdb6af087758_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  12%|█▏        | 143/1200 [01:11<10:15,  1.72it/s]

Warning: File tcga_tnbc_data/911047e4-1229-41a7-bb32-5280cf2a12c3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  12%|█▏        | 144/1200 [01:12<09:43,  1.81it/s]

Warning: File tcga_tnbc_data/f24e9b24-0705-4542-95c6-dda3e9b1b55a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  12%|█▏        | 145/1200 [01:12<08:50,  1.99it/s]

Warning: File tcga_tnbc_data/4a8a9db8-8891-4e3b-abf5-08e2a974a56f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  12%|█▏        | 146/1200 [01:13<08:40,  2.03it/s]

Warning: File tcga_tnbc_data/eade8358-09b3-4ff8-aea9-ffc96570fd05_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  12%|█▏        | 147/1200 [01:13<08:23,  2.09it/s]

Warning: File tcga_tnbc_data/3f543d08-e293-4892-b2f2-810a937898c1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  12%|█▏        | 148/1200 [01:14<07:49,  2.24it/s]

Warning: File tcga_tnbc_data/856ba6fb-c3f4-4212-8490-b7ab216a2a47_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  12%|█▏        | 149/1200 [01:14<07:21,  2.38it/s]

Warning: File tcga_tnbc_data/01626fb9-a7f7-4324-97f2-ef2fee03f3c7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  12%|█▎        | 150/1200 [01:15<07:42,  2.27it/s]

Warning: File tcga_tnbc_data/a6bb8040-1156-4b6b-8fdd-e0b2fcf4809f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  13%|█▎        | 151/1200 [01:15<07:59,  2.19it/s]

Warning: File tcga_tnbc_data/b0737e6f-6608-4ba3-babe-2d34db5f66b0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  13%|█▎        | 152/1200 [01:15<08:11,  2.13it/s]

Warning: File tcga_tnbc_data/9c6e6db1-4096-47e2-9b77-abd2b4c7d180_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  13%|█▎        | 153/1200 [01:16<07:52,  2.22it/s]

Warning: File tcga_tnbc_data/af417154-4a8e-4c16-b65d-3f912189daa3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  13%|█▎        | 154/1200 [01:16<08:09,  2.13it/s]

Warning: File tcga_tnbc_data/65f94233-e5fd-468f-aec6-94f2347d2f34_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  13%|█▎        | 155/1200 [01:17<08:09,  2.14it/s]

Warning: File tcga_tnbc_data/1eba8afe-a8de-4b2e-9ab9-0f38ffbe9bad_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  13%|█▎        | 156/1200 [01:17<08:03,  2.16it/s]

Warning: File tcga_tnbc_data/9189e175-f476-48b8-a192-9727ad0e872a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  13%|█▎        | 157/1200 [01:18<08:02,  2.16it/s]

Warning: File tcga_tnbc_data/25f521ec-012b-4872-b97a-7764f8a57dc1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  13%|█▎        | 158/1200 [01:18<07:28,  2.32it/s]

Warning: File tcga_tnbc_data/3d03ea94-ab5e-45d9-ad13-0b0e6af4ab69_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  13%|█▎        | 159/1200 [01:19<07:25,  2.34it/s]

Warning: File tcga_tnbc_data/071915bb-9433-473e-91c1-b13bc0ce35d2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  13%|█▎        | 160/1200 [01:19<07:50,  2.21it/s]

Warning: File tcga_tnbc_data/28a15efb-f538-41fd-9517-0fb86cae338b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  13%|█▎        | 161/1200 [01:20<07:50,  2.21it/s]

Warning: File tcga_tnbc_data/4d0164d4-2b43-4c4e-a02e-21884294134f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  14%|█▎        | 162/1200 [01:20<07:52,  2.20it/s]

Warning: File tcga_tnbc_data/914d3584-13d3-4509-8701-9dc9a92145f8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  14%|█▎        | 163/1200 [01:20<07:43,  2.24it/s]

Warning: File tcga_tnbc_data/4c626a21-9601-426a-9df4-3e2a7e2811d3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  14%|█▎        | 164/1200 [01:21<07:39,  2.26it/s]

Warning: File tcga_tnbc_data/d0907f83-4aa6-4aae-a059-56e315fbb037_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  14%|█▍        | 165/1200 [01:21<07:41,  2.24it/s]

Warning: File tcga_tnbc_data/8bc460ad-95cc-4a56-9e1a-8173ae6b1259_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  14%|█▍        | 166/1200 [01:22<07:11,  2.40it/s]

Warning: File tcga_tnbc_data/ad23a161-5387-4756-9a64-65bff938d85f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  14%|█▍        | 167/1200 [01:22<07:25,  2.32it/s]

Warning: File tcga_tnbc_data/f4d19d86-3b42-47fb-a052-85118a3e9718_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  14%|█▍        | 168/1200 [01:23<07:47,  2.21it/s]

Warning: File tcga_tnbc_data/641c7068-0f33-42dd-a4fe-cafb541826ee_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  14%|█▍        | 169/1200 [01:23<08:01,  2.14it/s]

Warning: File tcga_tnbc_data/fb22cfaa-6534-497a-905a-a05a7a089020_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  14%|█▍        | 170/1200 [01:23<07:29,  2.29it/s]

Warning: File tcga_tnbc_data/5f32df13-1cd6-4411-a7af-d20c52406dfd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  14%|█▍        | 171/1200 [01:24<07:05,  2.42it/s]

Warning: File tcga_tnbc_data/1d46b67b-8c6d-4a85-a837-30f54d45dce9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  14%|█▍        | 172/1200 [01:24<07:25,  2.31it/s]

Warning: File tcga_tnbc_data/ddeb5176-bbbb-4d71-bc23-1896711652be_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  14%|█▍        | 173/1200 [01:25<07:42,  2.22it/s]

Warning: File tcga_tnbc_data/7f660b4e-d8f6-40fe-af08-ff2b5c658026_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  14%|█▍        | 174/1200 [01:25<08:32,  2.00it/s]

Warning: File tcga_tnbc_data/dc731794-8d31-4fb8-a4a5-c894e788fa0b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  15%|█▍        | 175/1200 [01:26<09:20,  1.83it/s]

Warning: File tcga_tnbc_data/d774e774-3339-4507-adc0-c23e5954740e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  15%|█▍        | 176/1200 [01:27<09:13,  1.85it/s]

Warning: File tcga_tnbc_data/5a16cf9e-4362-4731-82ae-fb0fb1a4c577_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  15%|█▍        | 177/1200 [01:27<08:32,  2.00it/s]

Warning: File tcga_tnbc_data/8bfeb4f1-4193-4386-88d3-1dc935f5d7a9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  15%|█▍        | 178/1200 [01:27<08:21,  2.04it/s]

Warning: File tcga_tnbc_data/3cc7ebf0-012b-46e9-9ec0-26246e074da7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  15%|█▍        | 179/1200 [01:28<08:15,  2.06it/s]

Warning: File tcga_tnbc_data/77b7005e-ef2e-487e-8987-a08a9caac2f8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  15%|█▌        | 180/1200 [01:28<08:20,  2.04it/s]

Warning: File tcga_tnbc_data/e48a4127-695e-47d7-8949-db5e12abe3ff_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  15%|█▌        | 181/1200 [01:29<09:07,  1.86it/s]

Warning: File tcga_tnbc_data/f2661b45-0a12-43b8-9cca-54c260673072_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  15%|█▌        | 182/1200 [01:30<08:50,  1.92it/s]

Warning: File tcga_tnbc_data/b17acaf8-5eb3-40f8-bd9f-59d659f0bbd5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  15%|█▌        | 183/1200 [01:30<09:47,  1.73it/s]

Warning: File tcga_tnbc_data/1e325442-a40b-4f63-861a-ea4083cf7099_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  15%|█▌        | 184/1200 [01:32<13:10,  1.29it/s]

Warning: File tcga_tnbc_data/91016251-afca-4977-bece-c1a868a2c05f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  15%|█▌        | 185/1200 [01:32<12:03,  1.40it/s]

Warning: File tcga_tnbc_data/6dab0488-32d4-401a-b13b-eb31e2167bb0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  16%|█▌        | 186/1200 [01:33<11:05,  1.52it/s]

Warning: File tcga_tnbc_data/175f46cb-fc19-40b2-aa15-ddd534ef588c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  16%|█▌        | 187/1200 [01:33<09:28,  1.78it/s]

Warning: File tcga_tnbc_data/e6e6542c-bbac-46b9-ad05-ab211c14f675_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  16%|█▌        | 188/1200 [01:33<08:53,  1.90it/s]

Warning: File tcga_tnbc_data/456b880c-4bd6-4269-8f2d-029ddf89ceb7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  16%|█▌        | 189/1200 [01:34<08:57,  1.88it/s]

Warning: File tcga_tnbc_data/76c7c7b9-0ea8-4a26-bcf4-ad15da31c05d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  16%|█▌        | 190/1200 [01:34<08:53,  1.89it/s]

Warning: File tcga_tnbc_data/7406d49b-2695-4a31-a284-026fdc12debd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  16%|█▌        | 191/1200 [01:35<08:30,  1.97it/s]

Warning: File tcga_tnbc_data/a5bb52fd-8daa-4155-b9c4-b9453ea8b180_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  16%|█▌        | 192/1200 [01:35<08:14,  2.04it/s]

Warning: File tcga_tnbc_data/19943aa8-5fe4-475c-8398-529ce6c0a3c3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  16%|█▌        | 193/1200 [01:36<08:26,  1.99it/s]

Warning: File tcga_tnbc_data/12d172c8-5deb-447b-b651-ed10adff51d6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  16%|█▌        | 194/1200 [01:36<08:15,  2.03it/s]

Warning: File tcga_tnbc_data/71b2b807-30fa-45e1-839d-eeb71f5b8e60_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  16%|█▋        | 195/1200 [01:37<08:07,  2.06it/s]

Warning: File tcga_tnbc_data/10dcd71c-7ed9-43b5-a227-e1249f595b10_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  16%|█▋        | 196/1200 [01:37<08:43,  1.92it/s]

Warning: File tcga_tnbc_data/6fef6e45-aa6e-41e6-98b1-5dbb9a67b31f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  16%|█▋        | 197/1200 [01:38<08:39,  1.93it/s]

Warning: File tcga_tnbc_data/17b9f0f0-b59b-4fd1-bf48-80d319ee27ff_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  16%|█▋        | 198/1200 [01:38<08:25,  1.98it/s]

Warning: File tcga_tnbc_data/84a43eab-3343-4507-98d6-ae7aa155dadd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  17%|█▋        | 199/1200 [01:39<09:00,  1.85it/s]

Warning: File tcga_tnbc_data/bbed039a-72ba-4d90-b061-bb7f41daf2d8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  17%|█▋        | 200/1200 [01:40<08:43,  1.91it/s]

Warning: File tcga_tnbc_data/264c69d7-0eb5-4cb8-b990-abbe8e204e83_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  17%|█▋        | 201/1200 [01:40<08:25,  1.98it/s]

Warning: File tcga_tnbc_data/c0c2e14e-a426-40a9-96d3-ca2f6fbd8ec4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  17%|█▋        | 202/1200 [01:40<08:13,  2.02it/s]

Warning: File tcga_tnbc_data/46a43fa3-cc56-4c67-9e6e-811ef74cde57_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  17%|█▋        | 203/1200 [01:41<08:20,  1.99it/s]

Warning: File tcga_tnbc_data/e8b1577c-f4eb-4012-8fa0-07cfa4bff80f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  17%|█▋        | 204/1200 [01:41<08:02,  2.06it/s]

Warning: File tcga_tnbc_data/b81c2913-e110-44b3-8599-5e70d8d8cfbf_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  17%|█▋        | 205/1200 [01:42<08:50,  1.87it/s]

Warning: File tcga_tnbc_data/fcc826d6-c4b5-4d85-94cd-ae7a9988dc89_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  17%|█▋        | 206/1200 [01:43<08:22,  1.98it/s]

Warning: File tcga_tnbc_data/709ab1a2-1a46-4118-aaae-c1b7a361b77c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  17%|█▋        | 207/1200 [01:43<08:20,  1.98it/s]

Warning: File tcga_tnbc_data/2280024b-b2d5-454c-bd04-9c5bcabe8cf7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  17%|█▋        | 208/1200 [01:44<08:20,  1.98it/s]

Warning: File tcga_tnbc_data/f0aeb482-f529-42c0-9d17-1a4778e004da_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  17%|█▋        | 209/1200 [01:44<08:25,  1.96it/s]

Warning: File tcga_tnbc_data/c712ff91-262a-4a05-95b5-1e80ee9464bd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  18%|█▊        | 210/1200 [01:45<08:15,  2.00it/s]

Warning: File tcga_tnbc_data/78cdcb7f-e8e0-4612-87fa-5680d239df41_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  18%|█▊        | 211/1200 [01:45<08:19,  1.98it/s]

Warning: File tcga_tnbc_data/fdca715e-de7b-45e6-8cd8-3069bfbff602_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  18%|█▊        | 212/1200 [01:46<08:24,  1.96it/s]

Warning: File tcga_tnbc_data/828a28bf-5c89-4bd8-a791-19c3ea598efd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  18%|█▊        | 213/1200 [01:46<08:15,  1.99it/s]

Warning: File tcga_tnbc_data/d74854f1-7e39-4d8a-9882-faca089b4ab4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  18%|█▊        | 214/1200 [01:47<08:15,  1.99it/s]

Warning: File tcga_tnbc_data/19685baf-1d13-459b-9024-f5452054a6e7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  18%|█▊        | 215/1200 [01:47<08:22,  1.96it/s]

Warning: File tcga_tnbc_data/fc3603d8-3812-4715-8509-12f422d50f5f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  18%|█▊        | 216/1200 [01:48<08:36,  1.91it/s]

Warning: File tcga_tnbc_data/3ba60bf7-69de-49f1-b4c1-9277372c3dd7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  18%|█▊        | 217/1200 [01:48<08:02,  2.04it/s]

Warning: File tcga_tnbc_data/fc694e52-9335-488f-834d-1a9e178002ec_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  18%|█▊        | 218/1200 [01:49<07:45,  2.11it/s]

Warning: File tcga_tnbc_data/c5415243-f09a-4d9e-80d6-c1df7e6c9e3d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  18%|█▊        | 219/1200 [01:49<07:50,  2.08it/s]

Warning: File tcga_tnbc_data/26094c76-21b8-4583-aeb4-3bbad0da7f29_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  18%|█▊        | 220/1200 [01:50<08:01,  2.03it/s]

Warning: File tcga_tnbc_data/dac284f7-3121-43b1-a210-8ea6113d3642_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  18%|█▊        | 221/1200 [01:50<07:45,  2.10it/s]

Warning: File tcga_tnbc_data/9a768a8f-e8b0-43b7-931d-fabc3535c794_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  18%|█▊        | 222/1200 [01:51<08:36,  1.89it/s]

Warning: File tcga_tnbc_data/60607901-25bf-4dfd-8957-4d986cd44495_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  19%|█▊        | 223/1200 [01:51<08:14,  1.98it/s]

Warning: File tcga_tnbc_data/b7288a82-31a9-4c2a-bbcb-3f45d2901d55_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  19%|█▊        | 224/1200 [01:52<08:15,  1.97it/s]

Warning: File tcga_tnbc_data/0f2d2670-8b6b-43b7-a82a-8cf0c6ba7a77_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  19%|█▉        | 225/1200 [01:52<07:55,  2.05it/s]

Warning: File tcga_tnbc_data/871b8cfb-cb30-40ed-9f4f-40c7baf47954_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  19%|█▉        | 226/1200 [01:52<07:27,  2.17it/s]

Warning: File tcga_tnbc_data/f47e9f34-cedd-4473-8b56-01b01c80a89f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  19%|█▉        | 227/1200 [01:53<07:37,  2.13it/s]

Warning: File tcga_tnbc_data/0c8d1af7-7921-4134-b44b-50e09f456001_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  19%|█▉        | 228/1200 [01:55<13:17,  1.22it/s]

Warning: File tcga_tnbc_data/bd3542ab-4313-404a-9bbf-2aa20103b724_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  19%|█▉        | 229/1200 [01:55<11:11,  1.45it/s]

Warning: File tcga_tnbc_data/fbb3ab9c-1f19-4f31-bfb7-bb439717549b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  19%|█▉        | 230/1200 [01:55<10:27,  1.54it/s]

Warning: File tcga_tnbc_data/ffe0a789-d1ed-4a3d-b12b-3f2aad470bfb_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  19%|█▉        | 231/1200 [01:56<10:04,  1.60it/s]

Warning: File tcga_tnbc_data/dac2f6b9-6883-4c50-bb84-0e34290e66d2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  19%|█▉        | 232/1200 [01:57<09:50,  1.64it/s]

Warning: File tcga_tnbc_data/3e4b3c1f-cbb8-487f-9c9e-01291970ade3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  19%|█▉        | 233/1200 [01:57<08:47,  1.83it/s]

Warning: File tcga_tnbc_data/7cf82d45-89d9-4bd3-8776-cb1eb0c321f0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  20%|█▉        | 234/1200 [01:58<08:29,  1.89it/s]

Warning: File tcga_tnbc_data/06dd8f8a-0c1b-4cbb-b66f-4e38230236d7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  20%|█▉        | 235/1200 [01:58<08:16,  1.94it/s]

Warning: File tcga_tnbc_data/48fdfc18-781e-45f2-ac69-6ab2fc773513_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  20%|█▉        | 236/1200 [01:59<08:27,  1.90it/s]

Warning: File tcga_tnbc_data/262e5aa4-6892-4d82-9cee-99be4b6232bc_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  20%|█▉        | 237/1200 [01:59<08:42,  1.84it/s]

Warning: File tcga_tnbc_data/2a0bad5d-d833-4434-9a0f-f8eda09cb5c9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  20%|█▉        | 238/1200 [02:00<08:01,  2.00it/s]

Warning: File tcga_tnbc_data/89bbfa2d-ba3d-4f14-bf01-7292e5958215_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  20%|█▉        | 239/1200 [02:00<08:06,  1.97it/s]

Warning: File tcga_tnbc_data/308e951f-6d14-48fc-ab0f-604364928a56_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  20%|██        | 240/1200 [02:00<07:47,  2.05it/s]

Warning: File tcga_tnbc_data/90d43b1a-edaa-4a07-8527-54f69ea47b95_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  20%|██        | 241/1200 [02:01<07:39,  2.09it/s]

Warning: File tcga_tnbc_data/98fd1ef3-4068-4a44-9bab-ea7378b123e7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  20%|██        | 242/1200 [02:01<07:19,  2.18it/s]

Warning: File tcga_tnbc_data/1540ed84-19b0-49d5-a728-3b04a29abe8a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  20%|██        | 243/1200 [02:02<07:54,  2.02it/s]

Warning: File tcga_tnbc_data/a147ef9c-84d0-46b2-97d7-189460fe7606_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  20%|██        | 244/1200 [02:02<07:20,  2.17it/s]

Warning: File tcga_tnbc_data/17954171-8dab-4e7b-967a-9d2a34d3c2e2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  20%|██        | 245/1200 [02:03<07:49,  2.03it/s]

Warning: File tcga_tnbc_data/35dda171-6920-42b3-b9b1-37769c21d344_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  20%|██        | 246/1200 [02:03<07:53,  2.01it/s]

Warning: File tcga_tnbc_data/200161b3-4821-4d1c-857d-a8ffbbba0b62_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  21%|██        | 247/1200 [02:04<07:55,  2.00it/s]

Warning: File tcga_tnbc_data/191540a1-8853-4b2f-b7ff-2848bbee4c2b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  21%|██        | 248/1200 [02:04<07:47,  2.03it/s]

Warning: File tcga_tnbc_data/966f9637-a03c-41a8-9958-ea22ca86fed8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  21%|██        | 249/1200 [02:05<07:37,  2.08it/s]

Warning: File tcga_tnbc_data/7f39d582-da4f-41e6-aefc-de40b6892e2f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  21%|██        | 250/1200 [02:05<07:25,  2.13it/s]

Warning: File tcga_tnbc_data/cefd5b49-420f-4611-916b-7a4b7fda6fba_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  21%|██        | 251/1200 [02:06<07:25,  2.13it/s]

Warning: File tcga_tnbc_data/3c41e7b2-52f5-4f92-9ab9-b92846e972ba_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  21%|██        | 252/1200 [02:06<07:06,  2.22it/s]

Warning: File tcga_tnbc_data/94b2d8c5-6045-4907-8f65-1d9001f5da09_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  21%|██        | 253/1200 [02:07<06:49,  2.31it/s]

Warning: File tcga_tnbc_data/3b67e5f7-4c32-4f11-a626-7654cb696758_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  21%|██        | 254/1200 [02:07<07:15,  2.17it/s]

Warning: File tcga_tnbc_data/73a1ad6d-17fa-4f62-9275-8c6a5c0c1f2d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  21%|██▏       | 255/1200 [02:07<06:54,  2.28it/s]

Warning: File tcga_tnbc_data/1355d556-a49c-4b20-adf5-08a25de89759_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  21%|██▏       | 256/1200 [02:08<07:33,  2.08it/s]

Warning: File tcga_tnbc_data/b773be36-505b-48d5-88d8-7c14baad43b8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  21%|██▏       | 257/1200 [02:08<07:17,  2.15it/s]

Warning: File tcga_tnbc_data/4e4b13ec-bfb9-4e97-9210-1974b41a3e4d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  22%|██▏       | 258/1200 [02:09<07:25,  2.11it/s]

Warning: File tcga_tnbc_data/da6ed22f-8583-484c-85d2-cd5f29c4eeeb_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  22%|██▏       | 259/1200 [02:09<06:57,  2.26it/s]

Warning: File tcga_tnbc_data/e9d4139d-0b14-49ef-ab6c-297c5efd71d5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  22%|██▏       | 260/1200 [02:10<07:12,  2.17it/s]

Warning: File tcga_tnbc_data/baf45d0a-2691-4988-a33e-8ee88bcbdbb6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  22%|██▏       | 261/1200 [02:10<07:04,  2.21it/s]

Warning: File tcga_tnbc_data/d3ed4500-368c-42a3-998b-7aca451db233_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  22%|██▏       | 262/1200 [02:11<07:17,  2.15it/s]

Warning: File tcga_tnbc_data/5fc06877-c260-4af2-b0a0-98023bc1d718_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  22%|██▏       | 263/1200 [02:11<07:22,  2.12it/s]

Warning: File tcga_tnbc_data/bdc86b29-186c-49ac-9415-a75be73a63e2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  22%|██▏       | 264/1200 [02:12<07:55,  1.97it/s]

Warning: File tcga_tnbc_data/e193802b-e5e0-4d85-b15e-ed85a80ec2a7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  22%|██▏       | 265/1200 [02:12<07:52,  1.98it/s]

Warning: File tcga_tnbc_data/a416945e-cd2d-43f6-aeff-d35cb66684df_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  22%|██▏       | 266/1200 [02:13<08:05,  1.92it/s]

Warning: File tcga_tnbc_data/d4976851-cef0-47d5-9ea6-8c72ece9ed7a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  22%|██▏       | 267/1200 [02:13<08:09,  1.91it/s]

Warning: File tcga_tnbc_data/937c07c2-b2a5-4b3f-a5e1-09edc7fa9bf5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  22%|██▏       | 268/1200 [02:14<07:48,  1.99it/s]

Warning: File tcga_tnbc_data/68b113cd-faec-4cca-b21b-2683ef1bbb73_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  22%|██▏       | 269/1200 [02:14<07:38,  2.03it/s]

Warning: File tcga_tnbc_data/53df569d-4e33-41f5-9742-98bb082bf934_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  22%|██▎       | 270/1200 [02:15<07:38,  2.03it/s]

Warning: File tcga_tnbc_data/d44ffd83-1b69-4fd3-9b67-51e16228820f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  23%|██▎       | 271/1200 [02:15<07:26,  2.08it/s]

Warning: File tcga_tnbc_data/1bbd0673-59f4-4c8a-92e5-1bb19717931f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  23%|██▎       | 272/1200 [02:16<07:28,  2.07it/s]

Warning: File tcga_tnbc_data/fa288f78-75ff-4f7a-aa86-3e99857e47e8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  23%|██▎       | 273/1200 [02:16<07:40,  2.01it/s]

Warning: File tcga_tnbc_data/4e9d76de-98d7-4a5e-8132-2226c90a6af7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  23%|██▎       | 274/1200 [02:17<07:16,  2.12it/s]

Warning: File tcga_tnbc_data/296936b9-d038-44f8-bebc-ed5b7c4b2c38_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  23%|██▎       | 275/1200 [02:17<07:39,  2.01it/s]

Warning: File tcga_tnbc_data/a3870ea2-d450-44c3-b3e3-f26acd52cdb2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  23%|██▎       | 276/1200 [02:18<07:37,  2.02it/s]

Warning: File tcga_tnbc_data/05352d5f-6570-4926-8c20-2c14751c3f2d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  23%|██▎       | 277/1200 [02:18<07:31,  2.04it/s]

Warning: File tcga_tnbc_data/eef375b2-7441-4069-94fd-1035eb1f30f6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  23%|██▎       | 278/1200 [02:19<07:31,  2.04it/s]

Warning: File tcga_tnbc_data/c0e523de-6df0-433a-a174-8312b795d590_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  23%|██▎       | 279/1200 [02:19<07:18,  2.10it/s]

Warning: File tcga_tnbc_data/04248626-f31f-4e3a-aebb-8dca37771ddb_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  23%|██▎       | 280/1200 [02:20<07:52,  1.95it/s]

Warning: File tcga_tnbc_data/7d1f1cd0-526c-4a6f-a4d9-298060dde779_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  23%|██▎       | 281/1200 [02:20<07:37,  2.01it/s]

Warning: File tcga_tnbc_data/964aab26-ff67-4bfc-893a-68c3eb84752a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  24%|██▎       | 282/1200 [02:21<07:36,  2.01it/s]

Warning: File tcga_tnbc_data/f548c2c7-4f94-4e41-a0d7-c3a3e3232513_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  24%|██▎       | 283/1200 [02:21<07:54,  1.93it/s]

Warning: File tcga_tnbc_data/6f440be3-01eb-41c7-a80e-1c25310d3664_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  24%|██▎       | 284/1200 [02:22<07:48,  1.95it/s]

Warning: File tcga_tnbc_data/4fcf32e5-6b8c-4685-b067-888e9f7e0adf_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  24%|██▍       | 285/1200 [02:22<08:00,  1.90it/s]

Warning: File tcga_tnbc_data/dbb0837c-5ba2-4b10-bb93-a832fa11f481_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  24%|██▍       | 286/1200 [02:23<07:59,  1.91it/s]

Warning: File tcga_tnbc_data/c2125779-cfc4-4a84-901b-75223376ff59_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  24%|██▍       | 287/1200 [02:23<07:23,  2.06it/s]

Warning: File tcga_tnbc_data/79eaf58d-3f20-4e6b-9006-d71f80dd4898_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  24%|██▍       | 288/1200 [02:24<07:38,  1.99it/s]

Warning: File tcga_tnbc_data/7f250a22-778c-473d-bf11-9f2a84bfcd31_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  24%|██▍       | 289/1200 [02:24<07:56,  1.91it/s]

Warning: File tcga_tnbc_data/f0e5c4ca-1d9b-4fb7-92fa-3e36f625038a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  24%|██▍       | 290/1200 [02:25<07:48,  1.94it/s]

Warning: File tcga_tnbc_data/70c76e2f-3ce4-4864-8935-eaa51605612a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  24%|██▍       | 291/1200 [02:25<07:47,  1.94it/s]

Warning: File tcga_tnbc_data/2d164199-c4f0-48ca-90bd-5f363b28cc58_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  24%|██▍       | 292/1200 [02:26<07:56,  1.90it/s]

Warning: File tcga_tnbc_data/4821e883-36ff-4203-ab40-e1343b3c7017_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  24%|██▍       | 293/1200 [02:26<07:45,  1.95it/s]

Warning: File tcga_tnbc_data/25a7a89c-6dbe-4537-b664-55637aa6df10_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  24%|██▍       | 294/1200 [02:27<08:21,  1.81it/s]

Warning: File tcga_tnbc_data/2302f5d6-9dda-4c5e-bdf9-8e4834e27df2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  25%|██▍       | 295/1200 [02:28<08:07,  1.86it/s]

Warning: File tcga_tnbc_data/66d15d9c-5acd-4ff8-b4fe-b4bc3e10ba9b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  25%|██▍       | 296/1200 [02:28<07:50,  1.92it/s]

Warning: File tcga_tnbc_data/d018dc76-617b-4904-8e3d-b1f35456f9c8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  25%|██▍       | 297/1200 [02:29<07:33,  1.99it/s]

Warning: File tcga_tnbc_data/01999b22-fd19-4a12-aab9-049e5a3054bd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  25%|██▍       | 298/1200 [02:29<07:06,  2.11it/s]

Warning: File tcga_tnbc_data/3a34b41c-9fdb-4ca4-8afd-5e3319a84d24_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  25%|██▍       | 299/1200 [02:29<07:03,  2.13it/s]

Warning: File tcga_tnbc_data/ec0b35ab-e9cb-4c3f-bbef-6fc4537f3b66_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  25%|██▌       | 300/1200 [02:30<07:35,  1.98it/s]

Warning: File tcga_tnbc_data/98f5da8f-f9bf-4e9e-834c-31b5c931ba69_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  25%|██▌       | 301/1200 [02:30<07:30,  1.99it/s]

Warning: File tcga_tnbc_data/b67087c7-8a60-45e5-8087-4f442e8aa72d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  25%|██▌       | 302/1200 [02:31<07:33,  1.98it/s]

Warning: File tcga_tnbc_data/9d37685b-7c6d-4bf9-bb56-b68a19fa956a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  25%|██▌       | 303/1200 [02:32<08:08,  1.84it/s]

Warning: File tcga_tnbc_data/30843a4c-9ac8-4f2c-85ec-f33b87e716ae_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  25%|██▌       | 304/1200 [02:32<08:07,  1.84it/s]

Warning: File tcga_tnbc_data/e30030b5-84a4-46e6-b756-7d929c08d2e7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  25%|██▌       | 305/1200 [02:33<08:06,  1.84it/s]

Warning: File tcga_tnbc_data/c1c6a9a5-73f2-414a-896d-4d3e564f6e59_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  26%|██▌       | 306/1200 [02:39<34:59,  2.35s/it]

Warning: File tcga_tnbc_data/ceef11d5-dcf3-4ac6-a82f-44121dc48426_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  26%|██▌       | 307/1200 [02:40<26:50,  1.80s/it]

Warning: File tcga_tnbc_data/b63265a8-daa8-4c67-a596-f8432264abdf_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  26%|██▌       | 308/1200 [02:40<20:52,  1.40s/it]

Warning: File tcga_tnbc_data/e879f843-77a2-4f1d-9118-e7c65e860b33_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  26%|██▌       | 309/1200 [02:41<17:03,  1.15s/it]

Warning: File tcga_tnbc_data/93efebf6-85fd-41c5-ba4a-73ab25bd9f75_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  26%|██▌       | 310/1200 [02:41<14:13,  1.04it/s]

Warning: File tcga_tnbc_data/c04f1ad6-272d-41da-b028-44abd1b09f3b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  26%|██▌       | 311/1200 [02:42<12:29,  1.19it/s]

Warning: File tcga_tnbc_data/6216b0fe-e810-48ff-96f2-a09b7ad7cc4c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  26%|██▌       | 312/1200 [02:42<10:53,  1.36it/s]

Warning: File tcga_tnbc_data/ca75d3d9-83e8-4672-85cd-601917ac452e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  26%|██▌       | 313/1200 [02:43<09:45,  1.51it/s]

Warning: File tcga_tnbc_data/6fa95d3e-e33c-482c-87d8-cf41023b2e46_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  26%|██▌       | 314/1200 [02:43<09:11,  1.61it/s]

Warning: File tcga_tnbc_data/b5e2d74c-1626-42de-b97c-4e988e44f9f5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  26%|██▋       | 315/1200 [02:44<08:14,  1.79it/s]

Warning: File tcga_tnbc_data/46871a58-c437-49e3-93e0-915b47edb294_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  26%|██▋       | 316/1200 [02:44<07:20,  2.01it/s]

Warning: File tcga_tnbc_data/163df87a-766e-4781-905f-4dce8589f4b0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  26%|██▋       | 317/1200 [02:45<06:49,  2.16it/s]

Warning: File tcga_tnbc_data/da1008e1-36b1-4751-a386-e9e84b982c47_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  26%|██▋       | 318/1200 [02:45<07:08,  2.06it/s]

Warning: File tcga_tnbc_data/23bf746a-797a-47f5-afd1-76ff723d942e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  27%|██▋       | 319/1200 [02:46<07:14,  2.03it/s]

Warning: File tcga_tnbc_data/93b00070-2a34-4c3e-abdb-b1d1c7d6c6f2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  27%|██▋       | 320/1200 [02:46<07:07,  2.06it/s]

Warning: File tcga_tnbc_data/9f0f7a85-d2ac-4156-80ea-3c39c0f2f005_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  27%|██▋       | 321/1200 [02:47<07:03,  2.07it/s]

Warning: File tcga_tnbc_data/2fcd500e-cb86-4fdd-8340-fd355c0556cc_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  27%|██▋       | 322/1200 [02:47<06:59,  2.09it/s]

Warning: File tcga_tnbc_data/f16e1b44-07c0-4621-9750-d63d13044c42_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  27%|██▋       | 323/1200 [02:47<06:46,  2.16it/s]

Warning: File tcga_tnbc_data/b65dc8ab-c0bb-48f0-bfca-75117cecf8e8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  27%|██▋       | 324/1200 [02:48<06:50,  2.13it/s]

Warning: File tcga_tnbc_data/2932217e-1907-4729-82b0-f05d497fc783_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  27%|██▋       | 325/1200 [02:49<07:23,  1.98it/s]

Warning: File tcga_tnbc_data/4356726a-2bb1-4629-90db-803859bbb319_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  27%|██▋       | 326/1200 [02:49<07:15,  2.01it/s]

Warning: File tcga_tnbc_data/6f14ecd7-c87a-42cd-b90e-03de2964bd94_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  27%|██▋       | 327/1200 [02:50<07:13,  2.01it/s]

Warning: File tcga_tnbc_data/cbdc8782-69cc-49b2-babe-fbfc70185547_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  27%|██▋       | 328/1200 [02:50<06:55,  2.10it/s]

Warning: File tcga_tnbc_data/f09fd1c6-c8bb-49cd-97e1-6b9f661770f6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  27%|██▋       | 329/1200 [02:50<06:44,  2.15it/s]

Warning: File tcga_tnbc_data/94e3b26a-8ffe-4ad7-b432-d7c7be4b5028_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  28%|██▊       | 330/1200 [02:51<06:31,  2.22it/s]

Warning: File tcga_tnbc_data/9c762806-4ac1-4609-ae3e-0597c35d6203_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  28%|██▊       | 331/1200 [02:51<06:36,  2.19it/s]

Warning: File tcga_tnbc_data/0d11e213-5ddf-4d0a-9987-f9d0a3056f3a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  28%|██▊       | 332/1200 [02:52<07:04,  2.05it/s]

Warning: File tcga_tnbc_data/3157a8cb-4f6b-4a7a-a3b5-d4868302a295_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  28%|██▊       | 333/1200 [02:52<06:57,  2.07it/s]

Warning: File tcga_tnbc_data/42ac847d-71cc-468d-88b0-9cc65c38e241_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  28%|██▊       | 334/1200 [02:53<06:54,  2.09it/s]

Warning: File tcga_tnbc_data/eee52d5b-7be0-4795-88c9-75dc2645891f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  28%|██▊       | 335/1200 [02:53<06:38,  2.17it/s]

Warning: File tcga_tnbc_data/fa2558ac-53c0-4743-b3a2-8e7bf0cfe89b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  28%|██▊       | 336/1200 [02:54<06:49,  2.11it/s]

Warning: File tcga_tnbc_data/418c3046-4557-4d8c-aa82-efb372a04b44_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  28%|██▊       | 337/1200 [02:54<06:48,  2.11it/s]

Warning: File tcga_tnbc_data/4b8b4b05-a853-4ec2-ab04-2ccd8609277b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  28%|██▊       | 338/1200 [02:55<07:19,  1.96it/s]

Warning: File tcga_tnbc_data/e955427b-ab30-4634-b168-e46461dda626_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  28%|██▊       | 339/1200 [02:55<07:02,  2.04it/s]

Warning: File tcga_tnbc_data/f20fdb15-6b29-46af-bc5b-ea583dfa13c2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  28%|██▊       | 340/1200 [02:56<07:00,  2.05it/s]

Warning: File tcga_tnbc_data/94daa651-5d59-4a69-bfd0-b95e146cee04_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  28%|██▊       | 341/1200 [02:56<07:12,  1.99it/s]

Warning: File tcga_tnbc_data/fb336b62-9f4e-4cb8-b987-99cb4ef60da5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  28%|██▊       | 342/1200 [02:57<07:18,  1.96it/s]

Warning: File tcga_tnbc_data/82c32328-fe75-4968-9bdb-5c8fb341e394_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  29%|██▊       | 343/1200 [02:57<07:04,  2.02it/s]

Warning: File tcga_tnbc_data/6ab7d63d-a094-4b23-be06-1f93f8dae8a4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  29%|██▊       | 344/1200 [02:58<06:50,  2.08it/s]

Warning: File tcga_tnbc_data/dc74bb68-51b5-4c14-a017-7d68cb591df1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  29%|██▉       | 345/1200 [02:58<06:50,  2.08it/s]

Warning: File tcga_tnbc_data/638736e2-e96a-4f66-942d-0fb9662a5079_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  29%|██▉       | 346/1200 [02:59<06:42,  2.12it/s]

Warning: File tcga_tnbc_data/0174aa45-bcca-4677-b619-593ed2119a05_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  29%|██▉       | 347/1200 [02:59<06:40,  2.13it/s]

Warning: File tcga_tnbc_data/7d7d47f1-96f0-4905-b9d5-10ba619e75a2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  29%|██▉       | 348/1200 [03:00<06:47,  2.09it/s]

Warning: File tcga_tnbc_data/3f8e6f58-24eb-4c97-95f3-8dedd4a9d05a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  29%|██▉       | 349/1200 [03:00<07:17,  1.95it/s]

Warning: File tcga_tnbc_data/edc32d82-53d8-4980-aa5a-0c8f6c5ff311_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  29%|██▉       | 350/1200 [03:01<07:11,  1.97it/s]

Warning: File tcga_tnbc_data/5a1e7524-ff09-42d0-a77f-a7d497d4ebd0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  29%|██▉       | 351/1200 [03:01<07:43,  1.83it/s]

Warning: File tcga_tnbc_data/1fca89db-8baa-434f-a580-3a5b3dcb20c6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  29%|██▉       | 352/1200 [03:02<07:19,  1.93it/s]

Warning: File tcga_tnbc_data/c9bd0faa-8452-482a-bbab-4858f908428b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  29%|██▉       | 353/1200 [03:02<07:36,  1.86it/s]

Warning: File tcga_tnbc_data/5c57e4a1-6498-4ace-8a63-04550891ec02_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  30%|██▉       | 354/1200 [03:03<07:15,  1.94it/s]

Warning: File tcga_tnbc_data/a0992897-79c4-4e33-974a-a65248ee43fa_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  30%|██▉       | 355/1200 [03:03<07:20,  1.92it/s]

Warning: File tcga_tnbc_data/fe6096b0-5c9e-4aa4-85c6-a4d3420d95e0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  30%|██▉       | 356/1200 [03:04<06:37,  2.12it/s]

Warning: File tcga_tnbc_data/e6d69ef2-2ae5-4a6c-b162-6eb465953c88_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  30%|██▉       | 357/1200 [03:04<06:58,  2.01it/s]

Warning: File tcga_tnbc_data/baf89520-278b-461f-9c85-daad7f717a6b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  30%|██▉       | 358/1200 [03:05<06:29,  2.16it/s]

Warning: File tcga_tnbc_data/711608f3-1b39-45ae-9f55-248cbf2a707b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  30%|██▉       | 359/1200 [03:05<06:09,  2.27it/s]

Warning: File tcga_tnbc_data/5a41d026-6876-4db0-b8bf-a15fc771d1be_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  30%|███       | 360/1200 [03:05<06:22,  2.20it/s]

Warning: File tcga_tnbc_data/dca37698-a0de-4c13-ab69-408a3e2b8d65_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  30%|███       | 361/1200 [03:06<07:23,  1.89it/s]

Warning: File tcga_tnbc_data/48e35d76-273a-4dd7-ad6a-cd740e109921_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  30%|███       | 362/1200 [03:07<07:09,  1.95it/s]

Warning: File tcga_tnbc_data/4328f48c-5c7d-4ec4-98fc-f4a28674c49f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  30%|███       | 363/1200 [03:07<07:39,  1.82it/s]

Warning: File tcga_tnbc_data/65775f26-9935-472f-8187-8c488c4b1cee_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  30%|███       | 364/1200 [03:08<07:25,  1.88it/s]

Warning: File tcga_tnbc_data/7c2a4fee-489e-4368-be21-3c681c3fd5a9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  30%|███       | 365/1200 [03:09<08:15,  1.69it/s]

Warning: File tcga_tnbc_data/7434d066-f641-42ab-a87e-7e70ccf885f8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  30%|███       | 366/1200 [03:09<08:27,  1.64it/s]

Warning: File tcga_tnbc_data/284358d4-9c45-4749-b1f4-46e724c59d1f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  31%|███       | 367/1200 [03:10<07:47,  1.78it/s]

Warning: File tcga_tnbc_data/c1553238-b56b-407a-abc0-9a352d12f902_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  31%|███       | 368/1200 [03:10<07:21,  1.89it/s]

Warning: File tcga_tnbc_data/70e1218e-5d4c-49b7-a479-9b5a4a112938_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  31%|███       | 369/1200 [03:10<06:48,  2.04it/s]

Warning: File tcga_tnbc_data/133ae78e-fd83-4a13-9de6-28dbbe8e37c7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  31%|███       | 370/1200 [03:11<06:28,  2.14it/s]

Warning: File tcga_tnbc_data/b66f1001-d558-4884-9dad-923bf16a4ddb_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  31%|███       | 371/1200 [03:11<06:27,  2.14it/s]

Warning: File tcga_tnbc_data/397f6746-6dad-4181-89b7-63881d417277_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  31%|███       | 372/1200 [03:12<06:16,  2.20it/s]

Warning: File tcga_tnbc_data/d218396f-bc77-4846-8796-79e39928a925_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  31%|███       | 373/1200 [03:12<06:07,  2.25it/s]

Warning: File tcga_tnbc_data/be95b2ee-da62-4c6f-b699-c3d6bd89ab7c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  31%|███       | 374/1200 [03:13<06:33,  2.10it/s]

Warning: File tcga_tnbc_data/ffe830c1-061d-4123-95c8-48def573a04a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  31%|███▏      | 375/1200 [03:13<06:59,  1.97it/s]

Warning: File tcga_tnbc_data/dfc8d02e-6bb3-43b8-8076-25930dcd932b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  31%|███▏      | 376/1200 [03:14<07:12,  1.91it/s]

Warning: File tcga_tnbc_data/4db49f5a-4675-41f2-af9b-66cd8cab43cd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  31%|███▏      | 377/1200 [03:14<07:02,  1.95it/s]

Warning: File tcga_tnbc_data/6bf7f596-c9b0-452c-a8fb-8067d42f1936_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  32%|███▏      | 378/1200 [03:15<06:52,  1.99it/s]

Warning: File tcga_tnbc_data/c29ab2e6-ebc0-46c0-b1da-c0d5a5976d25_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  32%|███▏      | 379/1200 [03:15<07:16,  1.88it/s]

Warning: File tcga_tnbc_data/6b5a0fb4-95bd-4d90-89e3-d717493d7e6d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  32%|███▏      | 380/1200 [03:16<07:26,  1.83it/s]

Warning: File tcga_tnbc_data/ba7c2cbf-9951-46a7-b0df-79238aeac9ce_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  32%|███▏      | 381/1200 [03:16<06:47,  2.01it/s]

Warning: File tcga_tnbc_data/ea5d0124-14b8-492f-aecb-5aa464e182e1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  32%|███▏      | 382/1200 [03:17<06:18,  2.16it/s]

Warning: File tcga_tnbc_data/295fb489-c0ca-4793-878f-369bca5890d9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  32%|███▏      | 383/1200 [03:17<06:02,  2.25it/s]

Warning: File tcga_tnbc_data/76505f5a-502a-4e81-81dd-37dbba22547e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  32%|███▏      | 384/1200 [03:18<05:52,  2.32it/s]

Warning: File tcga_tnbc_data/5bcf4341-9360-4904-9dd9-6a43bdfa931c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  32%|███▏      | 385/1200 [03:18<06:07,  2.22it/s]

Warning: File tcga_tnbc_data/fb84de32-ed6d-4eeb-890c-05235a3aa853_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  32%|███▏      | 386/1200 [03:19<06:29,  2.09it/s]

Warning: File tcga_tnbc_data/0cd9169f-e533-4da9-8ed4-e56435fa4dc7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  32%|███▏      | 387/1200 [03:19<06:15,  2.16it/s]

Warning: File tcga_tnbc_data/6ab1f388-28e9-4b2c-bbdf-8383ef18b83c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  32%|███▏      | 388/1200 [03:20<06:26,  2.10it/s]

Warning: File tcga_tnbc_data/bdea9be8-e4d9-4bfb-b416-654b02fd43d1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  32%|███▏      | 389/1200 [03:20<06:50,  1.98it/s]

Warning: File tcga_tnbc_data/b8647788-d1b1-406d-baa6-607fb43d8056_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  32%|███▎      | 390/1200 [03:21<06:48,  1.98it/s]

Warning: File tcga_tnbc_data/ab195f1a-3afe-49b3-bf6f-105dfbee5e9f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  33%|███▎      | 391/1200 [03:21<06:45,  1.99it/s]

Warning: File tcga_tnbc_data/d9c999b0-9056-4680-b448-d918b1a1ab95_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  33%|███▎      | 392/1200 [03:22<06:44,  2.00it/s]

Warning: File tcga_tnbc_data/053e50eb-7f13-4fed-9264-ee6e9cf86f76_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  33%|███▎      | 393/1200 [03:22<07:02,  1.91it/s]

Warning: File tcga_tnbc_data/553abd08-4f08-4084-8d2e-8a56d6d6e120_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  33%|███▎      | 394/1200 [03:23<06:55,  1.94it/s]

Warning: File tcga_tnbc_data/7219f6f2-cd4c-410c-a435-888945502a71_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  33%|███▎      | 395/1200 [03:23<06:35,  2.04it/s]

Warning: File tcga_tnbc_data/d44ac398-6817-4571-bce1-0044f9d6dbd3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  33%|███▎      | 396/1200 [03:24<06:34,  2.04it/s]

Warning: File tcga_tnbc_data/85b21f9d-07de-4576-9652-740a5a550124_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  33%|███▎      | 397/1200 [03:24<07:10,  1.87it/s]

Warning: File tcga_tnbc_data/4f3259b0-5b8a-4d12-9e2d-467af7bbc78f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  33%|███▎      | 398/1200 [03:25<06:30,  2.05it/s]

Warning: File tcga_tnbc_data/a22f0a97-4b8b-4e03-ad35-6fae5522a88a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  33%|███▎      | 399/1200 [03:25<06:26,  2.07it/s]

Warning: File tcga_tnbc_data/bc1eea6a-889a-4412-908f-ccf4c22c9986_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  33%|███▎      | 400/1200 [03:26<06:16,  2.13it/s]

Warning: File tcga_tnbc_data/fcbad081-176a-4cbe-962f-4707138ddd90_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  33%|███▎      | 401/1200 [03:26<06:23,  2.08it/s]

Warning: File tcga_tnbc_data/ddea3865-c880-4836-b0d6-10de01390ad9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  34%|███▎      | 402/1200 [03:26<06:07,  2.17it/s]

Warning: File tcga_tnbc_data/f7db7956-5fbd-4118-864c-8b417e88580d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  34%|███▎      | 403/1200 [03:27<06:11,  2.15it/s]

Warning: File tcga_tnbc_data/9220ca81-c373-4cfa-876a-a7cf827e0d7a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  34%|███▎      | 404/1200 [03:27<06:20,  2.09it/s]

Warning: File tcga_tnbc_data/f406213e-322a-43df-9c2f-0e1583cd0d6a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  34%|███▍      | 405/1200 [03:28<06:55,  1.91it/s]

Warning: File tcga_tnbc_data/1fe883a5-e6ba-44ab-b24f-cfe19b68fc0c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  34%|███▍      | 406/1200 [03:29<06:28,  2.04it/s]

Warning: File tcga_tnbc_data/3d899ad8-1feb-480c-b3de-b588d6fc6106_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  34%|███▍      | 407/1200 [03:29<06:24,  2.06it/s]

Warning: File tcga_tnbc_data/9a387fca-241f-4ec5-8241-75d7cdc1a1f6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  34%|███▍      | 408/1200 [03:29<06:19,  2.09it/s]

Warning: File tcga_tnbc_data/8ad7eaaa-a0a0-4c2a-bf31-cd0832705aea_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  34%|███▍      | 409/1200 [03:30<06:48,  1.94it/s]

Warning: File tcga_tnbc_data/3698bb16-3f20-4ad1-988f-9eb5c7c2f970_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  34%|███▍      | 410/1200 [03:31<06:59,  1.88it/s]

Warning: File tcga_tnbc_data/9d29819e-a6e7-4277-b825-b80182164fd0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  34%|███▍      | 411/1200 [03:31<07:02,  1.87it/s]

Warning: File tcga_tnbc_data/ec8df8ea-c6b0-419d-830b-b22552ebed89_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  34%|███▍      | 412/1200 [03:32<06:47,  1.93it/s]

Warning: File tcga_tnbc_data/00d39f52-dfb1-4256-a6a9-54dea7a0401e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  34%|███▍      | 413/1200 [03:32<07:03,  1.86it/s]

Warning: File tcga_tnbc_data/68910c67-39e1-413d-8724-e772408a9acf_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  34%|███▍      | 414/1200 [03:33<06:31,  2.01it/s]

Warning: File tcga_tnbc_data/b5604d13-4cde-44fa-be67-203bc5da0caf_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  35%|███▍      | 415/1200 [03:33<06:48,  1.92it/s]

Warning: File tcga_tnbc_data/702e5fa4-0acc-442c-9fa3-4cca9f4f54bc_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  35%|███▍      | 416/1200 [03:34<06:38,  1.97it/s]

Warning: File tcga_tnbc_data/bc6abaf1-b5dd-41c7-b3b2-bac114e0ad78_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  35%|███▍      | 417/1200 [03:34<06:12,  2.10it/s]

Warning: File tcga_tnbc_data/8b55e14a-5fc7-4553-829a-ff02fe0f8f7f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  35%|███▍      | 418/1200 [03:34<05:57,  2.19it/s]

Warning: File tcga_tnbc_data/93d8c0e6-b97a-4734-92fd-b98f855301ab_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  35%|███▍      | 419/1200 [03:35<05:52,  2.22it/s]

Warning: File tcga_tnbc_data/6c491aa2-ab02-4e44-8d1b-1ebf3125469b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  35%|███▌      | 420/1200 [03:35<06:05,  2.14it/s]

Warning: File tcga_tnbc_data/5c679022-51b7-4238-b652-0198d7c7887a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  35%|███▌      | 421/1200 [03:36<06:01,  2.16it/s]

Warning: File tcga_tnbc_data/bafab974-b9fa-4516-9763-f37f8294d404_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  35%|███▌      | 422/1200 [03:36<05:56,  2.18it/s]

Warning: File tcga_tnbc_data/6266e5d6-5477-4a83-86bb-b8351923e416_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  35%|███▌      | 423/1200 [03:37<05:54,  2.19it/s]

Warning: File tcga_tnbc_data/bfe0c894-09d6-47ee-8334-23f81a23e1d4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  35%|███▌      | 424/1200 [03:37<05:48,  2.23it/s]

Warning: File tcga_tnbc_data/5ee4d61e-a926-4094-9ffe-312585edd0c4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  35%|███▌      | 425/1200 [03:38<05:52,  2.20it/s]

Warning: File tcga_tnbc_data/a1386644-1ef2-4445-b571-b7755061b18b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  36%|███▌      | 426/1200 [03:38<05:53,  2.19it/s]

Warning: File tcga_tnbc_data/252ee930-ff03-4cc7-8279-543bb5a955b4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  36%|███▌      | 427/1200 [03:39<06:02,  2.13it/s]

Warning: File tcga_tnbc_data/0f7c26d8-ec0b-40d3-8399-a93289d0c882_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  36%|███▌      | 428/1200 [03:39<06:43,  1.91it/s]

Warning: File tcga_tnbc_data/10058d63-4b67-4366-871a-17abf02495dc_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  36%|███▌      | 429/1200 [03:40<09:05,  1.41it/s]

Warning: File tcga_tnbc_data/3e824571-a3da-4d80-98d1-c161f569466d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  36%|███▌      | 430/1200 [03:41<08:35,  1.49it/s]

Warning: File tcga_tnbc_data/8cdfa98c-e2f7-4509-9d31-96eec5ce7a99_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  36%|███▌      | 431/1200 [03:42<07:58,  1.61it/s]

Warning: File tcga_tnbc_data/a7860e15-42f2-470b-83d8-da5d6657ddff_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  36%|███▌      | 432/1200 [03:42<07:30,  1.70it/s]

Warning: File tcga_tnbc_data/f16f009f-c863-43a8-94bf-f24ed4fde296_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  36%|███▌      | 433/1200 [03:42<06:56,  1.84it/s]

Warning: File tcga_tnbc_data/b02ef951-bb51-4378-b59c-ccffeff088ec_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  36%|███▌      | 434/1200 [03:43<06:58,  1.83it/s]

Warning: File tcga_tnbc_data/656df965-f7ff-4713-8981-0994a3244b02_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  36%|███▋      | 435/1200 [03:44<06:51,  1.86it/s]

Warning: File tcga_tnbc_data/1f7b950c-7711-44ee-9d25-0b4d68178a37_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  36%|███▋      | 436/1200 [03:44<06:10,  2.06it/s]

Warning: File tcga_tnbc_data/d83457c2-be25-460c-b782-c905874bfb05_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  36%|███▋      | 437/1200 [03:44<06:14,  2.04it/s]

Warning: File tcga_tnbc_data/0dbc2812-7acb-4f6c-a1bd-b9911b317d36_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  36%|███▋      | 438/1200 [03:45<05:59,  2.12it/s]

Warning: File tcga_tnbc_data/a8804277-1e01-4cb0-9a1a-a637ca5852d9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  37%|███▋      | 439/1200 [03:45<06:11,  2.05it/s]

Warning: File tcga_tnbc_data/ed717bf7-f59f-4563-992d-36119b9bede0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  37%|███▋      | 440/1200 [03:46<06:10,  2.05it/s]

Warning: File tcga_tnbc_data/4927d85f-e15d-490f-988f-9ebf31d20839_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  37%|███▋      | 441/1200 [03:46<06:05,  2.08it/s]

Warning: File tcga_tnbc_data/0bf16fde-30c1-443c-875a-b63a1c271125_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  37%|███▋      | 442/1200 [03:47<06:10,  2.04it/s]

Warning: File tcga_tnbc_data/fa2c92c8-c2a3-4d66-8607-25e26e3a95d2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  37%|███▋      | 443/1200 [03:47<06:06,  2.07it/s]

Warning: File tcga_tnbc_data/b64af68f-e463-4f68-86a1-15399cc15691_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  37%|███▋      | 444/1200 [03:48<05:46,  2.18it/s]

Warning: File tcga_tnbc_data/56a7095e-29b1-4c29-b1ed-9b5a18b36a2c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  37%|███▋      | 445/1200 [03:48<07:03,  1.78it/s]

Warning: File tcga_tnbc_data/57a5ea8d-a6eb-416b-9ae3-9ceac2814e3a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  37%|███▋      | 446/1200 [03:49<06:26,  1.95it/s]

Warning: File tcga_tnbc_data/0d0092fd-33be-4e11-93e8-42f353fbb8d1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  37%|███▋      | 447/1200 [03:49<06:46,  1.85it/s]

Warning: File tcga_tnbc_data/c513453d-3dd5-4fde-b891-b55d4f71fb38_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  37%|███▋      | 448/1200 [03:50<06:12,  2.02it/s]

Warning: File tcga_tnbc_data/8acfb9e1-3fc2-4736-a1e3-44593ca8d1fe_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  37%|███▋      | 449/1200 [03:50<06:27,  1.94it/s]

Warning: File tcga_tnbc_data/d14e57a0-143e-4faf-a197-e7429544ad86_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  38%|███▊      | 450/1200 [03:52<09:25,  1.33it/s]

Warning: File tcga_tnbc_data/86bbc63c-70a5-4d2c-bdea-f9de18f8b510_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  38%|███▊      | 451/1200 [03:52<08:23,  1.49it/s]

Warning: File tcga_tnbc_data/d704d644-c21e-49ef-9f83-7f350ba86b9c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  38%|███▊      | 452/1200 [03:53<07:49,  1.59it/s]

Warning: File tcga_tnbc_data/600a260b-0e31-4158-ab13-414d41ef7d35_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  38%|███▊      | 453/1200 [03:53<07:02,  1.77it/s]

Warning: File tcga_tnbc_data/bcf59ef3-e66b-49b6-92a8-478097e710c2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  38%|███▊      | 454/1200 [03:54<06:38,  1.87it/s]

Warning: File tcga_tnbc_data/046b15a8-38d3-41fc-b55f-04dd591a8e14_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  38%|███▊      | 455/1200 [03:54<06:35,  1.88it/s]

Warning: File tcga_tnbc_data/1cf994aa-a44c-4d08-9e06-01ed64693edf_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  38%|███▊      | 456/1200 [03:55<06:43,  1.84it/s]

Warning: File tcga_tnbc_data/54241bed-d309-494b-a892-f1a3c1a69398_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  38%|███▊      | 457/1200 [03:55<06:39,  1.86it/s]

Warning: File tcga_tnbc_data/d43f788a-06c6-4a53-a8e4-710209968064_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  38%|███▊      | 458/1200 [03:56<06:32,  1.89it/s]

Warning: File tcga_tnbc_data/7c44a1e3-6765-4a73-830f-6ff19d87d43f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  38%|███▊      | 459/1200 [03:56<06:30,  1.90it/s]

Warning: File tcga_tnbc_data/e3476c1f-d114-40df-8968-a8f51a0b6484_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  38%|███▊      | 460/1200 [03:57<06:05,  2.02it/s]

Warning: File tcga_tnbc_data/cd1576c6-1a9f-47de-b51d-9b1754d0ab3e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  38%|███▊      | 461/1200 [03:57<06:00,  2.05it/s]

Warning: File tcga_tnbc_data/3a06f1a2-3a06-4f3b-876a-2c570036a132_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  38%|███▊      | 462/1200 [03:58<06:08,  2.00it/s]

Warning: File tcga_tnbc_data/645d6a17-34c1-4af0-9786-55aad23f64e7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  39%|███▊      | 463/1200 [03:58<06:02,  2.04it/s]

Warning: File tcga_tnbc_data/7d00b97e-c2e5-493a-8952-a039e2635b2d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  39%|███▊      | 464/1200 [03:59<06:24,  1.91it/s]

Warning: File tcga_tnbc_data/20664f76-c4b2-4f86-be8c-f0bf9e4fb052_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  39%|███▉      | 465/1200 [03:59<05:59,  2.04it/s]

Warning: File tcga_tnbc_data/0e338fde-60dd-4d62-b5d8-0a3a01102b4b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  39%|███▉      | 466/1200 [04:00<05:34,  2.20it/s]

Warning: File tcga_tnbc_data/cebd233b-8463-4cc6-95c3-9150170b18de_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  39%|███▉      | 467/1200 [04:00<05:57,  2.05it/s]

Warning: File tcga_tnbc_data/adaebe36-5fdb-41f8-b05a-ed793fa6fd38_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  39%|███▉      | 468/1200 [04:01<06:09,  1.98it/s]

Warning: File tcga_tnbc_data/0f931145-8fc3-4b2c-bb8f-8e5e978b825b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  39%|███▉      | 469/1200 [04:01<05:48,  2.10it/s]

Warning: File tcga_tnbc_data/32b046cc-93cf-4f15-9d0a-cc8e7a163cbf_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  39%|███▉      | 470/1200 [04:01<05:25,  2.24it/s]

Warning: File tcga_tnbc_data/1641a198-218f-4c63-802d-16a09fabf82a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  39%|███▉      | 471/1200 [04:02<05:53,  2.06it/s]

Warning: File tcga_tnbc_data/e9c2b7e2-8a60-474f-97b0-1a153a47757b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  39%|███▉      | 472/1200 [04:02<05:38,  2.15it/s]

Warning: File tcga_tnbc_data/dedc6b67-b1a6-47c5-8f3b-365b4aa7d4bb_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  39%|███▉      | 473/1200 [04:03<05:53,  2.05it/s]

Warning: File tcga_tnbc_data/cab62404-4930-4260-b047-0029de7fad38_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  40%|███▉      | 474/1200 [04:03<05:54,  2.05it/s]

Warning: File tcga_tnbc_data/0f9c65de-7793-456e-a2dc-d3de101a5095_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  40%|███▉      | 475/1200 [04:04<05:32,  2.18it/s]

Warning: File tcga_tnbc_data/18a132a0-d95c-4311-a2e9-3cea86decb0e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  40%|███▉      | 476/1200 [04:04<05:34,  2.16it/s]

Warning: File tcga_tnbc_data/833c2264-3379-4f83-bd51-8dbda8fab013_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  40%|███▉      | 477/1200 [04:05<05:59,  2.01it/s]

Warning: File tcga_tnbc_data/fcd5f067-418e-4636-80b5-3acca97bdc29_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  40%|███▉      | 478/1200 [04:05<05:57,  2.02it/s]

Warning: File tcga_tnbc_data/32bb2085-8247-4f0c-92fd-cf5bf033daa5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  40%|███▉      | 479/1200 [04:06<05:51,  2.05it/s]

Warning: File tcga_tnbc_data/f96df44f-ca2f-4595-922a-bc0543413f23_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  40%|████      | 480/1200 [04:07<06:22,  1.88it/s]

Warning: File tcga_tnbc_data/c022e48e-fe91-49aa-8ee9-dbd6734d083f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  40%|████      | 481/1200 [04:07<05:54,  2.03it/s]

Warning: File tcga_tnbc_data/58df0564-7b33-4237-9867-c3426979fd94_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  40%|████      | 482/1200 [04:07<05:54,  2.02it/s]

Warning: File tcga_tnbc_data/36cbd6e5-aa8c-4cb5-88f3-086a6e896f36_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  40%|████      | 483/1200 [04:08<05:46,  2.07it/s]

Warning: File tcga_tnbc_data/2bff15a5-c2ca-4529-ba3a-3042c0de59f3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  40%|████      | 484/1200 [04:08<06:01,  1.98it/s]

Warning: File tcga_tnbc_data/8c105b54-7d1e-42ba-ba2c-259d2f7e9278_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  40%|████      | 485/1200 [04:09<05:44,  2.07it/s]

Warning: File tcga_tnbc_data/66b172d2-29be-4b0d-b52d-465149ec3e57_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  40%|████      | 486/1200 [04:09<05:35,  2.13it/s]

Warning: File tcga_tnbc_data/419dce6e-53aa-43b2-9f8b-1c8512b9b851_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  41%|████      | 487/1200 [04:10<05:42,  2.08it/s]

Warning: File tcga_tnbc_data/98c6443e-64f7-438c-bbe1-bea65458e98b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  41%|████      | 488/1200 [04:10<05:49,  2.04it/s]

Warning: File tcga_tnbc_data/5125a5a9-aeb1-4132-bd34-18d8eb38b61e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  41%|████      | 489/1200 [04:11<05:48,  2.04it/s]

Warning: File tcga_tnbc_data/b817f72a-3ba5-4dfc-81cc-d23ce5250798_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  41%|████      | 490/1200 [04:11<06:02,  1.96it/s]

Warning: File tcga_tnbc_data/04b15889-e23f-4df0-aeca-0a9e40a4acfe_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  41%|████      | 491/1200 [04:12<05:31,  2.14it/s]

Warning: File tcga_tnbc_data/f05495a0-738b-45fd-baef-ca26ff60969a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  41%|████      | 492/1200 [04:12<05:11,  2.27it/s]

Warning: File tcga_tnbc_data/89b3406b-023b-40d7-8ad0-1f8559500229_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  41%|████      | 493/1200 [04:13<05:26,  2.16it/s]

Warning: File tcga_tnbc_data/fe340d79-53e7-445f-9041-82441df94d20_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  41%|████      | 494/1200 [04:13<05:11,  2.26it/s]

Warning: File tcga_tnbc_data/84f42bf5-32e7-4100-9297-87957839e9e3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  41%|████▏     | 495/1200 [04:13<04:59,  2.36it/s]

Warning: File tcga_tnbc_data/25235c94-211b-46bc-a535-caf93aa623b8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  41%|████▏     | 496/1200 [04:14<05:35,  2.10it/s]

Warning: File tcga_tnbc_data/5bfcb451-b898-45cc-82f5-93edbb475cf2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  41%|████▏     | 497/1200 [04:15<06:13,  1.88it/s]

Warning: File tcga_tnbc_data/b7b6e492-59b0-45f5-aaff-051c2cab5ee8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  42%|████▏     | 498/1200 [04:15<06:00,  1.95it/s]

Warning: File tcga_tnbc_data/22879c27-d2a7-43cb-bebf-4fb3379003d9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  42%|████▏     | 499/1200 [04:16<06:13,  1.88it/s]

Warning: File tcga_tnbc_data/5ca43c0a-c892-4137-9cd2-18440dc47b58_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  42%|████▏     | 500/1200 [04:16<05:39,  2.06it/s]

Warning: File tcga_tnbc_data/ab171a6f-37cf-4dca-aca7-d5ca314d2544_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  42%|████▏     | 501/1200 [04:17<05:38,  2.07it/s]

Warning: File tcga_tnbc_data/8efd6f4c-e92b-4070-9d7c-5f8b55748b37_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  42%|████▏     | 502/1200 [04:17<06:07,  1.90it/s]

Warning: File tcga_tnbc_data/419ef164-1ce1-4fca-ac2a-c25cf18d781a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  42%|████▏     | 503/1200 [04:18<06:18,  1.84it/s]

Warning: File tcga_tnbc_data/0195917c-c127-4523-aff3-9e64ebdd4363_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  42%|████▏     | 504/1200 [04:18<06:18,  1.84it/s]

Warning: File tcga_tnbc_data/3ca8d0a7-8ff7-4d4b-a02c-76c7f3a8d0b7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  42%|████▏     | 505/1200 [04:19<06:15,  1.85it/s]

Warning: File tcga_tnbc_data/73214437-dde3-4ade-a938-740f7a28a4c9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  42%|████▏     | 506/1200 [04:19<05:59,  1.93it/s]

Warning: File tcga_tnbc_data/7f73cf13-d6a3-4a76-a5db-aaac249bcdae_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  42%|████▏     | 507/1200 [04:20<05:46,  2.00it/s]

Warning: File tcga_tnbc_data/0bc57387-0234-446f-8956-b4410fa60c41_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  42%|████▏     | 508/1200 [04:20<05:43,  2.02it/s]

Warning: File tcga_tnbc_data/a9e1fe98-7705-4751-8565-178d78bfe746_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  42%|████▏     | 509/1200 [04:22<09:13,  1.25it/s]

Warning: File tcga_tnbc_data/70c6f3c1-a9a5-40fd-a39d-0fdb0d66da1f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  42%|████▎     | 510/1200 [04:22<08:09,  1.41it/s]

Warning: File tcga_tnbc_data/c980e8d4-d258-40e5-a173-34b2719bb3a9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  43%|████▎     | 511/1200 [04:23<07:30,  1.53it/s]

Warning: File tcga_tnbc_data/c5292827-2f32-47c7-9c4e-75aefa709891_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  43%|████▎     | 512/1200 [04:23<07:06,  1.61it/s]

Warning: File tcga_tnbc_data/2a4b70ba-9030-4b04-abe0-5fa59f99564c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  43%|████▎     | 513/1200 [04:24<06:41,  1.71it/s]

Warning: File tcga_tnbc_data/bd161fdd-1714-45cb-b8f8-f042a691e297_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  43%|████▎     | 514/1200 [04:24<06:25,  1.78it/s]

Warning: File tcga_tnbc_data/3e0ad2f4-16c0-4c3f-a5c5-414e4f495b48_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  43%|████▎     | 515/1200 [04:25<06:12,  1.84it/s]

Warning: File tcga_tnbc_data/a48b7fbd-3805-4b2c-8cfd-88eb601a1ffe_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  43%|████▎     | 516/1200 [04:25<06:11,  1.84it/s]

Warning: File tcga_tnbc_data/f9b88865-6e80-46ed-98aa-6d81ba5d4a02_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  43%|████▎     | 517/1200 [04:26<06:06,  1.86it/s]

Warning: File tcga_tnbc_data/8780c854-7eaf-42e9-a4cc-31222f8a3025_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  43%|████▎     | 518/1200 [04:26<05:41,  2.00it/s]

Warning: File tcga_tnbc_data/2da52905-3b53-44ea-86de-f05a8de372fb_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  43%|████▎     | 519/1200 [04:27<05:36,  2.02it/s]

Warning: File tcga_tnbc_data/e7cc6b48-f782-4392-a22a-04459bf8e703_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  43%|████▎     | 520/1200 [04:27<05:28,  2.07it/s]

Warning: File tcga_tnbc_data/04d6d73c-53fd-4146-a163-c4bac388172a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  43%|████▎     | 521/1200 [04:28<05:22,  2.11it/s]

Warning: File tcga_tnbc_data/0051d081-c264-4d60-b4fd-a203ef7ef087_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  44%|████▎     | 522/1200 [04:28<05:14,  2.15it/s]

Warning: File tcga_tnbc_data/b789f2c1-a793-41c3-80b1-781e3fe6dbca_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  44%|████▎     | 523/1200 [04:29<05:24,  2.09it/s]

Warning: File tcga_tnbc_data/f30f905d-0da0-43f8-9993-21325d1fb751_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  44%|████▎     | 524/1200 [04:29<05:19,  2.12it/s]

Warning: File tcga_tnbc_data/37409434-dc17-4345-96d8-5cd388d90166_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  44%|████▍     | 525/1200 [04:30<05:07,  2.19it/s]

Warning: File tcga_tnbc_data/22e11e8c-fab5-40ec-90cc-700be19c5d51_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  44%|████▍     | 526/1200 [04:30<04:59,  2.25it/s]

Warning: File tcga_tnbc_data/24a6594d-c21e-45e3-9863-f6b7e304f21c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  44%|████▍     | 527/1200 [04:30<04:42,  2.38it/s]

Warning: File tcga_tnbc_data/540e89bf-d79c-4916-af91-cf79307103ef_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  44%|████▍     | 528/1200 [04:31<04:51,  2.31it/s]

Warning: File tcga_tnbc_data/db7aa78b-4bb9-4d89-9219-bc93eaa277a2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  44%|████▍     | 529/1200 [04:31<05:01,  2.23it/s]

Warning: File tcga_tnbc_data/3a5aeb89-be94-40ea-a60c-10cbeb1f6350_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  44%|████▍     | 530/1200 [04:32<04:50,  2.31it/s]

Warning: File tcga_tnbc_data/c329df5e-f892-4e34-a575-947b80e0f6fa_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  44%|████▍     | 531/1200 [04:32<04:50,  2.30it/s]

Warning: File tcga_tnbc_data/70f8d4a3-81e0-4d82-860e-ae359c3cac74_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  44%|████▍     | 532/1200 [04:33<05:04,  2.19it/s]

Warning: File tcga_tnbc_data/07ff7aa3-a3be-44c0-89d8-c67a0dedcc72_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  44%|████▍     | 533/1200 [04:33<05:22,  2.07it/s]

Warning: File tcga_tnbc_data/aa4061d1-8b1e-4aed-b0d7-fe3a5466737e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  44%|████▍     | 534/1200 [04:34<05:34,  1.99it/s]

Warning: File tcga_tnbc_data/6f335026-6df0-43f8-8076-fb6534e4420f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  45%|████▍     | 535/1200 [04:34<05:27,  2.03it/s]

Warning: File tcga_tnbc_data/b08c42c0-9cea-46e3-b6c4-cd9cda5876ac_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  45%|████▍     | 536/1200 [04:35<05:03,  2.19it/s]

Warning: File tcga_tnbc_data/ab865a79-8928-4178-8aff-44a95e43e697_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  45%|████▍     | 537/1200 [04:35<05:03,  2.19it/s]

Warning: File tcga_tnbc_data/30b2fec5-69ef-48db-9d33-e35642818ad5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  45%|████▍     | 538/1200 [04:36<05:08,  2.14it/s]

Warning: File tcga_tnbc_data/6d779189-cfd2-48bf-ada2-ca78e2818468_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  45%|████▍     | 539/1200 [04:36<04:55,  2.24it/s]

Warning: File tcga_tnbc_data/21abffb3-3e07-4022-86ff-51a41036cfc4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  45%|████▌     | 540/1200 [04:36<05:08,  2.14it/s]

Warning: File tcga_tnbc_data/4805e3d7-409d-41c9-b7a8-12614c50d354_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  45%|████▌     | 541/1200 [04:37<05:07,  2.14it/s]

Warning: File tcga_tnbc_data/556a4611-3db1-4e35-a401-e598433fdac2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  45%|████▌     | 542/1200 [04:37<04:59,  2.19it/s]

Warning: File tcga_tnbc_data/21278eb3-c93c-4b8a-b68b-2dec7b9f9fa3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  45%|████▌     | 543/1200 [04:38<04:50,  2.26it/s]

Warning: File tcga_tnbc_data/bf53b78f-1699-40b5-a76c-fb4b6c7e0de0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  45%|████▌     | 544/1200 [04:38<04:46,  2.29it/s]

Warning: File tcga_tnbc_data/65da41a1-a2fc-40da-b171-8ce45d8fcacb_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  45%|████▌     | 545/1200 [04:39<04:56,  2.21it/s]

Warning: File tcga_tnbc_data/e35f3c2a-1324-4b50-9096-5e59cf80da93_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  46%|████▌     | 546/1200 [04:39<04:51,  2.24it/s]

Warning: File tcga_tnbc_data/be3ff5e3-0d0a-4e82-84a6-4dd238c8bf7b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  46%|████▌     | 547/1200 [04:40<04:54,  2.21it/s]

Warning: File tcga_tnbc_data/5ea3601c-639a-4e8a-8b71-9586e2d5ea83_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  46%|████▌     | 548/1200 [04:40<05:03,  2.15it/s]

Warning: File tcga_tnbc_data/d716a9e8-f98d-4bb4-8cea-9d8cbe3f9838_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  46%|████▌     | 549/1200 [04:40<04:59,  2.17it/s]

Warning: File tcga_tnbc_data/5a647051-a5d5-4188-8671-bf1784415255_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  46%|████▌     | 550/1200 [04:41<04:58,  2.18it/s]

Warning: File tcga_tnbc_data/eb0eec1c-042c-4eb7-a2e0-eb50b49855c6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  46%|████▌     | 551/1200 [04:41<04:56,  2.19it/s]

Warning: File tcga_tnbc_data/200e65f4-0bba-4133-b0fd-6c69faddc1cc_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  46%|████▌     | 552/1200 [04:42<04:55,  2.19it/s]

Warning: File tcga_tnbc_data/4a3061a6-2931-4c2a-b8b9-84540c256eb4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  46%|████▌     | 553/1200 [04:42<05:05,  2.12it/s]

Warning: File tcga_tnbc_data/2dc58f9b-608f-4df7-8459-6a0e84e3e893_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  46%|████▌     | 554/1200 [04:43<05:18,  2.03it/s]

Warning: File tcga_tnbc_data/5702e8ad-1336-440d-a415-9c08a127cbd0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  46%|████▋     | 555/1200 [04:43<05:17,  2.03it/s]

Warning: File tcga_tnbc_data/05f36336-c79f-45cf-bdde-1acda13d415b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  46%|████▋     | 556/1200 [04:44<04:57,  2.16it/s]

Warning: File tcga_tnbc_data/6318d1bc-6c5c-43db-896d-931f487e4f47_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  46%|████▋     | 557/1200 [04:44<05:04,  2.11it/s]

Warning: File tcga_tnbc_data/a594e827-49e5-47a1-b1cc-2c20a123a041_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  46%|████▋     | 558/1200 [04:45<05:15,  2.03it/s]

Warning: File tcga_tnbc_data/dec82b4e-cb99-4b98-b2f6-7cdd64749cd0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  47%|████▋     | 559/1200 [04:45<05:24,  1.98it/s]

Warning: File tcga_tnbc_data/077413d4-9233-4a64-ac64-ada12cd08dd5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  47%|████▋     | 560/1200 [04:46<05:15,  2.03it/s]

Warning: File tcga_tnbc_data/5fb51a01-4042-49bd-9c70-a5bb7b23dd36_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  47%|████▋     | 561/1200 [04:46<05:23,  1.97it/s]

Warning: File tcga_tnbc_data/6d853114-609f-4be9-8f62-bb3384df0302_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  47%|████▋     | 562/1200 [04:47<05:20,  1.99it/s]

Warning: File tcga_tnbc_data/ee84d78c-72dd-4b1d-ac4b-402c9b19d3c2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  47%|████▋     | 563/1200 [04:47<05:18,  2.00it/s]

Warning: File tcga_tnbc_data/127aed4a-3eee-4e1d-aafd-0ca61759856a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  47%|████▋     | 564/1200 [04:48<05:08,  2.06it/s]

Warning: File tcga_tnbc_data/3b7583b0-9f6c-48d6-b3af-e19832bf2d9f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  47%|████▋     | 565/1200 [04:48<05:01,  2.11it/s]

Warning: File tcga_tnbc_data/bfdfa11e-b19b-4ee5-bed0-227a627ab1f3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  47%|████▋     | 566/1200 [04:49<04:49,  2.19it/s]

Warning: File tcga_tnbc_data/149a17a7-398c-4bd9-a871-7ab9ef9e6879_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  47%|████▋     | 567/1200 [04:49<05:09,  2.05it/s]

Warning: File tcga_tnbc_data/788a05e5-5fee-4430-b303-d4bc30649158_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  47%|████▋     | 568/1200 [04:50<05:11,  2.03it/s]

Warning: File tcga_tnbc_data/18ed43a1-e364-4a61-83c7-4d62392e0aa0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  47%|████▋     | 569/1200 [04:50<04:59,  2.10it/s]

Warning: File tcga_tnbc_data/108e18d9-cb5a-47b3-99c0-0a13b0c4a2a4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  48%|████▊     | 570/1200 [04:51<05:02,  2.08it/s]

Warning: File tcga_tnbc_data/d0766295-77cb-446a-9ebe-4820f57a8d36_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  48%|████▊     | 571/1200 [04:51<05:07,  2.05it/s]

Warning: File tcga_tnbc_data/92ad661c-b2ed-40fe-9289-5213a97271a7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  48%|████▊     | 572/1200 [04:52<05:13,  2.01it/s]

Warning: File tcga_tnbc_data/24a2cd1a-ff32-4704-ae91-088c7a94de24_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  48%|████▊     | 573/1200 [04:52<05:05,  2.05it/s]

Warning: File tcga_tnbc_data/b4c62ca8-0393-43dc-b5e2-749c777f948d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  48%|████▊     | 574/1200 [04:53<05:15,  1.98it/s]

Warning: File tcga_tnbc_data/cd925bc2-7870-4fbd-829e-8797bd839539_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  48%|████▊     | 575/1200 [04:53<05:20,  1.95it/s]

Warning: File tcga_tnbc_data/707a22be-e7f0-4d3e-91d4-deb6e30628c0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  48%|████▊     | 576/1200 [04:54<05:32,  1.88it/s]

Warning: File tcga_tnbc_data/edc9e931-6c62-4e0e-9c68-b6891ba007ac_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  48%|████▊     | 577/1200 [04:54<05:09,  2.01it/s]

Warning: File tcga_tnbc_data/eae8feaf-bc9e-4718-901b-127598acb7d4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  48%|████▊     | 578/1200 [04:55<04:56,  2.10it/s]

Warning: File tcga_tnbc_data/44326a5f-517c-4e99-a8ac-eea1bdf44eeb_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  48%|████▊     | 579/1200 [04:55<05:04,  2.04it/s]

Warning: File tcga_tnbc_data/11158ce6-cd7a-4450-8b57-395270b20a70_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  48%|████▊     | 580/1200 [04:56<04:48,  2.15it/s]

Warning: File tcga_tnbc_data/1d47e720-1a02-45f4-b0dc-99861916e3e1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  48%|████▊     | 581/1200 [04:56<04:41,  2.20it/s]

Warning: File tcga_tnbc_data/5ce26b4c-f373-41f3-82a5-25917a1114b6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  48%|████▊     | 582/1200 [04:57<04:51,  2.12it/s]

Warning: File tcga_tnbc_data/370ffc60-025d-4127-a6b5-3559e8f8a01c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  49%|████▊     | 583/1200 [04:57<04:50,  2.13it/s]

Warning: File tcga_tnbc_data/e7d55838-b9ad-4147-8ad2-cbe0dd6d5f24_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  49%|████▊     | 584/1200 [04:58<05:15,  1.95it/s]

Warning: File tcga_tnbc_data/6403a752-012e-41da-a8a8-7baed9cd79fc_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  49%|████▉     | 585/1200 [04:58<05:18,  1.93it/s]

Warning: File tcga_tnbc_data/17b53839-6c06-48cd-8829-0dd7499eec4e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  49%|████▉     | 586/1200 [04:59<05:05,  2.01it/s]

Warning: File tcga_tnbc_data/88d0452c-0693-4572-9bfd-bd856805c7e9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  49%|████▉     | 587/1200 [04:59<05:21,  1.91it/s]

Warning: File tcga_tnbc_data/dee8967e-7a32-4338-9fb0-e2c7faa2d68f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  49%|████▉     | 588/1200 [05:00<05:09,  1.98it/s]

Warning: File tcga_tnbc_data/c1e1a3ff-caba-4adb-b8de-27d2a8ec3ec8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  49%|████▉     | 589/1200 [05:00<04:58,  2.05it/s]

Warning: File tcga_tnbc_data/c1646f76-5b5d-4d42-bf77-73ddccedd406_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  49%|████▉     | 590/1200 [05:00<04:37,  2.20it/s]

Warning: File tcga_tnbc_data/ece77ba5-55bd-4937-80de-834b8e6c873b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  49%|████▉     | 591/1200 [05:01<05:21,  1.89it/s]

Warning: File tcga_tnbc_data/9adf1983-85b9-4ef6-aff4-dea772ff91a2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  49%|████▉     | 592/1200 [05:02<05:22,  1.89it/s]

Warning: File tcga_tnbc_data/6d88ce71-ecd1-4edf-8935-ea9137ed1ef1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  49%|████▉     | 593/1200 [05:02<05:03,  2.00it/s]

Warning: File tcga_tnbc_data/ffcc91b1-b803-4dab-a98e-37f12f28be82_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  50%|████▉     | 594/1200 [05:03<05:05,  1.99it/s]

Warning: File tcga_tnbc_data/4b08af50-9a8f-48a8-9fd5-e4d3e963dabc_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  50%|████▉     | 595/1200 [05:03<05:16,  1.91it/s]

Warning: File tcga_tnbc_data/d4654d40-a23f-4a56-8079-211087e14dee_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  50%|████▉     | 596/1200 [05:04<05:15,  1.91it/s]

Warning: File tcga_tnbc_data/144c5bf9-5214-4911-a403-01f9b479ab63_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  50%|████▉     | 597/1200 [05:04<05:22,  1.87it/s]

Warning: File tcga_tnbc_data/430527bb-2cef-45ec-9e5b-831b46c0746d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  50%|████▉     | 598/1200 [05:05<05:05,  1.97it/s]

Warning: File tcga_tnbc_data/588e3a31-b4c2-41ed-bb23-5ffa1c150ec7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  50%|████▉     | 599/1200 [05:05<05:04,  1.97it/s]

Warning: File tcga_tnbc_data/1bb15d67-0bcb-4d29-b186-2d57a0247f64_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  50%|█████     | 600/1200 [05:06<05:12,  1.92it/s]

Warning: File tcga_tnbc_data/8da07768-f3a7-4529-b042-bf2648999e91_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  50%|█████     | 601/1200 [05:06<05:08,  1.94it/s]

Warning: File tcga_tnbc_data/28bfa617-bafe-40fe-ae7b-fca66584b7cf_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  50%|█████     | 602/1200 [05:07<05:02,  1.97it/s]

Warning: File tcga_tnbc_data/65126cbb-60a9-41d4-9fa5-6acd91bf53e1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  50%|█████     | 603/1200 [05:07<04:55,  2.02it/s]

Warning: File tcga_tnbc_data/b5992b43-9915-4cbf-b709-86a721fd69c9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  50%|█████     | 604/1200 [05:08<04:45,  2.09it/s]

Warning: File tcga_tnbc_data/cf9b4491-4660-4ff9-b539-ad435047a505_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  50%|█████     | 605/1200 [05:08<04:39,  2.13it/s]

Warning: File tcga_tnbc_data/2050e0d5-b6c3-4bbf-9cb9-942141a07b3f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  50%|█████     | 606/1200 [05:08<04:21,  2.27it/s]

Warning: File tcga_tnbc_data/50db711e-b2eb-4b33-ae9f-48ce6d860a48_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  51%|█████     | 607/1200 [05:09<04:37,  2.14it/s]

Warning: File tcga_tnbc_data/0821624f-7175-40ae-894f-3c68376b5788_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  51%|█████     | 608/1200 [05:10<04:42,  2.10it/s]

Warning: File tcga_tnbc_data/210b1a48-1be8-407d-8354-50c0c60d5192_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  51%|█████     | 609/1200 [05:10<04:50,  2.03it/s]

Warning: File tcga_tnbc_data/c4c8ab78-32a4-4bcc-842a-766bf5157590_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  51%|█████     | 610/1200 [05:11<04:44,  2.07it/s]

Warning: File tcga_tnbc_data/eb9b4f6f-ef2e-4bdb-b4c9-354ca9b30af6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  51%|█████     | 611/1200 [05:11<04:49,  2.04it/s]

Warning: File tcga_tnbc_data/d5da7109-ec9b-45b4-ae60-1c3bf898c0e3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  51%|█████     | 612/1200 [05:12<04:48,  2.04it/s]

Warning: File tcga_tnbc_data/0b64742b-b99d-4fc1-bfbf-bb7074f21a67_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  51%|█████     | 613/1200 [05:12<04:47,  2.04it/s]

Warning: File tcga_tnbc_data/33f500d7-0967-4bbf-9b40-d1d6ff8e3e3a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  51%|█████     | 614/1200 [05:12<04:39,  2.10it/s]

Warning: File tcga_tnbc_data/cb9d4ce8-c82d-450d-bcb2-e6a286cf1484_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  51%|█████▏    | 615/1200 [05:13<04:47,  2.04it/s]

Warning: File tcga_tnbc_data/1555aab1-9350-4c12-8929-4f124f092106_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  51%|█████▏    | 616/1200 [05:13<04:43,  2.06it/s]

Warning: File tcga_tnbc_data/b756ef91-c3f5-4ab6-8cd8-05024d0f9316_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  51%|█████▏    | 617/1200 [05:14<04:33,  2.13it/s]

Warning: File tcga_tnbc_data/3951e52f-ee5a-4a71-9ed3-a112c97cca84_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  52%|█████▏    | 618/1200 [05:14<04:41,  2.07it/s]

Warning: File tcga_tnbc_data/0fe319f2-7a4f-4732-a488-f96c9db8a0dd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  52%|█████▏    | 619/1200 [05:15<04:37,  2.09it/s]

Warning: File tcga_tnbc_data/c536d613-9665-4607-8984-cecf71915c6f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  52%|█████▏    | 620/1200 [05:15<04:42,  2.05it/s]

Warning: File tcga_tnbc_data/d72da257-f34f-4efa-b698-aecfc2702e8b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  52%|█████▏    | 621/1200 [05:16<04:44,  2.04it/s]

Warning: File tcga_tnbc_data/449981a9-490d-49b9-81f4-8bdea23131b2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  52%|█████▏    | 622/1200 [05:16<04:37,  2.08it/s]

Warning: File tcga_tnbc_data/3cdae844-cac7-483a-aa41-cf58f7e958b6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  52%|█████▏    | 623/1200 [05:17<04:42,  2.04it/s]

Warning: File tcga_tnbc_data/50f47c84-b9e0-4d29-9e0c-7880432ef1d6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  52%|█████▏    | 624/1200 [05:17<04:48,  1.99it/s]

Warning: File tcga_tnbc_data/b0db14c6-8cc3-4950-8ce9-fac9d5e6d666_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  52%|█████▏    | 625/1200 [05:18<04:55,  1.94it/s]

Warning: File tcga_tnbc_data/b1e9cb2b-97ea-46b0-8d25-281843c50161_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  52%|█████▏    | 626/1200 [05:18<04:31,  2.11it/s]

Warning: File tcga_tnbc_data/814322ed-016a-4af6-b976-5a5a9a192f5d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  52%|█████▏    | 627/1200 [05:19<04:21,  2.19it/s]

Warning: File tcga_tnbc_data/4e60fda1-4bbe-4901-987d-6c15a87af886_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  52%|█████▏    | 628/1200 [05:19<04:27,  2.14it/s]

Warning: File tcga_tnbc_data/0b85120a-29ec-4948-9eb3-dbea5709cb31_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  52%|█████▏    | 629/1200 [05:20<04:31,  2.10it/s]

Warning: File tcga_tnbc_data/a3057594-7806-45d2-a92f-4b9f08fcc693_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  52%|█████▎    | 630/1200 [05:20<04:30,  2.10it/s]

Warning: File tcga_tnbc_data/e9eabd40-b997-417b-acf5-308e53803efc_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  53%|█████▎    | 631/1200 [05:21<04:26,  2.13it/s]

Warning: File tcga_tnbc_data/e1271843-3bd3-4f0b-8e6f-fc763ad65776_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  53%|█████▎    | 632/1200 [05:21<04:36,  2.05it/s]

Warning: File tcga_tnbc_data/9e246750-a285-4921-8134-4043d0d69efd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  53%|█████▎    | 633/1200 [05:22<04:26,  2.12it/s]

Warning: File tcga_tnbc_data/68137729-ef44-49c5-8bf0-2ff049162836_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  53%|█████▎    | 634/1200 [05:22<04:18,  2.19it/s]

Warning: File tcga_tnbc_data/782d5e4e-ad23-4ac8-8654-eb52bbc44f21_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  53%|█████▎    | 635/1200 [05:23<04:42,  2.00it/s]

Warning: File tcga_tnbc_data/23bc21ba-4d55-4f64-9bfb-8d0fc4c12c1a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  53%|█████▎    | 636/1200 [05:23<04:51,  1.93it/s]

Warning: File tcga_tnbc_data/4ef1bf1a-e6a4-4d0d-a84b-f0e742c09d8e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  53%|█████▎    | 637/1200 [05:24<04:29,  2.09it/s]

Warning: File tcga_tnbc_data/f139456f-3158-4ac4-8c60-454aa1c41861_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  53%|█████▎    | 638/1200 [05:24<04:54,  1.91it/s]

Warning: File tcga_tnbc_data/3cb4c6d3-ee1b-4869-9ffa-df20bfb95c77_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  53%|█████▎    | 639/1200 [05:25<05:07,  1.83it/s]

Warning: File tcga_tnbc_data/907d0887-5984-4d5e-8d5b-1a7ad1d53572_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  53%|█████▎    | 640/1200 [05:25<04:49,  1.93it/s]

Warning: File tcga_tnbc_data/7329ec19-7624-4c7c-9622-e6785ee4be09_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  53%|█████▎    | 641/1200 [05:26<04:42,  1.98it/s]

Warning: File tcga_tnbc_data/1658fd3a-39c9-4213-b97b-f87d04c603f8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  54%|█████▎    | 642/1200 [05:26<04:39,  1.99it/s]

Warning: File tcga_tnbc_data/ddcfa2c6-4647-4606-8b94-7ce79db9218e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  54%|█████▎    | 643/1200 [05:27<04:33,  2.04it/s]

Warning: File tcga_tnbc_data/0e35c4f4-0da9-4e46-a30b-8d73d57ccf76_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  54%|█████▎    | 644/1200 [05:27<04:36,  2.01it/s]

Warning: File tcga_tnbc_data/ec09d84c-1112-4530-a320-a99043794fe3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  54%|█████▍    | 645/1200 [05:28<04:41,  1.97it/s]

Warning: File tcga_tnbc_data/8753cc4b-0f5d-409a-a3b2-acf39fc7358b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  54%|█████▍    | 646/1200 [05:28<04:30,  2.05it/s]

Warning: File tcga_tnbc_data/84d67cc6-c004-4ae1-ba4c-565ee4646c1b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  54%|█████▍    | 647/1200 [05:29<04:26,  2.07it/s]

Warning: File tcga_tnbc_data/33a8226d-4908-42a2-a82a-8abc1abb23a8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  54%|█████▍    | 648/1200 [05:29<04:47,  1.92it/s]

Warning: File tcga_tnbc_data/016db033-3cec-4c63-b90f-0428da475a63_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  54%|█████▍    | 649/1200 [05:30<04:28,  2.05it/s]

Warning: File tcga_tnbc_data/bd5873b0-4c3c-4aba-987e-0730145d5ea1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  54%|█████▍    | 650/1200 [05:30<04:29,  2.04it/s]

Warning: File tcga_tnbc_data/4aa26af5-b589-49f4-ab6f-e00fda1ea56c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  54%|█████▍    | 651/1200 [05:31<04:29,  2.04it/s]

Warning: File tcga_tnbc_data/37485572-281d-4f54-b0b1-b104b7730d21_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  54%|█████▍    | 652/1200 [05:31<04:27,  2.05it/s]

Warning: File tcga_tnbc_data/730430cc-52a2-43c9-b919-549bb68eab69_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  54%|█████▍    | 653/1200 [05:32<04:23,  2.07it/s]

Warning: File tcga_tnbc_data/9a8b5955-c2ed-485b-ac13-9042c1adf631_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  55%|█████▍    | 654/1200 [05:32<04:22,  2.08it/s]

Warning: File tcga_tnbc_data/6759accf-5027-4673-aea5-f5b8171ba2c2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  55%|█████▍    | 655/1200 [05:33<04:33,  1.99it/s]

Warning: File tcga_tnbc_data/2683fb0e-6a84-4bff-a327-64cfb2dc3308_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  55%|█████▍    | 656/1200 [05:33<04:46,  1.90it/s]

Warning: File tcga_tnbc_data/5478889a-c160-472a-9c42-791c2e4da271_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  55%|█████▍    | 657/1200 [05:34<04:34,  1.98it/s]

Warning: File tcga_tnbc_data/309f6763-b665-495e-91b2-07007d5cdf04_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  55%|█████▍    | 658/1200 [05:34<04:25,  2.05it/s]

Warning: File tcga_tnbc_data/1d1d18b8-76d7-473e-bfc5-06d0a4f53a5d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  55%|█████▍    | 659/1200 [05:35<04:18,  2.10it/s]

Warning: File tcga_tnbc_data/1871694f-863b-4483-8157-8aa0ddfdda5e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  55%|█████▌    | 660/1200 [05:35<04:23,  2.05it/s]

Warning: File tcga_tnbc_data/7076d394-c6a7-4e0e-b728-842fdaf4af34_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  55%|█████▌    | 661/1200 [05:36<04:44,  1.89it/s]

Warning: File tcga_tnbc_data/cd5d99fe-041b-44c2-a01b-d860e35620d8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  55%|█████▌    | 662/1200 [05:36<04:40,  1.92it/s]

Warning: File tcga_tnbc_data/cb163fe6-e7d4-4c3f-b110-2920fa5ef95c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  55%|█████▌    | 663/1200 [05:37<04:36,  1.94it/s]

Warning: File tcga_tnbc_data/10273809-ad79-4848-a896-03f0cefe6861_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  55%|█████▌    | 664/1200 [05:37<04:35,  1.95it/s]

Warning: File tcga_tnbc_data/5ef0522a-89f3-4fb9-a9e1-dc8129d4a73d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  55%|█████▌    | 665/1200 [05:38<04:35,  1.94it/s]

Warning: File tcga_tnbc_data/d1d2e357-2dbf-4878-ac40-cf3b12d0aea4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  56%|█████▌    | 666/1200 [05:38<04:22,  2.03it/s]

Warning: File tcga_tnbc_data/9c1ea2bf-d320-44f8-832d-a831d8689c6e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  56%|█████▌    | 667/1200 [05:39<04:29,  1.98it/s]

Warning: File tcga_tnbc_data/fc8e0387-e751-4595-8c61-650e808da79b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  56%|█████▌    | 668/1200 [05:39<04:16,  2.08it/s]

Warning: File tcga_tnbc_data/9ba501e5-2be7-4edc-bbff-f6604ccb0692_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  56%|█████▌    | 669/1200 [05:40<04:17,  2.06it/s]

Warning: File tcga_tnbc_data/3cdba1e4-b7d4-47ea-8cae-68a8262515d4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  56%|█████▌    | 670/1200 [05:40<04:28,  1.98it/s]

Warning: File tcga_tnbc_data/c9f05d9f-4146-48bc-a562-5bad1bcb7293_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  56%|█████▌    | 671/1200 [05:41<04:27,  1.97it/s]

Warning: File tcga_tnbc_data/5c3861de-66cf-4e2d-95dd-931cee332666_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  56%|█████▌    | 672/1200 [05:41<04:10,  2.11it/s]

Warning: File tcga_tnbc_data/835c40ea-a4e1-44fc-82cd-31e3ac16415f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  56%|█████▌    | 673/1200 [05:42<04:21,  2.02it/s]

Warning: File tcga_tnbc_data/d91020aa-3661-4b53-bbe4-e9677678736b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  56%|█████▌    | 674/1200 [05:42<04:23,  1.99it/s]

Warning: File tcga_tnbc_data/ca97a614-bab8-4bdc-a663-2d6a81ae4c27_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  56%|█████▋    | 675/1200 [05:43<04:21,  2.01it/s]

Warning: File tcga_tnbc_data/ed32fcea-aa43-45e1-a20a-4942541ffccc_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  56%|█████▋    | 676/1200 [05:43<04:21,  2.00it/s]

Warning: File tcga_tnbc_data/4df97655-744a-405b-864d-1ed885a3c733_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  56%|█████▋    | 677/1200 [05:44<04:17,  2.03it/s]

Warning: File tcga_tnbc_data/a8f5ecb5-ec0f-4320-a7d3-218ab6d31b1a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  56%|█████▋    | 678/1200 [05:44<04:47,  1.82it/s]

Warning: File tcga_tnbc_data/bd884fbc-b8ad-4c27-8eb7-6202db49afec_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  57%|█████▋    | 679/1200 [05:45<04:34,  1.90it/s]

Warning: File tcga_tnbc_data/d2af75f6-2380-445c-8f54-e047c23e14e0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  57%|█████▋    | 680/1200 [05:45<04:20,  2.00it/s]

Warning: File tcga_tnbc_data/8d926fd8-ee4a-4edb-b875-cc3aaf96d1f7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  57%|█████▋    | 681/1200 [05:46<04:03,  2.13it/s]

Warning: File tcga_tnbc_data/d1b27d3f-a10c-4deb-acb7-9acb80815786_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  57%|█████▋    | 682/1200 [05:46<03:57,  2.18it/s]

Warning: File tcga_tnbc_data/0fdeab95-dd48-4523-87d5-76b1958f454c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  57%|█████▋    | 683/1200 [05:47<04:00,  2.15it/s]

Warning: File tcga_tnbc_data/5df1ba0e-a83f-4793-a880-0219a7250858_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  57%|█████▋    | 684/1200 [05:47<03:50,  2.24it/s]

Warning: File tcga_tnbc_data/95863f78-6d63-4de0-a42f-f4d8156e2a33_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  57%|█████▋    | 685/1200 [05:47<04:07,  2.08it/s]

Warning: File tcga_tnbc_data/119c02f2-2951-492e-bbe1-1e7120ec4a84_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  57%|█████▋    | 686/1200 [05:48<04:03,  2.11it/s]

Warning: File tcga_tnbc_data/bea553f4-ca68-4af4-9595-8259b556a2a2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  57%|█████▋    | 687/1200 [05:48<04:15,  2.01it/s]

Warning: File tcga_tnbc_data/56dc7cfa-903d-413b-84f8-12a3279889cd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  57%|█████▋    | 688/1200 [05:49<04:01,  2.12it/s]

Warning: File tcga_tnbc_data/2d2554be-a947-4b7c-90b8-be1b4a0bd943_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  57%|█████▋    | 689/1200 [05:49<04:04,  2.09it/s]

Warning: File tcga_tnbc_data/3d53785d-0e73-40d1-a6f5-644fe778417c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  57%|█████▊    | 690/1200 [05:50<03:53,  2.18it/s]

Warning: File tcga_tnbc_data/ecc9276a-f900-431c-a6e2-2ce7a1d62215_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  58%|█████▊    | 691/1200 [05:50<04:08,  2.05it/s]

Warning: File tcga_tnbc_data/af02f1d4-47ea-4b53-a7e6-1f966a5be07b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  58%|█████▊    | 692/1200 [05:51<04:15,  1.99it/s]

Warning: File tcga_tnbc_data/31894502-e558-4758-9bf6-1181ccb38412_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  58%|█████▊    | 693/1200 [05:51<04:00,  2.10it/s]

Warning: File tcga_tnbc_data/7019c592-f43b-43f8-b585-59173ad5c169_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  58%|█████▊    | 694/1200 [05:52<04:00,  2.11it/s]

Warning: File tcga_tnbc_data/a44c536a-f222-44e7-87f4-e63968b2017b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  58%|█████▊    | 695/1200 [05:52<03:44,  2.25it/s]

Warning: File tcga_tnbc_data/6ec4701f-1ed3-47c7-925a-5325a632eb1c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  58%|█████▊    | 696/1200 [05:53<03:54,  2.15it/s]

Warning: File tcga_tnbc_data/fdb89f96-3def-4855-884d-15da0853dd3a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  58%|█████▊    | 697/1200 [05:53<03:59,  2.10it/s]

Warning: File tcga_tnbc_data/92c40bfa-1683-461e-bac4-6f573534d2e6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  58%|█████▊    | 698/1200 [05:54<03:52,  2.16it/s]

Warning: File tcga_tnbc_data/83b2db75-facd-476a-ad40-6181717b928c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  58%|█████▊    | 699/1200 [05:54<03:46,  2.22it/s]

Warning: File tcga_tnbc_data/a607c74a-4ed5-4e2b-bf5b-3cc9e3214335_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  58%|█████▊    | 700/1200 [05:55<04:09,  2.01it/s]

Warning: File tcga_tnbc_data/14d1d18c-15e4-4cf1-b54e-131b7142d0cc_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  58%|█████▊    | 701/1200 [05:55<04:00,  2.07it/s]

Warning: File tcga_tnbc_data/aa94ebe3-13f3-40e6-98ee-4829309d819c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  58%|█████▊    | 702/1200 [05:55<03:45,  2.21it/s]

Warning: File tcga_tnbc_data/1c311e03-46af-4c35-978b-cbbd8fa725e9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  59%|█████▊    | 703/1200 [05:56<03:39,  2.27it/s]

Warning: File tcga_tnbc_data/64108f0b-a375-48f7-8f3d-cd024f622fe4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  59%|█████▊    | 704/1200 [05:56<03:57,  2.09it/s]

Warning: File tcga_tnbc_data/151cfaa5-f363-4988-9c12-551274545a26_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  59%|█████▉    | 705/1200 [05:57<03:50,  2.15it/s]

Warning: File tcga_tnbc_data/2ebe4258-3d6c-4753-9f3e-461653894107_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  59%|█████▉    | 706/1200 [05:57<03:58,  2.07it/s]

Warning: File tcga_tnbc_data/dad4f7b3-abcd-4dbc-8787-ea7c95450bff_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  59%|█████▉    | 707/1200 [05:58<04:08,  1.98it/s]

Warning: File tcga_tnbc_data/36091e7d-21aa-4471-bd96-8fd4d93c03ff_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  59%|█████▉    | 708/1200 [05:58<04:02,  2.03it/s]

Warning: File tcga_tnbc_data/7bc80f15-89d8-40e6-9a90-d320ca43e2c3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  59%|█████▉    | 709/1200 [05:59<03:48,  2.15it/s]

Warning: File tcga_tnbc_data/27ec5c6e-6119-474a-bb61-8d1310d1551b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  59%|█████▉    | 710/1200 [05:59<04:01,  2.03it/s]

Warning: File tcga_tnbc_data/069ed9fe-e992-43e8-993f-05bb474ace15_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  59%|█████▉    | 711/1200 [06:00<03:53,  2.09it/s]

Warning: File tcga_tnbc_data/45fe6130-71bb-4e1e-921c-61cdefc003ac_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  59%|█████▉    | 712/1200 [06:00<03:55,  2.07it/s]

Warning: File tcga_tnbc_data/b7c318d9-5739-4a47-b19c-428f5f1223ac_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  59%|█████▉    | 713/1200 [06:01<04:29,  1.81it/s]

Warning: File tcga_tnbc_data/ba9e1358-b0f0-49d3-8c53-21c7cf812589_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  60%|█████▉    | 714/1200 [06:02<04:24,  1.84it/s]

Warning: File tcga_tnbc_data/0173d27e-ff23-42b2-afb9-9b867ace3efc_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  60%|█████▉    | 715/1200 [06:02<04:11,  1.93it/s]

Warning: File tcga_tnbc_data/93a287f1-02ac-4023-a8d5-88e188b65168_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  60%|█████▉    | 716/1200 [06:03<04:10,  1.93it/s]

Warning: File tcga_tnbc_data/1cbd6458-7371-4a79-b4a9-e32894d0fa32_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  60%|█████▉    | 717/1200 [06:03<04:08,  1.94it/s]

Warning: File tcga_tnbc_data/b2c1efd2-e611-4dc8-bde7-cb6c2286fdaf_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  60%|█████▉    | 718/1200 [06:04<04:05,  1.96it/s]

Warning: File tcga_tnbc_data/ca7a1993-022c-4734-ab71-33ff5cba2179_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  60%|█████▉    | 719/1200 [06:04<04:01,  1.99it/s]

Warning: File tcga_tnbc_data/b16e4a88-6d23-479b-a68c-c4d7c3a16725_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  60%|██████    | 720/1200 [06:04<03:50,  2.09it/s]

Warning: File tcga_tnbc_data/17433796-a04c-46d5-a01c-b8c073504b5d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  60%|██████    | 721/1200 [06:05<03:34,  2.23it/s]

Warning: File tcga_tnbc_data/d6ffd7b8-7dd4-4342-8e0f-ccef57b16921_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  60%|██████    | 722/1200 [06:05<03:42,  2.15it/s]

Warning: File tcga_tnbc_data/4d4bb419-1f68-4c6e-92dc-bcfc0cc7c8e8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  60%|██████    | 723/1200 [06:06<03:47,  2.10it/s]

Warning: File tcga_tnbc_data/70a0fb72-e7ca-4fe5-8eed-7377dfc26b0c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  60%|██████    | 724/1200 [06:06<03:47,  2.09it/s]

Warning: File tcga_tnbc_data/2a30b4b5-e925-469c-8555-9cc602ea4e1f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  60%|██████    | 725/1200 [06:07<03:57,  2.00it/s]

Warning: File tcga_tnbc_data/17b9eed9-f422-4589-984d-800667aed1e7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  60%|██████    | 726/1200 [06:07<03:49,  2.07it/s]

Warning: File tcga_tnbc_data/ed3fd3e3-1b78-4a4f-8419-f4111c8c5c73_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  61%|██████    | 727/1200 [06:08<03:40,  2.14it/s]

Warning: File tcga_tnbc_data/5608dff0-72ab-468c-b25f-d411ad581052_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  61%|██████    | 728/1200 [06:08<03:39,  2.15it/s]

Warning: File tcga_tnbc_data/b9b73947-3920-4ef1-b6e9-c9481506face_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  61%|██████    | 729/1200 [06:09<03:48,  2.06it/s]

Warning: File tcga_tnbc_data/2e5887ce-ef0e-4d35-bb09-f84e6a4aeb77_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  61%|██████    | 730/1200 [06:09<03:46,  2.07it/s]

Warning: File tcga_tnbc_data/776ac485-6c96-4296-a988-ae6d160dd5b0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  61%|██████    | 731/1200 [06:10<03:57,  1.97it/s]

Warning: File tcga_tnbc_data/054d6883-9f0f-451e-a26d-cf0ff741afa4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  61%|██████    | 732/1200 [06:10<03:57,  1.97it/s]

Warning: File tcga_tnbc_data/22e40c6d-3f1d-434d-91ef-345cefd28983_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  61%|██████    | 733/1200 [06:11<03:48,  2.04it/s]

Warning: File tcga_tnbc_data/7fdf1402-fbd8-4d8e-9b84-e4a01495f3f8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  61%|██████    | 734/1200 [06:11<04:04,  1.91it/s]

Warning: File tcga_tnbc_data/74a7b430-ec80-47aa-95ed-7d202b72219b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  61%|██████▏   | 735/1200 [06:12<04:08,  1.87it/s]

Warning: File tcga_tnbc_data/4054a92c-e4c6-4742-99fc-2e9bc0b99ed5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  61%|██████▏   | 736/1200 [06:12<04:14,  1.82it/s]

Warning: File tcga_tnbc_data/671eaa5a-e0a3-4a53-8e38-ad77f217392f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  61%|██████▏   | 737/1200 [06:13<03:55,  1.96it/s]

Warning: File tcga_tnbc_data/0e15a5e4-5022-4efb-aef9-006b58911d27_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  62%|██████▏   | 738/1200 [06:13<04:01,  1.91it/s]

Warning: File tcga_tnbc_data/0759b027-a95e-4679-9262-cd32edbc9490_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  62%|██████▏   | 739/1200 [06:14<04:19,  1.77it/s]

Warning: File tcga_tnbc_data/e793b2cf-64db-413d-a40f-f64b4c338a78_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  62%|██████▏   | 740/1200 [06:15<04:15,  1.80it/s]

Warning: File tcga_tnbc_data/66f0a441-0bfb-49bf-a0a4-5e93b0177ce7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  62%|██████▏   | 741/1200 [06:15<03:57,  1.93it/s]

Warning: File tcga_tnbc_data/5104c30b-e7ca-4851-b766-53d2a60f6ce3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  62%|██████▏   | 742/1200 [06:16<04:04,  1.87it/s]

Warning: File tcga_tnbc_data/bc297e83-d1dc-4b87-b998-113423d686ca_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  62%|██████▏   | 743/1200 [06:16<03:59,  1.91it/s]

Warning: File tcga_tnbc_data/11b8df13-22dd-4ca1-a819-a5c350b80e63_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  62%|██████▏   | 744/1200 [06:17<04:03,  1.87it/s]

Warning: File tcga_tnbc_data/7d7a0a60-4b39-4f65-8037-9958f3b57440_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  62%|██████▏   | 745/1200 [06:17<04:04,  1.86it/s]

Warning: File tcga_tnbc_data/cc577b93-2d1c-4c35-9cde-47db994d2291_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  62%|██████▏   | 746/1200 [06:18<03:44,  2.02it/s]

Warning: File tcga_tnbc_data/424e28df-38e0-4fdd-a93a-f1d9b002a531_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  62%|██████▏   | 747/1200 [06:18<03:56,  1.92it/s]

Warning: File tcga_tnbc_data/a626fa2c-5e31-4504-a993-7f86aa21e8ab_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  62%|██████▏   | 748/1200 [06:19<03:56,  1.91it/s]

Warning: File tcga_tnbc_data/e3cae4c0-0f6a-4410-981f-165ae9aca8d5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  62%|██████▏   | 749/1200 [06:19<04:13,  1.78it/s]

Warning: File tcga_tnbc_data/fa81b241-f229-417e-8aa2-d2b1e5534561_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  62%|██████▎   | 750/1200 [06:20<04:02,  1.86it/s]

Warning: File tcga_tnbc_data/2c4770c9-01db-4f5e-b392-fca2d1c0ddcb_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  63%|██████▎   | 751/1200 [06:20<03:42,  2.02it/s]

Warning: File tcga_tnbc_data/5d9329e4-070b-455b-aedf-a1cc9a7dfdc2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  63%|██████▎   | 752/1200 [06:21<03:38,  2.05it/s]

Warning: File tcga_tnbc_data/dc16a8f2-01b0-4b62-8e4c-257314158169_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  63%|██████▎   | 753/1200 [06:21<03:44,  1.99it/s]

Warning: File tcga_tnbc_data/0a3a4c10-211c-48bf-9efb-e35cdfdac8f1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  63%|██████▎   | 754/1200 [06:22<03:46,  1.97it/s]

Warning: File tcga_tnbc_data/9691b06a-1a16-4616-b7e3-031792fbc0bd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  63%|██████▎   | 755/1200 [06:22<03:37,  2.05it/s]

Warning: File tcga_tnbc_data/0fbaa6ef-4d9d-4c95-a918-51500b9462b0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  63%|██████▎   | 756/1200 [06:23<03:36,  2.05it/s]

Warning: File tcga_tnbc_data/e5e500b0-8c8c-4c5d-b59b-476aa4f59575_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  63%|██████▎   | 757/1200 [06:23<03:38,  2.03it/s]

Warning: File tcga_tnbc_data/2a88609a-c32d-47a2-9fb0-10a1684dc883_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  63%|██████▎   | 758/1200 [06:24<03:21,  2.19it/s]

Warning: File tcga_tnbc_data/79252e70-e36c-4faa-96d7-7ce792ebf278_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  63%|██████▎   | 759/1200 [06:24<03:43,  1.97it/s]

Warning: File tcga_tnbc_data/a31942b6-0477-483f-8852-28d4b638ef65_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  63%|██████▎   | 760/1200 [06:25<03:37,  2.02it/s]

Warning: File tcga_tnbc_data/bc30ca6a-982b-4ba1-85a2-2e4adeba535a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  63%|██████▎   | 761/1200 [06:25<03:37,  2.02it/s]

Warning: File tcga_tnbc_data/e02c1321-88a2-43f5-9203-a56454e346df_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  64%|██████▎   | 762/1200 [06:26<03:20,  2.19it/s]

Warning: File tcga_tnbc_data/1a7c071e-3191-4766-9b2f-df1d2c5f46c7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  64%|██████▎   | 763/1200 [06:26<03:14,  2.24it/s]

Warning: File tcga_tnbc_data/ebb55c2b-057d-44f5-819b-df9dd596abdc_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  64%|██████▎   | 764/1200 [06:26<03:07,  2.32it/s]

Warning: File tcga_tnbc_data/abf531dc-e45a-471c-841f-7353c8fa8e8d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  64%|██████▍   | 765/1200 [06:27<03:21,  2.16it/s]

Warning: File tcga_tnbc_data/3d914f61-568a-4f5c-a97a-54be972c5e5f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  64%|██████▍   | 766/1200 [06:27<03:26,  2.10it/s]

Warning: File tcga_tnbc_data/33363284-aff9-4015-93c6-b94c39072073_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  64%|██████▍   | 767/1200 [06:28<03:23,  2.13it/s]

Warning: File tcga_tnbc_data/8be946ee-7395-42d4-af82-2d16b09b786d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  64%|██████▍   | 768/1200 [06:28<03:18,  2.18it/s]

Warning: File tcga_tnbc_data/99a16f47-f03b-4693-ac8d-a4653acf34d7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  64%|██████▍   | 769/1200 [06:29<03:35,  2.00it/s]

Warning: File tcga_tnbc_data/2cfde9cb-f746-4f70-b21d-d00ccb8f4d9b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  64%|██████▍   | 770/1200 [06:29<03:26,  2.08it/s]

Warning: File tcga_tnbc_data/e12941b0-d83c-4adf-9e8b-d48c5ddb67ed_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  64%|██████▍   | 771/1200 [06:30<03:15,  2.19it/s]

Warning: File tcga_tnbc_data/1022aa8a-ff64-4756-b20f-43a12a53efc1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  64%|██████▍   | 772/1200 [06:30<03:18,  2.16it/s]

Warning: File tcga_tnbc_data/03ff76ae-9b3e-40c5-87db-f13b7f520afb_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  64%|██████▍   | 773/1200 [06:31<03:27,  2.06it/s]

Warning: File tcga_tnbc_data/98fe188d-1922-4a7d-adc4-8dee37d92b4c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  64%|██████▍   | 774/1200 [06:31<03:26,  2.06it/s]

Warning: File tcga_tnbc_data/2184f692-a3ba-45c3-baf4-734fd4332f35_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  65%|██████▍   | 775/1200 [06:32<03:26,  2.06it/s]

Warning: File tcga_tnbc_data/c7302dc6-6512-415f-b26a-b6aa895a6cd7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  65%|██████▍   | 776/1200 [06:32<03:27,  2.04it/s]

Warning: File tcga_tnbc_data/0f9833f9-3923-46cc-ac42-506c5e9e635f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  65%|██████▍   | 777/1200 [06:33<03:34,  1.97it/s]

Warning: File tcga_tnbc_data/5533da9b-bc5b-4538-80d6-2d8aea2ba6a0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  65%|██████▍   | 778/1200 [06:33<03:27,  2.04it/s]

Warning: File tcga_tnbc_data/638641a8-0302-4d39-b7f5-edd00034e37b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  65%|██████▍   | 779/1200 [06:34<03:18,  2.12it/s]

Warning: File tcga_tnbc_data/2c658173-1941-45fe-baf5-ab67dfbcdfff_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  65%|██████▌   | 780/1200 [06:34<03:27,  2.03it/s]

Warning: File tcga_tnbc_data/7b337d83-0838-44f5-84d6-bf8376613c75_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  65%|██████▌   | 781/1200 [06:35<03:26,  2.02it/s]

Warning: File tcga_tnbc_data/05f65c8f-273a-4e14-9ba4-269c48dd5d0a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  65%|██████▌   | 782/1200 [06:35<03:23,  2.05it/s]

Warning: File tcga_tnbc_data/beac6749-18b8-43df-bc3b-32c3d3504eaa_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  65%|██████▌   | 783/1200 [06:36<03:19,  2.09it/s]

Warning: File tcga_tnbc_data/ef99ae23-c33f-49f4-9757-7bb6d944b622_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  65%|██████▌   | 784/1200 [06:36<03:14,  2.14it/s]

Warning: File tcga_tnbc_data/7d2b66f6-b6e4-4c5a-9694-39b1939680ac_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  65%|██████▌   | 785/1200 [06:36<03:01,  2.29it/s]

Warning: File tcga_tnbc_data/dd81dd2f-0be1-4507-b931-9cc2b197b9f8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  66%|██████▌   | 786/1200 [06:37<03:20,  2.06it/s]

Warning: File tcga_tnbc_data/c2cf4ba8-f4c8-4be0-b61a-2e3bd8119638_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  66%|██████▌   | 787/1200 [06:38<03:39,  1.88it/s]

Warning: File tcga_tnbc_data/f57b8cf0-2fd6-4b16-a2be-e9b48a86ae97_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  66%|██████▌   | 788/1200 [06:38<03:35,  1.91it/s]

Warning: File tcga_tnbc_data/0a74fef1-f136-4f66-8682-d5dc0a6e06ab_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  66%|██████▌   | 789/1200 [06:39<03:44,  1.83it/s]

Warning: File tcga_tnbc_data/0dfa1f7b-98f0-459e-b3bb-29ac447bee53_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  66%|██████▌   | 790/1200 [06:39<03:38,  1.88it/s]

Warning: File tcga_tnbc_data/6f2d4c85-893f-40ed-8ec1-a03b53ec59c1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  66%|██████▌   | 791/1200 [06:40<03:26,  1.99it/s]

Warning: File tcga_tnbc_data/8b18c127-13dc-4ca5-b3e8-38ccbd21b010_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  66%|██████▌   | 792/1200 [06:40<03:34,  1.90it/s]

Warning: File tcga_tnbc_data/e3bffebc-79c8-4cee-bad7-c7245a1ae50c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  66%|██████▌   | 793/1200 [06:41<03:31,  1.93it/s]

Warning: File tcga_tnbc_data/6a044464-d09f-4b9b-8df6-e0bfd78f455e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  66%|██████▌   | 794/1200 [06:41<03:08,  2.16it/s]

Warning: File tcga_tnbc_data/d51d209c-1403-49e9-a9b7-3c36659b64a9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  66%|██████▋   | 795/1200 [06:42<03:10,  2.12it/s]

Warning: File tcga_tnbc_data/a77b6765-6e36-4909-9cd3-90cd4efb8c6e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  66%|██████▋   | 796/1200 [06:42<03:20,  2.02it/s]

Warning: File tcga_tnbc_data/ff5b35ac-1ea0-49b7-8156-0f44760b7ee8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  66%|██████▋   | 797/1200 [06:43<03:11,  2.11it/s]

Warning: File tcga_tnbc_data/355ae847-d5f0-43ab-90e6-920c6ef8711c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  66%|██████▋   | 798/1200 [06:43<03:00,  2.22it/s]

Warning: File tcga_tnbc_data/d215fc19-0c97-46e1-946f-a293d95f581b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  67%|██████▋   | 799/1200 [06:44<03:23,  1.98it/s]

Warning: File tcga_tnbc_data/e09d0370-46e4-41ea-9fa4-7f0a39195507_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  67%|██████▋   | 800/1200 [06:44<03:20,  2.00it/s]

Warning: File tcga_tnbc_data/8e6ba6ce-5f0b-424d-bf39-2b2bf2f9adf7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  67%|██████▋   | 801/1200 [06:45<03:16,  2.03it/s]

Warning: File tcga_tnbc_data/90e945ed-de4a-4de2-9b10-67bf4f30fa0b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  67%|██████▋   | 802/1200 [06:45<03:24,  1.95it/s]

Warning: File tcga_tnbc_data/5f2f42c5-e9d1-4a47-86a7-fd19308eca52_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  67%|██████▋   | 803/1200 [06:46<03:23,  1.95it/s]

Warning: File tcga_tnbc_data/25491fb0-ac87-4b8e-a99d-59e13acc0bb5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  67%|██████▋   | 804/1200 [06:46<03:17,  2.01it/s]

Warning: File tcga_tnbc_data/4f513085-a7f0-495c-9a87-34f70d757900_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  67%|██████▋   | 805/1200 [06:47<03:24,  1.93it/s]

Warning: File tcga_tnbc_data/fb69a4f1-3642-4012-a9be-68afbfeea487_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  67%|██████▋   | 806/1200 [06:47<03:33,  1.85it/s]

Warning: File tcga_tnbc_data/7843d077-04e2-41d2-bd64-73edd83e9c1f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  67%|██████▋   | 807/1200 [06:48<03:30,  1.86it/s]

Warning: File tcga_tnbc_data/15d2a81f-6250-4152-abe8-a862a70a8399_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  67%|██████▋   | 808/1200 [06:48<03:20,  1.96it/s]

Warning: File tcga_tnbc_data/70f60c0b-b581-4735-9535-69fd9ac480fd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  67%|██████▋   | 809/1200 [06:49<03:14,  2.01it/s]

Warning: File tcga_tnbc_data/7fc4859d-6045-4eef-9688-4ecdb7e5eede_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  68%|██████▊   | 810/1200 [06:49<03:19,  1.96it/s]

Warning: File tcga_tnbc_data/5bd1aec2-6ba0-4396-8114-2e7e7f49edfa_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  68%|██████▊   | 811/1200 [06:50<03:23,  1.91it/s]

Warning: File tcga_tnbc_data/4d45722d-19a0-4540-9a2b-fb4269da9caa_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  68%|██████▊   | 812/1200 [06:50<03:24,  1.90it/s]

Warning: File tcga_tnbc_data/520792ea-db7f-4eb0-a34b-98b5bb2b7eb3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  68%|██████▊   | 813/1200 [06:51<03:22,  1.91it/s]

Warning: File tcga_tnbc_data/3211b546-a89b-4c63-8fb6-bedd9fcc7d0b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  68%|██████▊   | 814/1200 [06:51<03:31,  1.82it/s]

Warning: File tcga_tnbc_data/8658b402-5d8f-4fe1-aa07-49ba5c655e47_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  68%|██████▊   | 815/1200 [06:52<03:17,  1.95it/s]

Warning: File tcga_tnbc_data/5830e58b-da08-491e-b74d-b1e41058262a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  68%|██████▊   | 816/1200 [06:52<03:17,  1.94it/s]

Warning: File tcga_tnbc_data/57861daf-8afc-4c1b-85a3-cec9240e30ca_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  68%|██████▊   | 817/1200 [06:53<03:08,  2.04it/s]

Warning: File tcga_tnbc_data/428c71b7-7fa6-4b34-b85c-bc67329db834_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  68%|██████▊   | 818/1200 [06:53<03:09,  2.02it/s]

Warning: File tcga_tnbc_data/96730d4a-dd9c-4f50-beae-2e45359746ae_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  68%|██████▊   | 819/1200 [06:54<03:05,  2.06it/s]

Warning: File tcga_tnbc_data/25e9d1e2-2fc3-4ee0-bf29-421adfcaf781_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  68%|██████▊   | 820/1200 [06:54<03:07,  2.03it/s]

Warning: File tcga_tnbc_data/d72794d5-c18a-41a6-bb7c-353e4d5f0c96_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  68%|██████▊   | 821/1200 [06:55<03:20,  1.89it/s]

Warning: File tcga_tnbc_data/aaab4fd3-9025-4add-b199-7ae99245b0e6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  68%|██████▊   | 822/1200 [06:55<03:17,  1.91it/s]

Warning: File tcga_tnbc_data/de3a4d13-6a5d-4943-8b84-bffaa2410c27_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  69%|██████▊   | 823/1200 [06:56<03:09,  1.99it/s]

Warning: File tcga_tnbc_data/3ada67b6-bcdd-4682-b99b-89956219718c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  69%|██████▊   | 824/1200 [06:56<02:57,  2.11it/s]

Warning: File tcga_tnbc_data/e24e5985-c69b-457b-a790-ddb0198ed0de_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  69%|██████▉   | 825/1200 [06:57<03:02,  2.05it/s]

Warning: File tcga_tnbc_data/a257fbd4-8d85-459a-984c-83040a164db6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  69%|██████▉   | 826/1200 [06:57<03:02,  2.05it/s]

Warning: File tcga_tnbc_data/31fc1006-d826-4d63-8fe0-881cce64b722_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  69%|██████▉   | 827/1200 [06:58<03:00,  2.06it/s]

Warning: File tcga_tnbc_data/9d8eb79b-50fd-45d3-9b7e-88c1197c7bc7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  69%|██████▉   | 828/1200 [06:58<02:47,  2.22it/s]

Warning: File tcga_tnbc_data/b10e1f39-79f4-43f6-8352-4c2e95de228e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  69%|██████▉   | 829/1200 [06:59<03:15,  1.90it/s]

Warning: File tcga_tnbc_data/54283490-47a5-4176-baa7-a8d99ec0aed7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  69%|██████▉   | 830/1200 [06:59<03:14,  1.91it/s]

Warning: File tcga_tnbc_data/4c77f7fb-e9ad-4fa1-be7f-63db632adb60_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  69%|██████▉   | 831/1200 [07:00<03:11,  1.93it/s]

Warning: File tcga_tnbc_data/e2062079-ae4d-4655-850c-41600e336530_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  69%|██████▉   | 832/1200 [07:00<02:58,  2.06it/s]

Warning: File tcga_tnbc_data/93f62084-a6d0-4ccd-b84f-fddb1c3b6656_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  69%|██████▉   | 833/1200 [07:01<03:00,  2.04it/s]

Warning: File tcga_tnbc_data/c3ba1574-1df3-4ef6-9dbf-3176ee75556f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  70%|██████▉   | 834/1200 [07:01<03:01,  2.01it/s]

Warning: File tcga_tnbc_data/6fdf025f-20c2-404a-b40f-c625e7649b88_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  70%|██████▉   | 835/1200 [07:02<02:50,  2.14it/s]

Warning: File tcga_tnbc_data/1609b215-8d43-4764-a749-ba8d03cb49ed_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  70%|██████▉   | 836/1200 [07:02<02:49,  2.15it/s]

Warning: File tcga_tnbc_data/9993fdc8-ba90-4daa-8260-8e1a0941eff1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  70%|██████▉   | 837/1200 [07:03<02:50,  2.12it/s]

Warning: File tcga_tnbc_data/3b844b07-f24e-4135-b94a-5096e55c600e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  70%|██████▉   | 838/1200 [07:03<03:01,  2.00it/s]

Warning: File tcga_tnbc_data/51c4a595-ad63-4ee2-9d5c-1ab9d398e88f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  70%|██████▉   | 839/1200 [07:04<03:03,  1.97it/s]

Warning: File tcga_tnbc_data/6b261846-2cc0-4c86-b714-7429e18684d9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  70%|███████   | 840/1200 [07:04<03:02,  1.97it/s]

Warning: File tcga_tnbc_data/436a2acf-c97a-4423-999d-cfd752a70df9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  70%|███████   | 841/1200 [07:05<03:10,  1.88it/s]

Warning: File tcga_tnbc_data/3a443790-5604-4dc4-b5b7-1e927435acd5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  70%|███████   | 842/1200 [07:05<03:12,  1.86it/s]

Warning: File tcga_tnbc_data/09ace4e7-5c45-4492-b97c-46aa467820aa_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  70%|███████   | 843/1200 [07:06<03:10,  1.87it/s]

Warning: File tcga_tnbc_data/71b9896d-73fb-4f32-8e6e-e5d839095961_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  70%|███████   | 844/1200 [07:07<03:17,  1.80it/s]

Warning: File tcga_tnbc_data/2db0a3fd-2399-4bfb-b676-2b19c197f391_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  70%|███████   | 845/1200 [07:07<03:22,  1.75it/s]

Warning: File tcga_tnbc_data/4d6a370d-5a30-4f34-b8ff-d4490afcec73_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  70%|███████   | 846/1200 [07:08<03:04,  1.92it/s]

Warning: File tcga_tnbc_data/f2ac5078-6abc-4e01-80d1-a0d723fe91af_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  71%|███████   | 847/1200 [07:08<03:10,  1.86it/s]

Warning: File tcga_tnbc_data/34933250-0d06-4072-b05f-99306e9ce476_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  71%|███████   | 848/1200 [07:09<02:58,  1.97it/s]

Warning: File tcga_tnbc_data/a3a1a7b7-6109-4c9d-bb39-81d5d8a9c89f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  71%|███████   | 849/1200 [07:09<02:55,  2.00it/s]

Warning: File tcga_tnbc_data/515e127f-0f73-4b02-92ec-83f71b724b5e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  71%|███████   | 850/1200 [07:10<02:56,  1.98it/s]

Warning: File tcga_tnbc_data/54ffed74-ae60-4690-9bcb-8d5e1200ccad_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  71%|███████   | 851/1200 [07:10<02:50,  2.05it/s]

Warning: File tcga_tnbc_data/fb898446-9ba2-47d5-b86f-41a424c6fc38_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  71%|███████   | 852/1200 [07:11<02:55,  1.99it/s]

Warning: File tcga_tnbc_data/0e173e62-bccb-4a31-914f-e888bd412bc6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  71%|███████   | 853/1200 [07:11<02:52,  2.01it/s]

Warning: File tcga_tnbc_data/71f38728-5265-4317-a9da-95129726fe2b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  71%|███████   | 854/1200 [07:12<03:00,  1.92it/s]

Warning: File tcga_tnbc_data/b3c1a9a5-2d08-4a68-8eab-bc2bf4430ace_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  71%|███████▏  | 855/1200 [07:12<02:54,  1.98it/s]

Warning: File tcga_tnbc_data/7facf64a-4732-48a9-a274-79b33a066377_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  71%|███████▏  | 856/1200 [07:13<02:49,  2.03it/s]

Warning: File tcga_tnbc_data/d497caa1-a4f7-4ffc-a37b-61b35be3a32b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  71%|███████▏  | 857/1200 [07:13<02:50,  2.01it/s]

Warning: File tcga_tnbc_data/4cf796e7-dd9e-45b9-8095-44b0e0555d17_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  72%|███████▏  | 858/1200 [07:14<02:48,  2.02it/s]

Warning: File tcga_tnbc_data/19c3e7c5-bf6a-4b03-84ef-bf4c2f0d4d54_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  72%|███████▏  | 859/1200 [07:14<02:38,  2.15it/s]

Warning: File tcga_tnbc_data/4582abaa-1674-46f5-b049-96d9225759e2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  72%|███████▏  | 860/1200 [07:14<02:35,  2.18it/s]

Warning: File tcga_tnbc_data/7e4b904e-cacd-4c36-a5ad-0923bec03578_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  72%|███████▏  | 861/1200 [07:15<02:37,  2.16it/s]

Warning: File tcga_tnbc_data/e4fe45b7-34de-4467-9f6d-e65930b3d508_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  72%|███████▏  | 862/1200 [07:15<02:38,  2.14it/s]

Warning: File tcga_tnbc_data/939775c8-4388-4f97-997f-efb92dc93c79_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  72%|███████▏  | 863/1200 [07:16<02:38,  2.13it/s]

Warning: File tcga_tnbc_data/e48da6f7-3c3b-4518-8075-a18a944144f2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  72%|███████▏  | 864/1200 [07:16<02:46,  2.02it/s]

Warning: File tcga_tnbc_data/7d7401ae-d0e1-4296-9898-43d73e8bacfd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  72%|███████▏  | 865/1200 [07:17<02:41,  2.08it/s]

Warning: File tcga_tnbc_data/68dec41b-fbcc-4f7b-9562-8ea51f3617e4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  72%|███████▏  | 866/1200 [07:17<02:44,  2.03it/s]

Warning: File tcga_tnbc_data/ae7025c3-27ac-4435-958a-0a2887f5e737_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  72%|███████▏  | 867/1200 [07:18<02:57,  1.87it/s]

Warning: File tcga_tnbc_data/e1c94290-d7d0-4159-9ea4-6cd107e3f224_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  72%|███████▏  | 868/1200 [07:18<02:45,  2.01it/s]

Warning: File tcga_tnbc_data/9921ecf7-18c2-49ea-9243-293de7bd9e59_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  72%|███████▏  | 869/1200 [07:19<02:42,  2.04it/s]

Warning: File tcga_tnbc_data/a9034495-f0b8-4db4-9014-cf515083bb99_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  72%|███████▎  | 870/1200 [07:19<02:41,  2.05it/s]

Warning: File tcga_tnbc_data/b6eea29b-e628-4ba9-8c36-6fec76dad20b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  73%|███████▎  | 871/1200 [07:20<02:48,  1.96it/s]

Warning: File tcga_tnbc_data/d2c48770-5184-48fa-84af-8db038d4b8d8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  73%|███████▎  | 872/1200 [07:20<02:49,  1.94it/s]

Warning: File tcga_tnbc_data/4c3a8286-b1f9-486e-9ccc-4b93eb9abb1e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  73%|███████▎  | 873/1200 [07:21<02:48,  1.95it/s]

Warning: File tcga_tnbc_data/5cc8d0d0-e196-4ef2-85c8-20f8d35764e3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  73%|███████▎  | 874/1200 [07:21<02:35,  2.10it/s]

Warning: File tcga_tnbc_data/9326bb7f-da05-490c-a620-5c88323130d6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  73%|███████▎  | 875/1200 [07:22<02:29,  2.18it/s]

Warning: File tcga_tnbc_data/dbc969c2-024a-4b0a-bb3d-1bd35e000e36_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  73%|███████▎  | 876/1200 [07:22<02:33,  2.11it/s]

Warning: File tcga_tnbc_data/c9c262d1-a48f-49d8-a7d3-fcea1fd83691_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  73%|███████▎  | 877/1200 [07:23<02:40,  2.02it/s]

Warning: File tcga_tnbc_data/05960e82-e648-4b99-a116-9cf917d1bff7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  73%|███████▎  | 878/1200 [07:23<02:40,  2.00it/s]

Warning: File tcga_tnbc_data/386303b0-03dc-4202-8af9-fb7373909c84_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  73%|███████▎  | 879/1200 [07:24<02:29,  2.15it/s]

Warning: File tcga_tnbc_data/3efa1571-cad2-4796-a459-144c38b87d9c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  73%|███████▎  | 880/1200 [07:24<02:27,  2.17it/s]

Warning: File tcga_tnbc_data/7cdd6719-c7c9-4a29-8075-dbca0bce6aff_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  73%|███████▎  | 881/1200 [07:25<02:28,  2.15it/s]

Warning: File tcga_tnbc_data/f5a7db34-479b-4593-9ba9-fd22a726eacd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  74%|███████▎  | 882/1200 [07:25<02:44,  1.94it/s]

Warning: File tcga_tnbc_data/5c97f076-c198-4d3d-b680-97c3e9fb08db_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  74%|███████▎  | 883/1200 [07:26<02:41,  1.96it/s]

Warning: File tcga_tnbc_data/32c24548-2714-4a90-bfb1-002f1c46c0c5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  74%|███████▎  | 884/1200 [07:26<02:33,  2.05it/s]

Warning: File tcga_tnbc_data/f2c9c022-0b54-45f4-a31a-c97372dda545_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  74%|███████▍  | 885/1200 [07:27<02:32,  2.07it/s]

Warning: File tcga_tnbc_data/c3460a50-6e60-4d5e-8f54-3181991b94e4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  74%|███████▍  | 886/1200 [07:27<02:35,  2.02it/s]

Warning: File tcga_tnbc_data/e62de0de-c8eb-46b0-9d1e-d0e1d688d2ac_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  74%|███████▍  | 887/1200 [07:28<02:23,  2.18it/s]

Warning: File tcga_tnbc_data/cbe969fc-2e73-4ab6-94d4-c4c95d4e8ea5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  74%|███████▍  | 888/1200 [07:28<02:19,  2.24it/s]

Warning: File tcga_tnbc_data/735ece50-9155-418b-8e31-64d1bfaf153a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  74%|███████▍  | 889/1200 [07:28<02:24,  2.15it/s]

Warning: File tcga_tnbc_data/0e60fb9a-cb4c-4b9b-a1fd-5b2ae091dc5b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  74%|███████▍  | 890/1200 [07:29<02:29,  2.08it/s]

Warning: File tcga_tnbc_data/2d736297-0768-4c2d-a81e-3617d83c0d71_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  74%|███████▍  | 891/1200 [07:29<02:26,  2.11it/s]

Warning: File tcga_tnbc_data/472c5ce4-aedb-45b0-a4cb-0948619e358c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  74%|███████▍  | 892/1200 [07:30<02:25,  2.12it/s]

Warning: File tcga_tnbc_data/343e46a0-ce35-4efc-99d7-720f6a13eff4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  74%|███████▍  | 893/1200 [07:30<02:22,  2.16it/s]

Warning: File tcga_tnbc_data/704072c3-be9e-4221-9847-f558ccde7a5b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  74%|███████▍  | 894/1200 [07:31<02:19,  2.19it/s]

Warning: File tcga_tnbc_data/846495f1-2325-4885-860b-ecf2c64a2f4c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  75%|███████▍  | 895/1200 [07:31<02:22,  2.14it/s]

Warning: File tcga_tnbc_data/cb611345-3a56-4f49-b364-597d672152d7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  75%|███████▍  | 896/1200 [07:32<02:20,  2.16it/s]

Warning: File tcga_tnbc_data/16211ee3-2f4b-40e1-93b7-4f547b6c5778_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  75%|███████▍  | 897/1200 [07:32<02:16,  2.22it/s]

Warning: File tcga_tnbc_data/bb7f69e5-2fff-4178-bc7b-93a41fbe6123_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  75%|███████▍  | 898/1200 [07:33<02:08,  2.34it/s]

Warning: File tcga_tnbc_data/3d72d0e5-dbfb-4a74-b893-6057f533123c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  75%|███████▍  | 899/1200 [07:33<02:13,  2.25it/s]

Warning: File tcga_tnbc_data/32ae48df-7f72-479d-93b6-8ae2ebe1e531_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  75%|███████▌  | 900/1200 [07:33<02:08,  2.34it/s]

Warning: File tcga_tnbc_data/099fa24d-d952-4617-935c-a8d9439a5a11_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  75%|███████▌  | 901/1200 [07:34<02:08,  2.32it/s]

Warning: File tcga_tnbc_data/af68c263-395e-49d7-9595-024857785b06_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  75%|███████▌  | 902/1200 [07:34<02:07,  2.33it/s]

Warning: File tcga_tnbc_data/a790c01b-ddc7-459e-8a14-4e59f12bff6c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  75%|███████▌  | 903/1200 [07:35<02:14,  2.22it/s]

Warning: File tcga_tnbc_data/0db85fe0-94d6-4b8d-bff4-d69aea8a0806_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  75%|███████▌  | 904/1200 [07:36<03:40,  1.34it/s]

Warning: File tcga_tnbc_data/b25db78b-dd55-4bda-8705-30690ea11954_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  75%|███████▌  | 905/1200 [07:37<03:18,  1.49it/s]

Warning: File tcga_tnbc_data/2e1de344-442c-4c2b-929a-74021d92c95b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  76%|███████▌  | 906/1200 [07:37<02:50,  1.72it/s]

Warning: File tcga_tnbc_data/2bb3034f-d37a-4eb4-b633-a3952ab947dd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  76%|███████▌  | 907/1200 [07:38<02:44,  1.78it/s]

Warning: File tcga_tnbc_data/ab007457-2432-44c5-813e-8c80c4603ddf_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  76%|███████▌  | 908/1200 [07:39<04:14,  1.15it/s]

Warning: File tcga_tnbc_data/3f460a1a-f1dd-4c11-95b1-f5757a8e7cc4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  76%|███████▌  | 909/1200 [07:40<03:41,  1.32it/s]

Warning: File tcga_tnbc_data/57a5d70c-04d1-4b21-834e-2746f74bdce4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  76%|███████▌  | 910/1200 [07:40<03:20,  1.45it/s]

Warning: File tcga_tnbc_data/fd3b0853-0da6-41a2-8194-fd29e190ebd0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  76%|███████▌  | 911/1200 [07:43<07:01,  1.46s/it]

Warning: File tcga_tnbc_data/b91d66a1-c76f-4256-9eaf-411146e5c9df_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  76%|███████▌  | 912/1200 [07:44<05:37,  1.17s/it]

Warning: File tcga_tnbc_data/9400edd0-cc27-4b5c-802a-31ea10a73130_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  76%|███████▌  | 913/1200 [07:44<04:38,  1.03it/s]

Warning: File tcga_tnbc_data/a350c64f-68f6-4161-a336-253160f87c46_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  76%|███████▌  | 914/1200 [07:45<03:52,  1.23it/s]

Warning: File tcga_tnbc_data/683a097e-79ff-41d5-843c-d23674867f02_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  76%|███████▋  | 915/1200 [07:45<03:17,  1.44it/s]

Warning: File tcga_tnbc_data/a9dd39b4-6d45-47e3-9339-a5f357cd14c4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  76%|███████▋  | 916/1200 [07:46<03:06,  1.52it/s]

Warning: File tcga_tnbc_data/04ac5016-eca0-4536-ab2b-27ca4de15acd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  76%|███████▋  | 917/1200 [07:46<02:48,  1.67it/s]

Warning: File tcga_tnbc_data/df44fccd-11dc-4fed-b2b9-74ff4081405e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  76%|███████▋  | 918/1200 [07:47<02:38,  1.78it/s]

Warning: File tcga_tnbc_data/c58f9425-5789-4c8c-8bda-5e75ba382783_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  77%|███████▋  | 919/1200 [07:47<02:29,  1.88it/s]

Warning: File tcga_tnbc_data/f316e253-bb84-4c26-a1ef-1df6c5b679b1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  77%|███████▋  | 920/1200 [07:48<02:30,  1.86it/s]

Warning: File tcga_tnbc_data/f0101ef7-d3f7-458a-aa7e-77e68abb1cce_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  77%|███████▋  | 921/1200 [07:48<02:30,  1.86it/s]

Warning: File tcga_tnbc_data/6df91b39-f48d-4d97-bd65-0b1dbb4407ed_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  77%|███████▋  | 922/1200 [07:49<02:24,  1.93it/s]

Warning: File tcga_tnbc_data/bed76897-7a87-4692-869a-519f0f9279d7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  77%|███████▋  | 923/1200 [07:49<02:24,  1.92it/s]

Warning: File tcga_tnbc_data/2daeac8d-256d-49d7-b043-b18d8db812eb_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  77%|███████▋  | 924/1200 [07:50<02:16,  2.02it/s]

Warning: File tcga_tnbc_data/7e7d3e1a-8f9b-4f1b-9f5e-8ac64d308dfa_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  77%|███████▋  | 925/1200 [07:50<02:14,  2.05it/s]

Warning: File tcga_tnbc_data/45ede76e-9095-4b78-9227-21921468f3ee_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  77%|███████▋  | 926/1200 [07:51<02:18,  1.97it/s]

Warning: File tcga_tnbc_data/d2353436-a547-4431-b1fe-c7bd67f9bcb5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  77%|███████▋  | 927/1200 [07:51<02:20,  1.95it/s]

Warning: File tcga_tnbc_data/7037419d-af1b-4420-a855-6af478e6e31a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  77%|███████▋  | 928/1200 [07:52<02:12,  2.05it/s]

Warning: File tcga_tnbc_data/9914a808-171b-494f-9e66-d5a3adec3d4c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  77%|███████▋  | 929/1200 [07:52<02:13,  2.03it/s]

Warning: File tcga_tnbc_data/676ec2aa-cf5c-41f1-9b1a-1e797477a2f1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  78%|███████▊  | 930/1200 [07:53<02:26,  1.84it/s]

Warning: File tcga_tnbc_data/b8ccb1a4-10c7-4b58-997a-d8bc30b0da5e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  78%|███████▊  | 931/1200 [07:53<02:23,  1.88it/s]

Warning: File tcga_tnbc_data/8429fc49-57f7-47a9-98e3-ac0bf8966b52_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  78%|███████▊  | 932/1200 [07:54<02:20,  1.91it/s]

Warning: File tcga_tnbc_data/56b46dcf-c809-4b4d-8e69-9b03d39a4f7a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  78%|███████▊  | 933/1200 [07:54<02:16,  1.95it/s]

Warning: File tcga_tnbc_data/84aad260-dee1-46bb-9bb2-9f75f6dbf472_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  78%|███████▊  | 934/1200 [07:55<02:14,  1.98it/s]

Warning: File tcga_tnbc_data/1a2097ac-6aef-4740-8076-1679365e1f4f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  78%|███████▊  | 935/1200 [07:55<02:04,  2.12it/s]

Warning: File tcga_tnbc_data/2b696fa6-f248-4acc-93c0-9387591b75e7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  78%|███████▊  | 936/1200 [07:57<03:21,  1.31it/s]

Warning: File tcga_tnbc_data/3a5e7502-cf1f-459d-91af-34e92f5f60d0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  78%|███████▊  | 937/1200 [07:57<02:58,  1.47it/s]

Warning: File tcga_tnbc_data/522b6e1d-76dc-4f22-8d02-73b73af86309_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  78%|███████▊  | 938/1200 [07:58<02:36,  1.68it/s]

Warning: File tcga_tnbc_data/1cae5825-2dbe-4eda-a71f-40ea7a554420_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  78%|███████▊  | 939/1200 [07:58<02:20,  1.86it/s]

Warning: File tcga_tnbc_data/97ff9f47-cb8a-4348-a13e-8f87fe3330b0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  78%|███████▊  | 940/1200 [07:59<02:15,  1.93it/s]

Warning: File tcga_tnbc_data/1a4fea2e-132f-489d-8ee6-d9a0ec615f53_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  78%|███████▊  | 941/1200 [07:59<02:15,  1.91it/s]

Warning: File tcga_tnbc_data/1af6794a-2d3e-4a93-81e5-accc366c6922_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  78%|███████▊  | 942/1200 [08:00<02:08,  2.00it/s]

Warning: File tcga_tnbc_data/8c2ea0f3-474f-47f4-9900-d708e14e244c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  79%|███████▊  | 943/1200 [08:00<02:10,  1.97it/s]

Warning: File tcga_tnbc_data/a6996338-7dab-4816-898a-a20430141131_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  79%|███████▊  | 944/1200 [08:01<02:06,  2.02it/s]

Warning: File tcga_tnbc_data/378e7d58-2089-4797-85e8-af08e71477ab_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  79%|███████▉  | 945/1200 [08:01<02:04,  2.04it/s]

Warning: File tcga_tnbc_data/bf74aec5-b781-4cef-8b4a-7fbe0a8958d9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  79%|███████▉  | 946/1200 [08:02<02:06,  2.01it/s]

Warning: File tcga_tnbc_data/d6c77415-a3c1-4627-a0ab-dacdac3db507_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  79%|███████▉  | 947/1200 [08:02<02:11,  1.92it/s]

Warning: File tcga_tnbc_data/def8f9eb-8f3e-47af-97f3-99b588970937_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  79%|███████▉  | 948/1200 [08:02<01:59,  2.10it/s]

Warning: File tcga_tnbc_data/f91fc5b4-3e79-4028-81d5-56c947de95ee_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  79%|███████▉  | 949/1200 [08:03<01:53,  2.21it/s]

Warning: File tcga_tnbc_data/c8d46326-0b84-40cd-983e-0a8e99763727_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  79%|███████▉  | 950/1200 [08:03<01:52,  2.22it/s]

Warning: File tcga_tnbc_data/85e388dc-f9a8-40f9-a532-fbfb172ef122_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  79%|███████▉  | 951/1200 [08:04<01:48,  2.29it/s]

Warning: File tcga_tnbc_data/f5c2e3ee-f3a6-4cb2-81b1-7d7652b6b600_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  79%|███████▉  | 952/1200 [08:04<01:52,  2.20it/s]

Warning: File tcga_tnbc_data/1ef4181f-9d16-4e3e-a8aa-ac0849bb6ef8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  79%|███████▉  | 953/1200 [08:05<02:10,  1.90it/s]

Warning: File tcga_tnbc_data/52ed290d-a590-473d-8267-2a2de81b2d3f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  80%|███████▉  | 954/1200 [08:05<02:11,  1.87it/s]

Warning: File tcga_tnbc_data/93b8bab9-acd8-4a5a-b4ba-ec52b2ab186b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  80%|███████▉  | 955/1200 [08:06<02:10,  1.87it/s]

Warning: File tcga_tnbc_data/bcb337bb-7fc9-4182-9385-b2fd1fcc50b6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  80%|███████▉  | 956/1200 [08:06<02:05,  1.94it/s]

Warning: File tcga_tnbc_data/d7cbbbaf-e5cc-4e1d-84b4-c44244ff712c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  80%|███████▉  | 957/1200 [08:07<02:03,  1.97it/s]

Warning: File tcga_tnbc_data/59dc9929-f28e-4f94-b1cf-789f7007107f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  80%|███████▉  | 958/1200 [08:07<02:04,  1.95it/s]

Warning: File tcga_tnbc_data/67823e04-d914-4a9f-8231-7103e55a0a74_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  80%|███████▉  | 959/1200 [08:08<02:03,  1.96it/s]

Warning: File tcga_tnbc_data/41dbd6ab-871d-4ee4-be13-392b4995f6ce_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  80%|████████  | 960/1200 [08:09<02:54,  1.38it/s]

Warning: File tcga_tnbc_data/a8c56ead-63aa-453e-871b-4d1688c1e715_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  80%|████████  | 961/1200 [08:10<02:33,  1.56it/s]

Warning: File tcga_tnbc_data/21eda9bb-7b0c-46a0-8dde-4a6a02b4ea17_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  80%|████████  | 962/1200 [08:10<02:23,  1.66it/s]

Warning: File tcga_tnbc_data/9e73d394-b8e3-4ee2-bb35-a1fb43fd280f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  80%|████████  | 963/1200 [08:11<02:10,  1.82it/s]

Warning: File tcga_tnbc_data/ca69edd8-72d1-48f9-91e8-4ed748144c46_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  80%|████████  | 964/1200 [08:11<02:10,  1.81it/s]

Warning: File tcga_tnbc_data/3c230360-fe46-46ff-8e5e-225ee48484f2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  80%|████████  | 965/1200 [08:12<02:08,  1.83it/s]

Warning: File tcga_tnbc_data/cf34dfb9-b3cd-43a0-aad5-48329539e196_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  80%|████████  | 966/1200 [08:12<02:06,  1.85it/s]

Warning: File tcga_tnbc_data/260c1dd7-d6f8-4337-9bba-5de192fc5af3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  81%|████████  | 967/1200 [08:13<02:01,  1.92it/s]

Warning: File tcga_tnbc_data/e4c709ae-d1b7-4606-b671-a6d1c48b7c6a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  81%|████████  | 968/1200 [08:13<02:03,  1.88it/s]

Warning: File tcga_tnbc_data/602a190c-b633-4af8-ab82-96c9677f900b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  81%|████████  | 969/1200 [08:14<01:58,  1.94it/s]

Warning: File tcga_tnbc_data/04d487db-ee31-431d-ad5f-29645cf75e1b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  81%|████████  | 970/1200 [08:14<01:55,  1.99it/s]

Warning: File tcga_tnbc_data/28d07a0a-b5ea-4ec0-b831-e80e060ef49c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  81%|████████  | 971/1200 [08:15<02:00,  1.91it/s]

Warning: File tcga_tnbc_data/d12841a3-bb30-4068-84a9-1e71d3e4a223_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  81%|████████  | 972/1200 [08:15<01:58,  1.93it/s]

Warning: File tcga_tnbc_data/46113f4d-f105-4057-9ae7-27f4e0f60abe_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  81%|████████  | 973/1200 [08:16<02:03,  1.84it/s]

Warning: File tcga_tnbc_data/af0d61e8-9271-4a3a-8a25-b4417323043d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  81%|████████  | 974/1200 [08:16<01:58,  1.90it/s]

Warning: File tcga_tnbc_data/6ab4fc21-5a56-475e-84fe-ff08724120f2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  81%|████████▏ | 975/1200 [08:17<02:03,  1.82it/s]

Warning: File tcga_tnbc_data/1d5e0b6b-ed64-4ccc-9736-0469f2002040_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  81%|████████▏ | 976/1200 [08:18<02:06,  1.77it/s]

Warning: File tcga_tnbc_data/8e19027a-faf5-4f18-a23f-4fc0325ed416_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  81%|████████▏ | 977/1200 [08:18<02:03,  1.81it/s]

Warning: File tcga_tnbc_data/0c763950-a82a-42f3-9d68-67be5e5380a8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  82%|████████▏ | 978/1200 [08:19<01:57,  1.90it/s]

Warning: File tcga_tnbc_data/382047a4-54a9-412e-bfaf-aac8baf48726_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  82%|████████▏ | 979/1200 [08:19<02:00,  1.84it/s]

Warning: File tcga_tnbc_data/406fd7d3-b73a-4014-b315-1eeaae01e988_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  82%|████████▏ | 980/1200 [08:20<01:58,  1.85it/s]

Warning: File tcga_tnbc_data/62fe956f-d4ea-45b5-8650-bc0adc5d4291_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  82%|████████▏ | 981/1200 [08:20<01:54,  1.91it/s]

Warning: File tcga_tnbc_data/4b487c92-84e4-4f5d-af38-62fefd0baa93_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  82%|████████▏ | 982/1200 [08:21<01:52,  1.94it/s]

Warning: File tcga_tnbc_data/3f09ffc0-db54-4f87-b8e4-92c55f2045ea_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  82%|████████▏ | 983/1200 [08:21<02:02,  1.77it/s]

Warning: File tcga_tnbc_data/b88178b2-b232-440b-a8db-db4af1e36381_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  82%|████████▏ | 984/1200 [08:22<02:05,  1.72it/s]

Warning: File tcga_tnbc_data/a7f8eb90-be36-499a-924a-8cd1aaa5fb20_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  82%|████████▏ | 985/1200 [08:22<01:57,  1.83it/s]

Warning: File tcga_tnbc_data/597789b8-5b5e-47a3-a937-f7bb9979a554_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  82%|████████▏ | 986/1200 [08:23<01:55,  1.85it/s]

Warning: File tcga_tnbc_data/ed809f5e-f379-4f65-8663-83f586c55a98_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  82%|████████▏ | 987/1200 [08:24<02:01,  1.75it/s]

Warning: File tcga_tnbc_data/4f8f52e4-1a81-42a0-88a5-41e87b6be678_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  82%|████████▏ | 988/1200 [08:24<01:57,  1.80it/s]

Warning: File tcga_tnbc_data/4dbb7005-c218-434a-a462-6a7243edee12_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  82%|████████▏ | 989/1200 [08:25<01:53,  1.86it/s]

Warning: File tcga_tnbc_data/205a5aac-2040-4408-846d-19228ae435bf_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  82%|████████▎ | 990/1200 [08:25<01:53,  1.85it/s]

Warning: File tcga_tnbc_data/c7fcb557-2a7c-41d2-92f1-7014b9f639d3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  83%|████████▎ | 991/1200 [08:26<01:58,  1.76it/s]

Warning: File tcga_tnbc_data/04cfe993-afde-4e40-9cb1-d9c2415b16b6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  83%|████████▎ | 992/1200 [08:26<01:58,  1.75it/s]

Warning: File tcga_tnbc_data/f4d16cd8-479d-4984-87d6-7db8c1e421ab_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  83%|████████▎ | 993/1200 [08:27<01:50,  1.87it/s]

Warning: File tcga_tnbc_data/a68715a2-cd9b-4e96-8c20-5ebe9469d8d8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  83%|████████▎ | 994/1200 [08:27<01:48,  1.89it/s]

Warning: File tcga_tnbc_data/0e23a5a9-902d-4a57-87ad-c9ce385a9730_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  83%|████████▎ | 995/1200 [08:28<01:43,  1.98it/s]

Warning: File tcga_tnbc_data/87467089-c9c4-49cd-96da-3fae32599397_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  83%|████████▎ | 996/1200 [08:28<01:42,  2.00it/s]

Warning: File tcga_tnbc_data/f541d19f-8390-40f1-8446-2a3430cae304_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  83%|████████▎ | 997/1200 [08:29<01:37,  2.08it/s]

Warning: File tcga_tnbc_data/7cfd1188-7597-4259-a1a7-25dbdddae39a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  83%|████████▎ | 998/1200 [08:29<01:37,  2.08it/s]

Warning: File tcga_tnbc_data/2e354ad2-e897-44e9-8c6f-341fc5d878ec_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  83%|████████▎ | 999/1200 [08:30<01:41,  1.98it/s]

Warning: File tcga_tnbc_data/5af91b67-394a-4872-ad42-0f41e0998ad6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  83%|████████▎ | 1000/1200 [08:30<01:40,  1.98it/s]

Warning: File tcga_tnbc_data/dc8d96ef-81eb-41c8-a486-02d107c1a137_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  83%|████████▎ | 1001/1200 [08:31<01:39,  2.00it/s]

Warning: File tcga_tnbc_data/e4422832-2ce3-47aa-ab4e-ecc2bb8e4018_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  84%|████████▎ | 1002/1200 [08:31<01:41,  1.96it/s]

Warning: File tcga_tnbc_data/715f2d06-d430-4021-a192-7108fa0c1f63_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  84%|████████▎ | 1003/1200 [08:32<01:37,  2.02it/s]

Warning: File tcga_tnbc_data/b836b81e-adfc-41cf-9275-4ce2d3252122_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  84%|████████▎ | 1004/1200 [08:32<01:33,  2.09it/s]

Warning: File tcga_tnbc_data/d681c69f-3020-463b-90c0-bd9435e3f216_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  84%|████████▍ | 1005/1200 [08:34<02:37,  1.24it/s]

Warning: File tcga_tnbc_data/eb05707c-be5a-4faf-ac42-7e5ca6af53e2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  84%|████████▍ | 1006/1200 [08:34<02:18,  1.40it/s]

Warning: File tcga_tnbc_data/4e515787-2cff-421d-8c77-f7bc35632c46_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  84%|████████▍ | 1007/1200 [08:35<02:03,  1.56it/s]

Warning: File tcga_tnbc_data/830c13a4-a08e-4709-81cc-2f41bc4b978d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  84%|████████▍ | 1008/1200 [08:35<01:49,  1.76it/s]

Warning: File tcga_tnbc_data/c933036a-3ea4-4ed5-b318-95c310e6c11d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  84%|████████▍ | 1009/1200 [08:36<01:41,  1.89it/s]

Warning: File tcga_tnbc_data/34dd6421-03a0-4fc8-a0b4-77593cea0481_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  84%|████████▍ | 1010/1200 [08:36<01:33,  2.03it/s]

Warning: File tcga_tnbc_data/63970639-a366-42e8-aa18-d072a9fc1770_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  84%|████████▍ | 1011/1200 [08:36<01:30,  2.10it/s]

Warning: File tcga_tnbc_data/ffc1e2ea-a8ff-461f-8ed6-ed2ed6d547a1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  84%|████████▍ | 1012/1200 [08:37<01:27,  2.16it/s]

Warning: File tcga_tnbc_data/ccaa2c13-d1d9-4c7b-8a0e-453407863ca2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  84%|████████▍ | 1013/1200 [08:37<01:24,  2.20it/s]

Warning: File tcga_tnbc_data/3fdcb9b7-74db-462d-8903-c054eb8b9961_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  84%|████████▍ | 1014/1200 [08:38<01:25,  2.17it/s]

Warning: File tcga_tnbc_data/52b38845-c5ce-49c0-b84f-5f6b9ffdd310_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  85%|████████▍ | 1015/1200 [08:38<01:25,  2.16it/s]

Warning: File tcga_tnbc_data/5d2ea1db-2863-482d-8394-57c57cc64871_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  85%|████████▍ | 1016/1200 [08:39<01:35,  1.93it/s]

Warning: File tcga_tnbc_data/526ab5d5-9a94-4c80-b088-84d190400b23_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  85%|████████▍ | 1017/1200 [08:39<01:31,  2.01it/s]

Warning: File tcga_tnbc_data/6137053a-f7df-4eba-a296-16530ca8ea1e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  85%|████████▍ | 1018/1200 [08:40<01:33,  1.94it/s]

Warning: File tcga_tnbc_data/53dc00a4-4866-4803-b669-17a2ae4b25f9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  85%|████████▍ | 1019/1200 [08:40<01:30,  2.00it/s]

Warning: File tcga_tnbc_data/c2c6e1dd-c3fe-4196-a4e2-eedd600bd8d5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  85%|████████▌ | 1020/1200 [08:41<01:30,  1.99it/s]

Warning: File tcga_tnbc_data/c997955d-2e75-4b49-a891-6c335611ac0d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  85%|████████▌ | 1021/1200 [08:41<01:31,  1.96it/s]

Warning: File tcga_tnbc_data/af03c277-4949-4640-9da0-a25ca2d0df70_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  85%|████████▌ | 1022/1200 [08:42<01:31,  1.95it/s]

Warning: File tcga_tnbc_data/2da979d1-6b8f-4e13-9c51-24a1ac569935_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  85%|████████▌ | 1023/1200 [08:42<01:25,  2.07it/s]

Warning: File tcga_tnbc_data/25bc9363-e25e-4b4a-9d57-a70b867716b1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  85%|████████▌ | 1024/1200 [08:43<01:29,  1.97it/s]

Warning: File tcga_tnbc_data/4eea0701-8708-4c93-9f63-79ea480031f3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  85%|████████▌ | 1025/1200 [08:43<01:27,  1.99it/s]

Warning: File tcga_tnbc_data/38b76080-eeae-4c30-a6ec-955213c8c691_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  86%|████████▌ | 1026/1200 [08:44<01:27,  1.99it/s]

Warning: File tcga_tnbc_data/f61efa60-19ed-4edd-90ec-396fc999e103_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  86%|████████▌ | 1027/1200 [08:44<01:31,  1.90it/s]

Warning: File tcga_tnbc_data/fc2d38ef-7c0a-4126-92ae-35c41c2f0a7f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  86%|████████▌ | 1028/1200 [08:45<01:30,  1.91it/s]

Warning: File tcga_tnbc_data/5cf58cd3-84a5-4b38-9793-e35f0e4cc325_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  86%|████████▌ | 1029/1200 [08:45<01:29,  1.91it/s]

Warning: File tcga_tnbc_data/8b4d83e5-198c-4290-ad6a-78f962132f13_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  86%|████████▌ | 1030/1200 [08:46<01:27,  1.94it/s]

Warning: File tcga_tnbc_data/c2c9e2dd-74cc-4f23-964b-2094b2f5c4fd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  86%|████████▌ | 1031/1200 [08:47<01:28,  1.92it/s]

Warning: File tcga_tnbc_data/483ab415-03c0-4481-b4d3-9ecd61e6367b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  86%|████████▌ | 1032/1200 [08:47<01:27,  1.92it/s]

Warning: File tcga_tnbc_data/55e9dc18-7bee-4a15-9c77-db1ba5ad4a6b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  86%|████████▌ | 1033/1200 [08:48<01:24,  1.98it/s]

Warning: File tcga_tnbc_data/92e2366c-6120-48eb-acc7-f37acdb222ae_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  86%|████████▌ | 1034/1200 [08:48<01:26,  1.92it/s]

Warning: File tcga_tnbc_data/6e684fdf-142e-4285-a259-6457763d95a9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  86%|████████▋ | 1035/1200 [08:49<01:23,  1.98it/s]

Warning: File tcga_tnbc_data/38d4869b-6186-4af8-bac6-8fbf613b5861_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  86%|████████▋ | 1036/1200 [08:49<01:20,  2.04it/s]

Warning: File tcga_tnbc_data/1e87afb2-8635-4956-8b35-6aefbc568a61_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  86%|████████▋ | 1037/1200 [08:49<01:19,  2.04it/s]

Warning: File tcga_tnbc_data/fe02753e-a8d5-487d-87f9-f6879d185f0d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  86%|████████▋ | 1038/1200 [08:50<01:15,  2.14it/s]

Warning: File tcga_tnbc_data/ab3074a0-f071-4cc5-8d16-a18efa651db6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  87%|████████▋ | 1039/1200 [08:50<01:11,  2.24it/s]

Warning: File tcga_tnbc_data/e68bb5da-1d15-4de9-b8d4-eac78a205699_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  87%|████████▋ | 1040/1200 [08:51<01:13,  2.18it/s]

Warning: File tcga_tnbc_data/cb2f0749-b2c8-4c07-8def-943d52eeb1d8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  87%|████████▋ | 1041/1200 [08:51<01:16,  2.07it/s]

Warning: File tcga_tnbc_data/54507404-a9b0-48a3-9daa-934f0f1b5f3f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  87%|████████▋ | 1042/1200 [08:52<01:15,  2.10it/s]

Warning: File tcga_tnbc_data/76effecc-ab2b-415b-a1f9-52419c41baf9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  87%|████████▋ | 1043/1200 [08:53<01:41,  1.55it/s]

Warning: File tcga_tnbc_data/ba6e046a-347b-46a9-b12d-6ee392422dac_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  87%|████████▋ | 1044/1200 [08:53<01:35,  1.64it/s]

Warning: File tcga_tnbc_data/1e60fa48-4c11-467e-b41f-45eff7b6af08_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  87%|████████▋ | 1045/1200 [08:54<01:29,  1.73it/s]

Warning: File tcga_tnbc_data/413308af-8010-4fa7-b7d6-b7257d73e3c8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  87%|████████▋ | 1046/1200 [08:54<01:27,  1.76it/s]

Warning: File tcga_tnbc_data/aab803cb-6893-4bc3-890e-49b8c29cd4d5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  87%|████████▋ | 1047/1200 [08:55<01:24,  1.82it/s]

Warning: File tcga_tnbc_data/59be0bad-0e14-44e0-a72c-0564c85ea006_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  87%|████████▋ | 1048/1200 [08:55<01:23,  1.82it/s]

Warning: File tcga_tnbc_data/8b364946-e0c7-4452-be4e-220cea70f4ce_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  87%|████████▋ | 1049/1200 [08:56<01:19,  1.90it/s]

Warning: File tcga_tnbc_data/5ca319f2-dcbb-42b2-a105-160b8aa6025b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  88%|████████▊ | 1050/1200 [08:57<01:21,  1.83it/s]

Warning: File tcga_tnbc_data/7192fb2e-98ec-405b-a865-ab15373f4301_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  88%|████████▊ | 1051/1200 [08:57<01:18,  1.89it/s]

Warning: File tcga_tnbc_data/8bbb169b-2a11-4764-86a9-fb7e7162a898_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  88%|████████▊ | 1052/1200 [08:57<01:15,  1.95it/s]

Warning: File tcga_tnbc_data/7b729078-3fcc-4042-baa9-8e8d9c97463b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  88%|████████▊ | 1053/1200 [08:58<01:15,  1.94it/s]

Warning: File tcga_tnbc_data/dbe68d32-f5f4-48fd-9df5-8e5536655ae3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  88%|████████▊ | 1054/1200 [08:59<01:16,  1.91it/s]

Warning: File tcga_tnbc_data/fb0aa257-225e-4f4e-92d7-b59017ccac93_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  88%|████████▊ | 1055/1200 [08:59<01:15,  1.92it/s]

Warning: File tcga_tnbc_data/294e7fa6-c40a-418a-8e31-3ac2249aec82_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  88%|████████▊ | 1056/1200 [09:00<01:16,  1.88it/s]

Warning: File tcga_tnbc_data/ccd9bf66-fa1a-416c-b3bb-f3fff7a964ed_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  88%|████████▊ | 1057/1200 [09:00<01:13,  1.95it/s]

Warning: File tcga_tnbc_data/002f73df-6c1d-4187-bab8-09908ed64a75_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  88%|████████▊ | 1058/1200 [09:01<01:12,  1.97it/s]

Warning: File tcga_tnbc_data/3d8bc01a-49a3-4813-a12a-8582e4c58a14_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  88%|████████▊ | 1059/1200 [09:01<01:08,  2.06it/s]

Warning: File tcga_tnbc_data/166203ec-93c4-45cb-9906-8fbc8156d388_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  88%|████████▊ | 1060/1200 [09:02<01:11,  1.96it/s]

Warning: File tcga_tnbc_data/6bb91f05-41b6-4af2-b336-9cd7e92fd407_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  88%|████████▊ | 1061/1200 [09:02<01:09,  1.99it/s]

Warning: File tcga_tnbc_data/45f252ae-f837-4a81-bf3a-3e950f2ea5f8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  88%|████████▊ | 1062/1200 [09:03<01:08,  2.00it/s]

Warning: File tcga_tnbc_data/cbaaa15f-9fc5-43a2-8025-9b7529f7d61b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  89%|████████▊ | 1063/1200 [09:03<01:08,  2.01it/s]

Warning: File tcga_tnbc_data/79ab1074-d958-4de9-98a6-934277350b07_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  89%|████████▊ | 1064/1200 [09:04<01:07,  2.02it/s]

Warning: File tcga_tnbc_data/89663744-7c27-4310-a869-03fb9b499df0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  89%|████████▉ | 1065/1200 [09:04<01:07,  2.01it/s]

Warning: File tcga_tnbc_data/d53b4011-ae3c-47c2-b2cb-b722e457490f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  89%|████████▉ | 1066/1200 [09:05<01:07,  2.00it/s]

Warning: File tcga_tnbc_data/540f5a9f-330b-4817-baa6-490b83237292_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  89%|████████▉ | 1067/1200 [09:05<01:05,  2.02it/s]

Warning: File tcga_tnbc_data/d838c396-1196-49a9-adf0-0daf56187b1b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  89%|████████▉ | 1068/1200 [09:05<01:03,  2.07it/s]

Warning: File tcga_tnbc_data/c680a261-9fdf-48dd-9e87-274881d700c8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  89%|████████▉ | 1069/1200 [09:06<01:06,  1.97it/s]

Warning: File tcga_tnbc_data/f07843bd-9399-494d-856a-b53b2c364c3e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  89%|████████▉ | 1070/1200 [09:07<01:06,  1.97it/s]

Warning: File tcga_tnbc_data/c46637b9-d9e2-4652-800d-f037b8a8d204_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  89%|████████▉ | 1071/1200 [09:07<01:06,  1.95it/s]

Warning: File tcga_tnbc_data/dd4fcd4e-4c66-47b2-80a1-1d7aba2d0b4c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  89%|████████▉ | 1072/1200 [09:08<01:05,  1.96it/s]

Warning: File tcga_tnbc_data/5832479e-b21c-4613-9f88-87e21fd65475_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  89%|████████▉ | 1073/1200 [09:08<01:07,  1.89it/s]

Warning: File tcga_tnbc_data/533dcb1b-2216-4186-8fa5-90ff3b85b1af_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  90%|████████▉ | 1074/1200 [09:09<01:04,  1.96it/s]

Warning: File tcga_tnbc_data/e278cd4c-5cbb-42f7-9fc9-cc2c94a2bd4e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  90%|████████▉ | 1075/1200 [09:09<01:06,  1.88it/s]

Warning: File tcga_tnbc_data/a4ca193e-ee85-492b-b313-4e1bafc1e977_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  90%|████████▉ | 1076/1200 [09:10<01:04,  1.92it/s]

Warning: File tcga_tnbc_data/a9b9b321-f00e-4cdc-8b8c-92a377f89572_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  90%|████████▉ | 1077/1200 [09:10<01:07,  1.83it/s]

Warning: File tcga_tnbc_data/153f3345-4527-454e-9aa4-1cdde6d90512_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  90%|████████▉ | 1078/1200 [09:11<01:02,  1.95it/s]

Warning: File tcga_tnbc_data/91cf017e-0026-4939-b9b0-151b13397092_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  90%|████████▉ | 1079/1200 [09:11<00:59,  2.04it/s]

Warning: File tcga_tnbc_data/c13e5279-5a75-4470-8e8d-ed07f5d290be_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  90%|█████████ | 1080/1200 [09:12<00:58,  2.04it/s]

Warning: File tcga_tnbc_data/4bf14da6-816b-4ded-a43c-6156560da9f6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  90%|█████████ | 1081/1200 [09:12<01:02,  1.90it/s]

Warning: File tcga_tnbc_data/eb9bccdb-06ac-4936-ac3c-73b9eb60098b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  90%|█████████ | 1082/1200 [09:13<01:00,  1.95it/s]

Warning: File tcga_tnbc_data/5b221489-e4aa-4159-b29d-dc419328ece1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  90%|█████████ | 1083/1200 [09:13<01:01,  1.90it/s]

Warning: File tcga_tnbc_data/2a3fd28d-255b-4079-8348-029bd0755803_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  90%|█████████ | 1084/1200 [09:14<00:59,  1.94it/s]

Warning: File tcga_tnbc_data/25887338-b88d-4b8a-90a5-4b268fed148f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  90%|█████████ | 1085/1200 [09:14<01:03,  1.81it/s]

Warning: File tcga_tnbc_data/ac371bfe-2b05-4c3b-b878-4936c2320ab8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  90%|█████████ | 1086/1200 [09:15<00:58,  1.95it/s]

Warning: File tcga_tnbc_data/8348587d-a17a-4f7c-9df4-900ef7e3ee88_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  91%|█████████ | 1087/1200 [09:15<00:56,  2.01it/s]

Warning: File tcga_tnbc_data/0ebe924f-9ca9-45fc-8947-67fc6e1fb3d8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  91%|█████████ | 1088/1200 [09:16<00:56,  1.97it/s]

Warning: File tcga_tnbc_data/cb4ee6d3-8e15-4209-9b80-ff2ac3b97f7b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  91%|█████████ | 1089/1200 [09:16<00:53,  2.09it/s]

Warning: File tcga_tnbc_data/de750a3e-5286-44ec-a701-bcaa7a06e569_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  91%|█████████ | 1090/1200 [09:17<00:55,  1.97it/s]

Warning: File tcga_tnbc_data/e348dc0f-1105-43b4-a74a-6494593d338b_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  91%|█████████ | 1091/1200 [09:17<00:57,  1.90it/s]

Warning: File tcga_tnbc_data/b9bb9e55-ac52-4966-8dfa-879cefbc2cb2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  91%|█████████ | 1092/1200 [09:18<00:55,  1.96it/s]

Warning: File tcga_tnbc_data/747873af-ecdc-4cf5-9486-c3008456c685_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  91%|█████████ | 1093/1200 [09:18<00:53,  1.98it/s]

Warning: File tcga_tnbc_data/f2c479c0-f730-4751-a83c-8be312ea9f04_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  91%|█████████ | 1094/1200 [09:19<00:56,  1.88it/s]

Warning: File tcga_tnbc_data/16900217-2566-44d5-ab69-da58011b9f8a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  91%|█████████▏| 1095/1200 [09:20<00:55,  1.89it/s]

Warning: File tcga_tnbc_data/7f4749c7-725a-40d3-92a2-f745c94c75a1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  91%|█████████▏| 1096/1200 [09:20<00:52,  1.99it/s]

Warning: File tcga_tnbc_data/1cdda976-7910-4eb4-812f-c98b74ff1e07_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  91%|█████████▏| 1097/1200 [09:21<00:56,  1.82it/s]

Warning: File tcga_tnbc_data/1299ef53-eedc-4b49-99f5-888c347cd445_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  92%|█████████▏| 1098/1200 [09:21<00:51,  1.99it/s]

Warning: File tcga_tnbc_data/38427d4f-e677-41e0-abaa-e0fd094e5237_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  92%|█████████▏| 1099/1200 [09:22<00:54,  1.84it/s]

Warning: File tcga_tnbc_data/ced45efd-cd54-44ea-b80e-ff04b1f061a6_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  92%|█████████▏| 1100/1200 [09:22<00:51,  1.94it/s]

Warning: File tcga_tnbc_data/ef82a51b-93d6-4392-b6a1-6b0d8f863685_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  92%|█████████▏| 1101/1200 [09:23<00:48,  2.03it/s]

Warning: File tcga_tnbc_data/688378b3-998b-4b03-999b-b021ea26dbf0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  92%|█████████▏| 1102/1200 [09:23<00:47,  2.06it/s]

Warning: File tcga_tnbc_data/e3d63f30-4993-4def-8da5-e3af4202c98c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  92%|█████████▏| 1103/1200 [09:24<00:48,  2.01it/s]

Warning: File tcga_tnbc_data/7f77d610-f045-4640-9670-8c7e89dc7945_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  92%|█████████▏| 1104/1200 [09:24<00:47,  2.02it/s]

Warning: File tcga_tnbc_data/6af66fac-e9dc-43a7-b553-e54cd9e99896_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  92%|█████████▏| 1105/1200 [09:25<00:48,  1.95it/s]

Warning: File tcga_tnbc_data/ae41e3be-2fb2-4545-9b8f-5c5984d6bbf0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  92%|█████████▏| 1106/1200 [09:25<00:49,  1.90it/s]

Warning: File tcga_tnbc_data/d2366daf-c8d3-4384-ac08-ec0f245d8618_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  92%|█████████▏| 1107/1200 [09:26<00:47,  1.97it/s]

Warning: File tcga_tnbc_data/2bd8a058-6019-49bc-a56b-42fd8b227db7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  92%|█████████▏| 1108/1200 [09:26<00:46,  1.97it/s]

Warning: File tcga_tnbc_data/e279bb98-3f06-49bc-adff-24185116aa74_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  92%|█████████▏| 1109/1200 [09:27<00:46,  1.95it/s]

Warning: File tcga_tnbc_data/dc3fe022-54ca-43a3-a8aa-94c08635e04f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  92%|█████████▎| 1110/1200 [09:27<00:44,  2.02it/s]

Warning: File tcga_tnbc_data/bf43a3fc-c747-42e3-b607-1cb08cb0f78a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  93%|█████████▎| 1111/1200 [09:28<00:47,  1.85it/s]

Warning: File tcga_tnbc_data/4fc33c92-be6c-4239-8318-528527f49faf_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  93%|█████████▎| 1112/1200 [09:28<00:44,  1.96it/s]

Warning: File tcga_tnbc_data/38dafa49-8904-4098-9b2a-14c2616607d5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  93%|█████████▎| 1113/1200 [09:29<00:44,  1.94it/s]

Warning: File tcga_tnbc_data/b3a879c2-c96a-44ca-8ab9-b77ced6d0729_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  93%|█████████▎| 1114/1200 [09:29<00:43,  2.00it/s]

Warning: File tcga_tnbc_data/34b0683c-0ec2-4dc2-8dfb-cb906b1c45e1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  93%|█████████▎| 1115/1200 [09:30<00:41,  2.05it/s]

Warning: File tcga_tnbc_data/c4d1f019-3e1d-42a3-8f78-4ff63b25b4af_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  93%|█████████▎| 1116/1200 [09:30<00:41,  2.01it/s]

Warning: File tcga_tnbc_data/e01340a2-770f-43a4-96ba-c1223f105964_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  93%|█████████▎| 1117/1200 [09:31<00:43,  1.90it/s]

Warning: File tcga_tnbc_data/8aa6c876-e83d-4487-987d-b556ac07f4ad_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  93%|█████████▎| 1118/1200 [09:31<00:43,  1.90it/s]

Warning: File tcga_tnbc_data/386a3d1f-d3fc-40a8-9b85-846301a6d242_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  93%|█████████▎| 1119/1200 [09:32<00:40,  2.01it/s]

Warning: File tcga_tnbc_data/c2b7c87a-5508-424e-ba34-fe3d859ceca1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  93%|█████████▎| 1120/1200 [09:32<00:38,  2.08it/s]

Warning: File tcga_tnbc_data/457906f2-5c59-46a7-abdc-1ebce70de203_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  93%|█████████▎| 1121/1200 [09:33<00:37,  2.11it/s]

Warning: File tcga_tnbc_data/2265e04b-5eaa-48d9-94d8-796d2d80f22d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  94%|█████████▎| 1122/1200 [09:33<00:37,  2.11it/s]

Warning: File tcga_tnbc_data/a1852e52-ac0d-4e5b-bf75-03765e80ab57_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  94%|█████████▎| 1123/1200 [09:34<00:36,  2.12it/s]

Warning: File tcga_tnbc_data/9c322d05-b8a2-43cf-a25e-7e90cf8e85fc_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  94%|█████████▎| 1124/1200 [09:34<00:36,  2.09it/s]

Warning: File tcga_tnbc_data/4fa713f5-17fe-4ded-b35c-5423f897c058_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  94%|█████████▍| 1125/1200 [09:35<00:36,  2.07it/s]

Warning: File tcga_tnbc_data/1d094f05-2fda-48d4-b229-a4e03092fe57_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  94%|█████████▍| 1126/1200 [09:35<00:36,  2.05it/s]

Warning: File tcga_tnbc_data/56d317d6-6c38-4bd8-bacb-d38e93afba52_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  94%|█████████▍| 1127/1200 [09:36<00:39,  1.84it/s]

Warning: File tcga_tnbc_data/3f05e5c9-3855-418b-a6e4-6351712dba97_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  94%|█████████▍| 1128/1200 [09:36<00:37,  1.91it/s]

Warning: File tcga_tnbc_data/5a7be94c-d446-479e-93cd-a34f6e27153d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  94%|█████████▍| 1129/1200 [09:37<00:38,  1.83it/s]

Warning: File tcga_tnbc_data/62e81954-8dfc-42f9-98d4-dbfd0efc727a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  94%|█████████▍| 1130/1200 [09:37<00:37,  1.87it/s]

Warning: File tcga_tnbc_data/d77641e2-391d-4f64-858b-2c7fb2b492cd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  94%|█████████▍| 1131/1200 [09:38<00:35,  1.94it/s]

Warning: File tcga_tnbc_data/0df5c188-00ed-4407-9057-5d97df62e6f2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  94%|█████████▍| 1132/1200 [09:38<00:31,  2.13it/s]

Warning: File tcga_tnbc_data/5f095211-00ea-4e59-9b88-4eba00973fec_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  94%|█████████▍| 1133/1200 [09:39<00:31,  2.11it/s]

Warning: File tcga_tnbc_data/d89ab176-7669-47d8-9a8f-9334d4928735_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  94%|█████████▍| 1134/1200 [09:39<00:31,  2.08it/s]

Warning: File tcga_tnbc_data/d4937854-4d0d-4e68-b08f-916d23c87446_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  95%|█████████▍| 1135/1200 [09:40<00:39,  1.65it/s]

Warning: File tcga_tnbc_data/a0f2508c-e6f6-421d-9c26-c4d3c161dc24_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  95%|█████████▍| 1136/1200 [09:41<00:38,  1.68it/s]

Warning: File tcga_tnbc_data/b92eefed-5f1f-4a17-bd90-717153f023c7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  95%|█████████▍| 1137/1200 [09:41<00:34,  1.83it/s]

Warning: File tcga_tnbc_data/53e0f82f-80ca-46c1-b409-1605fbfea3bd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  95%|█████████▍| 1138/1200 [09:42<00:33,  1.87it/s]

Warning: File tcga_tnbc_data/8c851028-31ea-4bfb-835d-a5ebb722131c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  95%|█████████▍| 1139/1200 [09:42<00:33,  1.84it/s]

Warning: File tcga_tnbc_data/22bbada8-1c32-4c82-8bf0-3d71dce76841_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  95%|█████████▌| 1140/1200 [09:43<00:31,  1.89it/s]

Warning: File tcga_tnbc_data/49e34d2a-5ef0-4314-90b6-6a7ee887a541_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  95%|█████████▌| 1141/1200 [09:43<00:30,  1.95it/s]

Warning: File tcga_tnbc_data/2d1240f7-4d76-4364-87bc-943032f84702_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  95%|█████████▌| 1142/1200 [09:44<00:29,  1.98it/s]

Warning: File tcga_tnbc_data/f233bba2-88a0-4856-ab6f-0bfaf3f46ca4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  95%|█████████▌| 1143/1200 [09:44<00:28,  2.00it/s]

Warning: File tcga_tnbc_data/8b2999ed-78b2-4ced-adf4-b7ffbfee4b7f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  95%|█████████▌| 1144/1200 [09:44<00:27,  2.04it/s]

Warning: File tcga_tnbc_data/bfae82ee-70b1-4294-943c-3275bca4cebd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  95%|█████████▌| 1145/1200 [09:45<00:26,  2.05it/s]

Warning: File tcga_tnbc_data/a1ed6dca-3f6a-4824-887b-70cadb2f720c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  96%|█████████▌| 1146/1200 [09:45<00:26,  2.05it/s]

Warning: File tcga_tnbc_data/dda41694-ea43-4044-a1a6-7c445734c36c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  96%|█████████▌| 1147/1200 [09:46<00:28,  1.88it/s]

Warning: File tcga_tnbc_data/2bcb932d-2829-49a0-a30c-083ac9ff5c40_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  96%|█████████▌| 1148/1200 [09:47<00:26,  1.93it/s]

Warning: File tcga_tnbc_data/17e0d741-efb2-463b-ab38-7b9f8e449cc2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  96%|█████████▌| 1149/1200 [09:47<00:26,  1.92it/s]

Warning: File tcga_tnbc_data/764c4086-b9b7-467f-b572-4e8cbb93dc63_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  96%|█████████▌| 1150/1200 [09:48<00:25,  1.95it/s]

Warning: File tcga_tnbc_data/83bab9ef-ce9c-42c0-b103-f22f7c4abfc4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  96%|█████████▌| 1151/1200 [09:48<00:23,  2.05it/s]

Warning: File tcga_tnbc_data/c487acbe-618e-4444-903b-28c7a6fdffa0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  96%|█████████▌| 1152/1200 [09:49<00:23,  2.06it/s]

Warning: File tcga_tnbc_data/953070df-3af0-4580-985c-d816272cd4cd_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  96%|█████████▌| 1153/1200 [09:49<00:22,  2.13it/s]

Warning: File tcga_tnbc_data/f7d07de5-5429-446e-8aec-e7e2c4cb4c6d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  96%|█████████▌| 1154/1200 [09:49<00:21,  2.15it/s]

Warning: File tcga_tnbc_data/0590b55f-e322-4e93-b111-5e9b5241d393_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  96%|█████████▋| 1155/1200 [09:50<00:22,  2.03it/s]

Warning: File tcga_tnbc_data/f649a28b-0785-423b-8d46-5678266f721e_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  96%|█████████▋| 1156/1200 [09:50<00:20,  2.11it/s]

Warning: File tcga_tnbc_data/16f92138-89b8-44cb-a087-b940763c02f7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  96%|█████████▋| 1157/1200 [09:51<00:20,  2.13it/s]

Warning: File tcga_tnbc_data/072cca80-129c-4f94-b5bd-7595f22c779d_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  96%|█████████▋| 1158/1200 [09:51<00:19,  2.17it/s]

Warning: File tcga_tnbc_data/a82435ff-b4dc-4e27-8864-8dffec520b68_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  97%|█████████▋| 1159/1200 [09:52<00:19,  2.13it/s]

Warning: File tcga_tnbc_data/9e44b206-f1ff-4285-9dea-c848c7f47e9c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  97%|█████████▋| 1160/1200 [09:52<00:18,  2.17it/s]

Warning: File tcga_tnbc_data/b5d660fd-da9a-44b3-8ccf-b7777ffefca2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  97%|█████████▋| 1161/1200 [09:53<00:18,  2.07it/s]

Warning: File tcga_tnbc_data/0183a137-ce52-4716-9b50-d65d979d07c5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  97%|█████████▋| 1162/1200 [09:53<00:17,  2.13it/s]

Warning: File tcga_tnbc_data/ce2c980d-3cac-42af-9651-7da04b14183f_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  97%|█████████▋| 1163/1200 [09:54<00:18,  1.95it/s]

Warning: File tcga_tnbc_data/3fd4e7c0-63ba-4d26-bb4c-f7938527fa9a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  97%|█████████▋| 1164/1200 [09:54<00:18,  1.91it/s]

Warning: File tcga_tnbc_data/aa36ff74-0afe-4e5a-8bf7-64ab71c4e09a_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  97%|█████████▋| 1165/1200 [09:55<00:17,  2.03it/s]

Warning: File tcga_tnbc_data/981285c2-a019-40fd-b96d-3b1b21cf7fd9_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  97%|█████████▋| 1166/1200 [09:55<00:17,  1.90it/s]

Warning: File tcga_tnbc_data/5463e6ce-b3e3-46ef-bde4-8b25af4ecdb7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  97%|█████████▋| 1167/1200 [09:56<00:15,  2.09it/s]

Warning: File tcga_tnbc_data/856370c1-163c-4915-b71b-be8731c012e2_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  97%|█████████▋| 1168/1200 [09:56<00:15,  2.08it/s]

Warning: File tcga_tnbc_data/ce7e1f99-862b-446f-bcac-664371d62d68_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  97%|█████████▋| 1169/1200 [09:57<00:14,  2.09it/s]

Warning: File tcga_tnbc_data/f778028d-cc55-465f-a541-28ae7c2e5289_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  98%|█████████▊| 1170/1200 [09:57<00:14,  2.03it/s]

Warning: File tcga_tnbc_data/e83786fa-9cf0-404a-a326-7f5be3b22086_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  98%|█████████▊| 1171/1200 [09:58<00:14,  2.01it/s]

Warning: File tcga_tnbc_data/c9304075-c938-436b-a617-8e0d08b06f29_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  98%|█████████▊| 1172/1200 [09:58<00:14,  1.96it/s]

Warning: File tcga_tnbc_data/2afb9195-37c8-4e8c-9b39-53a2eefa6d31_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  98%|█████████▊| 1173/1200 [09:59<00:13,  1.95it/s]

Warning: File tcga_tnbc_data/68ce2616-d652-4e1c-8389-a22e875ed245_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  98%|█████████▊| 1174/1200 [09:59<00:13,  1.91it/s]

Warning: File tcga_tnbc_data/242669ce-6888-44b0-aae7-2bad4cccac4c_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  98%|█████████▊| 1175/1200 [10:00<00:12,  1.93it/s]

Warning: File tcga_tnbc_data/ec88c66b-3789-49a6-8479-5b2524858938_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  98%|█████████▊| 1176/1200 [10:00<00:12,  1.88it/s]

Warning: File tcga_tnbc_data/e275259d-aa1d-45ab-937c-6263a61a6cc8_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  98%|█████████▊| 1177/1200 [10:01<00:12,  1.82it/s]

Warning: File tcga_tnbc_data/2abc050a-c290-416a-b16f-1228c3ff0e39_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  98%|█████████▊| 1178/1200 [10:02<00:12,  1.72it/s]

Warning: File tcga_tnbc_data/c1e1d097-8593-4f45-9c88-cfa4c905d8b5_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  98%|█████████▊| 1179/1200 [10:02<00:11,  1.80it/s]

Warning: File tcga_tnbc_data/ea6594eb-a7a7-4aa9-a6b3-28a312c3adb4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  98%|█████████▊| 1180/1200 [10:03<00:11,  1.80it/s]

Warning: File tcga_tnbc_data/5d2a2e56-1301-4c5c-a26b-e8572281a3c3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  98%|█████████▊| 1181/1200 [10:03<00:10,  1.80it/s]

Warning: File tcga_tnbc_data/69040223-f00b-487d-832c-18f9a7b6cd58_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  98%|█████████▊| 1182/1200 [10:04<00:09,  1.87it/s]

Warning: File tcga_tnbc_data/06a337bb-c5f5-47a6-b3bd-beacb5fd62c7_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  99%|█████████▊| 1183/1200 [10:04<00:08,  1.89it/s]

Warning: File tcga_tnbc_data/6a06c9d6-3937-44c1-9e11-dddb3ba787b1_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  99%|█████████▊| 1184/1200 [10:05<00:08,  1.84it/s]

Warning: File tcga_tnbc_data/e5ece39d-fffb-46fc-bd88-47e56bb3ab70_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  99%|█████████▉| 1185/1200 [10:05<00:08,  1.80it/s]

Warning: File tcga_tnbc_data/90879f6d-e07a-480d-ab46-5e654b2c8030_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  99%|█████████▉| 1186/1200 [10:06<00:08,  1.72it/s]

Warning: File tcga_tnbc_data/1bdfaf91-88ec-4f4c-a14b-4a51a452bb28_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  99%|█████████▉| 1187/1200 [10:07<00:07,  1.83it/s]

Warning: File tcga_tnbc_data/e143cf9e-f313-4531-9962-bb55eb536a08_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  99%|█████████▉| 1188/1200 [10:07<00:06,  1.91it/s]

Warning: File tcga_tnbc_data/6787d656-d1ba-4396-be89-4e5532d643d0_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  99%|█████████▉| 1189/1200 [10:08<00:05,  1.90it/s]

Warning: File tcga_tnbc_data/37711a35-8e49-4c60-b1d1-572eff8b1f45_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  99%|█████████▉| 1190/1200 [10:08<00:05,  1.95it/s]

Warning: File tcga_tnbc_data/b5db0bf7-8c2d-41d8-814a-8eee45608c50_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  99%|█████████▉| 1191/1200 [10:08<00:04,  1.99it/s]

Warning: File tcga_tnbc_data/9645852b-d2bd-42db-bad3-078254bcc846_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  99%|█████████▉| 1192/1200 [10:09<00:04,  1.79it/s]

Warning: File tcga_tnbc_data/cb3da44f-e477-4ef3-bd43-3d2019d54f15_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files:  99%|█████████▉| 1193/1200 [10:10<00:03,  1.83it/s]

Warning: File tcga_tnbc_data/14b87f56-49b4-4c5a-8f98-6f02e74601e4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files: 100%|█████████▉| 1194/1200 [10:10<00:03,  1.92it/s]

Warning: File tcga_tnbc_data/6b1c475e-b897-457e-a6b7-3aad397202b4_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files: 100%|█████████▉| 1195/1200 [10:11<00:02,  1.92it/s]

Warning: File tcga_tnbc_data/d2741347-364d-4664-82ce-c4b3dff02c17_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files: 100%|█████████▉| 1196/1200 [10:11<00:02,  1.98it/s]

Warning: File tcga_tnbc_data/fae25d1e-3054-4428-b4fd-1b7cec89c4ef_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files: 100%|█████████▉| 1197/1200 [10:12<00:01,  1.99it/s]

Warning: File tcga_tnbc_data/c881c6c9-2774-4208-a528-83595c1618d3_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files: 100%|█████████▉| 1198/1200 [10:12<00:00,  2.17it/s]

Warning: File tcga_tnbc_data/0b9c4345-bf3a-4de7-a022-4039f93d7b27_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files: 100%|█████████▉| 1199/1200 [10:12<00:00,  2.16it/s]

Warning: File tcga_tnbc_data/1170b43b-b3cc-452d-a852-60646bd25420_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

Downloading miRNA files: 100%|██████████| 1200/1200 [10:13<00:00,  1.96it/s]

Warning: File tcga_tnbc_data/99359a4e-5bd3-4a80-99a4-f00be159e0ea_mirna.tsv.gz is not gzipped despite extension. Attempting to read as plain TSV with comments.

miRNA matrix saved to: tcga_tnbc_data/TCGA_BRCA_miRNA_matrix.csv

In [4]:
import os
from pathlib import Path

OUTPUT_DIR = Path("tcga_tnbc_data")

if OUTPUT_DIR.exists() and OUTPUT_DIR.is_dir():
    print(f"Contents of '{OUTPUT_DIR}':")
    for item in os.listdir(OUTPUT_DIR):
        print(f"- {item}")
else:
    print(f"Directory '{OUTPUT_DIR}' does not exist.")

Contents of 'tcga_tnbc_data':
- TCGA_BRCA_RNAseq_matrix.csv
- TCGA_BRCA_miRNA_matrix.csv

### Running Differential Gene Expression Analysis

Now that the RNA-seq expression matrix and clinical data (including TNBC status) are available, we can proceed with the differential gene expression analysis (DEG). This step will identify genes that are significantly differentially expressed between TNBC and non-TNBC samples.

In [6]:
import pandas as pd
import numpy as np
from scipy import stats
from pathlib import Path
from statsmodels.stats.multitest import multipletests

OUTPUT_DIR = Path("tcga_tnbc_data")


def simple_deg_analysis(
    rna_matrix_path,
    clinical_path,
    output_deg_path,
    tnbc_col="TNBC",
    min_samples_per_group=5,
):
    expr = pd.read_csv(rna_matrix_path, index_col=0)
    clin = pd.read_csv(clinical_path)

    # Map sample names in expression to submitter_id / case barcode
    # Expression columns are like: TCGA-XX-XXXX_ Primary Tumor
    # We'll extract the TCGA barcode part before the first underscore.
    def extract_barcode(col):
        return str(col).split("_")[0]

    sample_barcodes = [extract_barcode(c) for c in expr.columns]
    expr_tmp = expr.copy()
    expr_tmp.columns = sample_barcodes

    # Merge clinical info
    clin = clin.set_index("submitter_id")
    common = list(set(expr_tmp.columns) & set(clin.index))
    print(f"Common samples between expression and clinical: {len(common)}")

    expr_common = expr_tmp[common]
    clin_common = clin.loc[common]

    if tnbc_col not in clin_common.columns:
        raise ValueError(f"Column '{tnbc_col}' not found in clinical file.")

    group = clin_common[tnbc_col].astype(int)
    tnbc_samples = group[group == 1].index.tolist()
    other_samples = group[group == 0].index.tolist()

    if len(tnbc_samples) < min_samples_per_group or len(other_samples) < min_samples_per_group:
        raise ValueError("Not enough samples in one of the groups.")

    # Simple t-test per gene
    genes = expr_common.index.tolist()
    logfc_list = []
    pvals = []

    for g in genes:
        x = expr_common.loc[g, tnbc_samples].astype(float).dropna()
        y = expr_common.loc[g, other_samples].astype(float).dropna()

        if len(x) < 2 or len(y) < 2:
            logfc_list.append(np.nan)
            pvals.append(1.0)
            continue

        m1 = np.log2(x + 1).mean()
        m2 = np.log2(y + 1).mean()
        logfc = m1 - m2

        # t-test on log2(x+1)
        # The original code has an error here, stats.t_ind_test does not exist.
        # It should be stats.ttest_ind
        t_stat, p_val = stats.ttest_ind(np.log2(x + 1), np.log2(y + 1), equal_var=False) # Assuming unequal variances
        logfc_list.append(logfc)
        pvals.append(p_val)

    deg_df = pd.DataFrame({
        "gene": genes,
        "log2FC": logfc_list,
        "pval": pvals,
    })

    # FDR correction
    _, adj_pvals, _, _ = multipletests(deg_df["pval"].fillna(1.0), method="fdr_bh")
    deg_df["adj_pval"] = adj_pvals

    # Sort by adj_pval
    deg_df = deg_df.sort_values("adj_pval").reset_index(drop=True)

    deg_df.to_csv(output_deg_path, index=False)
    print(f"DEG list saved to: {output_deg_path}")
    return deg_df


if __name__ == "__main__":
    rna_matrix = OUTPUT_DIR / "TCGA_BRCA_RNAseq_matrix.csv"
    clinical = OUTPUT_DIR / "TCGA_BRCA_clinical_TNBC.csv"
    output_deg = OUTPUT_DIR / "TNBC_DEG_list_for_GO_KEGG.csv"

    if not rna_matrix.exists():
        print("RNA-seq matrix not found. Run 01_download_rnaseq_matrix.py first.")
    elif not clinical.exists():
        print("Clinical file not found. Run 03_download_clinical_TNBC.py first.")
    else:
        deg = simple_deg_analysis(rna_matrix, clinical, output_deg)

Clinical file not found. Run 03_download_clinical_TNBC.py first.

**Output:**
`tcga_tnbc_data/TCGA_BRCA_miRNA_matrix.csv` (miRNA × sample, RPM).

### 3) Clinical data with TNBC status (CSV)
This script:
- Pulls clinical data from GDC (stage, survival, etc.)
- Pulls receptor status (ER/PR/HER2) from cBioPortal’s public TCGA‑BRCA study
- Merges them and defines TNBC = ER‑, PR‑, HER2‑.

File: `03_download_clinical_TNBC.py`

In [15]:
import requests
import pandas as pd
from pathlib import Path
import time
import os # Import os module to check file size

GDC_API = "https://api.gdc.cancer.gov"
PROJECT = "TCGA-BRCA"
TOKEN_PATH = "gdc_token.txt"
OUTPUT_DIR = Path("tcga_tnbc_data")
OUTPUT_DIR.mkdir(exist_ok=True)

HEADERS_WITH_TOKEN = {}
try:
    with open(TOKEN_PATH, "r") as f:
        token = f.read().strip()
    HEADERS_WITH_TOKEN = {"X-GDC-TOKEN": token}
except FileNotFoundError:
    pass


def post_gdc(endpoint, filters, fields=None, size=200):
    url = f"{GDC_API}/{endpoint}"
    payload = {"filters": filters, "format": "JSON", "size": size}
    if fields:
        payload["fields"] = fields

    all_hits = []
    from_val = 0

    while True:
        params = {"from": from_val}
        resp = requests.post(url, params=params, json=payload, headers=HEADERS_WITH_TOKEN)
        resp.raise_for_status()
        data = resp.json()
        hits = data["data"]["hits"]
        all_hits.extend(hits)

        pagination = data["data"]["pagination"]
        # Changed 'per_page' to 'size' based on common GDC API pagination structure
        if pagination["page"] * pagination["size"] >= pagination["total"]:
            break
        from_val += pagination["size"]

    return all_hits


def get_gdc_clinical():
    filters = {
        "op": "=",
        "content": {"field": "cases.project.project_id", "value": PROJECT},
    }

    fields = ",".join([
        "case_id",
        "submitter_id",
        "demographic.gender",
        "demographic.race",
        "demographic.ethnicity",
        "diagnoses.age_at_diagnosis",
        "diagnoses.tumor_stage",
        "diagnoses.tumor_grade",
        "diagnoses.primary_diagnosis",
        "diagnoses.days_to_death",
        "diagnoses.days_to_last_follow_up",
        "diagnoses.vital_status",
        "diagnoses.progression_or_recurrence",
        "diagnoses.days_to_progression_or_recurrence",
        "diagnoses.er_status_by_ihc", # Added GDC ER status
        "diagnoses.pr_status_by_ihc", # Added GDC PR status
        "diagnoses.her2_status_by_ihc", # Added GDC HER2 status
        "samples.sample_type",
        "project.project_id",
    ])

    hits = post_gdc("cases", filters, fields=fields)

    rows = []
    for h in hits:
        case_id = h.get("case_id")
        submitter_id = h.get("submitter_id")
        demo = h.get("demographic", {})
        diag_list = h.get("diagnoses", [])
        samples_list = h.get("samples", [])

        diag = diag_list[0] if diag_list else {}
        sample = samples_list[0] if samples_list else {}

        row = {
            "case_id": case_id,
            "submitter_id": submitter_id,
            "gender": demo.get("gender"),
            "race": demo.get("race"),
            "ethnicity": demo.get("ethnicity"),
            "age_at_diagnosis": diag.get("age_at_diagnosis"),
            "tumor_stage": diag.get("tumor_stage"),
            "tumor_grade": diag.get("tumor_grade"),
            "primary_diagnosis": diag.get("primary_diagnosis"),
            "days_to_death": diag.get("days_to_death"),
            "days_to_last_follow_up": diag.get("days_to_last_follow_up"),
            "vital_status": diag.get("vital_status"),
            "progression_or_recurrence": diag.get("progression_or_recurrence"),
            "days_to_progression_or_recurrence": diag.get("days_to_progression_or_recurrence"),
            "er_status_gdc": diag.get("er_status_by_ihc"), # Extract GDC ER status
            "pr_status_gdc": diag.get("pr_status_by_ihc"), # Extract GDC PR status
            "her2_status_gdc": diag.get("her2_status_by_ihc"), # Extract GDC HER2 status
            "sample_type": sample.get("sample_type"),
            "project_id": h.get("project", {}).get("project_id"),
        }
        rows.append(row)

    clin_gdc = pd.DataFrame(rows)
    clin_gdc.to_csv(OUTPUT_DIR / "TCGA_BRCA_clinical_GDC.csv", index=False)
    print(f"GDC clinical saved to: {OUTPUT_DIR / 'TCGA_BRCA_clinical_GDC.csv'}")
    return clin_gdc


def get_cbioportal_clinical(study_id, out_file_prefix="TCGA_BRCA"):
    """
    Fetch clinical data from cBioPortal (public API) for a given study.
    We'll get patient-level attributes including ER/PR/HER2 if available.
    """
    CBIO_API = "https://www.cbioportal.org/api"

    # 1. Get all patient IDs for the study
    url_patients = f"{CBIO_API}/studies/{study_id}/patients"
    params_patients = {"pageSize": 10000} # Get all patients
    resp_patients = requests.get(url_patients, params=params_patients)
    resp_patients.raise_for_status()
    patients_summary = resp_patients.json()
    patient_ids = [p['patientId'] for p in patients_summary]

    if not patient_ids:
        print(f"No patient data found for {study_id} from cBioPortal.")
        return pd.DataFrame()

    # 2. Get all clinical attribute metadata for the study
    url_clinical_attributes = f"{CBIO_API}/studies/{study_id}/clinical-attributes"
    params_clinical_attributes = {"pageSize": 10000}
    resp_clinical_attributes = requests.get(url_clinical_attributes, params=params_clinical_attributes)
    resp_clinical_attributes.raise_for_status()
    clinical_attribute_meta = resp_clinical_attributes.json()

    # Map clinical attribute IDs to display names for column headers
    attr_id_to_name = {attr['clinicalAttributeId']: attr['displayName'] for attr in clinical_attribute_meta}

    print(f"Available clinical attributes for {study_id} (ID: Display Name):")
    for attr in clinical_attribute_meta:
        print(f"  {attr['clinicalAttributeId']}: {attr['displayName']}")

    # Explicitly define clinical attribute IDs for ER, PR, HER2 to request
    # These are specific for TCGA_BRCA, will need to be adapted for METABRIC
    relevant_attr_ids = ["ER_STATUS_BY_IHC", "PR_STATUS_BY_IHC", "HER2_IHC_STATUS"]

    # Filter for only those attributes that actually exist in the study metadata
    available_relevant_attr_ids = [aid for aid in relevant_attr_ids if aid in attr_id_to_name]
    clinical_attribute_ids_str = ",".join(available_relevant_attr_ids)

    if not clinical_attribute_ids_str:
        print(f"Warning: No known ER/PR/HER2 attributes found for {study_id}. Proceeding with all available attributes.")
        clinical_attribute_ids_str = ",".join(attr_id_to_name.keys())

    # 3. Fetch clinical data for all patients and selected attributes using GET
    url_clinical_data = f"{CBIO_API}/studies/{study_id}/clinical-data"

    all_raw_clinical_data = []
    patient_id_chunks = [patient_ids[i:i + 100] for i in range(0, len(patient_ids), 100)] # Chunk patient IDs

    for i, patient_chunk in enumerate(patient_id_chunks):
        print(f"Fetching clinical data for patient chunk {i+1}/{len(patient_id_chunks)} for {study_id}...")
        # Prepare query parameters for GET request for the current chunk
        params_clinical_data = {
            "patientIds": ",".join(patient_chunk),
            "clinicalAttributeIds": clinical_attribute_ids_str # Re-enabled to explicitly request ER/PR/HER2
        }

        # Add retry logic for the GET request
        MAX_RETRIES = 5
        for attempt in range(MAX_RETRIES):
            try:
                resp_clinical_data = requests.get(url_clinical_data, params=params_clinical_data, timeout=60)
                resp_clinical_data.raise_for_status()
                all_raw_clinical_data.extend(resp_clinical_data.json())
                break # Break out of the retry loop if successful
            except requests.exceptions.RequestException as e:
                print(f"RequestException encountered for chunk {i+1} of {study_id} (attempt {attempt + 1}/{MAX_RETRIES}): {e}")
                if attempt < MAX_RETRIES - 1:
                    time.sleep(2 ** attempt) # Exponential back-off
                else:
                    raise # Re-raise the last exception if all retries fail
        else:
            # This block is executed if the loop completes without a 'break'
            print(f"Failed to retrieve clinical data for chunk {i+1} of {study_id} after {MAX_RETRIES} attempts. Skipping this chunk.")

    # DEBUG: Print unique clinicalAttributeIds found in the raw data
    if all_raw_clinical_data:
        raw_attribute_ids = {item.get('clinicalAttributeId') for item in all_raw_clinical_data}
        print(f"Unique clinicalAttributeIds found in raw data for {study_id} (before mapping/pivot):")
        print(list(raw_attribute_ids))
    else:
        print(f"No raw clinical data returned from cBioPortal for {study_id} for the requested attributes.")

    # 4. Process raw clinical data into a DataFrame
    # The data comes in a 'long' format, need to pivot it to 'wide'
    clinical_rows = []
    for item in all_raw_clinical_data:
        clinical_rows.append({
            "patient_id": item["patientId"],
            "attribute_name": attr_id_to_name.get(item["clinicalAttributeId"], item["clinicalAttributeId"]),
            "attribute_value": item["value"]
        })

    df_clinical_long = pd.DataFrame(clinical_rows)

    if df_clinical_long.empty:
        print(f"No detailed clinical attributes found for {study_id} from cBioPortal.")
        return pd.DataFrame()

    print(f"Unique attribute names found in raw clinical data for {study_id} (before pivot):")
    print(df_clinical_long['attribute_name'].unique().tolist())

    # Handle potential duplicate (patient_id, attribute_name) combinations
    # Keep the first occurrence if duplicates exist to allow pivoting.
    df_clinical_long = df_clinical_long.drop_duplicates(subset=['patient_id', 'attribute_name'], keep='first')

    # Pivot the table to get attributes as columns
    clin_cbio = df_clinical_long.pivot(index='patient_id', columns='attribute_name', values='attribute_value')
    clin_cbio = clin_cbio.reset_index()
    clin_cbio.columns.name = None # Remove the name of the columns index

    print(f"Columns found in cBioPortal clinical data for {study_id}:")
    print(clin_cbio.columns.tolist())

    # Add a dummy sample_id for merging purposes if not naturally present
    if 'sample_id' not in clin_cbio.columns:
        clin_cbio['sample_id'] = None # Or extract from patient_id if a pattern exists

    out_path_cbio = OUTPUT_DIR / f"{out_file_prefix}_clinical_cBio.csv"
    clin_cbio.to_csv(out_path_cbio, index=False)
    print(f"cBioPortal clinical for {study_id} saved to: {out_path_cbio}")
    return clin_cbio


def merge_and_define_TNBC():
    clin_gdc = pd.read_csv(OUTPUT_DIR / "TCGA_BRCA_clinical_GDC.csv")
    clin_cbio = pd.read_csv(OUTPUT_DIR / "TCGA_BRCA_clinical_cBio.csv")

    # Map cBioPortal patient_id (e.g. TCGA-XX-XXXX) to GDC submitter_id
    # GDC submitter_id is usually the same as patient barcode.
    # We'll merge on that.
    clin_cbio = clin_cbio.rename(columns={"patient_id": "submitter_id"})

    merged = clin_gdc.merge(
        clin_cbio,
        on="submitter_id",
        how="left",
        suffixes=('_GDC', '_cBio'),
    )

    # Define ER/PR/HER2 status from GDC or cBioPortal columns
    er_col = None
    pr_col = None
    her2_col = None

    # Prioritize GDC columns first, then cBioPortal display names from metadata
    possible_er_cols = ["er_status_gdc", "ER Status By IHC", "ER_STATUS", "ER_STATUS_BY_IMMUNOHISTOCHEMISTRY", "ESTROGEN_RECEPTOR_STATUS"]
    possible_pr_cols = ["pr_status_gdc", "PR status by ihc", "PR Status By IHC", "PROGESTERONE_RECEPTOR_STATUS", "PROGESTERONE_RECEPTOR_STATUS_BY_IMMUNOHISTOCHEMISTRY"]
    possible_her2_cols = ["her2_status_gdc", "HER2 IHC Status", "HER2 Status By IHC", "HER2_STATUS", "HER2_STATUS_BY_IMMUNOHISTOCHEMISTRY"]

    for p_col in possible_er_cols:
        if p_col in merged.columns:
            er_col = p_col
            break
    for p_col in possible_pr_cols:
        if p_col in merged.columns:
            pr_col = p_col
            break
    for p_col in possible_her2_cols:
        if p_col in merged.columns:
            her2_col = p_col
            break

    print("Detected receptor columns:")
    print("ER:", er_col, "PR:", pr_col, "HER2:", her2_col)

    def is_negative(val):
        if pd.isna(val):
            return False
        v = str(val).strip().lower()
        # Also consider 'equivocal' as non-negative for TNBC definition, or handle explicitly
        return v in ["negative", "neg", "0", "no"]

    def is_positive(val):
        if pd.isna(val):
            return False
        v = str(val).strip().lower()
        return v in ["positive", "pos", "1", "yes"]

    if er_col and pr_col and her2_col:
        merged["ER_neg"] = merged[er_col].apply(is_negative)
        merged["PR_neg"] = merged[pr_col].apply(is_negative)
        merged["HER2_neg"] = merged[her2_col].apply(is_negative)

        merged["TNBC"] = (merged["ER_neg"] & merged["PR_neg"] & merged["HER2_neg"]).astype(int)
    else:
        print("Could not detect all ER/PR/HER2 columns; TNBC column will not be created.")
        merged["TNBC"] = pd.NA

    # Survival variables
    # Try to create OS_time (months) and OS_event (0/1)
    if "OS Months" in merged.columns and "OS Status" in merged.columns:
        merged["OS_months"] = merged["OS Months"]
        merged["OS_event"] = (
            merged["OS Status"]
            .astype(str)
            .str.lower()
            .map(lambda x: 1 if "deceased" in x else 0)
        )

    # Stage
    stage_col = None
    for c in merged.columns:
        if "stage" in str(c).lower() and "tumor" in str(c).lower():
            stage_col = c
            break
    if stage_col:
        merged["pathologic_stage"] = merged[stage_col]

    out_path = OUTPUT_DIR / "TCGA_BRCA_clinical_TNBC.csv"
    merged.to_csv(out_path, index=False)
    time.sleep(1) # Add a small delay to ensure file is written to disk
    print(f"Merged clinical + TNBC status saved to: {out_path}")

    # Add a check for file existence and size right after saving
    if out_path.exists():
        print(f"Confirmation: File {out_path} exists with size {os.path.getsize(out_path)} bytes.")
    else:
        print(f"Warning: File {out_path} was *not* found immediately after saving.")

    return merged


# __name__ == "__main__" block
# 1. GDC clinical
clin_gdc = get_gdc_clinical()

# 2. cBioPortal clinical (ER/PR/HER2)
clin_cbio = get_cbioportal_clinical("brca_tcga", "TCGA_BRCA")

# 3. Merge + define TNBC
merged = merge_and_define_TNBC()

GDC clinical saved to: tcga_tnbc_data/TCGA_BRCA_clinical_GDC.csv
Available clinical attributes for brca_tcga (ID: Display Name):
  AGE: Diagnosis Age
  AJCC_METASTASIS_PATHOLOGIC_PM: American Joint Committee on Cancer Metastasis Stage Code
  AJCC_NODES_PATHOLOGIC_PN: Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code
  AJCC_PATHOLOGIC_TUMOR_STAGE: Neoplasm Disease Stage American Joint Committee on Cancer Code
  AJCC_STAGING_EDITION: American Joint Committee on Cancer Publication Version Type
  AJCC_TUMOR_PATHOLOGIC_PT: American Joint Committee on Cancer Tumor Stage Code
  BRACHYTHERAPY_TOTAL_DOSE_POINT_A: Brachytherapy first reference point administered total dose
  CANCER_TYPE: Cancer Type
  CANCER_TYPE_DETAILED: Cancer Type Detailed
  CENT17_COPY_NUMBER: Cent17 Copy Number
  CLINICAL_STAGE: Neoplasm American Joint Committee on Cancer Clinical Group Stage
  CLIN_M_STAGE: Neoplasm American Joint Committee on Cancer Clinical Distant Metastasis M Stage
  CLIN_N_STAGE: Neoplasm American Joint Committee on Cancer Clinical Regional Lymph Node N Stage
  CLIN_T_STAGE: Neoplasm American Joint Committee on Cancer Clinical Primary Tumor T Stage
  DAYS_TO_COLLECTION: Days to Sample Collection.
  DAYS_TO_INITIAL_PATHOLOGIC_DIAGNOSIS: Last Alive Less Initial Pathologic Diagnosis Date Calculated Day Value
  DAYS_TO_PATIENT_PROGRESSION_FREE: days_to_patient_progression_free
  DAYS_TO_SPECIMEN_COLLECTION: Days to Sample Procurement
  DAYS_TO_TUMOR_PROGRESSION: days_to_tumor_progression
  DFS_MONTHS: Disease Free (Months)
  DFS_STATUS: Disease Free Status
  DISEASE_CODE: Disease code
  ER_POSITIVITY_SCALE_OTHER: ER positivity scale other
  ER_POSITIVITY_SCALE_USED: ER positivity scale used
  ER_STATUS_BY_IHC: ER Status By IHC
  ER_STATUS_IHC_PERCENT_POSITIVE: ER Status IHC Percent Positive
  ETHNICITY: Ethnicity Category
  EXTRANODAL_INVOLVEMENT: Lymphomatous Extranodal Site Involvement Indicator
  FIRST_SURGICAL_PROCEDURE_OTHER: First surgical procedure other
  FORM_COMPLETION_DATE: Form completion date
  FRACTION_GENOME_ALTERED: Fraction Genome Altered
  HER2_AND_CENT17_CELLS_COUNT: HER2 and cent17 cells count
  HER2_AND_CENT17_SCALE_OTHER: HER2 and cent17 scale other
  HER2_CENT17_COUNTED_CELLS_COUNT: HER2 cent17 counted cells count
  HER2_CENT17_RATIO: HER2 cent17 ratio
  HER2_COPY_NUMBER: HER2 copy number
  HER2_FISH_METHOD: HER2 fish method
  HER2_FISH_STATUS: HER2 fish status
  HER2_IHC_PERCENT_POSITIVE: HER2 ihc percent positive
  HER2_IHC_SCORE: HER2 ihc score
  HER2_POSITIVITY_METHOD_TEXT: HER2 positivity method text
  HER2_POSITIVITY_SCALE_OTHER: HER2 positivity scale other
  HISTOLOGICAL_DIAGNOSIS: Neoplasm Histologic Type Name
  HISTOLOGICAL_SUBTYPE: Tumor Other Histologic Subtype
  HISTORY_NEOADJUVANT_TRTYN: Neoadjuvant Therapy Type Administered Prior To Resection Text
  HISTORY_OTHER_MALIGNANCY: Prior Cancer Diagnosis Occurence
  ICD_10: ICD-10 Classification
  ICD_O_3_HISTOLOGY: International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code
  ICD_O_3_SITE: International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code
  IHC_HER2: IHC-HER2
  IHC_SCORE: IHC Score
  INFORMED_CONSENT_VERIFIED: Informed consent verified
  INITIAL_PATHOLOGIC_DX_YEAR: Year Cancer Initial Diagnosis
  IS_FFPE: Is FFPE
  LONGEST_DIMENSION: Longest Dimension
  LYMPH_NODES_EXAMINED: Primary Lymph Node Presentation Assessment Ind-3
  LYMPH_NODES_EXAMINED_HE_COUNT: Positive Finding Lymph Node Hematoxylin and Eosin Staining Microscopy Count
  LYMPH_NODES_EXAMINED_IHC_COUNT: Positive Finding Lymph Node Keratin Immunohistochemistry Staining Method Count
  LYMPH_NODE_EXAMINED_COUNT: Lymph Node(s) Examined Number
  MARGIN_STATUS_REEXCISION: Margin status reexcision
  MENOPAUSE_STATUS: Menopause Status
  METASTATIC_SITE_OTHER: Metastatic Site Other
  METASTATIC_SITE_PATIENT: Patient Metastatic Sites
  METASTATIC_TUMOR_INDICATOR: Metastatic tumor indicator
  METHOD_OF_INITIAL_SAMPLE_PROCUREMENT: First Pathologic Diagnosis Biospecimen Acquisition Method Type
  METHOD_OF_INITIAL_SAMPLE_PROCUREMENT_OTHER: First Pathologic Diagnosis Biospecimen Acquisition Other Method Type
  METHOD_OF_SAMPLE_PROCUREMENT: First Pathologic Diagnosis Biospecimen Acquisition Method Type
  MICROMET_DETECTION_BY_IHC: Micromet detection by ihc
  MUTATION_COUNT: Mutation Count
  NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT: New Neoplasm Event Post Initial Therapy Indicator
  NTE_CENT17_HER2_OTHER_SCALE: Nte cent17 HER2 other scale
  NTE_CENT_17_HER2_RATIO: Nte cent 17 HER2 ratio
  NTE_CENT_17_SIGNAL_NUMBER: Nte cent 17 signal number
  NTE_ER_IHC_INTENSITY_SCORE: Nte er ihc intensity score
  NTE_ER_POSITIVITY_DEFINE_METHOD: Nte er positivity define method
  NTE_ER_POSITIVITY_OTHER_SCALE: Nte er positivity other scale
  NTE_ER_STATUS: Nte er status
  NTE_ER_STATUS_IHC_POSITIVE: Nte er status ihc positive
  NTE_HER2_FISH_DEFINE_METHOD: Nte HER2 fish define method
  NTE_HER2_FISH_STATUS: Nte HER2 fish status
  NTE_HER2_POSITIVITY_IHC_SCORE: Nte HER2 positivity ihc score
  NTE_HER2_POSITIVITY_METHOD: Nte HER2 positivity method
  NTE_HER2_POSITIVITY_OTHER_SCALE: Nte HER2 positivity other scale
  NTE_HER2_SIGNAL_NUMBER: Nte HER2 signal number
  NTE_HER2_STATUS: Nte HER2 status
  NTE_HER2_STATUS_IHC_POSITIVE: Nte HER2 status ihc positive
  NTE_PR_IHC_INTENSITY_SCORE: Nte pr ihc intensity score
  NTE_PR_POSITIVITY_DEFINE_METHOD: Nte pr positivity define method
  NTE_PR_POSITIVITY_OTHER_SCALE: Nte pr positivity other scale
  NTE_PR_STATUS_BY_IHC: Nte pr status by ihc
  NTE_PR_STATUS_IHC_POSITIVE: Nte pr status ihc positive
  OCT_EMBEDDED: Oct embedded
  ONCOTREE_CODE: Oncotree Code
  OS_MONTHS: Overall Survival (Months)
  OS_STATUS: Overall Survival Status
  OTHER_METHOD_OF_SAMPLE_PROCUREMENT: Specimen Collection Method
  OTHER_PATIENT_ID: Other Patient ID
  OTHER_SAMPLE_ID: Other Sample ID
  PATHOLOGY_REPORT_FILE_NAME: Pathology Report File Name
  PATHOLOGY_REPORT_UUID: Pathology report uuid
  PATH_MARGIN: Disease Surgical Margin Status
  PHARMACEUTICAL_TX_ADJUVANT: Adjuvant Postoperative Pharmaceutical Therapy Administered Indicator
  PRIMARY_SITE_OTHER: Primary Other Site of Disease Name
  PRIMARY_SITE_PATIENT: Patient Primary Tumor Site
  PROJECT_CODE: Project code
  PROSPECTIVE_COLLECTION: Tissue Prospective Collection Indicator
  PR_POSITIVITY_DEFINE_METHOD: PR positivity define method
  PR_POSITIVITY_IHC_INTENSITY_SCORE: PR positivity ihc intensity score
  PR_POSITIVITY_SCALE_OTHER: PR positivity scale other
  PR_POSITIVITY_SCALE_USED: PR positivity scale used
  PR_STATUS_BY_IHC: PR status by ihc
  PR_STATUS_IHC_PERCENT_POSITIVE: PR status ihc percent positive
  RACE: Race Category
  RADIATION_TREATMENT_ADJUVANT: Did patient start adjuvant postoperative radiotherapy?
  RETROSPECTIVE_COLLECTION: Tissue Retrospective Collection Indicator
  SAMPLE_COUNT: Number of Samples Per Patient
  SAMPLE_INITIAL_WEIGHT: Sample Initial Weight
  SAMPLE_TYPE: Sample Type
  SAMPLE_TYPE_ID: Sample type id
  SEX: Sex
  SHORTEST_DIMENSION: Shortest Dimension
  SITE_OF_TUMOR_TISSUE: Tumor Tissue Site
  SOMATIC_STATUS: Somatic Status
  SPECIMEN_CURRENT_WEIGHT: Specimen Current Weight
  SPECIMEN_FREEZING_METHOD: Specimen Freezing Means
  SPECIMEN_SECOND_LONGEST_DIMENSION: Specimen Second Longest Dimension
  STAGE_OTHER: Stage Other
  STAGING_SYSTEM: Staging System
  STAGING_SYSTEM_OTHER: Staging System.1
  SURGERY_FOR_POSITIVE_MARGINS: Surgery for positive margins
  SURGERY_FOR_POSITIVE_MARGINS_OTHER: Surgery for positive margins other
  SURGICAL_PROCEDURE_FIRST: Surgical procedure first
  TIME_BETWEEN_CLAMPING_AND_FREEZING: Time between clamping and freezing
  TIME_BETWEEN_EXCISION_AND_FREEZING: Time between excision and freezing
  TISSUE_SOURCE_SITE: Tissue Source Site
  TMB_NONSYNONYMOUS: TMB (nonsynonymous)
  TUMOR_STATUS: Person Neoplasm Status
  VIAL_NUMBER: Vial number
Fetching clinical data for patient chunk 1/12 for brca_tcga...
Fetching clinical data for patient chunk 2/12 for brca_tcga...
Fetching clinical data for patient chunk 3/12 for brca_tcga...
Fetching clinical data for patient chunk 4/12 for brca_tcga...
Fetching clinical data for patient chunk 5/12 for brca_tcga...
Fetching clinical data for patient chunk 6/12 for brca_tcga...
Fetching clinical data for patient chunk 7/12 for brca_tcga...
Fetching clinical data for patient chunk 8/12 for brca_tcga...
Fetching clinical data for patient chunk 9/12 for brca_tcga...
Fetching clinical data for patient chunk 10/12 for brca_tcga...
Fetching clinical data for patient chunk 11/12 for brca_tcga...
Fetching clinical data for patient chunk 12/12 for brca_tcga...
Unique clinicalAttributeIds found in raw data for brca_tcga (before mapping/pivot):
['MUTATION_COUNT', 'SOMATIC_STATUS', 'ONCOTREE_CODE', 'SAMPLE_TYPE', 'DAYS_TO_COLLECTION', 'OCT_EMBEDDED', 'FRACTION_GENOME_ALTERED', 'SAMPLE_TYPE_ID', 'TMB_NONSYNONYMOUS', 'PATHOLOGY_REPORT_UUID', 'CANCER_TYPE_DETAILED', 'PATHOLOGY_REPORT_FILE_NAME', 'OTHER_SAMPLE_ID', 'CANCER_TYPE', 'IS_FFPE', 'SAMPLE_INITIAL_WEIGHT', 'VIAL_NUMBER']
Unique attribute names found in raw clinical data for brca_tcga (before pivot):
['Cancer Type', 'Cancer Type Detailed', 'Days to Sample Collection.', 'Fraction Genome Altered', 'Is FFPE', 'Mutation Count', 'Oct embedded', 'Oncotree Code', 'Other Sample ID', 'Pathology Report File Name', 'Pathology report uuid', 'Sample Initial Weight', 'Sample Type', 'Sample type id', 'Somatic Status', 'TMB (nonsynonymous)', 'Vial number']
Columns found in cBioPortal clinical data for brca_tcga:
['patient_id', 'Cancer Type', 'Cancer Type Detailed', 'Days to Sample Collection.', 'Fraction Genome Altered', 'Is FFPE', 'Mutation Count', 'Oct embedded', 'Oncotree Code', 'Other Sample ID', 'Pathology Report File Name', 'Pathology report uuid', 'Sample Initial Weight', 'Sample Type', 'Sample type id', 'Somatic Status', 'TMB (nonsynonymous)', 'Vial number']
cBioPortal clinical for brca_tcga saved to: tcga_tnbc_data/TCGA_BRCA_clinical_cBio.csv
Detected receptor columns:
ER: er_status_gdc PR: pr_status_gdc HER2: her2_status_gdc
Merged clinical + TNBC status saved to: tcga_tnbc_data/TCGA_BRCA_clinical_TNBC.csv
Confirmation: File tcga_tnbc_data/TCGA_BRCA_clinical_TNBC.csv exists with size 467780 bytes.

In [30]:
import pandas as pd
from pathlib import Path

OUTPUT_DIR = Path("tcga_tnbc_data")
clinical_cbio_path = OUTPUT_DIR / "TCGA_BRCA_clinical_cBio.csv"

if clinical_cbio_path.exists():
    df_cbio_check = pd.read_csv(clinical_cbio_path)
    print("Columns in TCGA_BRCA_clinical_cBio.csv:")
    print(df_cbio_check.columns.tolist())
else:
    print(f"File not found: {clinical_cbio_path}")

Columns in TCGA_BRCA_clinical_cBio.csv:
['patient_id', 'sample_id']

In [46]:
print(merged.columns.tolist())

['case_id', 'submitter_id', 'gender', 'race', 'ethnicity', 'age_at_diagnosis', 'tumor_stage', 'tumor_grade', 'primary_diagnosis', 'days_to_death', 'days_to_last_follow_up', 'vital_status', 'progression_or_recurrence', 'days_to_progression_or_recurrence', 'sample_type', 'project_id', 'Cancer Type', 'Cancer Type Detailed', 'Days to Sample Collection.', 'Fraction Genome Altered', 'Is FFPE', 'Mutation Count', 'Oct embedded', 'Oncotree Code', 'Other Sample ID', 'Pathology Report File Name', 'Pathology report uuid', 'Sample Initial Weight', 'Sample Type', 'Sample type id', 'Somatic Status', 'TMB (nonsynonymous)', 'Vial number', 'sample_id', 'TNBC', 'pathologic_stage']

**Output:**
`tcga_tnbc_data/TCGA_BRCA_clinical_TNBC.csv` with columns such as:

- `submitter_id`, `case_id`
- `age_at_diagnosis`, `gender`, `race`
- `pathologic_stage` (or similar)
- `vital_status`, `days_to_death`, `days_to_last_follow_up`
- `progression_or_recurrence`
- `ER_*`, `PR_*`, `HER2_*` (from cBioPortal)
- `TNBC` (1 = triple‑negative, 0 = other)
- `OS_months`, `OS_event` (if detected)

Use this file to filter TNBC samples: `TNBC == 1`.

In [7]:
import pandas as pd
from pathlib import Path

OUTPUT_DIR = Path("tcga_tnbc_data")

clinical_cbio_path = OUTPUT_DIR / "TCGA_BRCA_clinical_cBio.csv"
if clinical_cbio_path.exists():
    df_cbio = pd.read_csv(clinical_cbio_path)
    display(df_cbio.head(10))
else:
    print(f"File not found: {clinical_cbio_path}")

File not found: tcga_tnbc_data/TCGA_BRCA_clinical_cBio.csv

In [23]:
print(df_cbio.columns.tolist())

['patient_id', 'sample_id']

### 4) Cytoscape interaction table (from STRING)
This script:
- Reads your DEG list (you’ll create it in step 5, or use any gene list).
- Queries STRING for PPIs.
- Saves a TSV you can import into Cytoscape and then save as `.cys`.

File: `04_build_string_network.py`

In [6]:
import pandas as pd
import numpy as np
from scipy import stats
from pathlib import Path
from statsmodels.stats.multitest import multipletests

OUTPUT_DIR = Path("tcga_tnbc_data")


def simple_deg_analysis(
    rna_matrix_path,
    clinical_path,
    output_deg_path,
    tnbc_col="TNBC",
    min_samples_per_group=5,
):
    expr = pd.read_csv(rna_matrix_path, index_col=0)
    clin = pd.read_csv(clinical_path)

    # Map sample names in expression to submitter_id / case barcode
    # Expression columns are like: TCGA-XX-XXXX_ Primary Tumor
    # We'll extract the TCGA barcode part before the first underscore.
    def extract_barcode(col):
        return str(col).split("_")[0]

    sample_barcodes = [extract_barcode(c) for c in expr.columns]
    expr_tmp = expr.copy()
    expr_tmp.columns = sample_barcodes

    # Merge clinical info
    clin = clin.set_index("submitter_id")
    common = list(set(expr_tmp.columns) & set(clin.index))
    print(f"Common samples between expression and clinical: {len(common)}")

    expr_common = expr_tmp[common]
    clin_common = clin.loc[common]

    if tnbc_col not in clin_common.columns:
        raise ValueError(f"Column '{tnbc_col}' not found in clinical file.")

    group = clin_common[tnbc_col].astype(int)
    tnbc_samples = group[group == 1].index.tolist()
    other_samples = group[group == 0].index.tolist()

    print(f"Number of TNBC samples: {len(tnbc_samples)}")
    print(f"Number of non-TNBC samples: {len(other_samples)}")

    if len(tnbc_samples) < min_samples_per_group or len(other_samples) < min_samples_per_group:
        raise ValueError("Not enough samples in one of the groups.")

    # Simple t-test per gene
    genes = expr_common.index.tolist()
    logfc_list = []
    pvals = []

    for g in genes:
        x = expr_common.loc[g, tnbc_samples].astype(float).dropna()
        y = expr_common.loc[g, other_samples].astype(float).dropna()

        if len(x) < 2 or len(y) < 2:
            logfc_list.append(np.nan)
            pvals.append(1.0)
            continue

        m1 = np.log2(x + 1).mean()
        m2 = np.log2(y + 1).mean()
        logfc = m1 - m2

        # t-test on log2(x+1)
        # The original code has an error here, stats.t_ind_test does not exist.
        # It should be stats.ttest_ind
        t_stat, p_val = stats.ttest_ind(np.log2(x + 1), np.log2(y + 1), equal_var=False) # Assuming unequal variances
        logfc_list.append(logfc)
        pvals.append(p_val)

    deg_df = pd.DataFrame({
        "gene": genes,
        "log2FC": logfc_list,
        "pval": pvals,
    })

    # FDR correction
    _, adj_pvals, _, _ = multipletests(deg_df["pval"].fillna(1.0), method="fdr_bh")
    deg_df["adj_pval"] = adj_pvals

    # Sort by adj_pval
    deg_df = deg_df.sort_values("adj_pval").reset_index(drop=True)

    deg_df.to_csv(output_deg_path, index=False)
    print(f"DEG list saved to: {output_deg_path}")
    return deg_df


if __name__ == "__main__":
    rna_matrix = OUTPUT_DIR / "TCGA_BRCA_RNAseq_matrix.csv"
    clinical = OUTPUT_DIR / "TCGA_BRCA_clinical_TNBC.csv"
    output_deg = OUTPUT_DIR / "TNBC_DEG_list_for_GO_KEGG.csv"

    if not rna_matrix.exists():
        print("RNA-seq matrix not found. Run 01_download_rnaseq_matrix.py first.")
    elif not clinical.exists():
        print("Clinical file not found. Run 03_download_clinical_TNBC.py first.")
    else:
        deg = simple_deg_analysis(rna_matrix, clinical, output_deg)

RNA-seq matrix not found. Run 01_download_rnaseq_matrix.py first.

In [7]:
from pathlib import Path

OUTPUT_DIR = Path("tcga_tnbc_data")
rna_matrix_path = OUTPUT_DIR / "TCGA_BRCA_RNAseq_matrix.csv"
clinical_tnbc_path = OUTPUT_DIR / "TCGA_BRCA_clinical_TNBC.csv"

print(f"Checking for {rna_matrix_path}: {rna_matrix_path.exists()}")
print(f"Checking for {clinical_tnbc_path}: {clinical_tnbc_path.exists()}")

if rna_matrix_path.exists() and clinical_tnbc_path.exists():
    print("Both RNA-seq matrix and clinical TNBC files exist. Proceeding with DEG analysis.")
    # Re-run the DEG analysis if both files are confirmed to exist
    # (This logic is usually handled by the main DEG cell's __main__ block)
    # If the DEG cell consistently reports not found despite this check, there might be a path issue.
else:
    print("One or both required files are still missing. Please ensure previous steps completed successfully.")

Checking for tcga_tnbc_data/TCGA_BRCA_RNAseq_matrix.csv: False
Checking for tcga_tnbc_data/TCGA_BRCA_clinical_TNBC.csv: True
One or both required files are still missing. Please ensure previous steps completed successfully.

In [8]:
import pandas as pd
import numpy as np
from scipy import stats
from pathlib import Path
from statsmodels.stats.multitest import multipletests

OUTPUT_DIR = Path("tcga_tnbc_data")


def simple_deg_analysis(
    rna_matrix_path,
    clinical_path,
    output_deg_path,
    tnbc_col="TNBC",
    min_samples_per_group=5,
):
    expr = pd.read_csv(rna_matrix_path, index_col=0)
    clin = pd.read_csv(clinical_path)

    # Map sample names in expression to submitter_id / case barcode
    # Expression columns are like: TCGA-XX-XXXX_ Primary Tumor
    # We'll extract the TCGA barcode part before the first underscore.
    def extract_barcode(col):
        return str(col).split("_")[0]

    sample_barcodes = [extract_barcode(c) for c in expr.columns]
    expr_tmp = expr.copy()
    expr_tmp.columns = sample_barcodes

    # Merge clinical info
    clin = clin.set_index("submitter_id")
    common = list(set(expr_tmp.columns) & set(clin.index))
    print(f"Common samples between expression and clinical: {len(common)}")

    expr_common = expr_tmp[common]
    clin_common = clin.loc[common]

    if tnbc_col not in clin_common.columns:
        raise ValueError(f"Column '{tnbc_col}' not found in clinical file.")

    group = clin_common[tnbc_col].astype(int)
    tnbc_samples = group[group == 1].index.tolist()
    other_samples = group[group == 0].index.tolist()

    print(f"Number of TNBC samples: {len(tnbc_samples)}")
    print(f"Number of non-TNBC samples: {len(other_samples)}")

    if len(tnbc_samples) < min_samples_per_group or len(other_samples) < min_samples_per_group:
        raise ValueError("Not enough samples in one of the groups.")

    # Simple t-test per gene
    genes = expr_common.index.tolist()
    logfc_list = []
    pvals = []

    for g in genes:
        x = expr_common.loc[g, tnbc_samples].astype(float).dropna()
        y = expr_common.loc[g, other_samples].astype(float).dropna()

        if len(x) < 2 or len(y) < 2:
            logfc_list.append(np.nan)
            pvals.append(1.0)
            continue

        m1 = np.log2(x + 1).mean()
        m2 = np.log2(y + 1).mean()
        logfc = m1 - m2

        # t-test on log2(x+1)
        # The original code has an error here, stats.t_ind_test does not exist.
        # It should be stats.ttest_ind
        t_stat, p_val = stats.ttest_ind(np.log2(x + 1), np.log2(y + 1), equal_var=False) # Assuming unequal variances
        logfc_list.append(logfc)
        pvals.append(p_val)

    deg_df = pd.DataFrame({
        "gene": genes,
        "log2FC": logfc_list,
        "pval": pvals,
    })

    # FDR correction
    _, adj_pvals, _, _ = multipletests(deg_df["pval"].fillna(1.0), method="fdr_bh")
    deg_df["adj_pval"] = adj_pvals

    # Sort by adj_pval
    deg_df = deg_df.sort_values("adj_pval").reset_index(drop=True)

    deg_df.to_csv(output_deg_path, index=False)
    print(f"DEG list saved to: {output_deg_path}")
    return deg_df


if __name__ == "__main__":
    rna_matrix = OUTPUT_DIR / "TCGA_BRCA_RNAseq_matrix.csv"
    clinical = OUTPUT_DIR / "TCGA_BRCA_clinical_TNBC.csv"
    output_deg = OUTPUT_DIR / "TNBC_DEG_list_for_GO_KEGG.csv"

    if not rna_matrix.exists():
        print("RNA-seq matrix not found. Run 01_download_rnaseq_matrix.py first.")
    elif not clinical.exists():
        print("Clinical file not found. Run 03_download_clinical_TNBC.py first.")
    else:
        deg = simple_deg_analysis(rna_matrix, clinical, output_deg)

RNA-seq matrix not found. Run 01_download_rnaseq_matrix.py first.

In [ ]:
import pandas as pd
from pathlib import Path

OUTPUT_DIR = Path("tcga_tnbc_data")
clinical_tnbc_path = OUTPUT_DIR / "TCGA_BRCA_clinical_TNBC.csv"
rna_matrix_path = OUTPUT_DIR / "TCGA_BRCA_RNAseq_matrix.csv"

if clinical_tnbc_path.exists() and rna_matrix_path.exists():
    clin = pd.read_csv(clinical_tnbc_path)
    expr = pd.read_csv(rna_matrix_path, index_col=0)

    # Map sample names in expression to submitter_id / case barcode
    def extract_barcode(col):
        return str(col).split("_")[0]
    sample_barcodes = [extract_barcode(c) for c in expr.columns]
    expr_tmp = expr.copy()
    expr_tmp.columns = sample_barcodes

    # Merge clinical info based on common submitter_ids
    clin_indexed = clin.set_index("submitter_id")
    common_samples = list(set(expr_tmp.columns) & set(clin_indexed.index))

    print(f"Total unique samples in RNA-seq matrix: {len(expr_tmp.columns)}")
    print(f"Total unique samples in clinical data: {len(clin_indexed.index)}")
    print(f"Common samples between RNA-seq and clinical data: {len(common_samples)}")

    if not common_samples:
        print("No common samples found between expression and clinical data.")
    else:
        clin_common = clin_indexed.loc[common_samples]
        print("\nDistribution of TNBC status in common samples:")
        print(clin_common["TNBC"].value_counts())

        tnbc_samples = clin_common[clin_common["TNBC"] == 1].index.tolist()
        other_samples = clin_common[clin_common["TNBC"] == 0].index.tolist()

        print(f"\nNumber of TNBC samples: {len(tnbc_samples)}")
        print(f"Number of non-TNBC samples: {len(other_samples)}")

        # Check for NaN values in TNBC column within common samples
        tnbc_nan_count = clin_common['TNBC'].isna().sum()
        if tnbc_nan_count > 0:
            print(f"Warning: {tnbc_nan_count} common samples have NaN for TNBC status and will be excluded.")

        if len(tnbc_samples) < 5:
            print(f"TNBC group has {len(tnbc_samples)} samples, which is less than the minimum required (5).")
        if len(other_samples) < 5:
            print(f"Non-TNBC group has {len(other_samples)} samples, which is less than the minimum required (5).")

else:
    print("Required files (TCGA_BRCA_RNAseq_matrix.csv or TCGA_BRCA_clinical_TNBC.csv) not found.")

In [1]:
import pandas as pd
from pathlib import Path

OUTPUT_DIR = Path("tcga_tnbc_data")
clinical_tnbc_path = OUTPUT_DIR / "TCGA_BRCA_clinical_TNBC.csv"

if clinical_tnbc_path.exists():
    clin_tnbc = pd.read_csv(clinical_tnbc_path)
    if 'TNBC' in clin_tnbc.columns:
        print("Value counts for 'TNBC' column:")
        print(clin_tnbc['TNBC'].value_counts())
    else:
        print("The 'TNBC' column was not found in the clinical DataFrame.")
else:
    print(f"Clinical file not found: {clinical_tnbc_path}")

Clinical file not found: tcga_tnbc_data/TCGA_BRCA_clinical_TNBC.csv

In [2]:
from pathlib import Path

OUTPUT_DIR = Path("tcga_tnbc_data")
clinical_tnbc_path = OUTPUT_DIR / "TCGA_BRCA_clinical_TNBC.csv"

if clinical_tnbc_path.exists():
    print(f"The file {clinical_tnbc_path} exists.")
else:
    print(f"The file {clinical_tnbc_path} does NOT exist.")
    print("Please ensure cell `9b49dc42` (which generates this file) has been run successfully.")

The file tcga_tnbc_data/TCGA_BRCA_clinical_TNBC.csv does NOT exist.
Please ensure cell `9b49dc42` (which generates this file) has been run successfully.

In [3]:
import requests
import pandas as pd
from pathlib import Path

OUTPUT_DIR = Path("tcga_tnbc_data")
STRING_API = "https://string-db.org/api"
ORGANISM = "Homo sapiens"
MIN_SCORE = 0.4  # combined score threshold


def fetch_string_interactions(gene_list, min_score=MIN_SCORE):
    """
    Query STRING for PPIs among a list of gene symbols.
    Returns edge DataFrame suitable for Cytoscape import.
    """
    # 1) Map gene symbols to STRING protein IDs
    identifiers = "\n".join(gene_list)
    params = {
        "identifiers": identifiers,
        "species": ORGANISM,
        "limit": 1,
        "echo_query": 1,
    }
    resp = requests.get(f"{STRING_API}/json/resolve_list", params=params)
    resp.raise_for_status()
    mapping = resp.json()

    sym2id = {}
    for entry in mapping:
        sym2id[entry["inputIdentifier"]] = entry["preferredName"]

    string_ids = list(set(sym2id.values()))
    if len(string_ids) < 2:
        print("Less than 2 genes mapped to STRING; no network.")
        return pd.DataFrame()

    # 2) Get interactions
    params2 = {
        "identifiers": "\n".join(string_ids),
        "species": ORGANISM,
        "add_whitecolor_nodes": "0",
        "limit": 1,
        "echo_query": 1,
    }
    resp2 = requests.get(f"{STRING_API}/json/get_interactions_list", params=params2)
    resp2.raise_for_status()
    interactions = resp2.json()

    edges = []
    for e in interactions:
        if e["score"] < min_score:
            continue
        edges.append({
            "protein1": e["protein1"],
            "protein2": e["protein2"],
            "combined_score": e["score"],
        })

    return pd.DataFrame(edges)


# __name__ == "__main__" block
# Input: DEG list from step 5 (or any gene list CSV with column 'gene')
deg_path = OUTPUT_DIR / "TNBC_DEG_list_for_GO_KEGG.csv"
if not deg_path.exists():
    print("DEG list not found. Run 05_prepare_deg_list.py first.")
else:
    deg = pd.read_csv(deg_path)
    # Expect a 'gene' column; adjust if needed
    gene_col = "gene" if "gene" in deg.columns else deg.columns[0]
    genes = deg[gene_col].dropna().astype(str).tolist()

    # Optionally take top N (e.g., 300)
    genes = genes[:300]

    edge_df = fetch_string_interactions(genes)
    if edge_df.empty:
        print("No interactions found.")
    else:
        out_path = OUTPUT_DIR / "STRING_TNBC_interactions.tsv"
        edge_df.to_csv(out_path, sep="\t", index=False)
        print(f"STRING interaction table saved to: {out_path}")
        print("Import this TSV into Cytoscape: File → Import → Network → File")

DEG list not found. Run 05_prepare_deg_list.py first.

### Download Validation Cohort: METABRIC TNBC Cases from cBioPortal

First, we need to identify the cBioPortal study ID for METABRIC breast cancer. Then we'll fetch its clinical data and define TNBC status for this cohort.

In [11]:
import requests
import pandas as pd
from pathlib import Path
import time

CBIO_API = "https://www.cbioportal.org/api"
OUTPUT_DIR = Path("tcga_tnbc_data")
OUTPUT_DIR.mkdir(exist_ok=True)

def list_cbioportal_studies(search_term="METABRIC"):
    url = f"{CBIO_API}/studies"
    params = {"pageSize": 1000} # Fetch a reasonable number of studies
    resp = requests.get(url, params=params)
    resp.raise_for_status()
    studies = resp.json()

    print(f"Searching for studies containing '{search_term}'...")
    metabric_studies = [s for s in studies if search_term.lower() in s.get('name', '').lower() or search_term.lower() in s.get('description', '').lower() or search_term.lower() in s.get('studyId', '').lower()]

    if not metabric_studies:
        print(f"No studies found containing '{search_term}'.")
        return None

    print(f"Found {len(metabric_studies)} METABRIC-related studies:")
    for s in metabric_studies:
        print(f"  - Study ID: {s['studyId']}, Name: {s['name']}")

    # Heuristic: often the most relevant study is the one without a year or with a primary designation
    # For METABRIC, 'brca_metabric' is a common ID.
    for s in metabric_studies:
        if s['studyId'] == 'brca_metabric':
            return 'brca_metabric'

    # If 'brca_metabric' is not found, return the studyId of the first result as a fallback
    if metabric_studies:
        return metabric_studies[0]['studyId']
    return None

# Re-using the now-modified get_cbioportal_clinical function

def get_cbioportal_clinical(study_id, out_file_prefix="TCGA_BRCA"):
    """
    Fetch clinical data from cBioPortal (public API) for a given study.
    We'll get patient-level attributes including ER/PR/HER2 if available.
    """
    CBIO_API = "https://www.cbioportal.org/api"

    # 1. Get all patient IDs for the study
    url_patients = f"{CBIO_API}/studies/{study_id}/patients"
    params_patients = {"pageSize": 10000} # Get all patients
    resp_patients = requests.get(url_patients, params=params_patients)
    resp_patients.raise_for_status()
    patients_summary = resp_patients.json()
    patient_ids = [p['patientId'] for p in patients_summary]

    if not patient_ids:
        print(f"No patient data found for {study_id} from cBioPortal.")
        return pd.DataFrame()

    # 2. Get all clinical attribute metadata for the study
    url_clinical_attributes = f"{CBIO_API}/studies/{study_id}/clinical-attributes"
    params_clinical_attributes = {"pageSize": 10000}
    resp_clinical_attributes = requests.get(url_clinical_attributes, params=params_clinical_attributes)
    resp_clinical_attributes.raise_for_status()
    clinical_attribute_meta = resp_clinical_attributes.json()

    # Map clinical attribute IDs to display names for column headers
    attr_id_to_name = {attr['clinicalAttributeId']: attr['displayName'] for attr in clinical_attribute_meta}

    print(f"Available clinical attributes for {study_id} (ID: Display Name):")
    # For METABRIC, we specifically want to look for ER, PR, HER2 statuses
    # Let's list all attributes first to identify the correct ones.
    for attr in clinical_attribute_meta:
        print(f"  {attr['clinicalAttributeId']}: {attr['displayName']}")

    # It's important to identify the *correct* attribute IDs for ER/PR/HER2 for METABRIC.
    # Common ones are 'ER_STATUS', 'PR_STATUS', 'HER2_STATUS_BY_IHC', 'HER2_FISH_STATUS', 'HER2_STATUS'
    # We'll explicitly check for these or similar.
    possible_er_attr_ids = ["ER_STATUS", "ER_STATUS_BY_IMMUNOHISTOCHEMISTRY"]
    possible_pr_attr_ids = ["PR_STATUS", "PR_STATUS_BY_IMMUNOHISTOCHEMISTRY"]
    possible_her2_attr_ids = ["HER2_STATUS_BY_IHC", "HER2_STATUS", "HER2_FISH_STATUS"]

    metabric_relevant_attr_ids = []
    for attr_id_list in [possible_er_attr_ids, possible_pr_attr_ids, possible_her2_attr_ids]:
        for attr_id in attr_id_list:
            if attr_id in attr_id_to_name:
                metabric_relevant_attr_ids.append(attr_id)
                break # Found one, move to next receptor type

    if not metabric_relevant_attr_ids:
        print(f"Warning: No explicit ER/PR/HER2 status attributes found for {study_id} using common IDs. Fetching all available clinical attributes.")
        clinical_attribute_ids_str = ",".join(attr_id_to_name.keys())
    else:
        print(f"Detected receptor status attributes for {study_id}: {metabric_relevant_attr_ids}")
        clinical_attribute_ids_str = ",".join(metabric_relevant_attr_ids)

    # 3. Fetch clinical data for all patients and selected attributes using GET
    url_clinical_data = f"{CBIO_API}/studies/{study_id}/clinical-data"

    all_raw_clinical_data = []
    patient_id_chunks = [patient_ids[i:i + 100] for i in range(0, len(patient_ids), 100)] # Chunk patient IDs

    for i, patient_chunk in enumerate(patient_id_chunks):
        print(f"Fetching clinical data for patient chunk {i+1}/{len(patient_id_chunks)} for {study_id}...")
        # Prepare query parameters for GET request for the current chunk
        params_clinical_data = {
            "patientIds": ",".join(patient_chunk),
            "clinicalAttributeIds": clinical_attribute_ids_str # Only request relevant attributes
        }

        # Add retry logic for the GET request
        MAX_RETRIES = 5
        for attempt in range(MAX_RETRIES):
            try:
                resp_clinical_data = requests.get(url_clinical_data, params=params_clinical_data, timeout=60)
                resp_clinical_data.raise_for_status()
                all_raw_clinical_data.extend(resp_clinical_data.json())
                break # Break out of the retry loop if successful
            except requests.exceptions.RequestException as e:
                print(f"RequestException encountered for chunk {i+1} of {study_id} (attempt {attempt + 1}/{MAX_RETRIES}): {e}")
                if attempt < MAX_RETRIES - 1:
                    time.sleep(2 ** attempt) # Exponential back-off
                else:
                    raise # Re-raise the last exception if all retries fail
        else:
            # This block is executed if the loop completes without a 'break'
            print(f"Failed to retrieve clinical data for chunk {i+1} of {study_id} after {MAX_RETRIES} attempts. Skipping this chunk.")

    # DEBUG: Print unique clinicalAttributeIds found in the raw data
    if all_raw_clinical_data:
        raw_attribute_ids = {item.get('clinicalAttributeId') for item in all_raw_clinical_data}
        print(f"Unique clinicalAttributeIds found in raw data for {study_id} (before mapping/pivot):")
        print(list(raw_attribute_ids))
    else:
        print(f"No raw clinical data returned from cBioPortal for {study_id} for the requested attributes.")

    # 4. Process raw clinical data into a DataFrame
    # The data comes in a 'long' format, need to pivot it to 'wide'
    clinical_rows = []
    for item in all_raw_clinical_data:
        clinical_rows.append({
            "patient_id": item["patientId"],
            "attribute_name": attr_id_to_name.get(item["clinicalAttributeId"], item["clinicalAttributeId"]),
            "attribute_value": item["value"]
        })

    df_clinical_long = pd.DataFrame(clinical_rows)

    if df_clinical_long.empty:
        print(f"No detailed clinical attributes found for {study_id} from cBioPortal.")
        return pd.DataFrame()

    print(f"Unique attribute names found in raw clinical data for {study_id} (before pivot):")
    print(df_clinical_long['attribute_name'].unique().tolist())

    # Handle potential duplicate (patient_id, attribute_name) combinations
    # Keep the first occurrence if duplicates exist to allow pivoting.
    df_clinical_long = df_clinical_long.drop_duplicates(subset=['patient_id', 'attribute_name'], keep='first')

    # Pivot the table to get attributes as columns
    clin_cbio = df_clinical_long.pivot(index='patient_id', columns='attribute_name', values='attribute_value')
    clin_cbio = clin_cbio.reset_index()
    clin_cbio.columns.name = None # Remove the name of the columns index

    print(f"Columns found in cBioPortal clinical data for {study_id}:")
    print(clin_cbio.columns.tolist())

    # Add a dummy sample_id for merging purposes if not naturally present
    if 'sample_id' not in clin_cbio.columns:
        clin_cbio['sample_id'] = None # Or extract from patient_id if a pattern exists

    out_path_cbio = OUTPUT_DIR / f"{out_file_prefix}_clinical_cBio.csv"
    clin_cbio.to_csv(out_path_cbio, index=False)
    print(f"cBioPortal clinical for {study_id} saved to: {out_path_cbio}")
    return clin_cbio


metabric_study_id = list_cbioportal_studies("METABRIC")

if metabric_study_id:
    print(f"Identified primary METABRIC study ID: {metabric_study_id}")
    # Now call the (modified) get_cbioportal_clinical for METABRIC
    metabric_clinical_df = get_cbioportal_clinical(metabric_study_id, out_file_prefix="METABRIC")

    if not metabric_clinical_df.empty:
        print("METABRIC clinical data fetched successfully. Displaying head:")
        display(metabric_clinical_df.head())
    else:
        print("Failed to fetch METABRIC clinical data.")
else:
    print("Could not automatically identify a METABRIC study ID. Please manually check cBioPortal.")

Searching for studies containing 'METABRIC'...
Found 1 METABRIC-related studies:
  - Study ID: brca_metabric, Name: Breast Cancer (METABRIC, Nature 2012 & Nat Commun 2016)
Identified primary METABRIC study ID: brca_metabric
Available clinical attributes for brca_metabric (ID: Display Name):
  AGE_AT_DIAGNOSIS: Age at Diagnosis
  BREAST_SURGERY: Type of Breast Surgery
  CANCER_TYPE: Cancer Type
  CANCER_TYPE_DETAILED: Cancer Type Detailed
  CELLULARITY: Cellularity
  CHEMOTHERAPY: Chemotherapy
  CLAUDIN_SUBTYPE: Pam50 + Claudin-low subtype
  COHORT: Cohort
  ER_IHC: ER status measured by IHC
  ER_STATUS: ER Status
  GRADE: Neoplasm Histologic Grade
  HER2_SNP6: HER2 status measured by SNP6
  HER2_STATUS: HER2 Status
  HISTOLOGICAL_SUBTYPE: Tumor Other Histologic Subtype
  HORMONE_THERAPY: Hormone Therapy
  INFERRED_MENOPAUSAL_STATE: Inferred Menopausal State
  INTCLUST: Integrative Cluster
  LATERALITY: Primary Tumor Laterality
  LYMPH_NODES_EXAMINED_POSITIVE: Lymph nodes examined positive
  MUTATION_COUNT: Mutation Count
  NPI: Nottingham prognostic index
  ONCOTREE_CODE: Oncotree Code
  OS_MONTHS: Overall Survival (Months)
  OS_STATUS: Overall Survival Status
  PR_STATUS: PR Status
  RADIO_THERAPY: Radio Therapy
  RFS_MONTHS: Relapse Free Status (Months)
  RFS_STATUS: Relapse Free Status
  SAMPLE_COUNT: Number of Samples Per Patient
  SAMPLE_TYPE: Sample Type
  SEX: Sex
  THREEGENE: 3-Gene classifier subtype
  TMB_NONSYNONYMOUS: TMB (nonsynonymous)
  TUMOR_SIZE: Tumor Size
  TUMOR_STAGE: Tumor Stage
  VITAL_STATUS: Patient's Vital Status
Detected receptor status attributes for brca_metabric: ['ER_STATUS', 'PR_STATUS', 'HER2_STATUS']
Fetching clinical data for patient chunk 1/26 for brca_metabric...
Fetching clinical data for patient chunk 2/26 for brca_metabric...
Fetching clinical data for patient chunk 3/26 for brca_metabric...
Fetching clinical data for patient chunk 4/26 for brca_metabric...
Fetching clinical data for patient chunk 5/26 for brca_metabric...
Fetching clinical data for patient chunk 6/26 for brca_metabric...
Fetching clinical data for patient chunk 7/26 for brca_metabric...
Fetching clinical data for patient chunk 8/26 for brca_metabric...
Fetching clinical data for patient chunk 9/26 for brca_metabric...
Fetching clinical data for patient chunk 10/26 for brca_metabric...
Fetching clinical data for patient chunk 11/26 for brca_metabric...
Fetching clinical data for patient chunk 12/26 for brca_metabric...
Fetching clinical data for patient chunk 13/26 for brca_metabric...
Fetching clinical data for patient chunk 14/26 for brca_metabric...
Fetching clinical data for patient chunk 15/26 for brca_metabric...
Fetching clinical data for patient chunk 16/26 for brca_metabric...
Fetching clinical data for patient chunk 17/26 for brca_metabric...
Fetching clinical data for patient chunk 18/26 for brca_metabric...
Fetching clinical data for patient chunk 19/26 for brca_metabric...
Fetching clinical data for patient chunk 20/26 for brca_metabric...
Fetching clinical data for patient chunk 21/26 for brca_metabric...
Fetching clinical data for patient chunk 22/26 for brca_metabric...
Fetching clinical data for patient chunk 23/26 for brca_metabric...
Fetching clinical data for patient chunk 24/26 for brca_metabric...
Fetching clinical data for patient chunk 25/26 for brca_metabric...
Fetching clinical data for patient chunk 26/26 for brca_metabric...
Unique clinicalAttributeIds found in raw data for brca_metabric (before mapping/pivot):
['MUTATION_COUNT', 'ONCOTREE_CODE', 'TUMOR_SIZE', 'SAMPLE_TYPE', 'PR_STATUS', 'TUMOR_STAGE', 'HER2_STATUS', 'ER_STATUS', 'TMB_NONSYNONYMOUS', 'CANCER_TYPE_DETAILED', 'GRADE', 'CANCER_TYPE']
Unique attribute names found in raw clinical data for brca_metabric (before pivot):
['Cancer Type', 'Cancer Type Detailed', 'ER Status', 'Neoplasm Histologic Grade', 'HER2 Status', 'Oncotree Code', 'PR Status', 'Sample Type', 'TMB (nonsynonymous)', 'Tumor Size', 'Tumor Stage', 'Mutation Count']
Columns found in cBioPortal clinical data for brca_metabric:
['patient_id', 'Cancer Type', 'Cancer Type Detailed', 'ER Status', 'HER2 Status', 'Mutation Count', 'Neoplasm Histologic Grade', 'Oncotree Code', 'PR Status', 'Sample Type', 'TMB (nonsynonymous)', 'Tumor Size', 'Tumor Stage']
cBioPortal clinical for brca_metabric saved to: tcga_tnbc_data/METABRIC_clinical_cBio.csv
METABRIC clinical data fetched successfully. Displaying head:

,patient_id,Cancer Type,Cancer Type Detailed,ER Status,HER2 Status,Mutation Count,Neoplasm Histologic Grade,Oncotree Code,PR Status,Sample Type,TMB (nonsynonymous),Tumor Size,Tumor Stage,sample_id
0,MB-0000,Breast Cancer,Breast Invasive Ductal Carcinoma,Positive,Negative,NaN,3,IDC,Negative,Primary,0,22,2,None
1,MB-0002,Breast Cancer,Breast Invasive Ductal Carcinoma,Positive,Negative,2,3,IDC,Positive,Primary,2.615035408,10,1,None
2,MB-0005,Breast Cancer,Breast Invasive Ductal Carcinoma,Positive,Negative,2,2,IDC,Positive,Primary,2.615035408,15,2,None
3,MB-0006,Breast Cancer,Breast Mixed Ductal and Lobular Carcinoma,Positive,Negative,1,2,MDLC,Positive,Primary,1.307517704,25,2,None
4,MB-0008,Breast Cancer,Breast Mixed Ductal and Lobular Carcinoma,Positive,Negative,2,3,MDLC,Positive,Primary,2.615035408,40,2,None

### Define TNBC Status for METABRIC Cohort

Now that the METABRIC clinical data is downloaded, we will define the TNBC status based on ER, PR, and HER2 status, similar to the TCGA-BRCA cohort. The relevant columns found are `ER Status`, `PR Status`, and `HER2 Status`.

In [12]:
import pandas as pd
from pathlib import Path

OUTPUT_DIR = Path("tcga_tnbc_data")

def define_metabric_tnbc(metabric_clinical_df):
    df = metabric_clinical_df.copy()

    # Receptor status columns identified from previous step for METABRIC
    er_col = "ER Status"
    pr_col = "PR Status"
    her2_col = "HER2 Status"

    def is_negative_metabric(val):
        if pd.isna(val):
            return False
        v = str(val).strip().lower()
        # Common negative indicators for ER/PR/HER2 in METABRIC
        # Based on available clinical attributes from cBioPortal, values might be 'Negative', 'Positive'
        return v in ["negative", "0"]

    def is_positive_metabric(val):
        if pd.isna(val):
            return False
        v = str(val).strip().lower()
        return v in ["positive", "1"]

    if er_col in df.columns and pr_col in df.columns and her2_col in df.columns:
        df["ER_neg"] = df[er_col].apply(is_negative_metabric)
        df["PR_neg"] = df[pr_col].apply(is_negative_metabric)
        df["HER2_neg"] = df[her2_col].apply(is_negative_metabric)

        df["TNBC"] = (df["ER_neg"] & df["PR_neg"] & df["HER2_neg"]).astype(int)
        print(f"Defined TNBC status for METABRIC cohort. TNBC count: {df['TNBC'].sum()}")
    else:
        print("Could not detect all ER/PR/HER2 columns in METABRIC clinical data. TNBC column will not be created.")
        df["TNBC"] = pd.NA

    out_path = OUTPUT_DIR / "METABRIC_clinical_TNBC.csv"
    df.to_csv(out_path, index=False)
    print(f"METABRIC clinical data with TNBC status saved to: {out_path}")
    return df

# Call the function with the previously fetched METABRIC clinical DataFrame
if 'metabric_clinical_df' in locals() and not metabric_clinical_df.empty:
    metabric_clinical_tnbc_df = define_metabric_tnbc(metabric_clinical_df)
    if not metabric_clinical_tnbc_df.empty:
        print("METABRIC clinical data with TNBC status head:")
        display(metabric_clinical_tnbc_df.head())
else:
    print("METABRIC clinical data (metabric_clinical_df) not found or is empty. Please ensure previous step ran successfully.")

Defined TNBC status for METABRIC cohort. TNBC count: 320
METABRIC clinical data with TNBC status saved to: tcga_tnbc_data/METABRIC_clinical_TNBC.csv
METABRIC clinical data with TNBC status head:

,patient_id,Cancer Type,Cancer Type Detailed,ER Status,HER2 Status,Mutation Count,Neoplasm Histologic Grade,Oncotree Code,PR Status,Sample Type,TMB (nonsynonymous),Tumor Size,Tumor Stage,sample_id,ER_neg,PR_neg,HER2_neg,TNBC
0,MB-0000,Breast Cancer,Breast Invasive Ductal Carcinoma,Positive,Negative,NaN,3,IDC,Negative,Primary,0,22,2,None,False,True,True,0
1,MB-0002,Breast Cancer,Breast Invasive Ductal Carcinoma,Positive,Negative,2,3,IDC,Positive,Primary,2.615035408,10,1,None,False,False,True,0
2,MB-0005,Breast Cancer,Breast Invasive Ductal Carcinoma,Positive,Negative,2,2,IDC,Positive,Primary,2.615035408,15,2,None,False,False,True,0
3,MB-0006,Breast Cancer,Breast Mixed Ductal and Lobular Carcinoma,Positive,Negative,1,2,MDLC,Positive,Primary,1.307517704,25,2,None,False,False,True,0
4,MB-0008,Breast Cancer,Breast Mixed Ductal and Lobular Carcinoma,Positive,Negative,2,3,MDLC,Positive,Primary,2.615035408,40,2,None,False,False,True,0

In [13]:
import os
from pathlib import Path

OUTPUT_DIR = Path("tcga_tnbc_data")
RNASEQ_MATRIX_PATH = OUTPUT_DIR / "TCGA_BRCA_RNAseq_matrix.csv"

if RNASEQ_MATRIX_PATH.exists() and os.path.getsize(RNASEQ_MATRIX_PATH) > 0:
    print(f"Confirmation: The RNA-seq matrix '{RNASEQ_MATRIX_PATH}' exists and is not empty (size: {os.path.getsize(RNASEQ_MATRIX_PATH)} bytes).")
    # Optionally display head if it's not too big
    # import pandas as pd
    # df_rnaseq = pd.read_csv(RNASEQ_MATRIX_PATH, index_col=0)
    # print("RNA-seq matrix head:")
    # display(df_rnaseq.head())
else:
    print(f"Warning: The RNA-seq matrix '{RNASEQ_MATRIX_PATH}' is still missing or empty.")
    print("Please ensure the RNA-seq download and matrix building step (cell `9af4586e`) completed successfully.")

Warning: The RNA-seq matrix 'tcga_tnbc_data/TCGA_BRCA_RNAseq_matrix.csv' is still missing or empty.
Please ensure the RNA-seq download and matrix building step (cell `9af4586e`) completed successfully.

**How to get .cys:**
1. Open Cytoscape.
2. File → Import → Network → File → select `STRING_TNBC_interactions.tsv`.
3. Set `protein1` and `protein2` as source/target.
4. After import, save as `your_network.cys` (File → Save).

In [ ]:
import os
from pathlib import Path

OUTPUT_DIR = Path("tcga_tnbc_data")

print(f"Contents of '{OUTPUT_DIR}':")
if OUTPUT_DIR.exists() and OUTPUT_DIR.is_dir():
    for item in sorted(os.listdir(OUTPUT_DIR)):
        item_path = OUTPUT_DIR / item
        if item_path.is_file():
            print(f"- {item} (File, Size: {item_path.stat().st_size} bytes)")
        elif item_path.is_dir():
            print(f"- {item} (Directory)")
        else:
            print(f"- {item} (Other)")
else:
    print(f"Directory '{OUTPUT_DIR}' does not exist.")

### 5) Gene list for GO/KEGG enrichment (DEG list)
This script:
- Loads your RNA‑seq matrix and clinical file.
- Filters TNBC vs non‑TNBC (using TNBC column from step 3).
- Performs a simple differential expression (t‑test per gene).
- Saves a gene list with log2FC, p‑value, adj‑p‑value.

For a real project, you’d use DESeq2/edgeR in R; this is a Python approximation.

File: `05_prepare_deg_list.py`

In [2]:
import pandas as pd
import numpy as np
from scipy import stats
from pathlib import Path
from statsmodels.stats.multitest import multipletests

OUTPUT_DIR = Path("tcga_tnbc_data")


def simple_deg_analysis(
    rna_matrix_path,
    clinical_path,
    output_deg_path,
    tnbc_col="TNBC",
    min_samples_per_group=5,
):
    expr = pd.read_csv(rna_matrix_path, index_col=0)
    clin = pd.read_csv(clinical_path)

    # Map sample names in expression to submitter_id / case barcode
    # Expression columns are like: TCGA-XX-XXXX_ Primary Tumor
    # We'll extract the TCGA barcode part before the first underscore.
    def extract_barcode(col):
        return str(col).split("_")[0]

    sample_barcodes = [extract_barcode(c) for c in expr.columns]
    expr_tmp = expr.copy()
    expr_tmp.columns = sample_barcodes

    # Merge clinical info
    clin = clin.set_index("submitter_id")
    common = list(set(expr_tmp.columns) & set(clin.index))
    print(f"Common samples between expression and clinical: {len(common)}")

    expr_common = expr_tmp[common]
    clin_common = clin.loc[common]

    if tnbc_col not in clin_common.columns:
        raise ValueError(f"Column '{tnbc_col}' not found in clinical file.")

    group = clin_common[tnbc_col].astype(int)
    tnbc_samples = group[group == 1].index.tolist()
    other_samples = group[group == 0].index.tolist()

    if len(tnbc_samples) < min_samples_per_group or len(other_samples) < min_samples_per_group:
        raise ValueError("Not enough samples in one of the groups.")

    # Simple t-test per gene
    genes = expr_common.index.tolist()
    logfc_list = []
    pvals = []

    for g in genes:
        x = expr_common.loc[g, tnbc_samples].astype(float).dropna()
        y = expr_common.loc[g, other_samples].astype(float).dropna()

        if len(x) < 2 or len(y) < 2:
            logfc_list.append(np.nan)
            pvals.append(1.0)
            continue

        m1 = np.log2(x + 1).mean()
        m2 = np.log2(y + 1).mean()
        logfc = m1 - m2

        # t-test on log2(x+1)
        # The original code has an error here, stats.t_ind_test does not exist.
        # It should be stats.ttest_ind
        t_stat, p_val = stats.ttest_ind(np.log2(x + 1), np.log2(y + 1), equal_var=False) # Assuming unequal variances
        logfc_list.append(logfc)
        pvals.append(p_val)

    deg_df = pd.DataFrame({
        "gene": genes,
        "log2FC": logfc_list,
        "pval": pvals,
    })

    # FDR correction
    _, adj_pvals, _, _ = multipletests(deg_df["pval"].fillna(1.0), method="fdr_bh")
    deg_df["adj_pval"] = adj_pvals

    # Sort by adj_pval
    deg_df = deg_df.sort_values("adj_pval").reset_index(drop=True)

    deg_df.to_csv(output_deg_path, index=False)
    print(f"DEG list saved to: {output_deg_path}")
    return deg_df


# __name__ == "__main__" block
rna_matrix = OUTPUT_DIR / "TCGA_BRCA_RNAseq_matrix.csv"
clinical = OUTPUT_DIR / "TCGA_BRCA_clinical_TNBC.csv"
output_deg = OUTPUT_DIR / "TNBC_DEG_list_for_GO_KEGG.csv"

if not rna_matrix.exists():
    print("RNA-seq matrix not found. Run 01_download_rnaseq_matrix.py first.")
elif not clinical.exists():
    print("Clinical file not found. Run 03_download_clinical_TNBC.py first.")
else:
    deg = simple_deg_analysis(rna_matrix, clinical, output_deg)

RNA-seq matrix not found. Run 01_download_rnaseq_matrix.py first.

**Output:**
`tcga_tnbc_data/TNBC_DEG_list_for_GO_KEGG.csv` with:
- `gene`
- `log2FC` (TNBC vs non‑TNBC)
- `pval`
- `adj_pval`

Use this file for:
- g:Profiler, Enrichr, DAVID, or
- R clusterProfiler for GO/KEGG.

### How to run everything in order
In your terminal (or Colab cell with `!` prefix):

In [1]:
# To run these scripts in order, execute the following commands in separate cells:
# !python 01_download_rnaseq_matrix.py
# !python 02_download_mirna_matrix.py
# !python 03_download_clinical_TNBC.py
# !python 05_prepare_deg_list.py
# !python 04_build_string_network.py
# Note: In Colab, you would typically run the individual Python cells I generated above,
# rather than calling them as separate Python scripts from bash.
# I've commented out the bash commands as they are generally for terminal execution.